<hr>

# 🧫 DATA CLEANING - Valeurs Foncieres


<style>
h1 {
    text-align: left;
    color: blue;
    font-weight: bold;
}

</style>
<hr>

```text
STEPS:
- CONCATINATE from 6 txt files into 1 csv
- DROP columns
- STANDARDIZE column names
- INVALID VALUES
- Convert DATA TYPES
- Deal with NULLS
- Deal with DUPLICATES
- Deal with OUTLIERS
- Save CLEAN CSV
```

<style>
h3 {
    margin-top: 0px;
    margin-bottom: 0px;
    font-weight: bold;
}
</style>

### 📂 IMPORTs

In [1]:
# import necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import display
import seaborn as sns

plt.style.use('ggplot')
pd.set_option('display.max_columns', 200) # to display all columns in the dataframe
print("✅ Libraries imported successfully")

✅ Libraries imported successfully

<hr>

## 0️⃣ CONCATINATE 

<style>
h1 {
    text-align: center;
    color: black;
    font-weight: bold;
}
</style>

<style>
h2 {
    text-align: left;
    color: black;
    font-weight: bold;
}
</style>

<style>
h3 {
    text-align: left;
    color: black;
    font-weight: bold;
}
</style>

<style>
h4 {
    text-align: left;
    color: black;
    font-weight: bold;
}
</style>
<hr>

### **DISPLAY TXT Sample**

In [ ]:
import pandas as pd
from io import StringIO

sample_text = """Identifiant de document|Reference document|1 Articles CGI|2 Articles CGI|3 Articles CGI|4 Articles CGI|5 Articles CGI|No disposition|Date mutation|Nature mutation|Valeur fonciere|No voie|B/T/Q|Type de voie|Code voie|Voie|Code postal|Commune|Code departement|Code commune|Prefixe de section|Section|No plan|No Volume|1er lot|Surface Carrez du 1er lot|2eme lot|Surface Carrez du 2eme lot|3eme lot|Surface Carrez du 3eme lot|4eme lot|Surface Carrez du 4eme lot|5eme lot|Surface Carrez du 5eme lot|Nombre de lots|Code type local|Type local|Identifiant local|Surface reelle bati|Nombre pieces principales|Nature culture|Nature culture speciale|Surface terrain
|||||||000001|01/07/2020|Vente|31234,16||||B064|SAINT JULIEN|1560|SAINT-JULIEN-SUR-REYSSOUZE|01|367||A|8||||||||||||0||||||AB||1192
|||||||000001|01/07/2020|Vente|278000,00||||B188|A LA PEROUSE|1250|CORVEISSIAT|01|125||C|509||||||||||||0||||||BS||10092
|||||||000001|01/07/2020|Vente|278000,00||||B188|A LA PEROUSE|1250|CORVEISSIAT|01|125||C|510||||||||||||0||||||L||4570
|||||||000001|01/07/2020|Vente|278000,00||||B079|AUX COMMUNS|1250|CORVEISSIAT|01|125||ZL|96||||||||||||0||||||BS||5750
|||||||000001|01/07/2020|Vente|278000,00||||B033|EN COMBARNAUD|1250|SIMANDRE-SUR-SURAN|01|408||A|14||||||||||||0||||||BT||648170
|||||||000001|01/07/2020|Vente|278000,00||||B033|EN COMBARNAUD|1250|SIMANDRE-SUR-SURAN|01|408||A|14||||||||||||0||||||BT||150000
|||||||000001|01/07/2020|Vente|278000,00||||B093|A LANSIAT|1250|SIMANDRE-SUR-SURAN|01|408||A|112||||||||||||0||||||P||1763
|||||||000001|01/07/2020|Vente|278000,00||||B111|MOULIN DE CORRERIE|1250|SIMANDRE-SUR-SURAN|01|408||A|114||||||||||||0||||||BT||108
|||||||000001|01/07/2020|Vente|278000,00||||B037|COMBE BIZET|1250|SIMANDRE-SUR-SURAN|01|408||B|134||||||||||||0||||||BT||124420
"""

df_sample = pd.read_csv(
    StringIO(sample_text),
    sep="|",
    dtype=str
)

display(df_sample)

,Identifiant de document,Reference document,1 Articles CGI,2 Articles CGI,3 Articles CGI,4 Articles CGI,5 Articles CGI,No disposition,Date mutation,Nature mutation,Valeur fonciere,No voie,B/T/Q,Type de voie,Code voie,Voie,Code postal,Commune,Code departement,Code commune,Prefixe de section,Section,No plan,No Volume,1er lot,Surface Carrez du 1er lot,2eme lot,Surface Carrez du 2eme lot,3eme lot,Surface Carrez du 3eme lot,4eme lot,Surface Carrez du 4eme lot,5eme lot,Surface Carrez du 5eme lot,Nombre de lots,Code type local,Type local,Identifiant local,Surface reelle bati,Nombre pieces principales,Nature culture,Nature culture speciale,Surface terrain
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,000001,01/07/2020,Vente,"31234,16",NaN,NaN,NaN,B064,SAINT JULIEN,1560,SAINT-JULIEN-SUR-REYSSOUZE,01,367,NaN,A,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,AB,NaN,1192
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,000001,01/07/2020,Vente,"278000,00",NaN,NaN,NaN,B188,A LA PEROUSE,1250,CORVEISSIAT,01,125,NaN,C,509,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,BS,NaN,10092
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,000001,01/07/2020,Vente,"278000,00",NaN,NaN,NaN,B188,A LA PEROUSE,1250,CORVEISSIAT,01,125,NaN,C,510,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,L,NaN,4570
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,000001,01/07/2020,Vente,"278000,00",NaN,NaN,NaN,B079,AUX COMMUNS,1250,CORVEISSIAT,01,125,NaN,ZL,96,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,BS,NaN,5750
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,000001,01/07/2020,Vente,"278000,00",NaN,NaN,NaN,B033,EN COMBARNAUD,1250,SIMANDRE-SUR-SURAN,01,408,NaN,A,14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,BT,NaN,648170
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,000001,01/07/2020,Vente,"278000,00",NaN,NaN,NaN,B033,EN COMBARNAUD,1250,SIMANDRE-SUR-SURAN,01,408,NaN,A,14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,BT,NaN,150000
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,000001,01/07/2020,Vente,"278000,00",NaN,NaN,NaN,B093,A LANSIAT,1250,SIMANDRE-SUR-SURAN,01,408,NaN,A,112,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,P,NaN,1763
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,000001,01/07/2020,Vente,"278000,00",NaN,NaN,NaN,B111,MOULIN DE CORRERIE,1250,SIMANDRE-SUR-SURAN,01,408,NaN,A,114,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,BT,NaN,108
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,000001,01/07/2020,Vente,"278000,00",NaN,NaN,NaN,B037,COMBE BIZET,1250,SIMANDRE-SUR-SURAN,01,408,NaN,B,134,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,BT,NaN,124420

### **FROM 6 TXTs to 1 CSV & SAVE**

In [3]:
from pathlib import Path
import pandas as pd

RAW_DIR = Path("../data/raw")
OUTPUT_FILE = Path("../data/processed/CONCAT_ValeursFoncieres.csv")

FILES = [
    "ValeursFoncieres-2020-S2.txt",
    "ValeursFoncieres-2021.txt",
    "ValeursFoncieres-2022.txt",
    "ValeursFoncieres-2023.txt",
    "ValeursFoncieres-2024.txt",
    "ValeursFoncieres-2025-S1.txt",
]

SEP = "|"
ENCODINGS = ["utf-8", "latin-1", "cp1252"]
CHUNK_SIZE = 50_000


def detect_encoding(filepath: Path) -> str:
    for enc in ENCODINGS:
        try:
            pd.read_csv(filepath, sep=SEP, nrows=5, encoding=enc)
            return enc
        except Exception:
            continue
    raise RuntimeError(f"Cannot read file: {filepath}")


def concat_files_chunked() -> None:
    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)

    first_write = True
    total_rows = 0

    for filename in FILES:
        path = RAW_DIR / filename

        if not path.exists():
            raise FileNotFoundError(f"Missing file: {path}")

        encoding = detect_encoding(path)
        print(f"\nProcessing {filename} with encoding={encoding}")

        reader = pd.read_csv(
            path,
            sep=SEP,
            dtype=str,
            encoding=encoding,
            low_memory=True,
            chunksize=CHUNK_SIZE
        )

        for chunk_idx, chunk in enumerate(reader, start=1):
            chunk.to_csv(
                OUTPUT_FILE,
                mode="w" if first_write else "a",
                index=False,
                header=first_write,
                encoding="utf-8"
            )

            first_write = False
            total_rows += len(chunk)

            print(
                f"  chunk {chunk_idx} written: {len(chunk):,} rows "
                f"| total: {total_rows:,}"
            )

            del chunk

    print("\nDone")
    print(f"Saved to: {OUTPUT_FILE}")
    print(f"Total rows written: {total_rows:,}")


if __name__ == "__main__":
    concat_files_chunked()

Processing ValeursFoncieres-2020-S2.txt with encoding=utf-8
  chunk 1 written: 50,000 rows | total: 50,000
  chunk 2 written: 50,000 rows | total: 100,000
  chunk 3 written: 50,000 rows | total: 150,000
  chunk 4 written: 50,000 rows | total: 200,000
  chunk 5 written: 50,000 rows | total: 250,000
  chunk 6 written: 50,000 rows | total: 300,000
  chunk 7 written: 50,000 rows | total: 350,000
  chunk 8 written: 50,000 rows | total: 400,000
  chunk 9 written: 50,000 rows | total: 450,000
  chunk 10 written: 50,000 rows | total: 500,000
  chunk 11 written: 50,000 rows | total: 550,000
  chunk 12 written: 50,000 rows | total: 600,000
  chunk 13 written: 50,000 rows | total: 650,000
  chunk 14 written: 50,000 rows | total: 700,000
  chunk 15 written: 50,000 rows | total: 750,000
  chunk 16 written: 50,000 rows | total: 800,000
  chunk 17 written: 50,000 rows | total: 850,000
  chunk 18 written: 50,000 rows | total: 900,000
  chunk 19 written: 50,000 rows | total: 950,000
  chunk 20 written: 50,000 rows | total: 1,000,000
  chunk 21 written: 50,000 rows | total: 1,050,000
  chunk 22 written: 50,000 rows | total: 1,100,000
  chunk 23 written: 50,000 rows | total: 1,150,000
  chunk 24 written: 50,000 rows | total: 1,200,000
  chunk 25 written: 50,000 rows | total: 1,250,000
  chunk 26 written: 50,000 rows | total: 1,300,000
  chunk 27 written: 50,000 rows | total: 1,350,000
  chunk 28 written: 50,000 rows | total: 1,400,000
  chunk 29 written: 50,000 rows | total: 1,450,000
  chunk 30 written: 50,000 rows | total: 1,500,000
  chunk 31 written: 50,000 rows | total: 1,550,000
  chunk 32 written: 50,000 rows | total: 1,600,000
  chunk 33 written: 50,000 rows | total: 1,650,000
  chunk 34 written: 50,000 rows | total: 1,700,000
  chunk 35 written: 50,000 rows | total: 1,750,000
  chunk 36 written: 50,000 rows | total: 1,800,000
  chunk 37 written: 50,000 rows | total: 1,850,000
  chunk 38 written: 50,000 rows | total: 1,900,000
  chunk 39 written: 50,000 rows | total: 1,950,000
  chunk 40 written: 50,000 rows | total: 2,000,000
  chunk 41 written: 50,000 rows | total: 2,050,000
  chunk 42 written: 15,003 rows | total: 2,065,003

Processing ValeursFoncieres-2021.txt with encoding=utf-8
  chunk 1 written: 50,000 rows | total: 2,115,003
  chunk 2 written: 50,000 rows | total: 2,165,003
  chunk 3 written: 50,000 rows | total: 2,215,003
  chunk 4 written: 50,000 rows | total: 2,265,003
  chunk 5 written: 50,000 rows | total: 2,315,003
  chunk 6 written: 50,000 rows | total: 2,365,003
  chunk 7 written: 50,000 rows | total: 2,415,003
  chunk 8 written: 50,000 rows | total: 2,465,003
  chunk 9 written: 50,000 rows | total: 2,515,003
  chunk 10 written: 50,000 rows | total: 2,565,003
  chunk 11 written: 50,000 rows | total: 2,615,003
  chunk 12 written: 50,000 rows | total: 2,665,003
  chunk 13 written: 50,000 rows | total: 2,715,003
  chunk 14 written: 50,000 rows | total: 2,765,003
  chunk 15 written: 50,000 rows | total: 2,815,003
  chunk 16 written: 50,000 rows | total: 2,865,003
  chunk 17 written: 50,000 rows | total: 2,915,003
  chunk 18 written: 50,000 rows | total: 2,965,003
  chunk 19 written: 50,000 rows | total: 3,015,003
  chunk 20 written: 50,000 rows | total: 3,065,003
  chunk 21 written: 50,000 rows | total: 3,115,003
  chunk 22 written: 50,000 rows | total: 3,165,003
  chunk 23 written: 50,000 rows | total: 3,215,003
  chunk 24 written: 50,000 rows | total: 3,265,003
  chunk 25 written: 50,000 rows | total: 3,315,003
  chunk 26 written: 50,000 rows | total: 3,365,003
  chunk 27 written: 50,000 rows | total: 3,415,003
  chunk 28 written: 50,000 rows | total: 3,465,003
  chunk 29 written: 50,000 rows | total: 3,515,003
  chunk 30 written: 50,000 rows | total: 3,565,003
  chunk 31 written: 50,000 rows | total: 3,615,003
  chunk 32 written: 50,000 rows | total: 3,665,003
  chunk 33 written: 50,000 rows | total: 3,715,003
  chunk 34 written: 50,000 rows | total: 3,765,003
  chunk 35 written: 50,000 rows | total: 3,815,003
  chunk 36 written: 50,000 rows | total: 3,865,003
  chunk 37 written: 50,000 rows | total: 3,915,003
  chunk 38 written: 50,000 rows | total: 3,965,003
  chunk 39 written: 50,000 rows | total: 4,015,003
  chunk 40 written: 50,000 rows | total: 4,065,003
  chunk 41 written: 50,000 rows | total: 4,115,003
  chunk 42 written: 50,000 rows | total: 4,165,003
  chunk 43 written: 50,000 rows | total: 4,215,003
  chunk 44 written: 50,000 rows | total: 4,265,003
  chunk 45 written: 50,000 rows | total: 4,315,003
  chunk 46 written: 50,000 rows | total: 4,365,003
  chunk 47 written: 50,000 rows | total: 4,415,003
  chunk 48 written: 50,000 rows | total: 4,465,003
  chunk 49 written: 50,000 rows | total: 4,515,003
  chunk 50 written: 50,000 rows | total: 4,565,003
  chunk 51 written: 50,000 rows | total: 4,615,003
  chunk 52 written: 50,000 rows | total: 4,665,003
  chunk 53 written: 50,000 rows | total: 4,715,003
  chunk 54 written: 50,000 rows | total: 4,765,003
  chunk 55 written: 50,000 rows | total: 4,815,003
  chunk 56 written: 50,000 rows | total: 4,865,003
  chunk 57 written: 50,000 rows | total: 4,915,003
  chunk 58 written: 50,000 rows | total: 4,965,003
  chunk 59 written: 50,000 rows | total: 5,015,003
  chunk 60 written: 50,000 rows | total: 5,065,003
  chunk 61 written: 50,000 rows | total: 5,115,003
  chunk 62 written: 50,000 rows | total: 5,165,003
  chunk 63 written: 50,000 rows | total: 5,215,003
  chunk 64 written: 50,000 rows | total: 5,265,003
  chunk 65 written: 50,000 rows | total: 5,315,003
  chunk 66 written: 50,000 rows | total: 5,365,003
  chunk 67 written: 50,000 rows | total: 5,415,003
  chunk 68 written: 50,000 rows | total: 5,465,003
  chunk 69 written: 50,000 rows | total: 5,515,003
  chunk 70 written: 50,000 rows | total: 5,565,003
  chunk 71 written: 50,000 rows | total: 5,615,003
  chunk 72 written: 50,000 rows | total: 5,665,003
  chunk 73 written: 50,000 rows | total: 5,715,003
  chunk 74 written: 50,000 rows | total: 5,765,003
  chunk 75 written: 50,000 rows | total: 5,815,003
  chunk 76 written: 50,000 rows | total: 5,865,003
  chunk 77 written: 50,000 rows | total: 5,915,003
  chunk 78 written: 50,000 rows | total: 5,965,003
  chunk 79 written: 50,000 rows | total: 6,015,003
  chunk 80 written: 50,000 rows | total: 6,065,003
  chunk 81 written: 50,000 rows | total: 6,115,003
  chunk 82 written: 50,000 rows | total: 6,165,003
  chunk 83 written: 50,000 rows | total: 6,215,003
  chunk 84 written: 50,000 rows | total: 6,265,003
  chunk 85 written: 50,000 rows | total: 6,315,003
  chunk 86 written: 50,000 rows | total: 6,365,003
  chunk 87 written: 50,000 rows | total: 6,415,003
  chunk 88 written: 50,000 rows | total: 6,465,003
  chunk 89 written: 50,000 rows | total: 6,515,003
  chunk 90 written: 50,000 rows | total: 6,565,003
  chunk 91 written: 50,000 rows | total: 6,615,003
  chunk 92 written: 50,000 rows | total: 6,665,003
  chunk 93 written: 50,000 rows | total: 6,715,003
  chunk 94 written: 24,176 rows | total: 6,739,179

Processing ValeursFoncieres-2022.txt with encoding=utf-8
  chunk 1 written: 50,000 rows | total: 6,789,179
  chunk 2 written: 50,000 rows | total: 6,839,179
  chunk 3 written: 50,000 rows | total: 6,889,179
  chunk 4 written: 50,000 rows | total: 6,939,179
  chunk 5 written: 50,000 rows | total: 6,989,179
  chunk 6 written: 50,000 rows | total: 7,039,179
  chunk 7 written: 50,000 rows | total: 7,089,179
  chunk 8 written: 50,000 rows | total: 7,139,179
  chunk 9 written: 50,000 rows | total: 7,189,179
  chunk 10 written: 50,000 rows | total: 7,239,179
  chunk 11 written: 50,000 rows | total: 7,289,179
  chunk 12 written: 50,000 rows | total: 7,339,179
  chunk 13 written: 50,000 rows | total: 7,389,179
  chunk 14 written: 50,000 rows | total: 7,439,179
  chunk 15 written: 50,000 rows | total: 7,489,179
  chunk 16 written: 50,000 rows | total: 7,539,179
  chunk 17 written: 50,000 rows | total: 7,589,179
  chunk 18 written: 50,000 rows | total: 7,639,179
  chunk 19 written: 50,000 rows | total: 7,689,179
  chunk 20 written: 50,000 rows | total: 7,739,179
  chunk 21 written: 50,000 rows | total: 7,789,179
  chunk 22 written: 50,000 rows | total: 7,839,179
  chunk 23 written: 50,000 rows | total: 7,889,179
  chunk 24 written: 50,000 rows | total: 7,939,179
  chunk 25 written: 50,000 rows | total: 7,989,179
  chunk 26 written: 50,000 rows | total: 8,039,179
  chunk 27 written: 50,000 rows | total: 8,089,179
  chunk 28 written: 50,000 rows | total: 8,139,179
  chunk 29 written: 50,000 rows | total: 8,189,179
  chunk 30 written: 50,000 rows | total: 8,239,179
  chunk 31 written: 50,000 rows | total: 8,289,179
  chunk 32 written: 50,000 rows | total: 8,339,179
  chunk 33 written: 50,000 rows | total: 8,389,179
  chunk 34 written: 50,000 rows | total: 8,439,179
  chunk 35 written: 50,000 rows | total: 8,489,179
  chunk 36 written: 50,000 rows | total: 8,539,179
  chunk 37 written: 50,000 rows | total: 8,589,179
  chunk 38 written: 50,000 rows | total: 8,639,179
  chunk 39 written: 50,000 rows | total: 8,689,179
  chunk 40 written: 50,000 rows | total: 8,739,179
  chunk 41 written: 50,000 rows | total: 8,789,179
  chunk 42 written: 50,000 rows | total: 8,839,179
  chunk 43 written: 50,000 rows | total: 8,889,179
  chunk 44 written: 50,000 rows | total: 8,939,179
  chunk 45 written: 50,000 rows | total: 8,989,179
  chunk 46 written: 50,000 rows | total: 9,039,179
  chunk 47 written: 50,000 rows | total: 9,089,179
  chunk 48 written: 50,000 rows | total: 9,139,179
  chunk 49 written: 50,000 rows | total: 9,189,179
  chunk 50 written: 50,000 rows | total: 9,239,179
  chunk 51 written: 50,000 rows | total: 9,289,179
  chunk 52 written: 50,000 rows | total: 9,339,179
  chunk 53 written: 50,000 rows | total: 9,389,179
  chunk 54 written: 50,000 rows | total: 9,439,179
  chunk 55 written: 50,000 rows | total: 9,489,179
  chunk 56 written: 50,000 rows | total: 9,539,179
  chunk 57 written: 50,000 rows | total: 9,589,179
  chunk 58 written: 50,000 rows | total: 9,639,179
  chunk 59 written: 50,000 rows | total: 9,689,179
  chunk 60 written: 50,000 rows | total: 9,739,179
  chunk 61 written: 50,000 rows | total: 9,789,179
  chunk 62 written: 50,000 rows | total: 9,839,179
  chunk 63 written: 50,000 rows | total: 9,889,179
  chunk 64 written: 50,000 rows | total: 9,939,179
  chunk 65 written: 50,000 rows | total: 9,989,179
  chunk 66 written: 50,000 rows | total: 10,039,179
  chunk 67 written: 50,000 rows | total: 10,089,179
  chunk 68 written: 50,000 rows | total: 10,139,179
  chunk 69 written: 50,000 rows | total: 10,189,179
  chunk 70 written: 50,000 rows | total: 10,239,179
  chunk 71 written: 50,000 rows | total: 10,289,179
  chunk 72 written: 50,000 rows | total: 10,339,179
  chunk 73 written: 50,000 rows | total: 10,389,179
  chunk 74 written: 50,000 rows | total: 10,439,179
  chunk 75 written: 50,000 rows | total: 10,489,179
  chunk 76 written: 50,000 rows | total: 10,539,179
  chunk 77 written: 50,000 rows | total: 10,589,179
  chunk 78 written: 50,000 rows | total: 10,639,179
  chunk 79 written: 50,000 rows | total: 10,689,179
  chunk 80 written: 50,000 rows | total: 10,739,179
  chunk 81 written: 50,000 rows | total: 10,789,179
  chunk 82 written: 50,000 rows | total: 10,839,179
  chunk 83 written: 50,000 rows | total: 10,889,179
  chunk 84 written: 50,000 rows | total: 10,939,179
  chunk 85 written: 50,000 rows | total: 10,989,179
  chunk 86 written: 50,000 rows | total: 11,039,179
  chunk 87 written: 50,000 rows | total: 11,089,179
  chunk 88 written: 50,000 rows | total: 11,139,179
  chunk 89 written: 50,000 rows | total: 11,189,179
  chunk 90 written: 50,000 rows | total: 11,239,179
  chunk 91 written: 50,000 rows | total: 11,289,179
  chunk 92 written: 50,000 rows | total: 11,339,179
  chunk 93 written: 50,000 rows | total: 11,389,179
  chunk 94 written: 25,007 rows | total: 11,414,186

Processing ValeursFoncieres-2023.txt with encoding=utf-8
  chunk 1 written: 50,000 rows | total: 11,464,186
  chunk 2 written: 50,000 rows | total: 11,514,186
  chunk 3 written: 50,000 rows | total: 11,564,186
  chunk 4 written: 50,000 rows | total: 11,614,186
  chunk 5 written: 50,000 rows | total: 11,664,186
  chunk 6 written: 50,000 rows | total: 11,714,186
  chunk 7 written: 50,000 rows | total: 11,764,186
  chunk 8 written: 50,000 rows | total: 11,814,186
  chunk 9 written: 50,000 rows | total: 11,864,186
  chunk 10 written: 50,000 rows | total: 11,914,186
  chunk 11 written: 50,000 rows | total: 11,964,186
  chunk 12 written: 50,000 rows | total: 12,014,186
  chunk 13 written: 50,000 rows | total: 12,064,186
  chunk 14 written: 50,000 rows | total: 12,114,186
  chunk 15 written: 50,000 rows | total: 12,164,186
  chunk 16 written: 50,000 rows | total: 12,214,186
  chunk 17 written: 50,000 rows | total: 12,264,186
  chunk 18 written: 50,000 rows | total: 12,314,186
  chunk 19 written: 50,000 rows | total: 12,364,186
  chunk 20 written: 50,000 rows | total: 12,414,186
  chunk 21 written: 50,000 rows | total: 12,464,186
  chunk 22 written: 50,000 rows | total: 12,514,186
  chunk 23 written: 50,000 rows | total: 12,564,186
  chunk 24 written: 50,000 rows | total: 12,614,186
  chunk 25 written: 50,000 rows | total: 12,664,186
  chunk 26 written: 50,000 rows | total: 12,714,186
  chunk 27 written: 50,000 rows | total: 12,764,186
  chunk 28 written: 50,000 rows | total: 12,814,186
  chunk 29 written: 50,000 rows | total: 12,864,186
  chunk 30 written: 50,000 rows | total: 12,914,186
  chunk 31 written: 50,000 rows | total: 12,964,186
  chunk 32 written: 50,000 rows | total: 13,014,186
  chunk 33 written: 50,000 rows | total: 13,064,186
  chunk 34 written: 50,000 rows | total: 13,114,186
  chunk 35 written: 50,000 rows | total: 13,164,186
  chunk 36 written: 50,000 rows | total: 13,214,186
  chunk 37 written: 50,000 rows | total: 13,264,186
  chunk 38 written: 50,000 rows | total: 13,314,186
  chunk 39 written: 50,000 rows | total: 13,364,186
  chunk 40 written: 50,000 rows | total: 13,414,186
  chunk 41 written: 50,000 rows | total: 13,464,186
  chunk 42 written: 50,000 rows | total: 13,514,186
  chunk 43 written: 50,000 rows | total: 13,564,186
  chunk 44 written: 50,000 rows | total: 13,614,186
  chunk 45 written: 50,000 rows | total: 13,664,186
  chunk 46 written: 50,000 rows | total: 13,714,186
  chunk 47 written: 50,000 rows | total: 13,764,186
  chunk 48 written: 50,000 rows | total: 13,814,186
  chunk 49 written: 50,000 rows | total: 13,864,186
  chunk 50 written: 50,000 rows | total: 13,914,186
  chunk 51 written: 50,000 rows | total: 13,964,186
  chunk 52 written: 50,000 rows | total: 14,014,186
  chunk 53 written: 50,000 rows | total: 14,064,186
  chunk 54 written: 50,000 rows | total: 14,114,186
  chunk 55 written: 50,000 rows | total: 14,164,186
  chunk 56 written: 50,000 rows | total: 14,214,186
  chunk 57 written: 50,000 rows | total: 14,264,186
  chunk 58 written: 50,000 rows | total: 14,314,186
  chunk 59 written: 50,000 rows | total: 14,364,186
  chunk 60 written: 50,000 rows | total: 14,414,186
  chunk 61 written: 50,000 rows | total: 14,464,186
  chunk 62 written: 50,000 rows | total: 14,514,186
  chunk 63 written: 50,000 rows | total: 14,564,186
  chunk 64 written: 50,000 rows | total: 14,614,186
  chunk 65 written: 50,000 rows | total: 14,664,186
  chunk 66 written: 50,000 rows | total: 14,714,186
  chunk 67 written: 50,000 rows | total: 14,764,186
  chunk 68 written: 50,000 rows | total: 14,814,186
  chunk 69 written: 50,000 rows | total: 14,864,186
  chunk 70 written: 50,000 rows | total: 14,914,186
  chunk 71 written: 50,000 rows | total: 14,964,186
  chunk 72 written: 50,000 rows | total: 15,014,186
  chunk 73 written: 50,000 rows | total: 15,064,186
  chunk 74 written: 50,000 rows | total: 15,114,186
  chunk 75 written: 50,000 rows | total: 15,164,186
  chunk 76 written: 50,000 rows | total: 15,214,186
  chunk 77 written: 12,327 rows | total: 15,226,513

Processing ValeursFoncieres-2024.txt with encoding=utf-8
  chunk 1 written: 50,000 rows | total: 15,276,513
  chunk 2 written: 50,000 rows | total: 15,326,513
  chunk 3 written: 50,000 rows | total: 15,376,513
  chunk 4 written: 50,000 rows | total: 15,426,513
  chunk 5 written: 50,000 rows | total: 15,476,513
  chunk 6 written: 50,000 rows | total: 15,526,513
  chunk 7 written: 50,000 rows | total: 15,576,513
  chunk 8 written: 50,000 rows | total: 15,626,513
  chunk 9 written: 50,000 rows | total: 15,676,513
  chunk 10 written: 50,000 rows | total: 15,726,513
  chunk 11 written: 50,000 rows | total: 15,776,513
  chunk 12 written: 50,000 rows | total: 15,826,513
  chunk 13 written: 50,000 rows | total: 15,876,513
  chunk 14 written: 50,000 rows | total: 15,926,513
  chunk 15 written: 50,000 rows | total: 15,976,513
  chunk 16 written: 50,000 rows | total: 16,026,513
  chunk 17 written: 50,000 rows | total: 16,076,513
  chunk 18 written: 50,000 rows | total: 16,126,513
  chunk 19 written: 50,000 rows | total: 16,176,513
  chunk 20 written: 50,000 rows | total: 16,226,513
  chunk 21 written: 50,000 rows | total: 16,276,513
  chunk 22 written: 50,000 rows | total: 16,326,513
  chunk 23 written: 50,000 rows | total: 16,376,513
  chunk 24 written: 50,000 rows | total: 16,426,513
  chunk 25 written: 50,000 rows | total: 16,476,513
  chunk 26 written: 50,000 rows | total: 16,526,513
  chunk 27 written: 50,000 rows | total: 16,576,513
  chunk 28 written: 50,000 rows | total: 16,626,513
  chunk 29 written: 50,000 rows | total: 16,676,513
  chunk 30 written: 50,000 rows | total: 16,726,513
  chunk 31 written: 50,000 rows | total: 16,776,513
  chunk 32 written: 50,000 rows | total: 16,826,513
  chunk 33 written: 50,000 rows | total: 16,876,513
  chunk 34 written: 50,000 rows | total: 16,926,513
  chunk 35 written: 50,000 rows | total: 16,976,513
  chunk 36 written: 50,000 rows | total: 17,026,513
  chunk 37 written: 50,000 rows | total: 17,076,513
  chunk 38 written: 50,000 rows | total: 17,126,513
  chunk 39 written: 50,000 rows | total: 17,176,513
  chunk 40 written: 50,000 rows | total: 17,226,513
  chunk 41 written: 50,000 rows | total: 17,276,513
  chunk 42 written: 50,000 rows | total: 17,326,513
  chunk 43 written: 50,000 rows | total: 17,376,513
  chunk 44 written: 50,000 rows | total: 17,426,513
  chunk 45 written: 50,000 rows | total: 17,476,513
  chunk 46 written: 50,000 rows | total: 17,526,513
  chunk 47 written: 50,000 rows | total: 17,576,513
  chunk 48 written: 50,000 rows | total: 17,626,513
  chunk 49 written: 50,000 rows | total: 17,676,513
  chunk 50 written: 50,000 rows | total: 17,726,513
  chunk 51 written: 50,000 rows | total: 17,776,513
  chunk 52 written: 50,000 rows | total: 17,826,513
  chunk 53 written: 50,000 rows | total: 17,876,513
  chunk 54 written: 50,000 rows | total: 17,926,513
  chunk 55 written: 50,000 rows | total: 17,976,513
  chunk 56 written: 50,000 rows | total: 18,026,513
  chunk 57 written: 50,000 rows | total: 18,076,513
  chunk 58 written: 50,000 rows | total: 18,126,513
  chunk 59 written: 50,000 rows | total: 18,176,513
  chunk 60 written: 50,000 rows | total: 18,226,513
  chunk 61 written: 50,000 rows | total: 18,276,513
  chunk 62 written: 50,000 rows | total: 18,326,513
  chunk 63 written: 50,000 rows | total: 18,376,513
  chunk 64 written: 50,000 rows | total: 18,426,513
  chunk 65 written: 50,000 rows | total: 18,476,513
  chunk 66 written: 50,000 rows | total: 18,526,513
  chunk 67 written: 50,000 rows | total: 18,576,513
  chunk 68 written: 50,000 rows | total: 18,626,513
  chunk 69 written: 50,000 rows | total: 18,676,513
  chunk 70 written: 39,149 rows | total: 18,715,662

Processing ValeursFoncieres-2025-S1.txt with encoding=utf-8
  chunk 1 written: 50,000 rows | total: 18,765,662
  chunk 2 written: 50,000 rows | total: 18,815,662
  chunk 3 written: 50,000 rows | total: 18,865,662
  chunk 4 written: 50,000 rows | total: 18,915,662
  chunk 5 written: 50,000 rows | total: 18,965,662
  chunk 6 written: 50,000 rows | total: 19,015,662

<hr>

## 1️⃣ STANDARDIZE NAMES


<style>
h1 {
    text-align: center;
    color: black;
    font-weight: bold;
}
</style>

<style>
h2 {
    text-align: left;
    color: black;
    font-weight: bold;
}
</style>

<style>
h3 {
    text-align: left;
    color: black;
    font-weight: bold;
}
</style>

<style>
h4 {
    text-align: left;
    color: black;
    font-weight: bold;
}
</style>
<hr>

### **SHAPE & HEAD**

In [ ]:
import pandas as pd

FILE = "../data/processed/CONCAT_ValeursFoncieres.csv"
CHUNK_SIZE = 50_000

total_rows = 0
columns = None

for chunk in pd.read_csv(FILE, chunksize=CHUNK_SIZE, dtype=str):
    total_rows += len(chunk)
    if columns is None:
        columns = chunk.columns

print("Shape:", total_rows, "rows and", len(columns), "columns")

df_head = pd.read_csv(FILE, nrows=5, dtype=str)
display(df_head)

Shape: 20102739 rows and 43 columns

,Identifiant de document,Reference document,1 Articles CGI,2 Articles CGI,3 Articles CGI,4 Articles CGI,5 Articles CGI,No disposition,Date mutation,Nature mutation,Valeur fonciere,No voie,B/T/Q,Type de voie,Code voie,Voie,Code postal,Commune,Code departement,Code commune,Prefixe de section,Section,No plan,No Volume,1er lot,Surface Carrez du 1er lot,2eme lot,Surface Carrez du 2eme lot,3eme lot,Surface Carrez du 3eme lot,4eme lot,Surface Carrez du 4eme lot,5eme lot,Surface Carrez du 5eme lot,Nombre de lots,Code type local,Type local,Identifiant local,Surface reelle bati,Nombre pieces principales,Nature culture,Nature culture speciale,Surface terrain
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,000001,01/07/2020,Vente,"31234,16",NaN,NaN,NaN,B064,SAINT JULIEN,1560,SAINT-JULIEN-SUR-REYSSOUZE,01,367,NaN,A,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,AB,NaN,1192
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,000001,01/07/2020,Vente,"278000,00",NaN,NaN,NaN,B188,A LA PEROUSE,1250,CORVEISSIAT,01,125,NaN,C,509,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,BS,NaN,10092
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,000001,01/07/2020,Vente,"278000,00",NaN,NaN,NaN,B188,A LA PEROUSE,1250,CORVEISSIAT,01,125,NaN,C,510,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,L,NaN,4570
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,000001,01/07/2020,Vente,"278000,00",NaN,NaN,NaN,B079,AUX COMMUNS,1250,CORVEISSIAT,01,125,NaN,ZL,96,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,BS,NaN,5750
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,000001,01/07/2020,Vente,"278000,00",NaN,NaN,NaN,B033,EN COMBARNAUD,1250,SIMANDRE-SUR-SURAN,01,408,NaN,A,14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,BT,NaN,648170

### **INFO**

In [ ]:
df_sample = pd.read_csv(FILE, nrows=100_000, dtype=str)
df_sample.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 43 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Identifiant de document     0 non-null       object
 1   Reference document          0 non-null       object
 2   1 Articles CGI              0 non-null       object
 3   2 Articles CGI              0 non-null       object
 4   3 Articles CGI              0 non-null       object
 5   4 Articles CGI              0 non-null       object
 6   5 Articles CGI              0 non-null       object
 7   No disposition              100000 non-null  object
 8   Date mutation               100000 non-null  object
 9   Nature mutation             100000 non-null  object
 10  Valeur fonciere             99092 non-null   object
 11  No voie                     59909 non-null   object
 12  B/T/Q                       3940 non-null    object
 13  Type de voie                56183 non-null   object
 14  Code voie                   98826 non-null   object
 15  Voie                        98826 non-null   object
 16  Code postal                 98826 non-null   object
 17  Commune                     100000 non-null  object
 18  Code departement            100000 non-null  object
 19  Code commune                100000 non-null  object
 20  Prefixe de section          1808 non-null    object
 21  Section                     99983 non-null   object
 22  No plan                     100000 non-null  object
 23  No Volume                   244 non-null     object
 24  1er lot                     37744 non-null   object
 25  Surface Carrez du 1er lot   11365 non-null   object
 26  2eme lot                    8057 non-null    object
 27  Surface Carrez du 2eme lot  3421 non-null    object
 28  3eme lot                    893 non-null     object
 29  Surface Carrez du 3eme lot  208 non-null     object
 30  4eme lot                    318 non-null     object
 31  Surface Carrez du 4eme lot  48 non-null      object
 32  5eme lot                    125 non-null     object
 33  Surface Carrez du 5eme lot  20 non-null      object
 34  Nombre de lots              100000 non-null  object
 35  Code type local             57654 non-null   object
 36  Type local                  57654 non-null   object
 37  Identifiant local           0 non-null       object
 38  Surface reelle bati         57573 non-null   object
 39  Nombre pieces principales   57573 non-null   object
 40  Nature culture              61772 non-null   object
 41  Nature culture speciale     2920 non-null    object
 42  Surface terrain             61772 non-null   object
dtypes: object(43)
memory usage: 32.8+ MB

### **UNIQUE VALUES**

In [14]:
from collections import defaultdict
import pandas as pd

FILE = "../data/processed/CONCAT_ValeursFoncieres.csv"

unique_values = defaultdict(set)
null_counts = defaultdict(int)

for chunk in pd.read_csv(FILE, chunksize=50_000, dtype=str):
    for col in chunk.columns:
        null_counts[col] += chunk[col].isna().sum()
        unique_values[col].update(chunk[col].fillna("MISSING").unique())

for col in unique_values:
    print(f"\n➡️ {col}")
    print(f"{col} [{len(unique_values[col])}]:")
    print(f"Null count: {null_counts[col]}")
    print(f"Unique  values: {list(unique_values[col])[:120]}")

➡️ Identifiant de document
Identifiant de document [1]:
Null count: 20102739
Unique  values: ['MISSING']

➡️ Reference document
Reference document [1]:
Null count: 20102739
Unique  values: ['MISSING']

➡️ 1 Articles CGI
1 Articles CGI [1]:
Null count: 20102739
Unique  values: ['MISSING']

➡️ 2 Articles CGI
2 Articles CGI [1]:
Null count: 20102739
Unique  values: ['MISSING']

➡️ 3 Articles CGI
3 Articles CGI [1]:
Null count: 20102739
Unique  values: ['MISSING']

➡️ 4 Articles CGI
4 Articles CGI [1]:
Null count: 20102739
Unique  values: ['MISSING']

➡️ 5 Articles CGI
5 Articles CGI [1]:
Null count: 20102739
Unique  values: ['MISSING']

➡️ No disposition
No disposition [1204]:
Null count: 0
Unique  values: ['000268', '000382', '000646', '000175', '000457', '000252', '000274', '000269', '000048', '000282', '000134', '000177', '000229', '000738', '001110', '001219', '000459', '000465', '000918', '001056', '001183', '000568', '000599', '001135', '000020', '000098', '001154', '000308', '000715', '001233', '000445', '000819', '000847', '001127', '001194', '000828', '000797', '000095', '000541', '000103', '000914', '000049', '001075', '000197', '000551', '000767', '000004', '000587', '001200', '000622', '000840', '000305', '000327', '000758', '000365', '000590', '001084', '001116', '000006', '001147', '000345', '000549', '000959', '000463', '000572', '000786', '000513', '000854', '000954', '000635', '000477', '000675', '000392', '000510', '000454', '000056', '000591', '001111', '000496', '000826', '001109', '000027', '000505', '000712', '000328', '000246', '000664', '000372', '000827', '000413', '000853', '001028', '000154', '000043', '000247', '001073', '000196', '000996', '000250', '000855', '000795', '001089', '001202', '000711', '000593', '000534', '000575', '000696', '000491', '000497', '001083', '000422', '000021', '000396', '000015', '000757', '000117', '001043', '000256', '000875']

➡️ Date mutation
Date mutation [1806]:
Null count: 0
Unique  values: ['28/12/2023', '29/01/2024', '29/08/2023', '05/08/2024', '25/09/2022', '04/07/2024', '10/03/2021', '04/01/2022', '11/04/2025', '02/10/2023', '02/07/2021', '07/09/2021', '16/09/2021', '18/01/2025', '14/07/2023', '04/12/2021', '04/05/2024', '11/11/2024', '30/01/2025', '16/12/2022', '21/12/2020', '04/04/2025', '23/11/2020', '19/03/2022', '09/11/2024', '30/12/2021', '05/05/2022', '15/04/2024', '23/06/2025', '25/07/2022', '20/02/2025', '23/10/2021', '10/02/2022', '07/09/2023', '09/08/2022', '24/10/2024', '15/01/2025', '11/10/2020', '26/01/2022', '06/02/2025', '29/10/2021', '29/06/2024', '16/08/2024', '07/01/2024', '07/08/2020', '10/07/2021', '08/02/2021', '21/08/2023', '29/03/2021', '26/06/2024', '09/07/2020', '09/01/2024', '29/06/2023', '04/08/2021', '24/04/2023', '06/05/2023', '16/01/2021', '22/01/2022', '15/08/2022', '31/01/2021', '18/12/2020', '09/12/2021', '30/05/2021', '03/10/2022', '23/02/2024', '28/07/2022', '19/05/2023', '18/05/2023', '05/11/2020', '16/09/2022', '26/04/2023', '31/12/2022', '24/01/2025', '09/06/2025', '01/05/2023', '06/08/2021', '29/04/2023', '18/04/2024', '22/11/2024', '24/04/2025', '10/08/2021', '31/01/2022', '22/07/2020', '16/02/2023', '12/01/2021', '08/05/2022', '18/06/2023', '30/10/2020', '27/09/2021', '26/07/2023', '14/11/2021', '19/02/2024', '23/09/2020', '02/01/2021', '12/08/2022', '15/02/2024', '12/09/2020', '13/01/2025', '13/07/2023', '19/04/2024', '27/09/2023', '17/07/2022', '20/07/2020', '20/03/2023', '19/01/2024', '01/03/2025', '10/01/2021', '01/09/2021', '02/03/2024', '04/11/2023', '06/09/2023', '22/03/2024', '03/01/2021', '05/03/2022', '02/08/2022', '16/09/2023', '28/11/2021', '27/01/2021', '01/02/2021', '27/06/2025']

➡️ Nature mutation
Nature mutation [6]:
Null count: 0
Unique  values: ['Adjudication', "Vente en l'état futur d'achèvement", 'Vente', 'Expropriation', 'Echange', 'Vente terrain à bâtir']

➡️ Valeur fonciere
Valeur fonciere [466668]:
Null count: 194390
Unique  values: ['223215,00', '952771,00', '95613,75', '17164,00', '633267,25', '141352,00', '1228000,00', '460348,00', '228135,00', '47614,50', '439600,00', '231477,55', '69539,05', '338111,00', '256525,00', '110765,00', '2033,25', '139170,00', '336318,00', '322000,78', '88791,00', '405605,90', '178201,77', '129479,20', '297220,00', '248166,48', '173270,00', '21323,05', '441,25', '302003,00', '1178930,00', '34437,00', '687312,00', '162458,00', '296711,00', '108835,20', '389938,38', '94233,60', '253340,66', '2000,16', '123868,51', '365213,00', '184744,00', '9340007,00', '183585,00', '56973,00', '349700,00', '351,55', '66321,00', '243150,00', '38291,10', '1528,00', '37917,60', '889511,00', '366911,00', '9344263,00', '303972,00', '552210,00', '25512,00', '833992,00', '217975,00', '418461,00', '40100000,00', '395290,00', '69458,00', '67585,00', '73683,00', '354691,00', '1079200,00', '33380,00', '226200,00', '99974,40', '251558,00', '960220,90', '141578,00', '2147,50', '410885,00', '271259,00', '77177,56', '355710,00', '72734,00', '2307646,50', '240264,00', '253667,00', '195370,00', '115977,00', '395568,00', '125976,00', '9258,54', '172240,00', '227430,00', '9323,56', '25558512,00', '192880,30', '352790,00', '6244,07', '45330,00', '3375180,00', '328779,10', '186655,00', '1855102,00', '648330,00', '39383,27', '590917,00', '4873,00', '243524,00', '440,00', '524080,00', '112381,00', '789440,00', '83261,62', '58600,00', '158070,00', '237995,00', '1636530,00', '392987,50', '921720,00', '124342,00', '59174,40', '54112,22']

➡️ No voie
No voie [9127]:
Null count: 7474511
Unique  values: ['4116', '9529', '729', '9187', '919', '9358', '9540', '9098', '804', '964', '9330', '5501', '7508', '1746', '4665', '2659', '8509', '1285', '2909', '5652', '5435', '6670', '2474', '2274', '4236', '9292', '1421', '3610', '3556', '1777', '3431', '6970', '6040', '1312', '6394', '9197', '3407', '9423', '2464', '1644', '2701', '2106', '3261', '6236', '8037', '7592', '5070', '3968', '7529', '5044', '6883', '3298', '6435', '7759', '4401', '1190', '715', '6384', '416', '9449', '14', '8931', '3850', '7601', '8454', '7767', '5020', '7631', '774', '5544', '5599', '2741', '8913', '6819', '4570', '2524', '3318', '5574', '5124', '6843', '3919', '3072', '6996', '6748', '2628', '4228', '2587', '8685', '2695', '7528', '5320', '2962', '5308', '2903', '1395', '2835', '9719', '8052', '945', '4789', '6680', '9723', '6351', '6595', '6933', '9216', '4480', '7357', '6444', '9531', '303', '3344', '9037', '5852', '4774', '949', '2660', '5981', '1994', '6932']

➡️ B/T/Q
B/T/Q [41]:
Null count: 19197659
Unique  values: ['-', 'A', 'MISSING', 'W', 'H', 'X', '9', 'Y', '7', 'G', 'V', 'P', '5', '2', 'Z', 'E', 'K', 'T', 'I', 'M', 'U', '3', 'D', '8', '1', 'O', 'B', '6', '0', 'L', '4', 'R', 'N', 'b', 'F', 'J', '*', '.', 'Q', 'S', 'C']

➡️ Type de voie
Type de voie [153]:
Null count: 7942059
Unique  values: ['SQ', 'RES', 'COTE', 'COL', 'RLE', 'PL', 'RTD', 'CTRE', 'VOIR', 'BRTL', 'FOS', 'VAL', 'ESC', 'CRS', 'GARE', 'ESPA', 'VOY', 'JTE', 'TSSE', 'RPE', 'ENC', 'PASS', 'VTE', 'RAC', 'HLM', 'CHEM', 'DIG', 'ZA', 'NTE', 'CHL', 'PLA', 'PRV', 'MRN', 'ECL', 'PONT', 'COIN', 'HLE', 'RPT', 'PTTE', 'ENV', 'DSC', 'PLCI', 'PTA', 'DOM', 'VALL', 'CHT', 'GPL', 'MAIL', 'CASR', 'CTR', 'ZAD', 'BRG', 'D', 'ART', 'STDE', 'IMP', 'CIVE', 'N', 'VCHE', 'CC', 'VOIE', 'EMBR', 'BRE', 'CF', 'DEVI', 'CORO', 'GAL', 'MAIS', 'LOT', 'FRM', 'TRAB', 'PAS', 'ROC', 'VEN', 'VC', 'VOUT', 'CAR', 'HLG', 'ALL', 'PLAN', 'RUET', 'CPG', 'ZUP', 'SEN', 'ILOT', 'PTR', 'LEVE', 'BER', 'CITE', 'MAR', 'BSN', 'CHE', 'RUE', 'TRT', 'PROM', 'ACH', 'BD', 'HAB', 'RULT', 'CR', 'CD', 'VIA', 'CAE', 'HAM', 'MTE', 'PORT', 'PARC', 'COR', 'AGL', 'JARD', 'PLE', 'AV', 'PAE', 'DRA', 'ANGL', 'PLAG', 'MISSING', 'ZAC', 'PLT', 'RUIS']

➡️ Code voie
Code voie [20065]:
Null count: 150482
Unique  values: ['8808', '9529', 'I528', '9540', 'A434', 'I818', 'H811', 'F646', 'F102', 'I734', '3578', '8657', 'P395', 'B479', 'A567', '0104', '1312', 'I238', '3407', 'G781', 'E580', '9423', '8932', '8337', '1644', '2701', 'K015', '6236', '8474', 'D611', 'H048', 'A475', 'D451', '3968', 'G564', '4401', 'G251', '1190', '6384', 'B255', 'E502', 'A743', 'G588', '8454', 'I541', 'A207', '2741', '8913', '5599', '4570', '3318', '5574', 'I279', 'F979', '6996', '6748', '8960', '2628', 'B243', '0827', 'H297', '7696', '2587', '8685', '2695', 'G602', 'B493', '5320', '5308', 'C640', 'F375', 'I077', '6933', 'B251', 'C543', 'F707', 'D927', '4480', 'J197', '3344', '9037', 'A666', '2660', '6080', 'A069', 'B398', '4918', 'D829', 'I562', '7117', '7301', 'C388', 'J200', '6668', 'W987', '8745', 'C837', '0989', 'B649', '5996', 'S110', 'E401', 'I215', 'A840', '4254', 'A341', 'H187', 'H268', 'G590', 'H182', '4780', 'H428', '3563', '3903', '3022', 'F083', 'E107', '5072', 'S914', 'K159']

➡️ Voie
Voie [1132200]:
Null count: 151263
Unique  values: ['ROGER DEUMIE', "DE L'ARPENTEUR", 'ECONVAL', 'BERNARD BOBIN', 'DE LABREU BOISSIERES', 'ALBERT ET HENRI GRUELLES', 'HAUTE BARBERIE', 'LES MOINS PAS', 'PETIT BONNUET', 'DU CHATEAU DE LA GRAVE', 'DE LUSSAC LES CHATEAUX', 'DES AGATHIS', 'EN MESSIEURS', 'DU CLOS DAVY', 'DE RIBE', 'BENVENUTO CELLINI', 'PONT AR CHLAN', 'PRES HINCELIN', 'DE LA TROLANDERIE', 'DE NANTHUY', 'DULAURANS', 'DU LIEUTENANT ISNARD', 'LA VILLE ES FRAY', 'DU RUISSEAU DE LA GALERE', 'LE CHAMP CATHERINE', 'LA SOURBERE', 'DE GOMMECOURT', 'LA BOUHERNIERE', 'CHEMIN DE RI', 'LE CALVAIRE SUD', 'PATUREAU DE LA PREE', 'DE LA BRAUDE', 'LA LIBERATION VAL HERVELIN', 'GRANDS BOIS DE LA COURTAUD', 'HORT DEL LAC', 'DAMONT LA VILLE', 'LA COMPOINTERIE', 'COULAGNES HAUTES', 'PRES D AYROUX', 'LES OUCHES CLIVIS', 'LE MONT DE VILLE', 'LA TOUR BEAUFORT', 'JULES PLAT', 'LES REVERDIS', 'HAMEAU DU DEFFEND', 'COMBALADET', 'DES CHAMPS BERGERS', 'PHILIOMEL', 'FESCHAL', 'LE CHAMP DE LA MERCERIE', 'LE CLOS HAUT BOIS', 'PESPINASSOU', 'GOUBAIN', 'LE GRAND ETANG DU GALLAS', 'DES EQUEUVES', 'LES COSSONNIERES', 'TRINQUEPEL', 'LE GRAND MAUDUIT', 'DE HALAGE DE LA NIVE', 'LA MANZO', 'ABRIGUES', 'PRE DE L EPINARDIERE', 'DE BUSCHHOVEN', 'COTEAUX DE DURIGNE', 'MOULIN DE KERSPEC', 'LES EGLICHEES', 'GRAND BREMORET', 'LA VILLE YAIS', 'LA PETITE BOUTEILLE', 'DE LA GUEUDIERE - MONTGOTH', 'DE L AIRE BURON', 'DE LA PORTE HUILLIER', 'DE LA VIERHOUCK', 'KERANTAER', 'DES AUBARINES', 'RENSE', 'SUR LES NOIRS PRES', 'LE CLOS GUEROT', 'LA CROIX MAGNIEN', 'LES COTES DE L ETANG', 'OBIOLES', 'MANER NEVEZ', 'CHAMP DE DOMUITES', 'TERRES DES GRANDES CAVES', 'GOAREM VIHEN', 'LE DOUET NORMAND', 'LE FREAUX QUEMARD', 'HAYE SAINT ETIENNE', 'BRONDEAU DE SENELLES', 'LE BRIGAUMONT', 'LES POUZADOUX', 'PUYARNAOUT', 'AU NETILLON', 'ROGER VALLOIS', 'LOT LES BOUGAINVILLIERS', 'DE BEL ORIENT', 'LES COUARIERES', 'CRAMAILLE', 'PARC TAL EN THY', 'NICOLAZIC', 'DE RAMPIEUX', 'DU BESNIER', 'L ADOUREAU', 'BOIS DES MERONS', 'DE BAVILLIERS', 'GRAND CLOTEAU DES HAIES', 'TOULET OUEST', 'POUDAIRE EST', 'RUE AUTAIN', 'MARAIS DE PERIAZ', 'AUX FOURNEY', 'AU CHEMIN D ANGLAS', 'LES MARGES', 'DE CHALONS A ST MARTIN', 'LA MOUSSARDERIE', 'DE TACHENNIC', 'ERNEST ZUBER PAPETERIES', 'FOMPUDI OUEST', 'ZAC DES SARS', 'FONTAINE DE YON']

➡️ Code postal
Code postal [5872]:
Null count: 151600
Unique  values: ['13930', '77440', '43300', '39600', '87460', '35960', '77250', '60550', '22410', '77920', '15600', '42131', '83490', '9330', '21520', '93200', '66750', '59258', '81190', '17530', '34290', '20147', '63690', '28210', '89170', '6670', '19600', '33640', '48210', '69490', '81150', '59282', '34850', '72130', '83400', '84830', '62223', '97120', '78210', '62120', '59231', '69890', '89270', '36260', '70190', '21600', '84190', '76620', '1190', '34400', '40290', '20171', '47470', '77660', '76300', '23380', '78940', '55800', '48190', '13600', '87430', '30330', '25320', '60200', '92120', '95220', '60430', '5320', '79240', '54114', '74960', '38380', '17920', '10190', '60320', '95740', '59730', '59293', '86140', '45300', '54730', '83570', '85270', '71270', '40390', '74500', '37130', '90300', '6410', '7350', '92160', '39250', '59410', '73480', '59135', '46090', '12160', '81140', '80230', '88380', '60860', '24130', '77910', '63119', '59283', '62420', '24460', '60100', '58410', '17150', '86500', '97412', '50890', '53160', '16250', '59178', '36340', '59255', '79430', '76740']

➡️ Commune
Commune [31569]:
Null count: 0
Unique  values: ['SAINT-URBAIN', 'ADISSAN', 'SAINT-LEGER-SUR-SARTHE', 'VILLAVARD', 'PLASNE', 'ANJOUTEY', 'VOIRES', 'TROULEY-LABARTHE', 'PERGAIN-TAILLAC', 'SASSENAY', 'ALLAN', 'VILLIERS-EN-PLAINE', 'TAVERNY', 'CHERY LES ROZOY', 'CLERMONT-DESSOUS', 'COURLAC', 'BOISSET', 'FONTENU', 'OSNY', 'CHEVROUX', 'LAUJUZAN', 'HEUDREVILLE EN LIEUVIN', 'JURANVILLE', 'VIEILLE-EGLISE-EN-YVELINES', 'SAINT NAZAIRE', 'ASSEVENT', 'SAINT-MAURICE-EN-TRIEVES', 'MORTAIN-BOCAGE', 'SAINTE FEYRE LA MONTAGNE', 'STE ANASTASIE SUR ISSOLE', 'LAGORD', 'OBTERRE', 'BOUYON', 'ORMOY VILLERS', 'OYE', 'BERNOY LE CHATEAU', 'MONLEZUN-D ARMAGNAC', 'MACOGNY', 'BILLEZOIS', 'TROUSSEY', 'CRAMAILLE', 'BONNEBOSQ', 'SAINT-MAURICE-COLOMBIER', 'GRENEVILLE-EN-BEAUCE', 'DOULCON', 'LA CHAPELLE-MOULIERE', 'CUQ', 'SEYNES', 'ERONDELLE', 'CEYRESTE', 'SAINT-PIERRE-LES-BOIS', 'GRAUVES', 'LATOUR DE CAROL', 'BASCONS', 'IDAUX-MENDY', 'TROUVILLE', 'VIGNAUX', 'SAINT-ETIENNE-DU-VALDONNEZ', 'CANALE DI VERDE', 'MOISENAY', 'SAINT-CHAMANT', 'MORTROUX', 'GERGY', 'BOLLEVILLE', 'LA CHAPELLE BERTIN', 'COURCELLES LES GISORS', 'TORCY EN VALOIS', 'SAINT-MARTIN-DE-SALENCEY', 'JOUCOU', 'LALLEU', 'ILONSE', 'LONGUEIL STE MARIE', 'SIORAC-DE-RIBERAC', 'LIGNIERES-LES-ROYE', 'LES IFFS', 'ASNIERES-SUR-NOUERE', 'BRUNIQUEL', 'JESONVILLE', 'SAN GAVINO DI FIUMORBO', 'MANDRES-LA-COTE', 'FRICOURT', 'REGNIE-DURETTE', 'FELON', 'VAL DE ROULANS', 'AVRESSIEUX', 'PEYRUSSE', 'ROMILLY SUR SEINE', 'BARBERY', 'CAYCHAX', 'DUSSAC', 'HERICOURT-EN-CAUX', 'CORNEILLA DEL VERCOL', 'SAINT-MARTIN-D ARY', "SAINTE-MARGUERITE-D'ELLE", 'YZERON', 'LUCENAY', 'SAINT-HILAIRE-DE-RIEZ', 'LE GRAND-AUVERNE', 'ST MARTIN LE NOEUD', 'MARTAGNY', 'MANNEVILLE-LA-RAOULT', 'LIEURON', 'SAINT-JEAN-DE-MUZOLS', 'VIGNOUX-SUR-BARANGEON', 'LIEUCHE', 'MENIL-GONDOUIN', 'POMMIERS-MOULONS', 'SAINT-AUVENT', 'AUGAN', 'VERNEGUES', 'VIALAS', 'SAILLY', 'SENOUILLAC', 'ETERVILLE', 'BETONCOURT SAINT PANCRAS', 'SAINT-SEVER-DE-RUSTAN', 'CHAILLEY', 'CUGNY', 'SOYE-EN-SEPTAINE', 'VILLY-SUR-YERES']

➡️ Code departement
Code departement [97]:
Null count: 0
Unique  values: ['01', '08', '22', '37', '15', '52', '02', '78', '17', '974', '87', '56', '64', '19', '82', '65', '70', '31', '51', '35', '86', '81', '10', '71', '44', '76', '973', '85', '38', '04', '54', '48', '95', '21', '25', '62', '18', '46', '79', '34', '84', '90', '47', '09', '89', '27', '92', '11', '14', '40', '06', '24', '66', '83', '36', '75', '23', '50', '94', '971', '32', '2A', '42', '43', '73', '16', '29', '77', '59', '12', '69', '88', '49', '74', '53', '2B', '72', '91', '80', '55', '03', '30', '05', '13', '61', '41', '93', '33', '26', '45', '58', '07', '63', '972', '39', '60', '28']

➡️ Code commune
Code commune [908]:
Null count: 0
Unique  values: ['764', '146', '98', '833', '729', '334', '122', '22', '602', '724', '673', '751', '618', '708', '759', '217', '860', '490', '512', '222', '376', '175', '52', '909', '299', '804', '390', '869', '641', '361', '424', '412', '740', '738', '562', '585', '200', '168', '295', '791', '757', '227', '538', '352', '531', '135', '842', '152', '810', '815', '172', '438', '70', '460', '31', '647', '459', '362', '854', '747', '666', '342', '411', '555', '560', '81', '784', '696', '446', '583', '894', '219', '393', '787', '519', '628', '780', '809', '265', '308', '415', '742', '409', '709', '805', '526', '54', '536', '158', '592', '120', '296', '413', '625', '155', '713', '25', '464', '149', '655', '692', '848', '820', '484', '839', '398', '343', '505', '572', '715', '396', '626', '697', '416', '637', '620', '800', '405', '92', '14']

➡️ Prefixe de section
Prefixe de section [760]:
Null count: 19147817
Unique  values: ['146', '98', '833', '729', '334', '122', '22', '602', '618', '217', '860', '222', '909', '52', '175', '376', '299', '804', '390', '869', '641', '361', '424', '412', '910', '562', '585', '168', '200', '757', '295', '227', '538', '352', '531', '135', '842', '152', '810', '815', '172', '438', '70', '460', '31', '647', '459', '362', '854', '342', '411', '560', '81', '696', '583', '894', '219', '393', '519', '628', '809', '265', '308', '415', '409', '742', '805', '526', '54', '158', '120', '296', '413', '625', '155', '655', '25', '713', '149', '820', '484', '839', '398', '343', '505', '396', '626', '697', '416', '620', '637', '92', '632', '14', '405', '40', '433', '561', '241', '483', '402', '66', '813', '431', '240', '509', '119', '639', '502', '297', '449', '451', '354', '457', '348', '293', '211', '866', '42', '513']

➡️ Section
Section [589]:
Null count: 725
Unique  values: ['ZK', 'WS', 'JA', 'YK', 'XA', 'DX', 'MC', 'AH', 'P', 'WF', 'GF', 'VN', 'NM', 'KJ', 'ZU', 'VM', 'HD', 'NY', 'XH', 'XM', 'HE', 'GP', 'VD', 'PN', 'DE', 'SA', 'SM', 'YV', 'GV', 'ZA', 'FS', 'TV', 'WI', 'PZ', 'NV', 'KR', 'EA', 'WZ', 'NZ', 'IU', 'NI', 'AB', 'OZ', 'WH', 'SE', 'ID', 'OE', 'HS', 'NB', 'KI', 'ER', 'WO', 'PY', 'DH', 'TC', 'ZE', 'WP', 'PA', 'LQ', 'CE', 'XL', 'SV', 'GZ', 'PE', 'N', 'WE', 'ZW', 'KA', 'MH', 'A', 'XG', 'ON', 'PX', 'BC', 'MV', 'TY', 'XD', 'HM', 'XV', 'Z', 'KZ', 'JJ', 'K', 'HL', 'VX', 'OK', 'BM', 'M', 'NT', 'SW', 'TN', 'XI', 'EE', 'EZ', 'CG', 'ZT', 'PK', 'L', 'YC', 'AF', 'KN', 'JE', 'XP', 'LO', 'CN', 'GS', 'CM', 'LJ', 'PW', 'AC', 'AV', 'ES', 'EG', 'EM', 'IG', 'MISSING', 'H', 'RR', 'BY', 'FU']

➡️ No plan
No plan [8239]:
Null count: 0
Unique  values: ['4116', '4966', '729', '919', '4387', '804', '964', '9330', '5501', '7508', '1746', '4665', '2659', '8509', '8253', '7648', '3578', '1285', '2909', '5652', '2474', '5435', '6670', '2274', '4236', '1421', '3610', '3556', '1777', '3431', '6970', '1312', '6040', '6394', '9197', '3407', '8337', '9423', '2464', '1644', '2701', '2106', '3261', '8258', '6236', '8474', '7592', '5070', '3968', '7529', '3298', '5044', '6883', '6435', '7759', '4401', '3728', '1190', '715', '6384', '416', '14', '3850', '7767', '5020', '7631', '774', '5544', '5599', '2741', '6819', '4570', '2524', '3318', '5574', '5124', '6843', '3919', '3072', '6996', '7847', '6748', '2628', '4228', '7696', '2587', '2695', '7528', '5320', '2962', '5308', '2903', '1395', '2835', '945', '4789', '9723', '6680', '6351', '6595', '6933', '4480', '4158', '7357', '6444', '303', '3344', '9037', '5852', '4774', '949', '2660', '1994', '5981', '6932', '6080', '3753', '1595', '4182', '2555']

➡️ No Volume
No Volume [2069]:
Null count: 20057358
Unique  values: ['3143', '1135', 'QUATRE', '1401', '490', '206237', '9044', '390', '106027', '106604', '13281', '2152', '3135', '1176', '31177', '2001', '20038', '295', '11441', '531', '207180', '211501', '2043', '203090', '208130', '3130', '4201', '1164', '20031', '555', '50000', '1421', '205042', '105060', '10167', 'AB', '894', '33205', '32271', '393', '519', '1B', '31166', '205501', '415', '1123', '1108', '805', '54', 'P419003', '3019', '413', '155', '106022', '25', '10601', '13272', '206238', '1134', '105211', '715', '11442', '416', '3B', '204006', '104136', '14', '105052', '105524', '11480', '205906', '3042', '5B', '1115', '7015', '240', '119', '2207', '1133', '1010', '2A', '293', '17664', '3072', '513', '1304', '204508', '916', '499', '105066', '511', '6062', '463', '224', '206783', '200020', 'AC', '868', '3147', '74', '2X', '1056', '2345', '116', '1093', '31178', '4008', '80', '420', '735', '105008', '11428', '303', '14000', '210116', '497', '207009', '659', '105050', '2191']

➡️ 1er lot
1er lot [18514]:
Null count: 13798466

### **DROP COLUMNS**

In [15]:
from pathlib import Path
import pandas as pd

INPUT_FILE = Path("../data/processed/CONCAT_ValeursFoncieres.csv")
OUTPUT_FILE = Path("../data/processed/DROP_ValeursFoncieres.csv")

CHUNK_SIZE = 50_000

cols_to_drop = [
    "Identifiant de document",
    "Reference document",
    "1 Articles CGI",
    "2 Articles CGI",
    "3 Articles CGI",
    "4 Articles CGI",
    "5 Articles CGI",
    "Identifiant local",
]

def drop_columns_chunked(input_file: Path, output_file: Path, cols_to_drop: list[str], chunk_size: int = 50_000) -> None:
    output_file.parent.mkdir(parents=True, exist_ok=True)

    first_write = True
    total_rows = 0

    for chunk_idx, chunk in enumerate(
        pd.read_csv(input_file, chunksize=chunk_size, dtype=str),
        start=1
    ):
        existing_cols_to_drop = [col for col in cols_to_drop if col in chunk.columns]
        chunk = chunk.drop(columns=existing_cols_to_drop)

        chunk.to_csv(
            output_file,
            mode="w" if first_write else "a",
            index=False,
            header=first_write,
            encoding="utf-8"
        )

        first_write = False
        total_rows += len(chunk)

        print(f"Chunk {chunk_idx} written -> {len(chunk):,} rows | total: {total_rows:,}")

    print("\nDone! Dropped columns")
    print(f"Saved file: {output_file}")
    print(f"Total rows written: {total_rows:,}")

drop_columns_chunked(INPUT_FILE, OUTPUT_FILE, cols_to_drop, CHUNK_SIZE)

Chunk 1 written -> 50,000 rows | total: 50,000
Chunk 2 written -> 50,000 rows | total: 100,000
Chunk 3 written -> 50,000 rows | total: 150,000
Chunk 4 written -> 50,000 rows | total: 200,000
Chunk 5 written -> 50,000 rows | total: 250,000
Chunk 6 written -> 50,000 rows | total: 300,000
Chunk 7 written -> 50,000 rows | total: 350,000
Chunk 8 written -> 50,000 rows | total: 400,000
Chunk 9 written -> 50,000 rows | total: 450,000
Chunk 10 written -> 50,000 rows | total: 500,000
Chunk 11 written -> 50,000 rows | total: 550,000
Chunk 12 written -> 50,000 rows | total: 600,000
Chunk 13 written -> 50,000 rows | total: 650,000
Chunk 14 written -> 50,000 rows | total: 700,000
Chunk 15 written -> 50,000 rows | total: 750,000
Chunk 16 written -> 50,000 rows | total: 800,000
Chunk 17 written -> 50,000 rows | total: 850,000
Chunk 18 written -> 50,000 rows | total: 900,000
Chunk 19 written -> 50,000 rows | total: 950,000
Chunk 20 written -> 50,000 rows | total: 1,000,000
Chunk 21 written -> 50,000 rows | total: 1,050,000
Chunk 22 written -> 50,000 rows | total: 1,100,000
Chunk 23 written -> 50,000 rows | total: 1,150,000
Chunk 24 written -> 50,000 rows | total: 1,200,000
Chunk 25 written -> 50,000 rows | total: 1,250,000
Chunk 26 written -> 50,000 rows | total: 1,300,000
Chunk 27 written -> 50,000 rows | total: 1,350,000
Chunk 28 written -> 50,000 rows | total: 1,400,000
Chunk 29 written -> 50,000 rows | total: 1,450,000
Chunk 30 written -> 50,000 rows | total: 1,500,000
Chunk 31 written -> 50,000 rows | total: 1,550,000
Chunk 32 written -> 50,000 rows | total: 1,600,000
Chunk 33 written -> 50,000 rows | total: 1,650,000
Chunk 34 written -> 50,000 rows | total: 1,700,000
Chunk 35 written -> 50,000 rows | total: 1,750,000
Chunk 36 written -> 50,000 rows | total: 1,800,000
Chunk 37 written -> 50,000 rows | total: 1,850,000
Chunk 38 written -> 50,000 rows | total: 1,900,000
Chunk 39 written -> 50,000 rows | total: 1,950,000
Chunk 40 written -> 50,000 rows | total: 2,000,000
Chunk 41 written -> 50,000 rows | total: 2,050,000
Chunk 42 written -> 50,000 rows | total: 2,100,000
Chunk 43 written -> 50,000 rows | total: 2,150,000
Chunk 44 written -> 50,000 rows | total: 2,200,000
Chunk 45 written -> 50,000 rows | total: 2,250,000
Chunk 46 written -> 50,000 rows | total: 2,300,000
Chunk 47 written -> 50,000 rows | total: 2,350,000
Chunk 48 written -> 50,000 rows | total: 2,400,000
Chunk 49 written -> 50,000 rows | total: 2,450,000
Chunk 50 written -> 50,000 rows | total: 2,500,000
Chunk 51 written -> 50,000 rows | total: 2,550,000
Chunk 52 written -> 50,000 rows | total: 2,600,000
Chunk 53 written -> 50,000 rows | total: 2,650,000
Chunk 54 written -> 50,000 rows | total: 2,700,000
Chunk 55 written -> 50,000 rows | total: 2,750,000
Chunk 56 written -> 50,000 rows | total: 2,800,000
Chunk 57 written -> 50,000 rows | total: 2,850,000
Chunk 58 written -> 50,000 rows | total: 2,900,000
Chunk 59 written -> 50,000 rows | total: 2,950,000
Chunk 60 written -> 50,000 rows | total: 3,000,000
Chunk 61 written -> 50,000 rows | total: 3,050,000
Chunk 62 written -> 50,000 rows | total: 3,100,000
Chunk 63 written -> 50,000 rows | total: 3,150,000
Chunk 64 written -> 50,000 rows | total: 3,200,000
Chunk 65 written -> 50,000 rows | total: 3,250,000
Chunk 66 written -> 50,000 rows | total: 3,300,000
Chunk 67 written -> 50,000 rows | total: 3,350,000
Chunk 68 written -> 50,000 rows | total: 3,400,000
Chunk 69 written -> 50,000 rows | total: 3,450,000
Chunk 70 written -> 50,000 rows | total: 3,500,000
Chunk 71 written -> 50,000 rows | total: 3,550,000
Chunk 72 written -> 50,000 rows | total: 3,600,000
Chunk 73 written -> 50,000 rows | total: 3,650,000
Chunk 74 written -> 50,000 rows | total: 3,700,000
Chunk 75 written -> 50,000 rows | total: 3,750,000
Chunk 76 written -> 50,000 rows | total: 3,800,000
Chunk 77 written -> 50,000 rows | total: 3,850,000
Chunk 78 written -> 50,000 rows | total: 3,900,000
Chunk 79 written -> 50,000 rows | total: 3,950,000
Chunk 80 written -> 50,000 rows | total: 4,000,000
Chunk 81 written -> 50,000 rows | total: 4,050,000
Chunk 82 written -> 50,000 rows | total: 4,100,000
Chunk 83 written -> 50,000 rows | total: 4,150,000
Chunk 84 written -> 50,000 rows | total: 4,200,000
Chunk 85 written -> 50,000 rows | total: 4,250,000
Chunk 86 written -> 50,000 rows | total: 4,300,000
Chunk 87 written -> 50,000 rows | total: 4,350,000
Chunk 88 written -> 50,000 rows | total: 4,400,000
Chunk 89 written -> 50,000 rows | total: 4,450,000
Chunk 90 written -> 50,000 rows | total: 4,500,000
Chunk 91 written -> 50,000 rows | total: 4,550,000
Chunk 92 written -> 50,000 rows | total: 4,600,000
Chunk 93 written -> 50,000 rows | total: 4,650,000
Chunk 94 written -> 50,000 rows | total: 4,700,000
Chunk 95 written -> 50,000 rows | total: 4,750,000
Chunk 96 written -> 50,000 rows | total: 4,800,000
Chunk 97 written -> 50,000 rows | total: 4,850,000
Chunk 98 written -> 50,000 rows | total: 4,900,000
Chunk 99 written -> 50,000 rows | total: 4,950,000
Chunk 100 written -> 50,000 rows | total: 5,000,000
Chunk 101 written -> 50,000 rows | total: 5,050,000
Chunk 102 written -> 50,000 rows | total: 5,100,000
Chunk 103 written -> 50,000 rows | total: 5,150,000
Chunk 104 written -> 50,000 rows | total: 5,200,000
Chunk 105 written -> 50,000 rows | total: 5,250,000
Chunk 106 written -> 50,000 rows | total: 5,300,000
Chunk 107 written -> 50,000 rows | total: 5,350,000
Chunk 108 written -> 50,000 rows | total: 5,400,000
Chunk 109 written -> 50,000 rows | total: 5,450,000
Chunk 110 written -> 50,000 rows | total: 5,500,000
Chunk 111 written -> 50,000 rows | total: 5,550,000
Chunk 112 written -> 50,000 rows | total: 5,600,000
Chunk 113 written -> 50,000 rows | total: 5,650,000
Chunk 114 written -> 50,000 rows | total: 5,700,000
Chunk 115 written -> 50,000 rows | total: 5,750,000
Chunk 116 written -> 50,000 rows | total: 5,800,000
Chunk 117 written -> 50,000 rows | total: 5,850,000
Chunk 118 written -> 50,000 rows | total: 5,900,000
Chunk 119 written -> 50,000 rows | total: 5,950,000
Chunk 120 written -> 50,000 rows | total: 6,000,000
Chunk 121 written -> 50,000 rows | total: 6,050,000
Chunk 122 written -> 50,000 rows | total: 6,100,000
Chunk 123 written -> 50,000 rows | total: 6,150,000
Chunk 124 written -> 50,000 rows | total: 6,200,000
Chunk 125 written -> 50,000 rows | total: 6,250,000
Chunk 126 written -> 50,000 rows | total: 6,300,000
Chunk 127 written -> 50,000 rows | total: 6,350,000
Chunk 128 written -> 50,000 rows | total: 6,400,000
Chunk 129 written -> 50,000 rows | total: 6,450,000
Chunk 130 written -> 50,000 rows | total: 6,500,000
Chunk 131 written -> 50,000 rows | total: 6,550,000
Chunk 132 written -> 50,000 rows | total: 6,600,000
Chunk 133 written -> 50,000 rows | total: 6,650,000
Chunk 134 written -> 50,000 rows | total: 6,700,000
Chunk 135 written -> 50,000 rows | total: 6,750,000
Chunk 136 written -> 50,000 rows | total: 6,800,000
Chunk 137 written -> 50,000 rows | total: 6,850,000
Chunk 138 written -> 50,000 rows | total: 6,900,000
Chunk 139 written -> 50,000 rows | total: 6,950,000
Chunk 140 written -> 50,000 rows | total: 7,000,000
Chunk 141 written -> 50,000 rows | total: 7,050,000
Chunk 142 written -> 50,000 rows | total: 7,100,000
Chunk 143 written -> 50,000 rows | total: 7,150,000
Chunk 144 written -> 50,000 rows | total: 7,200,000
Chunk 145 written -> 50,000 rows | total: 7,250,000
Chunk 146 written -> 50,000 rows | total: 7,300,000
Chunk 147 written -> 50,000 rows | total: 7,350,000
Chunk 148 written -> 50,000 rows | total: 7,400,000
Chunk 149 written -> 50,000 rows | total: 7,450,000
Chunk 150 written -> 50,000 rows | total: 7,500,000
Chunk 151 written -> 50,000 rows | total: 7,550,000
Chunk 152 written -> 50,000 rows | total: 7,600,000
Chunk 153 written -> 50,000 rows | total: 7,650,000
Chunk 154 written -> 50,000 rows | total: 7,700,000
Chunk 155 written -> 50,000 rows | total: 7,750,000
Chunk 156 written -> 50,000 rows | total: 7,800,000
Chunk 157 written -> 50,000 rows | total: 7,850,000
Chunk 158 written -> 50,000 rows | total: 7,900,000
Chunk 159 written -> 50,000 rows | total: 7,950,000
Chunk 160 written -> 50,000 rows | total: 8,000,000
Chunk 161 written -> 50,000 rows | total: 8,050,000
Chunk 162 written -> 50,000 rows | total: 8,100,000
Chunk 163 written -> 50,000 rows | total: 8,150,000
Chunk 164 written -> 50,000 rows | total: 8,200,000
Chunk 165 written -> 50,000 rows | total: 8,250,000
Chunk 166 written -> 50,000 rows | total: 8,300,000
Chunk 167 written -> 50,000 rows | total: 8,350,000
Chunk 168 written -> 50,000 rows | total: 8,400,000
Chunk 169 written -> 50,000 rows | total: 8,450,000
Chunk 170 written -> 50,000 rows | total: 8,500,000
Chunk 171 written -> 50,000 rows | total: 8,550,000
Chunk 172 written -> 50,000 rows | total: 8,600,000
Chunk 173 written -> 50,000 rows | total: 8,650,000
Chunk 174 written -> 50,000 rows | total: 8,700,000
Chunk 175 written -> 50,000 rows | total: 8,750,000
Chunk 176 written -> 50,000 rows | total: 8,800,000
Chunk 177 written -> 50,000 rows | total: 8,850,000
Chunk 178 written -> 50,000 rows | total: 8,900,000
Chunk 179 written -> 50,000 rows | total: 8,950,000
Chunk 180 written -> 50,000 rows | total: 9,000,000
Chunk 181 written -> 50,000 rows | total: 9,050,000
Chunk 182 written -> 50,000 rows | total: 9,100,000
Chunk 183 written -> 50,000 rows | total: 9,150,000
Chunk 184 written -> 50,000 rows | total: 9,200,000
Chunk 185 written -> 50,000 rows | total: 9,250,000
Chunk 186 written -> 50,000 rows | total: 9,300,000
Chunk 187 written -> 50,000 rows | total: 9,350,000
Chunk 188 written -> 50,000 rows | total: 9,400,000
Chunk 189 written -> 50,000 rows | total: 9,450,000
Chunk 190 written -> 50,000 rows | total: 9,500,000
Chunk 191 written -> 50,000 rows | total: 9,550,000
Chunk 192 written -> 50,000 rows | total: 9,600,000
Chunk 193 written -> 50,000 rows | total: 9,650,000
Chunk 194 written -> 50,000 rows | total: 9,700,000
Chunk 195 written -> 50,000 rows | total: 9,750,000
Chunk 196 written -> 50,000 rows | total: 9,800,000
Chunk 197 written -> 50,000 rows | total: 9,850,000
Chunk 198 written -> 50,000 rows | total: 9,900,000
Chunk 199 written -> 50,000 rows | total: 9,950,000
Chunk 200 written -> 50,000 rows | total: 10,000,000
Chunk 201 written -> 50,000 rows | total: 10,050,000
Chunk 202 written -> 50,000 rows | total: 10,100,000
Chunk 203 written -> 50,000 rows | total: 10,150,000
Chunk 204 written -> 50,000 rows | total: 10,200,000
Chunk 205 written -> 50,000 rows | total: 10,250,000
Chunk 206 written -> 50,000 rows | total: 10,300,000
Chunk 207 written -> 50,000 rows | total: 10,350,000
Chunk 208 written -> 50,000 rows | total: 10,400,000
Chunk 209 written -> 50,000 rows | total: 10,450,000
Chunk 210 written -> 50,000 rows | total: 10,500,000
Chunk 211 written -> 50,000 rows | total: 10,550,000
Chunk 212 written -> 50,000 rows | total: 10,600,000
Chunk 213 written -> 50,000 rows | total: 10,650,000
Chunk 214 written -> 50,000 rows | total: 10,700,000
Chunk 215 written -> 50,000 rows | total: 10,750,000
Chunk 216 written -> 50,000 rows | total: 10,800,000
Chunk 217 written -> 50,000 rows | total: 10,850,000
Chunk 218 written -> 50,000 rows | total: 10,900,000
Chunk 219 written -> 50,000 rows | total: 10,950,000
Chunk 220 written -> 50,000 rows | total: 11,000,000
Chunk 221 written -> 50,000 rows | total: 11,050,000
Chunk 222 written -> 50,000 rows | total: 11,100,000
Chunk 223 written -> 50,000 rows | total: 11,150,000
Chunk 224 written -> 50,000 rows | total: 11,200,000
Chunk 225 written -> 50,000 rows | total: 11,250,000
Chunk 226 written -> 50,000 rows | total: 11,300,000
Chunk 227 written -> 50,000 rows | total: 11,350,000
Chunk 228 written -> 50,000 rows | total: 11,400,000
Chunk 229 written -> 50,000 rows | total: 11,450,000
Chunk 230 written -> 50,000 rows | total: 11,500,000
Chunk 231 written -> 50,000 rows | total: 11,550,000
Chunk 232 written -> 50,000 rows | total: 11,600,000
Chunk 233 written -> 50,000 rows | total: 11,650,000
Chunk 234 written -> 50,000 rows | total: 11,700,000
Chunk 235 written -> 50,000 rows | total: 11,750,000
Chunk 236 written -> 50,000 rows | total: 11,800,000
Chunk 237 written -> 50,000 rows | total: 11,850,000
Chunk 238 written -> 50,000 rows | total: 11,900,000
Chunk 239 written -> 50,000 rows | total: 11,950,000
Chunk 240 written -> 50,000 rows | total: 12,000,000
Chunk 241 written -> 50,000 rows | total: 12,050,000
Chunk 242 written -> 50,000 rows | total: 12,100,000
Chunk 243 written -> 50,000 rows | total: 12,150,000
Chunk 244 written -> 50,000 rows | total: 12,200,000
Chunk 245 written -> 50,000 rows | total: 12,250,000
Chunk 246 written -> 50,000 rows | total: 12,300,000
Chunk 247 written -> 50,000 rows | total: 12,350,000
Chunk 248 written -> 50,000 rows | total: 12,400,000
Chunk 249 written -> 50,000 rows | total: 12,450,000
Chunk 250 written -> 50,000 rows | total: 12,500,000
Chunk 251 written -> 50,000 rows | total: 12,550,000
Chunk 252 written -> 50,000 rows | total: 12,600,000
Chunk 253 written -> 50,000 rows | total: 12,650,000
Chunk 254 written -> 50,000 rows | total: 12,700,000
Chunk 255 written -> 50,000 rows | total: 12,750,000
Chunk 256 written -> 50,000 rows | total: 12,800,000
Chunk 257 written -> 50,000 rows | total: 12,850,000
Chunk 258 written -> 50,000 rows | total: 12,900,000
Chunk 259 written -> 50,000 rows | total: 12,950,000
Chunk 260 written -> 50,000 rows | total: 13,000,000
Chunk 261 written -> 50,000 rows | total: 13,050,000
Chunk 262 written -> 50,000 rows | total: 13,100,000
Chunk 263 written -> 50,000 rows | total: 13,150,000
Chunk 264 written -> 50,000 rows | total: 13,200,000
Chunk 265 written -> 50,000 rows | total: 13,250,000
Chunk 266 written -> 50,000 rows | total: 13,300,000
Chunk 267 written -> 50,000 rows | total: 13,350,000
Chunk 268 written -> 50,000 rows | total: 13,400,000
Chunk 269 written -> 50,000 rows | total: 13,450,000
Chunk 270 written -> 50,000 rows | total: 13,500,000
Chunk 271 written -> 50,000 rows | total: 13,550,000
Chunk 272 written -> 50,000 rows | total: 13,600,000
Chunk 273 written -> 50,000 rows | total: 13,650,000
Chunk 274 written -> 50,000 rows | total: 13,700,000
Chunk 275 written -> 50,000 rows | total: 13,750,000
Chunk 276 written -> 50,000 rows | total: 13,800,000
Chunk 277 written -> 50,000 rows | total: 13,850,000
Chunk 278 written -> 50,000 rows | total: 13,900,000
Chunk 279 written -> 50,000 rows | total: 13,950,000
Chunk 280 written -> 50,000 rows | total: 14,000,000
Chunk 281 written -> 50,000 rows | total: 14,050,000
Chunk 282 written -> 50,000 rows | total: 14,100,000
Chunk 283 written -> 50,000 rows | total: 14,150,000
Chunk 284 written -> 50,000 rows | total: 14,200,000
Chunk 285 written -> 50,000 rows | total: 14,250,000
Chunk 286 written -> 50,000 rows | total: 14,300,000
Chunk 287 written -> 50,000 rows | total: 14,350,000
Chunk 288 written -> 50,000 rows | total: 14,400,000
Chunk 289 written -> 50,000 rows | total: 14,450,000
Chunk 290 written -> 50,000 rows | total: 14,500,000
Chunk 291 written -> 50,000 rows | total: 14,550,000
Chunk 292 written -> 50,000 rows | total: 14,600,000
Chunk 293 written -> 50,000 rows | total: 14,650,000
Chunk 294 written -> 50,000 rows | total: 14,700,000
Chunk 295 written -> 50,000 rows | total: 14,750,000
Chunk 296 written -> 50,000 rows | total: 14,800,000
Chunk 297 written -> 50,000 rows | total: 14,850,000
Chunk 298 written -> 50,000 rows | total: 14,900,000
Chunk 299 written -> 50,000 rows | total: 14,950,000
Chunk 300 written -> 50,000 rows | total: 15,000,000
Chunk 301 written -> 50,000 rows | total: 15,050,000
Chunk 302 written -> 50,000 rows | total: 15,100,000
Chunk 303 written -> 50,000 rows | total: 15,150,000
Chunk 304 written -> 50,000 rows | total: 15,200,000
Chunk 305 written -> 50,000 rows | total: 15,250,000
Chunk 306 written -> 50,000 rows | total: 15,300,000
Chunk 307 written -> 50,000 rows | total: 15,350,000
Chunk 308 written -> 50,000 rows | total: 15,400,000
Chunk 309 written -> 50,000 rows | total: 15,450,000
Chunk 310 written -> 50,000 rows | total: 15,500,000
Chunk 311 written -> 50,000 rows | total: 15,550,000
Chunk 312 written -> 50,000 rows | total: 15,600,000
Chunk 313 written -> 50,000 rows | total: 15,650,000
Chunk 314 written -> 50,000 rows | total: 15,700,000
Chunk 315 written -> 50,000 rows | total: 15,750,000
Chunk 316 written -> 50,000 rows | total: 15,800,000
Chunk 317 written -> 50,000 rows | total: 15,850,000
Chunk 318 written -> 50,000 rows | total: 15,900,000
Chunk 319 written -> 50,000 rows | total: 15,950,000
Chunk 320 written -> 50,000 rows | total: 16,000,000
Chunk 321 written -> 50,000 rows | total: 16,050,000
Chunk 322 written -> 50,000 rows | total: 16,100,000
Chunk 323 written -> 50,000 rows | total: 16,150,000
Chunk 324 written -> 50,000 rows | total: 16,200,000
Chunk 325 written -> 50,000 rows | total: 16,250,000
Chunk 326 written -> 50,000 rows | total: 16,300,000
Chunk 327 written -> 50,000 rows | total: 16,350,000
Chunk 328 written -> 50,000 rows | total: 16,400,000
Chunk 329 written -> 50,000 rows | total: 16,450,000
Chunk 330 written -> 50,000 rows | total: 16,500,000
Chunk 331 written -> 50,000 rows | total: 16,550,000
Chunk 332 written -> 50,000 rows | total: 16,600,000
Chunk 333 written -> 50,000 rows | total: 16,650,000
Chunk 334 written -> 50,000 rows | total: 16,700,000
Chunk 335 written -> 50,000 rows | total: 16,750,000
Chunk 336 written -> 50,000 rows | total: 16,800,000
Chunk 337 written -> 50,000 rows | total: 16,850,000
Chunk 338 written -> 50,000 rows | total: 16,900,000
Chunk 339 written -> 50,000 rows | total: 16,950,000
Chunk 340 written -> 50,000 rows | total: 17,000,000
Chunk 341 written -> 50,000 rows | total: 17,050,000
Chunk 342 written -> 50,000 rows | total: 17,100,000
Chunk 343 written -> 50,000 rows | total: 17,150,000
Chunk 344 written -> 50,000 rows | total: 17,200,000
Chunk 345 written -> 50,000 rows | total: 17,250,000
Chunk 346 written -> 50,000 rows | total: 17,300,000
Chunk 347 written -> 50,000 rows | total: 17,350,000
Chunk 348 written -> 50,000 rows | total: 17,400,000
Chunk 349 written -> 50,000 rows | total: 17,450,000
Chunk 350 written -> 50,000 rows | total: 17,500,000
Chunk 351 written -> 50,000 rows | total: 17,550,000
Chunk 352 written -> 50,000 rows | total: 17,600,000
Chunk 353 written -> 50,000 rows | total: 17,650,000
Chunk 354 written -> 50,000 rows | total: 17,700,000
Chunk 355 written -> 50,000 rows | total: 17,750,000
Chunk 356 written -> 50,000 rows | total: 17,800,000
Chunk 357 written -> 50,000 rows | total: 17,850,000
Chunk 358 written -> 50,000 rows | total: 17,900,000
Chunk 359 written -> 50,000 rows | total: 17,950,000
Chunk 360 written -> 50,000 rows | total: 18,000,000
Chunk 361 written -> 50,000 rows | total: 18,050,000
Chunk 362 written -> 50,000 rows | total: 18,100,000
Chunk 363 written -> 50,000 rows | total: 18,150,000
Chunk 364 written -> 50,000 rows | total: 18,200,000
Chunk 365 written -> 50,000 rows | total: 18,250,000
Chunk 366 written -> 50,000 rows | total: 18,300,000
Chunk 367 written -> 50,000 rows | total: 18,350,000
Chunk 368 written -> 50,000 rows | total: 18,400,000
Chunk 369 written -> 50,000 rows | total: 18,450,000
Chunk 370 written -> 50,000 rows | total: 18,500,000
Chunk 371 written -> 50,000 rows | total: 18,550,000
Chunk 372 written -> 50,000 rows | total: 18,600,000
Chunk 373 written -> 50,000 rows | total: 18,650,000
Chunk 374 written -> 50,000 rows | total: 18,700,000
Chunk 375 written -> 50,000 rows | total: 18,750,000
Chunk 376 written -> 50,000 rows | total: 18,800,000
Chunk 377 written -> 50,000 rows | total: 18,850,000
Chunk 378 written -> 50,000 rows | total: 18,900,000
Chunk 379 written -> 50,000 rows | total: 18,950,000
Chunk 380 written -> 50,000 rows | total: 19,000,000
Chunk 381 written -> 50,000 rows | total: 19,050,000
Chunk 382 written -> 50,000 rows | total: 19,100,000
Chunk 383 written -> 50,000 rows | total: 19,150,000

### **Original vs Standard Column Names**

| Original Column Name            | Standardized              | Description                                      |
|--------------------------------|---------------------------|--------------------------------------------------|
| **No disposition**             | `transaction_id`          | Unique identifier of the transaction             |
| **Date mutation**              | `transaction_date`        | Date when the property was sold                  |
| **Nature mutation**            | `transaction_type`        | Nature of transaction (sale, exchange, etc.)     |
| **Valeur fonciere**            | `property_value`          | Transaction price in euros                       |
| **No voie**                    | `street_number`           | Street number of the property                    |
| **B/T/Q**                      | `btq_code`                | Building / Type / Quarter code                   |
| **Type de voie**               | `street_type`             | Type of street (Rue, Avenue, etc.)               |
| **Code voie**                  | `street_id`               | Street identifier code                           |
| **Voie**                       | `street_name`             | Full street name                                 |
| **Code postal**                | `postal_code`             | Postal code (categorical, not numeric)           |
| **Commune**                    | `com_name`                | Commune name                                     |
| **Code departement**           | `dep_code`                | Department code: DD                              |
| **Code commune**               | `com_code`                | Commune code: CCC                                |
| **Prefixe de section**         | `section_prefix`          | Section prefix (cadastral division)              |
| **Section**                    | `section`                 | Cadastral section identifier                     |
| **No plan**                    | `plot_number`             | Parcel/plot number                               |
| **No Volume**                  | `volume_number`           | Volume number (rarely used cadastral info)       |
| **1er lot**                    | `lot_1`                   | Identifier of the first lot                      |
| **Surface Carrez du 1er lot**  | `lot_1_surface`    | Carrez surface of the first lot (m²)             |
| **2eme lot**                   | `lot_2`                   | Identifier of the second lot                     |
| **Surface Carrez du 2eme lot** | `lot_2_surface`    | Carrez surface of the second lot (m²)            |
| **3eme lot**                   | `lot_3`                   | Identifier of the third lot                      |
| **Surface Carrez du 3eme lot** | `lot_3_surface`    | Carrez surface of the third lot (m²)             |
| **4eme lot**                   | `lot_4`                   | Identifier of the fourth lot                     |
| **Surface Carrez du 4eme lot** | `lot_4_surface`    | Carrez surface of the fourth lot (m²)            |
| **5eme lot**                   | `lot_5`                   | Identifier of the fifth lot                      |
| **Surface Carrez du 5eme lot** | `lot_5_surface`    | Carrez surface of the fifth lot (m²)             |
| **Nombre de lots**             | `lots_count`          | Number of lots in the transaction                |
| **Code type local**            | `property_type_code`      | Code for property type                           |
| **Type local**                 | `property_type`           | Property type (Apartment, House, etc.)           |
| **Surface reelle bati**        | `building_real_surface`   | Built area in square meters                      |
| **Nombre pieces principales**  | `main_rooms_count`        | Number of main rooms                             |
| **Nature culture**             | `land_nature`             | Type of land usage                               |
| **Nature culture speciale**    | `land_nature_special`     | Specific land usage classification               |
| **Surface terrain**            | `land_surface`            | Land area in square meters                       |

### **RENAME COLUMNS**

In [42]:
from pathlib import Path
import pandas as pd

INPUT_FILE = Path("../data/processed/DROP_ValeursFoncieres.csv")
OUTPUT_FILE = Path("../data/processed/STANDARD_ValeursFoncieres.csv")

CHUNK_SIZE = 50_000

# ---------------------------------------------
# Define the renaming dictionary
# ---------------------------------------------
rename_columns = {
    "No disposition": "transaction_id",
    "Date mutation": "transaction_date",
    "Nature mutation": "transaction_type",
    "Valeur fonciere": "property_value",
    "No voie": "street_number",
    "B/T/Q": "btq_code",
    "Type de voie": "street_type",
    "Code voie": "street_id",
    "Voie": "street_name",
    "Code postal": "postal_code",
    "Commune": "com_name",
    "Code departement": "dep_code",
    "Code commune": "com_code",
    "Prefixe de section": "section_prefix",
    "Section": "section",
    "No plan": "plot_number",
    "No Volume": "volume_number",

    # Lot identifier and surface
    "1er lot": "lot_1",
    "Surface Carrez du 1er lot": "lot_1_surface",
    "2eme lot": "lot_2",
    "Surface Carrez du 2eme lot": "lot_2_surface",
    "3eme lot": "lot_3",
    "Surface Carrez du 3eme lot": "lot_3_surface",
    "4eme lot": "lot_4",
    "Surface Carrez du 4eme lot": "lot_4_surface",
    "5eme lot": "lot_5",
    "Surface Carrez du 5eme lot": "lot_5_surface",

    "Nombre de lots": "lots_count",

    "Code type local": "property_type_code",
    "Type local": "property_type",
    "Surface reelle bati": "building_real_surface",
    "Nombre pieces principales": "main_rooms_count",
    "Nature culture": "land_nature",
    "Nature culture speciale": "land_nature_special",
    "Surface terrain": "land_surface"
}

def rename_columns_chunked(
    input_file: Path,
    output_file: Path,
    rename_dict: dict,
    chunk_size: int = 50_000
) -> None:
    output_file.parent.mkdir(parents=True, exist_ok=True)

    first_write = True
    total_rows = 0

    for chunk_idx, chunk in enumerate(
        pd.read_csv(input_file, chunksize=chunk_size, dtype=str),
        start=1
    ):
        chunk = chunk.rename(columns=rename_dict)

        chunk.to_csv(
            output_file,
            mode="w" if first_write else "a",
            index=False,
            header=first_write,
            encoding="utf-8"
        )

        first_write = False
        total_rows += len(chunk)

        print(f"Chunk {chunk_idx} written -> {len(chunk):,} rows | total: {total_rows:,}")

    print("\nDone! Standardized columns")
    print(f"Saved file: {output_file}")
    print(f"Shape: {total_rows:,} rows and {len(rename_dict)} columns")

rename_columns_chunked(INPUT_FILE, OUTPUT_FILE, rename_columns, CHUNK_SIZE)

Chunk 1 written -> 50,000 rows | total: 50,000
Chunk 2 written -> 50,000 rows | total: 100,000
Chunk 3 written -> 50,000 rows | total: 150,000
Chunk 4 written -> 50,000 rows | total: 200,000
Chunk 5 written -> 50,000 rows | total: 250,000
Chunk 6 written -> 50,000 rows | total: 300,000
Chunk 7 written -> 50,000 rows | total: 350,000
Chunk 8 written -> 50,000 rows | total: 400,000
Chunk 9 written -> 50,000 rows | total: 450,000
Chunk 10 written -> 50,000 rows | total: 500,000
Chunk 11 written -> 50,000 rows | total: 550,000
Chunk 12 written -> 50,000 rows | total: 600,000
Chunk 13 written -> 50,000 rows | total: 650,000
Chunk 14 written -> 50,000 rows | total: 700,000
Chunk 15 written -> 50,000 rows | total: 750,000
Chunk 16 written -> 50,000 rows | total: 800,000
Chunk 17 written -> 50,000 rows | total: 850,000
Chunk 18 written -> 50,000 rows | total: 900,000
Chunk 19 written -> 50,000 rows | total: 950,000
Chunk 20 written -> 50,000 rows | total: 1,000,000
Chunk 21 written -> 50,000 rows | total: 1,050,000
Chunk 22 written -> 50,000 rows | total: 1,100,000
Chunk 23 written -> 50,000 rows | total: 1,150,000
Chunk 24 written -> 50,000 rows | total: 1,200,000
Chunk 25 written -> 50,000 rows | total: 1,250,000
Chunk 26 written -> 50,000 rows | total: 1,300,000
Chunk 27 written -> 50,000 rows | total: 1,350,000
Chunk 28 written -> 50,000 rows | total: 1,400,000
Chunk 29 written -> 50,000 rows | total: 1,450,000
Chunk 30 written -> 50,000 rows | total: 1,500,000
Chunk 31 written -> 50,000 rows | total: 1,550,000
Chunk 32 written -> 50,000 rows | total: 1,600,000
Chunk 33 written -> 50,000 rows | total: 1,650,000
Chunk 34 written -> 50,000 rows | total: 1,700,000
Chunk 35 written -> 50,000 rows | total: 1,750,000
Chunk 36 written -> 50,000 rows | total: 1,800,000
Chunk 37 written -> 50,000 rows | total: 1,850,000
Chunk 38 written -> 50,000 rows | total: 1,900,000
Chunk 39 written -> 50,000 rows | total: 1,950,000
Chunk 40 written -> 50,000 rows | total: 2,000,000
Chunk 41 written -> 50,000 rows | total: 2,050,000
Chunk 42 written -> 50,000 rows | total: 2,100,000
Chunk 43 written -> 50,000 rows | total: 2,150,000
Chunk 44 written -> 50,000 rows | total: 2,200,000
Chunk 45 written -> 50,000 rows | total: 2,250,000
Chunk 46 written -> 50,000 rows | total: 2,300,000
Chunk 47 written -> 50,000 rows | total: 2,350,000
Chunk 48 written -> 50,000 rows | total: 2,400,000
Chunk 49 written -> 50,000 rows | total: 2,450,000
Chunk 50 written -> 50,000 rows | total: 2,500,000
Chunk 51 written -> 50,000 rows | total: 2,550,000
Chunk 52 written -> 50,000 rows | total: 2,600,000
Chunk 53 written -> 50,000 rows | total: 2,650,000
Chunk 54 written -> 50,000 rows | total: 2,700,000
Chunk 55 written -> 50,000 rows | total: 2,750,000
Chunk 56 written -> 50,000 rows | total: 2,800,000
Chunk 57 written -> 50,000 rows | total: 2,850,000
Chunk 58 written -> 50,000 rows | total: 2,900,000
Chunk 59 written -> 50,000 rows | total: 2,950,000
Chunk 60 written -> 50,000 rows | total: 3,000,000
Chunk 61 written -> 50,000 rows | total: 3,050,000
Chunk 62 written -> 50,000 rows | total: 3,100,000
Chunk 63 written -> 50,000 rows | total: 3,150,000
Chunk 64 written -> 50,000 rows | total: 3,200,000
Chunk 65 written -> 50,000 rows | total: 3,250,000
Chunk 66 written -> 50,000 rows | total: 3,300,000
Chunk 67 written -> 50,000 rows | total: 3,350,000
Chunk 68 written -> 50,000 rows | total: 3,400,000
Chunk 69 written -> 50,000 rows | total: 3,450,000
Chunk 70 written -> 50,000 rows | total: 3,500,000
Chunk 71 written -> 50,000 rows | total: 3,550,000
Chunk 72 written -> 50,000 rows | total: 3,600,000
Chunk 73 written -> 50,000 rows | total: 3,650,000
Chunk 74 written -> 50,000 rows | total: 3,700,000
Chunk 75 written -> 50,000 rows | total: 3,750,000
Chunk 76 written -> 50,000 rows | total: 3,800,000
Chunk 77 written -> 50,000 rows | total: 3,850,000
Chunk 78 written -> 50,000 rows | total: 3,900,000
Chunk 79 written -> 50,000 rows | total: 3,950,000
Chunk 80 written -> 50,000 rows | total: 4,000,000
Chunk 81 written -> 50,000 rows | total: 4,050,000
Chunk 82 written -> 50,000 rows | total: 4,100,000
Chunk 83 written -> 50,000 rows | total: 4,150,000
Chunk 84 written -> 50,000 rows | total: 4,200,000
Chunk 85 written -> 50,000 rows | total: 4,250,000
Chunk 86 written -> 50,000 rows | total: 4,300,000
Chunk 87 written -> 50,000 rows | total: 4,350,000
Chunk 88 written -> 50,000 rows | total: 4,400,000
Chunk 89 written -> 50,000 rows | total: 4,450,000
Chunk 90 written -> 50,000 rows | total: 4,500,000
Chunk 91 written -> 50,000 rows | total: 4,550,000
Chunk 92 written -> 50,000 rows | total: 4,600,000
Chunk 93 written -> 50,000 rows | total: 4,650,000
Chunk 94 written -> 50,000 rows | total: 4,700,000
Chunk 95 written -> 50,000 rows | total: 4,750,000
Chunk 96 written -> 50,000 rows | total: 4,800,000
Chunk 97 written -> 50,000 rows | total: 4,850,000
Chunk 98 written -> 50,000 rows | total: 4,900,000
Chunk 99 written -> 50,000 rows | total: 4,950,000
Chunk 100 written -> 50,000 rows | total: 5,000,000
Chunk 101 written -> 50,000 rows | total: 5,050,000
Chunk 102 written -> 50,000 rows | total: 5,100,000
Chunk 103 written -> 50,000 rows | total: 5,150,000
Chunk 104 written -> 50,000 rows | total: 5,200,000
Chunk 105 written -> 50,000 rows | total: 5,250,000
Chunk 106 written -> 50,000 rows | total: 5,300,000
Chunk 107 written -> 50,000 rows | total: 5,350,000
Chunk 108 written -> 50,000 rows | total: 5,400,000
Chunk 109 written -> 50,000 rows | total: 5,450,000
Chunk 110 written -> 50,000 rows | total: 5,500,000
Chunk 111 written -> 50,000 rows | total: 5,550,000
Chunk 112 written -> 50,000 rows | total: 5,600,000
Chunk 113 written -> 50,000 rows | total: 5,650,000
Chunk 114 written -> 50,000 rows | total: 5,700,000
Chunk 115 written -> 50,000 rows | total: 5,750,000
Chunk 116 written -> 50,000 rows | total: 5,800,000
Chunk 117 written -> 50,000 rows | total: 5,850,000
Chunk 118 written -> 50,000 rows | total: 5,900,000
Chunk 119 written -> 50,000 rows | total: 5,950,000
Chunk 120 written -> 50,000 rows | total: 6,000,000
Chunk 121 written -> 50,000 rows | total: 6,050,000
Chunk 122 written -> 50,000 rows | total: 6,100,000
Chunk 123 written -> 50,000 rows | total: 6,150,000
Chunk 124 written -> 50,000 rows | total: 6,200,000
Chunk 125 written -> 50,000 rows | total: 6,250,000
Chunk 126 written -> 50,000 rows | total: 6,300,000
Chunk 127 written -> 50,000 rows | total: 6,350,000
Chunk 128 written -> 50,000 rows | total: 6,400,000
Chunk 129 written -> 50,000 rows | total: 6,450,000
Chunk 130 written -> 50,000 rows | total: 6,500,000
Chunk 131 written -> 50,000 rows | total: 6,550,000
Chunk 132 written -> 50,000 rows | total: 6,600,000
Chunk 133 written -> 50,000 rows | total: 6,650,000
Chunk 134 written -> 50,000 rows | total: 6,700,000
Chunk 135 written -> 50,000 rows | total: 6,750,000
Chunk 136 written -> 50,000 rows | total: 6,800,000
Chunk 137 written -> 50,000 rows | total: 6,850,000
Chunk 138 written -> 50,000 rows | total: 6,900,000
Chunk 139 written -> 50,000 rows | total: 6,950,000
Chunk 140 written -> 50,000 rows | total: 7,000,000
Chunk 141 written -> 50,000 rows | total: 7,050,000
Chunk 142 written -> 50,000 rows | total: 7,100,000
Chunk 143 written -> 50,000 rows | total: 7,150,000
Chunk 144 written -> 50,000 rows | total: 7,200,000
Chunk 145 written -> 50,000 rows | total: 7,250,000
Chunk 146 written -> 50,000 rows | total: 7,300,000
Chunk 147 written -> 50,000 rows | total: 7,350,000
Chunk 148 written -> 50,000 rows | total: 7,400,000
Chunk 149 written -> 50,000 rows | total: 7,450,000
Chunk 150 written -> 50,000 rows | total: 7,500,000
Chunk 151 written -> 50,000 rows | total: 7,550,000
Chunk 152 written -> 50,000 rows | total: 7,600,000
Chunk 153 written -> 50,000 rows | total: 7,650,000
Chunk 154 written -> 50,000 rows | total: 7,700,000
Chunk 155 written -> 50,000 rows | total: 7,750,000
Chunk 156 written -> 50,000 rows | total: 7,800,000
Chunk 157 written -> 50,000 rows | total: 7,850,000
Chunk 158 written -> 50,000 rows | total: 7,900,000
Chunk 159 written -> 50,000 rows | total: 7,950,000
Chunk 160 written -> 50,000 rows | total: 8,000,000
Chunk 161 written -> 50,000 rows | total: 8,050,000
Chunk 162 written -> 50,000 rows | total: 8,100,000
Chunk 163 written -> 50,000 rows | total: 8,150,000
Chunk 164 written -> 50,000 rows | total: 8,200,000
Chunk 165 written -> 50,000 rows | total: 8,250,000
Chunk 166 written -> 50,000 rows | total: 8,300,000
Chunk 167 written -> 50,000 rows | total: 8,350,000
Chunk 168 written -> 50,000 rows | total: 8,400,000
Chunk 169 written -> 50,000 rows | total: 8,450,000
Chunk 170 written -> 50,000 rows | total: 8,500,000
Chunk 171 written -> 50,000 rows | total: 8,550,000
Chunk 172 written -> 50,000 rows | total: 8,600,000
Chunk 173 written -> 50,000 rows | total: 8,650,000
Chunk 174 written -> 50,000 rows | total: 8,700,000
Chunk 175 written -> 50,000 rows | total: 8,750,000
Chunk 176 written -> 50,000 rows | total: 8,800,000
Chunk 177 written -> 50,000 rows | total: 8,850,000
Chunk 178 written -> 50,000 rows | total: 8,900,000
Chunk 179 written -> 50,000 rows | total: 8,950,000
Chunk 180 written -> 50,000 rows | total: 9,000,000
Chunk 181 written -> 50,000 rows | total: 9,050,000
Chunk 182 written -> 50,000 rows | total: 9,100,000
Chunk 183 written -> 50,000 rows | total: 9,150,000
Chunk 184 written -> 50,000 rows | total: 9,200,000
Chunk 185 written -> 50,000 rows | total: 9,250,000
Chunk 186 written -> 50,000 rows | total: 9,300,000
Chunk 187 written -> 50,000 rows | total: 9,350,000
Chunk 188 written -> 50,000 rows | total: 9,400,000
Chunk 189 written -> 50,000 rows | total: 9,450,000
Chunk 190 written -> 50,000 rows | total: 9,500,000
Chunk 191 written -> 50,000 rows | total: 9,550,000
Chunk 192 written -> 50,000 rows | total: 9,600,000
Chunk 193 written -> 50,000 rows | total: 9,650,000
Chunk 194 written -> 50,000 rows | total: 9,700,000
Chunk 195 written -> 50,000 rows | total: 9,750,000
Chunk 196 written -> 50,000 rows | total: 9,800,000
Chunk 197 written -> 50,000 rows | total: 9,850,000
Chunk 198 written -> 50,000 rows | total: 9,900,000
Chunk 199 written -> 50,000 rows | total: 9,950,000
Chunk 200 written -> 50,000 rows | total: 10,000,000
Chunk 201 written -> 50,000 rows | total: 10,050,000
Chunk 202 written -> 50,000 rows | total: 10,100,000
Chunk 203 written -> 50,000 rows | total: 10,150,000
Chunk 204 written -> 50,000 rows | total: 10,200,000
Chunk 205 written -> 50,000 rows | total: 10,250,000
Chunk 206 written -> 50,000 rows | total: 10,300,000
Chunk 207 written -> 50,000 rows | total: 10,350,000
Chunk 208 written -> 50,000 rows | total: 10,400,000
Chunk 209 written -> 50,000 rows | total: 10,450,000
Chunk 210 written -> 50,000 rows | total: 10,500,000
Chunk 211 written -> 50,000 rows | total: 10,550,000
Chunk 212 written -> 50,000 rows | total: 10,600,000
Chunk 213 written -> 50,000 rows | total: 10,650,000
Chunk 214 written -> 50,000 rows | total: 10,700,000
Chunk 215 written -> 50,000 rows | total: 10,750,000
Chunk 216 written -> 50,000 rows | total: 10,800,000
Chunk 217 written -> 50,000 rows | total: 10,850,000
Chunk 218 written -> 50,000 rows | total: 10,900,000
Chunk 219 written -> 50,000 rows | total: 10,950,000
Chunk 220 written -> 50,000 rows | total: 11,000,000
Chunk 221 written -> 50,000 rows | total: 11,050,000
Chunk 222 written -> 50,000 rows | total: 11,100,000
Chunk 223 written -> 50,000 rows | total: 11,150,000
Chunk 224 written -> 50,000 rows | total: 11,200,000
Chunk 225 written -> 50,000 rows | total: 11,250,000
Chunk 226 written -> 50,000 rows | total: 11,300,000
Chunk 227 written -> 50,000 rows | total: 11,350,000
Chunk 228 written -> 50,000 rows | total: 11,400,000
Chunk 229 written -> 50,000 rows | total: 11,450,000
Chunk 230 written -> 50,000 rows | total: 11,500,000
Chunk 231 written -> 50,000 rows | total: 11,550,000
Chunk 232 written -> 50,000 rows | total: 11,600,000
Chunk 233 written -> 50,000 rows | total: 11,650,000
Chunk 234 written -> 50,000 rows | total: 11,700,000
Chunk 235 written -> 50,000 rows | total: 11,750,000
Chunk 236 written -> 50,000 rows | total: 11,800,000
Chunk 237 written -> 50,000 rows | total: 11,850,000
Chunk 238 written -> 50,000 rows | total: 11,900,000
Chunk 239 written -> 50,000 rows | total: 11,950,000
Chunk 240 written -> 50,000 rows | total: 12,000,000
Chunk 241 written -> 50,000 rows | total: 12,050,000
Chunk 242 written -> 50,000 rows | total: 12,100,000
Chunk 243 written -> 50,000 rows | total: 12,150,000
Chunk 244 written -> 50,000 rows | total: 12,200,000
Chunk 245 written -> 50,000 rows | total: 12,250,000
Chunk 246 written -> 50,000 rows | total: 12,300,000
Chunk 247 written -> 50,000 rows | total: 12,350,000
Chunk 248 written -> 50,000 rows | total: 12,400,000
Chunk 249 written -> 50,000 rows | total: 12,450,000
Chunk 250 written -> 50,000 rows | total: 12,500,000
Chunk 251 written -> 50,000 rows | total: 12,550,000
Chunk 252 written -> 50,000 rows | total: 12,600,000
Chunk 253 written -> 50,000 rows | total: 12,650,000
Chunk 254 written -> 50,000 rows | total: 12,700,000
Chunk 255 written -> 50,000 rows | total: 12,750,000
Chunk 256 written -> 50,000 rows | total: 12,800,000
Chunk 257 written -> 50,000 rows | total: 12,850,000
Chunk 258 written -> 50,000 rows | total: 12,900,000
Chunk 259 written -> 50,000 rows | total: 12,950,000
Chunk 260 written -> 50,000 rows | total: 13,000,000
Chunk 261 written -> 50,000 rows | total: 13,050,000
Chunk 262 written -> 50,000 rows | total: 13,100,000
Chunk 263 written -> 50,000 rows | total: 13,150,000
Chunk 264 written -> 50,000 rows | total: 13,200,000
Chunk 265 written -> 50,000 rows | total: 13,250,000
Chunk 266 written -> 50,000 rows | total: 13,300,000
Chunk 267 written -> 50,000 rows | total: 13,350,000
Chunk 268 written -> 50,000 rows | total: 13,400,000
Chunk 269 written -> 50,000 rows | total: 13,450,000
Chunk 270 written -> 50,000 rows | total: 13,500,000
Chunk 271 written -> 50,000 rows | total: 13,550,000
Chunk 272 written -> 50,000 rows | total: 13,600,000
Chunk 273 written -> 50,000 rows | total: 13,650,000
Chunk 274 written -> 50,000 rows | total: 13,700,000
Chunk 275 written -> 50,000 rows | total: 13,750,000
Chunk 276 written -> 50,000 rows | total: 13,800,000
Chunk 277 written -> 50,000 rows | total: 13,850,000
Chunk 278 written -> 50,000 rows | total: 13,900,000
Chunk 279 written -> 50,000 rows | total: 13,950,000
Chunk 280 written -> 50,000 rows | total: 14,000,000
Chunk 281 written -> 50,000 rows | total: 14,050,000
Chunk 282 written -> 50,000 rows | total: 14,100,000
Chunk 283 written -> 50,000 rows | total: 14,150,000
Chunk 284 written -> 50,000 rows | total: 14,200,000
Chunk 285 written -> 50,000 rows | total: 14,250,000
Chunk 286 written -> 50,000 rows | total: 14,300,000
Chunk 287 written -> 50,000 rows | total: 14,350,000
Chunk 288 written -> 50,000 rows | total: 14,400,000
Chunk 289 written -> 50,000 rows | total: 14,450,000
Chunk 290 written -> 50,000 rows | total: 14,500,000
Chunk 291 written -> 50,000 rows | total: 14,550,000
Chunk 292 written -> 50,000 rows | total: 14,600,000
Chunk 293 written -> 50,000 rows | total: 14,650,000
Chunk 294 written -> 50,000 rows | total: 14,700,000
Chunk 295 written -> 50,000 rows | total: 14,750,000
Chunk 296 written -> 50,000 rows | total: 14,800,000
Chunk 297 written -> 50,000 rows | total: 14,850,000
Chunk 298 written -> 50,000 rows | total: 14,900,000
Chunk 299 written -> 50,000 rows | total: 14,950,000
Chunk 300 written -> 50,000 rows | total: 15,000,000
Chunk 301 written -> 50,000 rows | total: 15,050,000
Chunk 302 written -> 50,000 rows | total: 15,100,000
Chunk 303 written -> 50,000 rows | total: 15,150,000
Chunk 304 written -> 50,000 rows | total: 15,200,000
Chunk 305 written -> 50,000 rows | total: 15,250,000
Chunk 306 written -> 50,000 rows | total: 15,300,000
Chunk 307 written -> 50,000 rows | total: 15,350,000
Chunk 308 written -> 50,000 rows | total: 15,400,000
Chunk 309 written -> 50,000 rows | total: 15,450,000
Chunk 310 written -> 50,000 rows | total: 15,500,000
Chunk 311 written -> 50,000 rows | total: 15,550,000
Chunk 312 written -> 50,000 rows | total: 15,600,000
Chunk 313 written -> 50,000 rows | total: 15,650,000
Chunk 314 written -> 50,000 rows | total: 15,700,000
Chunk 315 written -> 50,000 rows | total: 15,750,000
Chunk 316 written -> 50,000 rows | total: 15,800,000
Chunk 317 written -> 50,000 rows | total: 15,850,000
Chunk 318 written -> 50,000 rows | total: 15,900,000
Chunk 319 written -> 50,000 rows | total: 15,950,000
Chunk 320 written -> 50,000 rows | total: 16,000,000
Chunk 321 written -> 50,000 rows | total: 16,050,000
Chunk 322 written -> 50,000 rows | total: 16,100,000
Chunk 323 written -> 50,000 rows | total: 16,150,000
Chunk 324 written -> 50,000 rows | total: 16,200,000
Chunk 325 written -> 50,000 rows | total: 16,250,000
Chunk 326 written -> 50,000 rows | total: 16,300,000
Chunk 327 written -> 50,000 rows | total: 16,350,000
Chunk 328 written -> 50,000 rows | total: 16,400,000
Chunk 329 written -> 50,000 rows | total: 16,450,000
Chunk 330 written -> 50,000 rows | total: 16,500,000
Chunk 331 written -> 50,000 rows | total: 16,550,000
Chunk 332 written -> 50,000 rows | total: 16,600,000
Chunk 333 written -> 50,000 rows | total: 16,650,000
Chunk 334 written -> 50,000 rows | total: 16,700,000
Chunk 335 written -> 50,000 rows | total: 16,750,000
Chunk 336 written -> 50,000 rows | total: 16,800,000
Chunk 337 written -> 50,000 rows | total: 16,850,000
Chunk 338 written -> 50,000 rows | total: 16,900,000
Chunk 339 written -> 50,000 rows | total: 16,950,000
Chunk 340 written -> 50,000 rows | total: 17,000,000
Chunk 341 written -> 50,000 rows | total: 17,050,000
Chunk 342 written -> 50,000 rows | total: 17,100,000
Chunk 343 written -> 50,000 rows | total: 17,150,000
Chunk 344 written -> 50,000 rows | total: 17,200,000
Chunk 345 written -> 50,000 rows | total: 17,250,000
Chunk 346 written -> 50,000 rows | total: 17,300,000
Chunk 347 written -> 50,000 rows | total: 17,350,000
Chunk 348 written -> 50,000 rows | total: 17,400,000
Chunk 349 written -> 50,000 rows | total: 17,450,000
Chunk 350 written -> 50,000 rows | total: 17,500,000
Chunk 351 written -> 50,000 rows | total: 17,550,000
Chunk 352 written -> 50,000 rows | total: 17,600,000
Chunk 353 written -> 50,000 rows | total: 17,650,000
Chunk 354 written -> 50,000 rows | total: 17,700,000
Chunk 355 written -> 50,000 rows | total: 17,750,000
Chunk 356 written -> 50,000 rows | total: 17,800,000
Chunk 357 written -> 50,000 rows | total: 17,850,000
Chunk 358 written -> 50,000 rows | total: 17,900,000
Chunk 359 written -> 50,000 rows | total: 17,950,000
Chunk 360 written -> 50,000 rows | total: 18,000,000
Chunk 361 written -> 50,000 rows | total: 18,050,000
Chunk 362 written -> 50,000 rows | total: 18,100,000
Chunk 363 written -> 50,000 rows | total: 18,150,000
Chunk 364 written -> 50,000 rows | total: 18,200,000
Chunk 365 written -> 50,000 rows | total: 18,250,000
Chunk 366 written -> 50,000 rows | total: 18,300,000
Chunk 367 written -> 50,000 rows | total: 18,350,000
Chunk 368 written -> 50,000 rows | total: 18,400,000
Chunk 369 written -> 50,000 rows | total: 18,450,000
Chunk 370 written -> 50,000 rows | total: 18,500,000
Chunk 371 written -> 50,000 rows | total: 18,550,000
Chunk 372 written -> 50,000 rows | total: 18,600,000
Chunk 373 written -> 50,000 rows | total: 18,650,000
Chunk 374 written -> 50,000 rows | total: 18,700,000
Chunk 375 written -> 50,000 rows | total: 18,750,000
Chunk 376 written -> 50,000 rows | total: 18,800,000
Chunk 377 written -> 50,000 rows | total: 18,850,000
Chunk 378 written -> 50,000 rows | total: 18,900,000
Chunk 379 written -> 50,000 rows | total: 18,950,000
Chunk 380 written -> 50,000 rows | total: 19,000,000
Chunk 381 written -> 50,000 rows | total: 19,050,000
Chunk 382 written -> 50,000 rows | total: 19,100,000
Chunk 383 written -> 50,000 rows | total: 19,150,000

<hr>

## 2️⃣ INVALID VALUES


<style>
h1 {
    text-align: center;
    color: black;
    font-weight: bold;
}
</style>

<style>
h2 {
    text-align: left;
    color: black;
    font-weight: bold;
}
</style>

<style>
h3 {
    text-align: left;
    color: black;
    font-weight: bold;
}
</style>

<style>
h4 {
    text-align: left;
    color: black;
    font-weight: bold;
}
</style>
<hr>

### **SHAPE & HEAD**

In [43]:
import pandas as pd

FILE = "../data/processed/STANDARD_ValeursFoncieres.csv"
CHUNK_SIZE = 50_000

total_rows = 0
columns = None

for chunk in pd.read_csv(FILE, chunksize=CHUNK_SIZE, dtype=str):
    total_rows += len(chunk)
    if columns is None:
        columns = chunk.columns

print("Shape:", total_rows, "rows and", len(columns), "columns")

df_head = pd.read_csv(FILE, nrows=5, dtype=str)
display(df_head)

Shape: 20102739 rows and 35 columns

,transaction_id,transaction_date,transaction_type,property_value,street_number,btq_code,street_type,street_id,street_name,postal_code,com_name,dep_code,com_code,section_prefix,section,plot_number,volume_number,lot_1,lot_1_surface,lot_2,lot_2_surface,lot_3,lot_3_surface,lot_4,lot_4_surface,lot_5,lot_5_surface,lots_count,property_type_code,property_type,building_real_surface,main_rooms_count,land_nature,land_nature_special,land_surface
0,000001,01/07/2020,Vente,"31234,16",NaN,NaN,NaN,B064,SAINT JULIEN,1560,SAINT-JULIEN-SUR-REYSSOUZE,01,367,NaN,A,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,AB,NaN,1192
1,000001,01/07/2020,Vente,"278000,00",NaN,NaN,NaN,B188,A LA PEROUSE,1250,CORVEISSIAT,01,125,NaN,C,509,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,BS,NaN,10092
2,000001,01/07/2020,Vente,"278000,00",NaN,NaN,NaN,B188,A LA PEROUSE,1250,CORVEISSIAT,01,125,NaN,C,510,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,L,NaN,4570
3,000001,01/07/2020,Vente,"278000,00",NaN,NaN,NaN,B079,AUX COMMUNS,1250,CORVEISSIAT,01,125,NaN,ZL,96,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,BS,NaN,5750
4,000001,01/07/2020,Vente,"278000,00",NaN,NaN,NaN,B033,EN COMBARNAUD,1250,SIMANDRE-SUR-SURAN,01,408,NaN,A,14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,BT,NaN,648170

### **INFO**

In [44]:
import pandas as pd

FILE = "../data/processed/STANDARD_ValeursFoncieres.csv"
CHUNK_SIZE = 50_000

total_rows = 0
columns = None
non_null_counts = None
dtypes = None

for chunk in pd.read_csv(FILE, chunksize=CHUNK_SIZE, dtype=str):
    if columns is None:
        columns = chunk.columns.tolist()
        non_null_counts = {col: 0 for col in columns}
        dtypes = chunk.dtypes.astype(str).to_dict()

    total_rows += len(chunk)

    for col in columns:
        non_null_counts[col] += chunk[col].notna().sum()

# Build info-style summary
info_df = pd.DataFrame({
    "column": columns,
    "non_null_count": [non_null_counts[col] for col in columns],
    "null_count": [total_rows - non_null_counts[col] for col in columns],
    "dtype": [dtypes[col] for col in columns]
})

print(f"RangeIndex: {total_rows} entries, 0 to {total_rows - 1}")
print(f"Data columns (total {len(columns)} columns):")
display(info_df)
print(f"dtypes: {info_df['dtype'].value_counts().to_dict()}")
print(f"memory usage: not computed (chunked mode)")

RangeIndex: 20102739 entries, 0 to 20102738
Data columns (total 35 columns):

                   column  non_null_count  null_count   dtype
0          transaction_id        20102739           0  object
1        transaction_date        20102739           0  object
2        transaction_type        20102739           0  object
3          property_value        19908349      194390  object
4           street_number        12628228     7474511  object
5                btq_code          905080    19197659  object
6             street_type        12160680     7942059  object
7               street_id        19952257      150482  object
8             street_name        19951476      151263  object
9             postal_code        19951139      151600  object
10               com_name        20102739           0  object
11               dep_code        20102739           0  object
12               com_code        20102739           0  object
13         section_prefix          954922    19147817  object
14                section        20102014         725  object
15            plot_number        20102739           0  object
16          volume_number           45381    20057358  object
17                  lot_1         6304273    13798466  object
18          lot_1_surface         1772926    18329813  object
19                  lot_2         1848289    18254450  object
20          lot_2_surface          570300    19532439  object
21                  lot_3          331965    19770774  object
22          lot_3_surface           64116    20038623  object
23                  lot_4          108005    19994734  object
24          lot_4_surface           15935    20086804  object
25                  lot_5           48066    20054673  object
26          lot_5_surface            5697    20097042  object
27             lots_count        20102739           0  object
28     property_type_code        11890422     8212317  object
29          property_type        11890422     8212317  object
30  building_real_surface        11877616     8225123  object
31       main_rooms_count        11877616     8225123  object
32            land_nature        13706037     6396702  object
33    land_nature_special          863125    19239614  object
34           land_surface        13706037     6396702  object

dtypes: {'object': 35}
memory usage: not computed (chunked mode)

### **FIXED INVALID VALUES FOR GOOD**

In [6]:
from pathlib import Path
import pandas as pd

INPUT_FILE = Path("../data/processed/STANDARD_ValeursFoncieres.csv")
OUTPUT_FILE = Path("../data/processed/INVALIDS_ValeursFoncieres.csv")

CHUNK_SIZE = 50_000

date_cols = [
    "transaction_date",
]

numeric_float_cols = [
    "property_value",
    "building_real_surface",
    "land_surface",
    "lot_1_surface",
    "lot_2_surface",
    "lot_3_surface",
    "lot_4_surface",
    "lot_5_surface",
]

numeric_int_cols = [
    "lots_count",
    "main_rooms_count",
]

categorical_cols = [
    "transaction_id",
    "transaction_type",
    "street_number",
    "btq_code",
    "street_type",
    "street_id",
    "street_name",
    "postal_code",
    "com_name",
    "dep_code",
    "com_code",
    "section_prefix",
    "section",
    "plot_number",
    "volume_number",
    "property_type_code",
    "property_type",
    "land_nature",
    "land_nature_special",
    "lot_1",
    "lot_2",
    "lot_3",
    "lot_4",
    "lot_5",
]

missing_markers = {
    "MISSING", "", " ", "NA", "N/A", "None", "null", "NULL", "nan", "NaN"
}


def standardize_nulls(chunk: pd.DataFrame) -> pd.DataFrame:
    for col in chunk.columns:
        if chunk[col].dtype == "object" or str(chunk[col].dtype) == "string":
            chunk[col] = chunk[col].astype("string").str.strip()
            chunk[col] = chunk[col].replace(missing_markers, pd.NA)
    return chunk


def clean_date_columns(chunk: pd.DataFrame, cols: list[str]) -> pd.DataFrame:
    for col in cols:
        if col in chunk.columns:
            chunk[col] = pd.to_datetime(
                chunk[col],
                format="%d/%m/%Y",
                errors="coerce"
            )
    return chunk


def clean_float_columns(chunk: pd.DataFrame, cols: list[str]) -> pd.DataFrame:
    for col in cols:
        if col in chunk.columns:
            chunk[col] = (
                chunk[col]
                .astype("string")
                .str.replace(",", ".", regex=False)
                .str.strip()
            )
            chunk[col] = pd.to_numeric(chunk[col], errors="coerce")
    return chunk


def clean_int_columns(chunk: pd.DataFrame, cols: list[str]) -> pd.DataFrame:
    for col in cols:
        if col in chunk.columns:
            chunk[col] = (
                chunk[col]
                .astype("string")
                .str.strip()
            )
            chunk[col] = pd.to_numeric(chunk[col], errors="coerce").astype("Int64")
    return chunk


def clean_categorical_columns(chunk: pd.DataFrame, cols: list[str]) -> pd.DataFrame:
    for col in cols:
        if col in chunk.columns:
            chunk[col] = chunk[col].astype("string").str.strip()
    return chunk


def apply_custom_invalid_rules(chunk: pd.DataFrame) -> pd.DataFrame:
    # transaction_type: translate and standardize
    if "transaction_type" in chunk.columns:
        chunk["transaction_type"] = chunk["transaction_type"].replace({
            "Vente": "Sale",
            "Vente en l'état futur d'achèvement": "Sale in future state of completion",
            "Vente terrain à bâtir": "Sale of unbuilt land",
            "Echange": "Exchange",
            "Adjudication": "Auction",
            "Expropriation": "Expropriation",
        })

    # property_type: translate actual DVF categories seen in your data
    if "property_type" in chunk.columns:
        chunk["property_type"] = chunk["property_type"].replace({
            "Maison": "House",
            "Appartement": "Apartment",
            "Dépendance": "Outbuilding",
            "Local industriel. commercial ou assimilé": "Industrial or commercial premises",
        })

    # btq_code: clean invalid symbols and standardize lowercase b
    if "btq_code" in chunk.columns:
        chunk["btq_code"] = chunk["btq_code"].replace(["-", ".", "*"], pd.NA)
        chunk["btq_code"] = chunk["btq_code"].replace({"b": "B"})

    # building_real_surface and main_rooms_count:
    # use 0 when missing at this invalid-handling stage
    if "building_real_surface" in chunk.columns:
        chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0.0)

    if "main_rooms_count" in chunk.columns:
        chunk["main_rooms_count"] = chunk["main_rooms_count"].fillna(0).astype("Int64")

    # create surface_type
    if {"building_real_surface", "land_surface"}.issubset(chunk.columns):
        b = chunk["building_real_surface"].fillna(0)
        l = chunk["land_surface"].fillna(0)

        chunk["surface_type"] = pd.NA
        chunk.loc[(b > 0) & (l == 0), "surface_type"] = "building"
        chunk.loc[(b == 0) & (l > 0), "surface_type"] = "land"
        chunk.loc[(b > 0) & (l > 0), "surface_type"] = "combined"

    return chunk


def clean_chunk(chunk: pd.DataFrame) -> pd.DataFrame:
    chunk = standardize_nulls(chunk)
    chunk = clean_date_columns(chunk, date_cols)
    chunk = clean_float_columns(chunk, numeric_float_cols)
    chunk = clean_int_columns(chunk, numeric_int_cols)
    chunk = clean_categorical_columns(chunk, categorical_cols)
    chunk = apply_custom_invalid_rules(chunk)
    return chunk


def clean_file_chunked(input_file: Path, output_file: Path, chunk_size: int = 50_000) -> None:
    output_file.parent.mkdir(parents=True, exist_ok=True)

    first_write = True
    total_rows = 0

    for chunk_idx, chunk in enumerate(
        pd.read_csv(input_file, chunksize=chunk_size, dtype=str, low_memory=False),
        start=1
    ):
        chunk = clean_chunk(chunk)

        chunk.to_csv(
            output_file,
            mode="w" if first_write else "a",
            index=False,
            header=first_write,
            encoding="utf-8"
        )

        first_write = False
        total_rows += len(chunk)

        print(f"Chunk {chunk_idx} written -> {len(chunk):,} rows | total: {total_rows:,}")

    print("\nDone! Handled invalid values")
    print(f"Saved file: {output_file}")
    print(f"Total rows written: {total_rows:,}")


clean_file_chunked(INPUT_FILE, OUTPUT_FILE, CHUNK_SIZE)

Chunk 1 written -> 50,000 rows | total: 50,000
Chunk 2 written -> 50,000 rows | total: 100,000
Chunk 3 written -> 50,000 rows | total: 150,000
Chunk 4 written -> 50,000 rows | total: 200,000
Chunk 5 written -> 50,000 rows | total: 250,000
Chunk 6 written -> 50,000 rows | total: 300,000
Chunk 7 written -> 50,000 rows | total: 350,000
Chunk 8 written -> 50,000 rows | total: 400,000
Chunk 9 written -> 50,000 rows | total: 450,000
Chunk 10 written -> 50,000 rows | total: 500,000
Chunk 11 written -> 50,000 rows | total: 550,000
Chunk 12 written -> 50,000 rows | total: 600,000
Chunk 13 written -> 50,000 rows | total: 650,000
Chunk 14 written -> 50,000 rows | total: 700,000
Chunk 15 written -> 50,000 rows | total: 750,000
Chunk 16 written -> 50,000 rows | total: 800,000
Chunk 17 written -> 50,000 rows | total: 850,000
Chunk 18 written -> 50,000 rows | total: 900,000
Chunk 19 written -> 50,000 rows | total: 950,000
Chunk 20 written -> 50,000 rows | total: 1,000,000
Chunk 21 written -> 50,000 rows | total: 1,050,000
Chunk 22 written -> 50,000 rows | total: 1,100,000
Chunk 23 written -> 50,000 rows | total: 1,150,000
Chunk 24 written -> 50,000 rows | total: 1,200,000
Chunk 25 written -> 50,000 rows | total: 1,250,000
Chunk 26 written -> 50,000 rows | total: 1,300,000
Chunk 27 written -> 50,000 rows | total: 1,350,000
Chunk 28 written -> 50,000 rows | total: 1,400,000
Chunk 29 written -> 50,000 rows | total: 1,450,000
Chunk 30 written -> 50,000 rows | total: 1,500,000
Chunk 31 written -> 50,000 rows | total: 1,550,000
Chunk 32 written -> 50,000 rows | total: 1,600,000
Chunk 33 written -> 50,000 rows | total: 1,650,000
Chunk 34 written -> 50,000 rows | total: 1,700,000
Chunk 35 written -> 50,000 rows | total: 1,750,000
Chunk 36 written -> 50,000 rows | total: 1,800,000
Chunk 37 written -> 50,000 rows | total: 1,850,000
Chunk 38 written -> 50,000 rows | total: 1,900,000
Chunk 39 written -> 50,000 rows | total: 1,950,000
Chunk 40 written -> 50,000 rows | total: 2,000,000
Chunk 41 written -> 50,000 rows | total: 2,050,000
Chunk 42 written -> 50,000 rows | total: 2,100,000
Chunk 43 written -> 50,000 rows | total: 2,150,000
Chunk 44 written -> 50,000 rows | total: 2,200,000
Chunk 45 written -> 50,000 rows | total: 2,250,000
Chunk 46 written -> 50,000 rows | total: 2,300,000
Chunk 47 written -> 50,000 rows | total: 2,350,000
Chunk 48 written -> 50,000 rows | total: 2,400,000
Chunk 49 written -> 50,000 rows | total: 2,450,000
Chunk 50 written -> 50,000 rows | total: 2,500,000
Chunk 51 written -> 50,000 rows | total: 2,550,000
Chunk 52 written -> 50,000 rows | total: 2,600,000
Chunk 53 written -> 50,000 rows | total: 2,650,000
Chunk 54 written -> 50,000 rows | total: 2,700,000
Chunk 55 written -> 50,000 rows | total: 2,750,000
Chunk 56 written -> 50,000 rows | total: 2,800,000
Chunk 57 written -> 50,000 rows | total: 2,850,000
Chunk 58 written -> 50,000 rows | total: 2,900,000
Chunk 59 written -> 50,000 rows | total: 2,950,000
Chunk 60 written -> 50,000 rows | total: 3,000,000
Chunk 61 written -> 50,000 rows | total: 3,050,000
Chunk 62 written -> 50,000 rows | total: 3,100,000
Chunk 63 written -> 50,000 rows | total: 3,150,000
Chunk 64 written -> 50,000 rows | total: 3,200,000
Chunk 65 written -> 50,000 rows | total: 3,250,000
Chunk 66 written -> 50,000 rows | total: 3,300,000
Chunk 67 written -> 50,000 rows | total: 3,350,000
Chunk 68 written -> 50,000 rows | total: 3,400,000
Chunk 69 written -> 50,000 rows | total: 3,450,000
Chunk 70 written -> 50,000 rows | total: 3,500,000
Chunk 71 written -> 50,000 rows | total: 3,550,000
Chunk 72 written -> 50,000 rows | total: 3,600,000
Chunk 73 written -> 50,000 rows | total: 3,650,000
Chunk 74 written -> 50,000 rows | total: 3,700,000
Chunk 75 written -> 50,000 rows | total: 3,750,000
Chunk 76 written -> 50,000 rows | total: 3,800,000
Chunk 77 written -> 50,000 rows | total: 3,850,000
Chunk 78 written -> 50,000 rows | total: 3,900,000
Chunk 79 written -> 50,000 rows | total: 3,950,000
Chunk 80 written -> 50,000 rows | total: 4,000,000
Chunk 81 written -> 50,000 rows | total: 4,050,000
Chunk 82 written -> 50,000 rows | total: 4,100,000
Chunk 83 written -> 50,000 rows | total: 4,150,000
Chunk 84 written -> 50,000 rows | total: 4,200,000
Chunk 85 written -> 50,000 rows | total: 4,250,000
Chunk 86 written -> 50,000 rows | total: 4,300,000
Chunk 87 written -> 50,000 rows | total: 4,350,000
Chunk 88 written -> 50,000 rows | total: 4,400,000
Chunk 89 written -> 50,000 rows | total: 4,450,000
Chunk 90 written -> 50,000 rows | total: 4,500,000
Chunk 91 written -> 50,000 rows | total: 4,550,000
Chunk 92 written -> 50,000 rows | total: 4,600,000
Chunk 93 written -> 50,000 rows | total: 4,650,000
Chunk 94 written -> 50,000 rows | total: 4,700,000
Chunk 95 written -> 50,000 rows | total: 4,750,000
Chunk 96 written -> 50,000 rows | total: 4,800,000
Chunk 97 written -> 50,000 rows | total: 4,850,000
Chunk 98 written -> 50,000 rows | total: 4,900,000
Chunk 99 written -> 50,000 rows | total: 4,950,000
Chunk 100 written -> 50,000 rows | total: 5,000,000
Chunk 101 written -> 50,000 rows | total: 5,050,000
Chunk 102 written -> 50,000 rows | total: 5,100,000
Chunk 103 written -> 50,000 rows | total: 5,150,000
Chunk 104 written -> 50,000 rows | total: 5,200,000
Chunk 105 written -> 50,000 rows | total: 5,250,000
Chunk 106 written -> 50,000 rows | total: 5,300,000
Chunk 107 written -> 50,000 rows | total: 5,350,000
Chunk 108 written -> 50,000 rows | total: 5,400,000
Chunk 109 written -> 50,000 rows | total: 5,450,000
Chunk 110 written -> 50,000 rows | total: 5,500,000
Chunk 111 written -> 50,000 rows | total: 5,550,000
Chunk 112 written -> 50,000 rows | total: 5,600,000
Chunk 113 written -> 50,000 rows | total: 5,650,000
Chunk 114 written -> 50,000 rows | total: 5,700,000
Chunk 115 written -> 50,000 rows | total: 5,750,000
Chunk 116 written -> 50,000 rows | total: 5,800,000
Chunk 117 written -> 50,000 rows | total: 5,850,000
Chunk 118 written -> 50,000 rows | total: 5,900,000
Chunk 119 written -> 50,000 rows | total: 5,950,000
Chunk 120 written -> 50,000 rows | total: 6,000,000
Chunk 121 written -> 50,000 rows | total: 6,050,000
Chunk 122 written -> 50,000 rows | total: 6,100,000
Chunk 123 written -> 50,000 rows | total: 6,150,000
Chunk 124 written -> 50,000 rows | total: 6,200,000
Chunk 125 written -> 50,000 rows | total: 6,250,000
Chunk 126 written -> 50,000 rows | total: 6,300,000
Chunk 127 written -> 50,000 rows | total: 6,350,000
Chunk 128 written -> 50,000 rows | total: 6,400,000
Chunk 129 written -> 50,000 rows | total: 6,450,000
Chunk 130 written -> 50,000 rows | total: 6,500,000
Chunk 131 written -> 50,000 rows | total: 6,550,000
Chunk 132 written -> 50,000 rows | total: 6,600,000
Chunk 133 written -> 50,000 rows | total: 6,650,000
Chunk 134 written -> 50,000 rows | total: 6,700,000
Chunk 135 written -> 50,000 rows | total: 6,750,000
Chunk 136 written -> 50,000 rows | total: 6,800,000
Chunk 137 written -> 50,000 rows | total: 6,850,000
Chunk 138 written -> 50,000 rows | total: 6,900,000
Chunk 139 written -> 50,000 rows | total: 6,950,000
Chunk 140 written -> 50,000 rows | total: 7,000,000
Chunk 141 written -> 50,000 rows | total: 7,050,000
Chunk 142 written -> 50,000 rows | total: 7,100,000
Chunk 143 written -> 50,000 rows | total: 7,150,000
Chunk 144 written -> 50,000 rows | total: 7,200,000
Chunk 145 written -> 50,000 rows | total: 7,250,000
Chunk 146 written -> 50,000 rows | total: 7,300,000
Chunk 147 written -> 50,000 rows | total: 7,350,000
Chunk 148 written -> 50,000 rows | total: 7,400,000
Chunk 149 written -> 50,000 rows | total: 7,450,000
Chunk 150 written -> 50,000 rows | total: 7,500,000
Chunk 151 written -> 50,000 rows | total: 7,550,000
Chunk 152 written -> 50,000 rows | total: 7,600,000
Chunk 153 written -> 50,000 rows | total: 7,650,000
Chunk 154 written -> 50,000 rows | total: 7,700,000
Chunk 155 written -> 50,000 rows | total: 7,750,000
Chunk 156 written -> 50,000 rows | total: 7,800,000
Chunk 157 written -> 50,000 rows | total: 7,850,000
Chunk 158 written -> 50,000 rows | total: 7,900,000
Chunk 159 written -> 50,000 rows | total: 7,950,000
Chunk 160 written -> 50,000 rows | total: 8,000,000
Chunk 161 written -> 50,000 rows | total: 8,050,000
Chunk 162 written -> 50,000 rows | total: 8,100,000
Chunk 163 written -> 50,000 rows | total: 8,150,000
Chunk 164 written -> 50,000 rows | total: 8,200,000
Chunk 165 written -> 50,000 rows | total: 8,250,000
Chunk 166 written -> 50,000 rows | total: 8,300,000
Chunk 167 written -> 50,000 rows | total: 8,350,000
Chunk 168 written -> 50,000 rows | total: 8,400,000
Chunk 169 written -> 50,000 rows | total: 8,450,000
Chunk 170 written -> 50,000 rows | total: 8,500,000
Chunk 171 written -> 50,000 rows | total: 8,550,000
Chunk 172 written -> 50,000 rows | total: 8,600,000
Chunk 173 written -> 50,000 rows | total: 8,650,000
Chunk 174 written -> 50,000 rows | total: 8,700,000
Chunk 175 written -> 50,000 rows | total: 8,750,000
Chunk 176 written -> 50,000 rows | total: 8,800,000
Chunk 177 written -> 50,000 rows | total: 8,850,000
Chunk 178 written -> 50,000 rows | total: 8,900,000
Chunk 179 written -> 50,000 rows | total: 8,950,000
Chunk 180 written -> 50,000 rows | total: 9,000,000
Chunk 181 written -> 50,000 rows | total: 9,050,000
Chunk 182 written -> 50,000 rows | total: 9,100,000
Chunk 183 written -> 50,000 rows | total: 9,150,000
Chunk 184 written -> 50,000 rows | total: 9,200,000
Chunk 185 written -> 50,000 rows | total: 9,250,000
Chunk 186 written -> 50,000 rows | total: 9,300,000
Chunk 187 written -> 50,000 rows | total: 9,350,000
Chunk 188 written -> 50,000 rows | total: 9,400,000
Chunk 189 written -> 50,000 rows | total: 9,450,000
Chunk 190 written -> 50,000 rows | total: 9,500,000
Chunk 191 written -> 50,000 rows | total: 9,550,000
Chunk 192 written -> 50,000 rows | total: 9,600,000
Chunk 193 written -> 50,000 rows | total: 9,650,000
Chunk 194 written -> 50,000 rows | total: 9,700,000
Chunk 195 written -> 50,000 rows | total: 9,750,000
Chunk 196 written -> 50,000 rows | total: 9,800,000
Chunk 197 written -> 50,000 rows | total: 9,850,000
Chunk 198 written -> 50,000 rows | total: 9,900,000
Chunk 199 written -> 50,000 rows | total: 9,950,000
Chunk 200 written -> 50,000 rows | total: 10,000,000
Chunk 201 written -> 50,000 rows | total: 10,050,000
Chunk 202 written -> 50,000 rows | total: 10,100,000
Chunk 203 written -> 50,000 rows | total: 10,150,000
Chunk 204 written -> 50,000 rows | total: 10,200,000
Chunk 205 written -> 50,000 rows | total: 10,250,000
Chunk 206 written -> 50,000 rows | total: 10,300,000
Chunk 207 written -> 50,000 rows | total: 10,350,000
Chunk 208 written -> 50,000 rows | total: 10,400,000
Chunk 209 written -> 50,000 rows | total: 10,450,000
Chunk 210 written -> 50,000 rows | total: 10,500,000
Chunk 211 written -> 50,000 rows | total: 10,550,000
Chunk 212 written -> 50,000 rows | total: 10,600,000
Chunk 213 written -> 50,000 rows | total: 10,650,000
Chunk 214 written -> 50,000 rows | total: 10,700,000
Chunk 215 written -> 50,000 rows | total: 10,750,000
Chunk 216 written -> 50,000 rows | total: 10,800,000
Chunk 217 written -> 50,000 rows | total: 10,850,000
Chunk 218 written -> 50,000 rows | total: 10,900,000
Chunk 219 written -> 50,000 rows | total: 10,950,000
Chunk 220 written -> 50,000 rows | total: 11,000,000
Chunk 221 written -> 50,000 rows | total: 11,050,000
Chunk 222 written -> 50,000 rows | total: 11,100,000
Chunk 223 written -> 50,000 rows | total: 11,150,000
Chunk 224 written -> 50,000 rows | total: 11,200,000
Chunk 225 written -> 50,000 rows | total: 11,250,000
Chunk 226 written -> 50,000 rows | total: 11,300,000
Chunk 227 written -> 50,000 rows | total: 11,350,000
Chunk 228 written -> 50,000 rows | total: 11,400,000
Chunk 229 written -> 50,000 rows | total: 11,450,000
Chunk 230 written -> 50,000 rows | total: 11,500,000
Chunk 231 written -> 50,000 rows | total: 11,550,000
Chunk 232 written -> 50,000 rows | total: 11,600,000
Chunk 233 written -> 50,000 rows | total: 11,650,000
Chunk 234 written -> 50,000 rows | total: 11,700,000
Chunk 235 written -> 50,000 rows | total: 11,750,000
Chunk 236 written -> 50,000 rows | total: 11,800,000
Chunk 237 written -> 50,000 rows | total: 11,850,000
Chunk 238 written -> 50,000 rows | total: 11,900,000
Chunk 239 written -> 50,000 rows | total: 11,950,000
Chunk 240 written -> 50,000 rows | total: 12,000,000
Chunk 241 written -> 50,000 rows | total: 12,050,000
Chunk 242 written -> 50,000 rows | total: 12,100,000
Chunk 243 written -> 50,000 rows | total: 12,150,000
Chunk 244 written -> 50,000 rows | total: 12,200,000
Chunk 245 written -> 50,000 rows | total: 12,250,000
Chunk 246 written -> 50,000 rows | total: 12,300,000
Chunk 247 written -> 50,000 rows | total: 12,350,000
Chunk 248 written -> 50,000 rows | total: 12,400,000
Chunk 249 written -> 50,000 rows | total: 12,450,000
Chunk 250 written -> 50,000 rows | total: 12,500,000
Chunk 251 written -> 50,000 rows | total: 12,550,000
Chunk 252 written -> 50,000 rows | total: 12,600,000
Chunk 253 written -> 50,000 rows | total: 12,650,000
Chunk 254 written -> 50,000 rows | total: 12,700,000
Chunk 255 written -> 50,000 rows | total: 12,750,000
Chunk 256 written -> 50,000 rows | total: 12,800,000
Chunk 257 written -> 50,000 rows | total: 12,850,000
Chunk 258 written -> 50,000 rows | total: 12,900,000
Chunk 259 written -> 50,000 rows | total: 12,950,000
Chunk 260 written -> 50,000 rows | total: 13,000,000
Chunk 261 written -> 50,000 rows | total: 13,050,000
Chunk 262 written -> 50,000 rows | total: 13,100,000
Chunk 263 written -> 50,000 rows | total: 13,150,000
Chunk 264 written -> 50,000 rows | total: 13,200,000
Chunk 265 written -> 50,000 rows | total: 13,250,000
Chunk 266 written -> 50,000 rows | total: 13,300,000
Chunk 267 written -> 50,000 rows | total: 13,350,000
Chunk 268 written -> 50,000 rows | total: 13,400,000
Chunk 269 written -> 50,000 rows | total: 13,450,000
Chunk 270 written -> 50,000 rows | total: 13,500,000
Chunk 271 written -> 50,000 rows | total: 13,550,000
Chunk 272 written -> 50,000 rows | total: 13,600,000
Chunk 273 written -> 50,000 rows | total: 13,650,000
Chunk 274 written -> 50,000 rows | total: 13,700,000
Chunk 275 written -> 50,000 rows | total: 13,750,000
Chunk 276 written -> 50,000 rows | total: 13,800,000
Chunk 277 written -> 50,000 rows | total: 13,850,000
Chunk 278 written -> 50,000 rows | total: 13,900,000
Chunk 279 written -> 50,000 rows | total: 13,950,000
Chunk 280 written -> 50,000 rows | total: 14,000,000
Chunk 281 written -> 50,000 rows | total: 14,050,000
Chunk 282 written -> 50,000 rows | total: 14,100,000
Chunk 283 written -> 50,000 rows | total: 14,150,000
Chunk 284 written -> 50,000 rows | total: 14,200,000
Chunk 285 written -> 50,000 rows | total: 14,250,000
Chunk 286 written -> 50,000 rows | total: 14,300,000
Chunk 287 written -> 50,000 rows | total: 14,350,000
Chunk 288 written -> 50,000 rows | total: 14,400,000
Chunk 289 written -> 50,000 rows | total: 14,450,000
Chunk 290 written -> 50,000 rows | total: 14,500,000
Chunk 291 written -> 50,000 rows | total: 14,550,000
Chunk 292 written -> 50,000 rows | total: 14,600,000
Chunk 293 written -> 50,000 rows | total: 14,650,000
Chunk 294 written -> 50,000 rows | total: 14,700,000
Chunk 295 written -> 50,000 rows | total: 14,750,000
Chunk 296 written -> 50,000 rows | total: 14,800,000
Chunk 297 written -> 50,000 rows | total: 14,850,000
Chunk 298 written -> 50,000 rows | total: 14,900,000
Chunk 299 written -> 50,000 rows | total: 14,950,000
Chunk 300 written -> 50,000 rows | total: 15,000,000
Chunk 301 written -> 50,000 rows | total: 15,050,000
Chunk 302 written -> 50,000 rows | total: 15,100,000
Chunk 303 written -> 50,000 rows | total: 15,150,000
Chunk 304 written -> 50,000 rows | total: 15,200,000
Chunk 305 written -> 50,000 rows | total: 15,250,000
Chunk 306 written -> 50,000 rows | total: 15,300,000
Chunk 307 written -> 50,000 rows | total: 15,350,000
Chunk 308 written -> 50,000 rows | total: 15,400,000
Chunk 309 written -> 50,000 rows | total: 15,450,000
Chunk 310 written -> 50,000 rows | total: 15,500,000
Chunk 311 written -> 50,000 rows | total: 15,550,000
Chunk 312 written -> 50,000 rows | total: 15,600,000
Chunk 313 written -> 50,000 rows | total: 15,650,000
Chunk 314 written -> 50,000 rows | total: 15,700,000
Chunk 315 written -> 50,000 rows | total: 15,750,000
Chunk 316 written -> 50,000 rows | total: 15,800,000
Chunk 317 written -> 50,000 rows | total: 15,850,000
Chunk 318 written -> 50,000 rows | total: 15,900,000
Chunk 319 written -> 50,000 rows | total: 15,950,000
Chunk 320 written -> 50,000 rows | total: 16,000,000
Chunk 321 written -> 50,000 rows | total: 16,050,000
Chunk 322 written -> 50,000 rows | total: 16,100,000
Chunk 323 written -> 50,000 rows | total: 16,150,000
Chunk 324 written -> 50,000 rows | total: 16,200,000
Chunk 325 written -> 50,000 rows | total: 16,250,000
Chunk 326 written -> 50,000 rows | total: 16,300,000
Chunk 327 written -> 50,000 rows | total: 16,350,000
Chunk 328 written -> 50,000 rows | total: 16,400,000
Chunk 329 written -> 50,000 rows | total: 16,450,000
Chunk 330 written -> 50,000 rows | total: 16,500,000
Chunk 331 written -> 50,000 rows | total: 16,550,000
Chunk 332 written -> 50,000 rows | total: 16,600,000
Chunk 333 written -> 50,000 rows | total: 16,650,000
Chunk 334 written -> 50,000 rows | total: 16,700,000
Chunk 335 written -> 50,000 rows | total: 16,750,000
Chunk 336 written -> 50,000 rows | total: 16,800,000
Chunk 337 written -> 50,000 rows | total: 16,850,000
Chunk 338 written -> 50,000 rows | total: 16,900,000
Chunk 339 written -> 50,000 rows | total: 16,950,000
Chunk 340 written -> 50,000 rows | total: 17,000,000
Chunk 341 written -> 50,000 rows | total: 17,050,000
Chunk 342 written -> 50,000 rows | total: 17,100,000
Chunk 343 written -> 50,000 rows | total: 17,150,000
Chunk 344 written -> 50,000 rows | total: 17,200,000
Chunk 345 written -> 50,000 rows | total: 17,250,000
Chunk 346 written -> 50,000 rows | total: 17,300,000
Chunk 347 written -> 50,000 rows | total: 17,350,000
Chunk 348 written -> 50,000 rows | total: 17,400,000
Chunk 349 written -> 50,000 rows | total: 17,450,000
Chunk 350 written -> 50,000 rows | total: 17,500,000
Chunk 351 written -> 50,000 rows | total: 17,550,000
Chunk 352 written -> 50,000 rows | total: 17,600,000
Chunk 353 written -> 50,000 rows | total: 17,650,000
Chunk 354 written -> 50,000 rows | total: 17,700,000
Chunk 355 written -> 50,000 rows | total: 17,750,000
Chunk 356 written -> 50,000 rows | total: 17,800,000
Chunk 357 written -> 50,000 rows | total: 17,850,000
Chunk 358 written -> 50,000 rows | total: 17,900,000
Chunk 359 written -> 50,000 rows | total: 17,950,000
Chunk 360 written -> 50,000 rows | total: 18,000,000
Chunk 361 written -> 50,000 rows | total: 18,050,000
Chunk 362 written -> 50,000 rows | total: 18,100,000
Chunk 363 written -> 50,000 rows | total: 18,150,000
Chunk 364 written -> 50,000 rows | total: 18,200,000
Chunk 365 written -> 50,000 rows | total: 18,250,000
Chunk 366 written -> 50,000 rows | total: 18,300,000
Chunk 367 written -> 50,000 rows | total: 18,350,000
Chunk 368 written -> 50,000 rows | total: 18,400,000
Chunk 369 written -> 50,000 rows | total: 18,450,000
Chunk 370 written -> 50,000 rows | total: 18,500,000
Chunk 371 written -> 50,000 rows | total: 18,550,000
Chunk 372 written -> 50,000 rows | total: 18,600,000
Chunk 373 written -> 50,000 rows | total: 18,650,000
Chunk 374 written -> 50,000 rows | total: 18,700,000
Chunk 375 written -> 50,000 rows | total: 18,750,000
Chunk 376 written -> 50,000 rows | total: 18,800,000
Chunk 377 written -> 50,000 rows | total: 18,850,000
Chunk 378 written -> 50,000 rows | total: 18,900,000
Chunk 379 written -> 50,000 rows | total: 18,950,000
Chunk 380 written -> 50,000 rows | total: 19,000,000
Chunk 381 written -> 50,000 rows | total: 19,050,000
Chunk 382 written -> 50,000 rows | total: 19,100,000
Chunk 383 written -> 50,000 rows | total: 19,150,000

### **STANDARDIZE FAKE NULLS to NaN**

In [5]:
from collections import defaultdict
import pandas as pd

FILE = "../data/processed/INVALIDS_ValeursFoncieres.csv"
CHUNK_SIZE = 50_000

missing_markers = {
    "MISSING", "", " ", "NA", "N/A", "None", "null", "NULL", "nan", "NaN"
}

unique_values = defaultdict(set)
null_counts = defaultdict(int)

for chunk in pd.read_csv(
    FILE,
    chunksize=CHUNK_SIZE,
    dtype=str,
    low_memory=False
):
    # ✅ Clean per column (avoids FutureWarning)
    for col in chunk.columns:
        chunk[col] = chunk[col].str.strip()
        chunk[col] = chunk[col].replace(missing_markers, pd.NA)

    for col in chunk.columns:
        null_counts[col] += chunk[col].isna().sum()
        unique_values[col].update(chunk[col].dropna().unique())

print(100 * "-")
for col in unique_values:
    print(f"\n➡️ {col}:")
    print(f"Unique values count: {len(unique_values[col])}")
    print(f"Null count: {null_counts[col]}")
    print(f"Unique values (sample): {list(unique_values[col])[:120]}")
    print(100 * "-")

C:\Users\sboub\AppData\Local\Temp\ipykernel_11120\2539792997.py:23: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  chunk[col] = chunk[col].replace(missing_markers, pd.NA)
C:\Users\sboub\AppData\Local\Temp\ipykernel_11120\2539792997.py:23: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  chunk[col] = chunk[col].replace(missing_markers, pd.NA)
C:\Users\sboub\AppData\Local\Temp\ipykernel_11120\2539792997.py:23: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  chunk[col] = chunk[col].replace(missing_markers, pd.NA)
C:\Users\sboub\AppData\Local\Temp\ipykernel_11120\2539792997.py:23: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  chunk[col] = chunk[col].replace(missing_markers, pd.NA)
C:\Users\sboub\AppData\Local\Temp\ipykernel_11120\2539792997.py:23: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  chunk[col] = chunk[col].replace(missing_markers, pd.NA)
C:\Users\sboub\AppData\Local\Temp\ipykernel_11120\2539792997.py:23: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  chunk[col] = chunk[col].replace(missing_markers, pd.NA)
C:\Users\sboub\AppData\Local\Temp\ipykernel_11120\2539792997.py:23: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  chunk[col] = chunk[col].replace(missing_markers, pd.NA)
C:\Users\sboub\AppData\Local\Temp\ipykernel_11120\2539792997.py:23: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  chunk[col] = chunk[col].replace(missing_markers, pd.NA)
C:\Users\sboub\AppData\Local\Temp\ipykernel_11120\2539792997.py:23: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  chunk[col] = chunk[col].replace(missing_markers, pd.NA)
C:\Users\sboub\AppData\Local\Temp\ipykernel_11120\2539792997.py:23: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  chunk[col] = chunk[col].replace(missing_markers, pd.NA)
C:\Users\sboub\AppData\Local\Temp\ipykernel_11120\2539792997.py:23: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  chunk[col] = chunk[col].replace(missing_markers, pd.NA)
C:\Users\sboub\AppData\Local\Temp\ipykernel_11120\2539792997.py:23: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  chunk[col] = chunk[col].replace(missing_markers, pd.NA)
C:\Users\sboub\AppData\Local\Temp\ipykernel_11120\2539792997.py:23: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  chunk[col] = chunk[col].replace(missing_markers, pd.NA)
C:\Users\sboub\AppData\Local\Temp\ipykernel_11120\2539792997.py:23: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  chunk[col] = chunk[col].replace(missing_markers, pd.NA)
C:\Users\sboub\AppData\Local\Temp\ipykernel_11120\2539792997.py:23: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  chunk[col] = chunk[col].replace(missing_markers, pd.NA)
C:\Users\sboub\AppData\Local\Temp\ipykernel_11120\2539792997.py:23: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  chunk[col] = chunk[col].replace(missing_markers, pd.NA)
C:\Users\sboub\AppData\Local\Temp\ipykernel_11120\2539792997.py:23: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  chunk[col] = chunk[col].replace(missing_markers, pd.NA)
C:\Users\sboub\AppData\Local\Temp\ipykernel_11120\2539792997.py:23: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  chunk[col] = chunk[col].replace(missing_markers, pd.NA)
C:\Users\sboub\AppData\Local\Temp\ipykernel_11120\2539792997.py:23: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  chunk[col] = chunk[col].replace(missing_markers, pd.NA)
C:\Users\sboub\AppData\Local\Temp\ipykernel_11120\2539792997.py:23: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  chunk[col] = chunk[col].replace(missing_markers, pd.NA)
C:\Users\sboub\AppData\Local\Temp\ipykernel_11120\2539792997.py:23: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  chunk[col] = chunk[col].replace(missing_markers, pd.NA)
C:\Users\sboub\AppData\Local\Temp\ipykernel_11120\2539792997.py:23: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  chunk[col] = chunk[col].replace(missing_markers, pd.NA)
C:\Users\sboub\AppData\Local\Temp\ipykernel_11120\2539792997.py:23: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  chunk[col] = chunk[col].replace(missing_markers, pd.NA)
C:\Users\sboub\AppData\Local\Temp\ipykernel_11120\2539792997.py:23: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  chunk[col] = chunk[col].replace(missing_markers, pd.NA)
C:\Users\sboub\AppData\Local\Temp\ipykernel_11120\2539792997.py:23: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  chunk[col] = chunk[col].replace(missing_markers, pd.NA)
C:\Users\sboub\AppData\Local\Temp\ipykernel_11120\2539792997.py:23: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  chunk[col] = chunk[col].replace(missing_markers, pd.NA)
C:\Users\sboub\AppData\Local\Temp\ipykernel_11120\2539792997.py:23: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  chunk[col] = chunk[col].replace(missing_markers, pd.NA)
C:\Users\sboub\AppData\Local\Temp\ipykernel_11120\2539792997.py:23: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  chunk[col] = chunk[col].replace(missing_markers, pd.NA)
C:\Users\sboub\AppData\Local\Temp\ipykernel_11120\2539792997.py:23: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  chunk[col] = chunk[col].replace(missing_markers, pd.NA)
C:\Users\sboub\AppData\Local\Temp\ipykernel_11120\2539792997.py:23: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  chunk[col] = chunk[col].replace(missing_markers, pd.NA)
C:\Users\sboub\AppData\Local\Temp\ipykernel_11120\2539792997.py:23: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  chunk[col] = chunk[col].replace(missing_markers, pd.NA)
C:\Users\sboub\AppData\Local\Temp\ipykernel_11120\2539792997.py:23: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  chunk[col] = chunk[col].replace(missing_markers, pd.NA)
C:\Users\sboub\AppData\Local\Temp\ipykernel_11120\2539792997.py:23: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  chunk[col] = chunk[col].replace(missing_markers, pd.NA)
C:\Users\sboub\AppData\Local\Temp\ipykernel_11120\2539792997.py:23: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  chunk[col] = chunk[col].replace(missing_markers, pd.NA)
C:\Users\sboub\AppData\Local\Temp\ipykernel_11120\2539792997.py:23: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  chunk[col] = chunk[col].replace(missing_markers, pd.NA)
C:\Users\sboub\AppData\Local\Temp\ipykernel_11120\2539792997.py:23: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  chunk[col] = chunk[col].replace(missing_markers, pd.NA)
C:\Users\sboub\AppData\Local\Temp\ipykernel_11120\2539792997.py:23: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  chunk[col] = chunk[col].replace(missing_markers, pd.NA)
C:\Users\sboub\AppData\Local\Temp\ipykernel_11120\2539792997.py:23: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  chunk[col] = chunk[col].replace(missing_markers, pd.NA)
C:\Users\sboub\AppData\Local\Temp\ipykernel_11120\2539792997.py:23: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  chunk[col] = chunk[col].replace(missing_markers, pd.NA)
C:\Users\sboub\AppData\Local\Temp\ipykernel_11120\2539792997.py:23: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  chunk[col] = chunk[col].replace(missing_markers, pd.NA)
C:\Users\sboub\AppData\Local\Temp\ipykernel_11120\2539792997.py:23: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  chunk[col] = chunk[col].replace(missing_markers, pd.NA)
C:\Users\sboub\AppData\Local\Temp\ipykernel_11120\2539792997.py:23: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  chunk[col] = chunk[col].replace(missing_markers, pd.NA)
C:\Users\sboub\AppData\Local\Temp\ipykernel_11120\2539792997.py:23: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  chunk[col] = chunk[col].replace(missing_markers, pd.NA)
C:\Users\sboub\AppData\Local\Temp\ipykernel_11120\2539792997.py:23: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  chunk[col] = chunk[col].replace(missing_markers, pd.NA)
C:\Users\sboub\AppData\Local\Temp\ipykernel_11120\2539792997.py:23: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  chunk[col] = chunk[col].replace(missing_markers, pd.NA)
C:\Users\sboub\AppData\Local\Temp\ipykernel_11120\2539792997.py:23: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  chunk[col] = chunk[col].replace(missing_markers, pd.NA)
C:\Users\sboub\AppData\Local\Temp\ipykernel_11120\2539792997.py:23: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  chunk[col] = chunk[col].replace(missing_markers, pd.NA)
C:\Users\sboub\AppData\Local\Temp\ipykernel_11120\2539792997.py:23: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  chunk[col] = chunk[col].replace(missing_markers, pd.NA)
C:\Users\sboub\AppData\Local\Temp\ipykernel_11120\2539792997.py:23: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  chunk[col] = chunk[col].replace(missing_markers, pd.NA)

----------------------------------------------------------------------------------------------------

➡️ transaction_id:
Unique values count: 1204
Null count: 0
Unique values (sample): ['000449', '000627', '000663', '000302', '001216', '000539', '000591', '000822', '001168', '001094', '000246', '000692', '000929', '000645', '000197', '000604', '000306', '000701', '000785', '000937', '000133', '000403', '000922', '001081', '000070', '000696', '000429', '000094', '000196', '001171', '001200', '000451', '000712', '000994', '000052', '001170', '000312', '000675', '001183', '001071', '001116', '000817', '000615', '000533', '000846', '001132', '001026', '000980', '000924', '000073', '000898', '000986', '000006', '000063', '000466', '000470', '000198', '001164', '001227', '000528', '000425', '000968', '001175', '000435', '000609', '000830', '000758', '000248', '000697', '001073', '001144', '000523', '000109', '000744', '000123', '000943', '000055', '000062', '000933', '000467', '000289', '000867', '000495', '000545', '000337', '000729', '000786', '000869', '001035', '000475', '000679', '000733', '000382', '001196', '000512', '000549', '001199', '001033', '001194', '000749', '000736', '000480', '001090', '000526', '000972', '000008', '000235', '000321', '000732', '000713', '000894', '000594', '000121', '001079', '000322', '000771', '000769', '000170', '000693', '000919']
----------------------------------------------------------------------------------------------------

➡️ transaction_date:
Unique values count: 1806
Null count: 0
Unique values (sample): ['2024-05-21', '2023-12-25', '2023-11-29', '2023-12-05', '2024-11-13', '2021-10-29', '2022-03-23', '2025-05-26', '2021-07-12', '2021-11-11', '2023-02-24', '2022-08-03', '2022-06-12', '2025-04-12', '2024-03-05', '2020-10-28', '2023-11-27', '2022-03-30', '2020-09-28', '2024-07-05', '2021-03-27', '2023-10-28', '2024-08-26', '2021-10-08', '2024-10-05', '2020-11-24', '2020-12-21', '2021-04-16', '2023-08-03', '2024-06-14', '2022-06-24', '2025-04-15', '2021-11-23', '2022-09-24', '2024-09-12', '2021-04-10', '2024-12-03', '2023-11-11', '2025-01-04', '2020-10-16', '2023-06-14', '2022-04-10', '2022-05-08', '2025-01-21', '2022-04-17', '2024-06-13', '2023-07-28', '2023-03-24', '2022-03-15', '2024-04-07', '2020-09-18', '2023-10-16', '2025-05-22', '2025-05-21', '2024-02-20', '2024-08-05', '2022-01-21', '2022-04-09', '2021-05-11', '2024-04-28', '2023-08-17', '2023-09-19', '2021-03-12', '2024-11-04', '2024-10-15', '2022-04-22', '2025-05-06', '2021-01-21', '2024-04-18', '2024-09-15', '2024-09-11', '2021-03-23', '2021-10-31', '2023-11-22', '2024-04-11', '2024-09-26', '2022-03-21', '2023-03-14', '2024-10-06', '2021-06-02', '2024-06-05', '2023-02-23', '2025-02-06', '2023-09-13', '2023-02-03', '2024-06-03', '2020-07-14', '2020-07-21', '2020-09-27', '2022-09-17', '2021-12-20', '2024-10-09', '2021-10-16', '2022-04-30', '2025-01-20', '2021-11-17', '2024-09-25', '2025-06-14', '2021-04-03', '2024-01-10', '2024-09-16', '2022-11-25', '2025-04-20', '2021-07-08', '2023-11-03', '2024-04-08', '2022-02-13', '2023-12-18', '2022-01-16', '2022-05-03', '2023-07-12', '2020-11-30', '2022-04-21', '2024-07-18', '2021-06-19', '2021-03-21', '2021-05-30', '2021-02-23', '2020-09-16', '2024-03-17']
----------------------------------------------------------------------------------------------------

➡️ transaction_type:
Unique values count: 6
Null count: 0
Unique values (sample): ['Exchange', 'Sale in future state of completion', 'Expropriation', 'Sale', 'Auction', 'Sale of unbuilt land']
----------------------------------------------------------------------------------------------------

➡️ property_value:
Unique values count: 466667
Null count: 194390
Unique values (sample): ['1117.8', '34389.6', '187076.0', '1047.5', '48931.26', '1509220.0', '15760.0', '221962.0', '131094.27', '102997.29', '4925425.5', '203942.0', '103230.0', '41863.0', '198331.0', '1328490.0', '309790.0', '156546.0', '4198.2', '68534.4', '120230.0', '271522.22', '2088700.0', '209710.0', '725630.0', '75708.19', '598.25', '548438.0', '2720400.0', '782051.0', '9310.0', '126970.0', '4754.5', '4110.6', '252340.0', '7839000.0', '229095.0', '614955.2', '2159.3', '642785.0', '6897.3', '1267.2', '29982.69', '68116.0', '1814500.0', '3199314.2', '473554.6', '20062.04', '56107.0', '4925619.5', '21004.0', '876611.2', '364166.66', '12735.2', '4318.5', '208556.0', '198761.0', '359571.0', '181.17', '93524.83', '2608.5', '4190.7', '884607.6', '31756.98', '159963.0', '31876.51', '328758.4', '437449.0', '461329.0', '110362.0', '415425.0', '125240.0', '187017.0', '2802.5', '355010.0', '5346226.0', '677083.0', '18755430.0', '5812.24', '1244600.0', '8747.2', '75952.0', '1098540.0', '1105930.0', '37006.2', '172362.0', '156733.0', '516375.5', '800711.0', '98818.5', '322275.0', '537259.25', '91998.0', '6230.4', '801250.0', '26193.36', '196098.0', '37191.49', '893520.0', '856100.0', '89888.0', '468846.0', '5917422.0', '12196.0', '958000.0', '27016.0', '387855.0', '333215.0', '158239.0', '390841.0', '40163.0', '99325.0', '1308760.0', '314039.0', '408090.0', '483250.0', '16332.75', '546846.0', '1820.5', '34435.0']
----------------------------------------------------------------------------------------------------

➡️ street_number:
Unique values count: 9126
Null count: 7474511
Unique values (sample): ['4599', '177', '2335', '3739', '5951', '7407', '7332', '2018', '7160', '723', '8931', '6983', '6303', '4105', '9647', '3836', '650', '6167', '3052', '9981', '858', '2575', '5805', '7406', '3740', '7094', '4277', '5221', '6552', '7197', '4099', '6212', '2472', '1266', '6382', '4698', '1991', '5334', '5799', '5139', '9432', '253', '5662', '2478', '5020', '2808', '4716', '5668', '9042', '4674', '2498', '9610', '2035', '9918', '7716', '3314', '2128', '7598', '8667', '121', '5078', '7334', '3092', '5108', '889', '2624', '3936', '3901', '2059', '1859', '9499', '7911', '7503', '6432', '854', '9707', '7636', '484', '4880', '2118', '7684', '6787', '9769', '6093', '743', '1371', '3582', '4801', '1466', '5478', '7445', '8342', '6964', '7476', '6065', '3989', '2780', '6203', '7597', '4937', '6114', '3486', '7228', '6024', '364', '2751', '2921', '8155', '6000', '2374', '2193', '7013', '3332', '7732', '6518', '4547', '4940', '5540', '852', '6604']
----------------------------------------------------------------------------------------------------

➡️ btq_code:
Unique values count: 36
Null count: 19197741
Unique values (sample): ['2', 'X', 'T', 'O', 'V', 'Z', '6', 'I', '4', 'B', '8', 'A', '5', 'M', 'S', '3', 'F', 'W', 'Y', 'K', 'Q', 'C', 'N', '0', '7', 'H', 'G', 'R', 'U', '1', 'L', 'P', '9', 'D', 'J', 'E']
----------------------------------------------------------------------------------------------------

➡️ street_type:
Unique values count: 152
Null count: 7942059
Unique values (sample): ['CAN', 'VCHE', 'EMBR', 'VGE', 'PLCI', 'PARC', 'DIG', 'CC', 'VEN', 'PLAG', 'AV', 'RAC', 'PONT', 'PKG', 'CTR', 'CD', 'RES', 'CRX', 'GAL', 'CHT', 'HAB', 'CALL', 'RPT', 'ROC', 'QUAI', 'JARD', 'CHS', 'PL', 'CORO', 'PASS', 'PTTE', 'PAE', 'COTE', 'BRE', 'COR', 'PLAN', 'CAMI', 'CHL', 'ESP', 'RLE', 'ESC', 'VIA', 'VC', 'ZONE', 'ZAD', 'RUE', 'VAL', 'ILOT', 'ALL', 'BD', 'REM', 'SEN', 'PTE', 'TRA', 'QUA', 'JTE', 'TRAB', 'PLT', 'AGL', 'NTE', 'COL', 'MRN', 'ZUP', 'BRTL', 'SQ', 'TSSE', 'CPG', 'CAMP', 'VOUT', 'ART', 'CHE', 'PCH', 'BRG', 'FG', 'MAR', 'PTR', 'ZI', 'PLA', 'RTE', 'VLA', 'PIST', 'VOIE', 'ESPA', 'VOIR', 'ECL', 'D', 'ENC', 'PRV', 'PLE', 'DOM', 'RTD', 'BSN', 'CLOS', 'PAS', 'MAIL', 'LOT', 'TOUR', 'HLG', 'PROM', 'PRT', 'DSC', 'MAIS', 'CF', 'LEVE', 'COIN', 'COUR', 'IMP', 'CASR', 'RIVE', 'CHEM', 'ZAC', 'CAR', 'DRA', 'VALL', 'CLR', 'DEVI', 'BER', 'PORT', 'VOY', 'CRS']
----------------------------------------------------------------------------------------------------

➡️ street_id:
Unique values count: 20064
Null count: 150482
Unique values (sample): ['T383', '3739', 'W419', '5951', '7332', '0003', '7160', '7839', 'B071', 'J491', '7406', 'E916', 'D568', 'I015', '4277', '6552', 'H503', '4099', 'E365', '6212', 'D782', '5799', '9432', '5662', 'W308', 'F823', '5668', 'I324', '4674', 'G562', 'E915', '0124', 'J206', 'B770', 'X015', 'I931', 'R534', '0396', '8435', '2624', '5108', '1859', 'I904', '4707', '2118', 'G544', 'E802', '6787', '8475', 'E414', '6093', 'F270', '0973', 'D531', 'H796', '8151', '1466', '5478', 'I261', 'E125', 'C695', 'D009', '0824', '7228', '2751', 'B545', '2921', 'E420', 'H415', 'W364', 'P736', 'C461', '4547', '4940', 'F646', 'I952', '5540', '8602', 'E468', '4728', '1906', 'E829', '2155', '6962', 'W583', '6692', '1590', '8103', 'A095', '6353', 'D892', '7048', '0837', 'Q748', '0766', '6785', 'F941', '5857', '0854', '4250', 'F378', 'D068', 'B677', 'D105', '7780', 'H235', 'F819', 'Q443', '1842', 'G050', 'J209', 'B458', 'I138', 'E541', 'D154', '0657', '4518', 'B009', 'D417', 'F897']
----------------------------------------------------------------------------------------------------

➡️ street_name:
Unique values count: 1132199
Null count: 151263
Unique values (sample): ['MOULIN DE LA BOULE', 'LA RUSTE', 'LE PRE BECQUET', 'BORNILLON', 'LA BASSE VERRIERE', 'LE VERGER DE LA BROUSTIERE', 'SUR LE CHEMIN DE COURCHAMP', 'LES PERCIERES', 'LES BAS LORIOT', 'DU 22 JUIN 1944', 'BRETEUIL CENTRE', 'LA BARBAQUENNE', 'LES CHAUMES DE RISSAT', 'MONTBETON', 'LA CROIX PAQUET', 'LA VILLE PIQUANT', 'DU CHEMIN SONDROT', 'COUVIGNAC BAS', 'BOUZANNE', 'LES CRX', 'MEJOU KERVILLY', 'LE ROUTY ET LES LONGS 5 MU', 'LE ZIEN', 'DU BOIS DURET', 'DE ST LAURENT LA VERNEDE', 'BOURG DE RAVEL', 'SONGY SUD', 'TORTEILLAN', 'FAREDONDE', 'MEZ LORS', 'QUELERN EN BAS', 'PUCHULU', 'DE LA MEGRETTERIE', 'VALLOUREC SAINT SAULVE', 'URRETTE', 'LES LONGEURS', 'COLLAMBUTO', 'DE LA VILLE BALLET', 'EN POMMETIN', 'LA POIVRIE', 'DU CHANCELIER ADENAUER', 'DES PIVOLLES', 'DES FLAQUES', 'LE CLOS DE LA SAUVELLIERE', 'L HOTEL BONNET', 'LA CHARMAUDE', 'LABROUSSE SUD', 'LA POITEVIN', 'LAUBRAY', 'LE PONT DES QUESNOTS', 'SERRE BOUTONET', 'BAMBARA', 'LE DRESSAN', 'ENTRE RUE ORLEANS RLE ROQU', 'CLOS DERRIERE', 'LES GUILBAUDIERES', 'LES PATEZES', 'FUMADES', 'DU TUE VAQUES', 'CHER SOUBRANT', 'BASSE SAINT JEAN (MONTFAU', 'MARCEL BERNE', 'DE GOULMY', 'DU VIEUX JOUVENCON', 'DOC FRANCOIS', 'BOLLELONGUE', 'HT BILAIN', 'KERIHUEL EST', 'LA SAUVASSE', 'DE PECHPEYROU', 'SCUDERI', 'MALASSOUMADE', 'EN MALSARD A ROUSSOT', 'PROFESSEUR A P    BOUIN', 'DU SERRE DE CASSAGNES', 'EN JEAN', 'LA VAQUERESSE', 'LA CHAIGNEAU', 'CHEZ FILLAUX', 'BARRIERE DU TRONE', 'MARIUS CHALENDARD', 'LANNEC CRECH BIDAN', 'LA COMBRENEE', 'DES ETOQUIS', 'DES 7 FONTAINES', 'LE MOULIN DE FROMENTIERE', 'DE LA PETITE BOURGADE', 'LAIN HALLEC', 'TREVENANOU PARC AN AVALOU', 'LE PRE GOSSET', 'DES BRIGANTINS (PLAGE)', 'PRE A BOEUFS', "LES VIGNES D'ANTAN", 'FERME DU MAUNY', 'DU CASTEL OGI', 'CHARLES GODEFROY', 'LE CHAMP FAUDET', 'DE SENARENS', 'MOULIN DES VIGNES', 'CALA DI GIGLIO', 'LA COTE-SUD', 'DU HAUT GAUVIN', 'A LA CARRIERE DU CHEMIN D', 'VERS LE MOULIN DE ROUCOURT', 'AU FACHE', 'LA PINEDE DE GRIMAUD', 'HAUTE DES BAINS (VC93)', 'DE CANTO COUCUT', 'DU BARET', 'DESSOUS DE LA BUTTE', 'LES PRESIDANNES', 'CANTON DES NOUES', 'PLAGNES DE DESSUS', 'JACQUES-LOUIS BLOT', 'GERARD BAUMEL', 'GEORGES HELMINGER', 'PIECES DES METAIRIES', 'MAURICE RAIMBAUD', 'DE LIMITETAKO BIDEA', 'DE PACALON']
----------------------------------------------------------------------------------------------------

➡️ postal_code:
Unique values count: 5871
Null count: 151600
Unique values (sample): ['26330', '48260', '63200', '36400', '83260', '7160', '81360', '97130', '33860', '69150', '12780', '79160', '13360', '33141', '28410', '85660', '72530', '35500', '38490', '27860', '14114', '44200', '89113', '79290', '25260', '46330', '27750', '45420', '82410', '25160', '46190', '24470', '59125', '61440', '73530', '50000', '44115', '12580', '79800', '49112', '47500', '83870', '74120', '85560', '50620', '84300', '44410', '95110', '63260', '91160', '20137', '43210', '59239', '27910', '45400', '97330', '31360', '50480', '38450', '59530', '8190', '36290', '38370', '35320', '81440', '29510', '33170', '97450', '12360', '72350', '6000', '56410', '17570', '39230', '25210', '54810', '60940', '42840', '66820', '73520', '24360', '59231', '13810', '42600', '59117', '95280', '47000', '54580', '13100', '1590', '44260', '49220', '45260', '78570', '51240', '14670', '9000', '71670', '36330', '59181', '95700', '77860', '97280', '66500', '56350', '60540', '60100', '42155', '42920', '77630', '14112', '62800', '4250', '36250', '7100', '50810', '92400', '66680', '61140', '30820']
----------------------------------------------------------------------------------------------------

➡️ com_name:
Unique values count: 31569
Null count: 0
Unique values (sample): ['CESTAYROLS', 'COURTHIEZY', 'FRAISANS', 'MOUTIERS-EN-PUISAYE', 'ROCHE SUR YON (LA)', 'VILLIERS-EN-BIERE', 'MONTBETON', 'JOUAIGNES', 'LA DIGNE D AMONT', 'PAULIN', 'MONTREUIL-SOUS-PEROUSE', 'VAUX VILLAINE', 'BELVEDERE-CAMPOMORO', 'ROCHE-GUYON (LA)', 'LOUBAJAC', 'BEUZEVILLE-LA-GRENIER', 'BEUGNY', 'MATIGNICOURT-GONCOURT', 'LOUBIGNE', 'SAINT-MICHEL-SUR-ORGE', 'SALAZAC', 'SAVIGNY-POIL-FOL', 'CERNOY-EN-BERRY', 'MOUSTIERS-SAINTE-MARIE', 'SAINT YVI', 'SAINT GEORGES DE LA COUEE', 'SAINT-LEGER', 'LAREE', 'CARENCY', 'FERICY', 'CASTELNAU LE LEZ', 'RAILLENCOURT-SAINTE-OLLE', 'SAINT-CYR-SUR-MER', 'UROST', 'PLEUGRIFFET', 'CHILLY-LE-VIGNOBLE', 'NOVALE', 'OZOUER-LE-VOULGIS', 'BEAUFORT-EN-ANJOU', 'LE TOUVET', 'VALLE D OREZZA', 'DAGONVILLE', 'BELFONDS', 'MONCE EN SAOSNOIS', 'LOUVIERS', 'SAINT-ROMAIN-DE-POPEY', 'CAUVICOURT', 'ISSAMOULENC', 'CALONNE RICOUART', 'DEOLS', 'THEHILLAC', 'LES ISLETTES', 'ST-GERMAIN-LES-PAROISSES', 'AUREILLE', 'DANJOUTIN', 'LEMBRAS', 'MALVES-EN-MINERVOIS', 'PUY-DU-LAC', 'SAINT-BROING', 'GERARDMER', 'MARCIGNY', 'PELLEAUTIER', 'TERREBASSE', 'FONTAINE BONNELEAU', 'SAINT-LOUET-SUR-SEULLES', 'LA CHATRE-LANGLIN', 'MONTIGNY-LENCOUP', 'CROISILLES', 'SAINT VINCENT', 'SAINT-ILLIERS-LA-VILLE', 'BALAGUERES', 'TREMAOUEZAN', 'PALAVAS-LES-FLOTS', 'TREZILIDE', 'MAROLLETTE', 'LAVELINE-DU-HOUX', 'ST-PAUL-D OUEIL', 'BEZANCOURT', 'COURCELLES-SOUS-CHATENOIS', 'LE BOURG', 'VAROUVILLE', 'FORGES-LES-EAUX', 'BAUDRECOURT', 'POUILLY-SUR-VINGEANNE', 'PRUILLE LE CHETIF', 'LABOULE', 'OCCEY', 'CRENANS', 'MUNCQ-NIEURLET', 'GIBEAUMEIX', 'CHALEZEULE', 'LARNAUD', 'LE CHARMEL', 'DERNANCOURT', 'COUTEVROULT', 'THEUVILLE', 'LANDAVRAN', 'LE CHATEAU D OLERON', 'BROUSSE-LE-CHATEAU', 'RIGNY LE FERRON', 'SAINT-ESTEBEN', 'COSMES', 'GIVENCHY-LES-LA-BASSEE', 'BELBEZE-EN-COMMINGES', 'CUPERLY', 'GARDE-COLOMBE', 'LA CLUSAZ', 'RACHECOURT-SUZEMONT', 'CHAUSSY', 'EGLISOLLES', 'BURGARONNE', 'TREFFLEAN', 'SAINT-GERMAIN-LA-MONTAGNE', 'PROUVILLE', 'LANEUVELLE', 'JOU-SOUS-MONJOU', 'VANDONCOURT', 'SOULAIRES', 'LE BROUILH-MONBERT', 'COULOUVRAY-BOISBENATRE']
----------------------------------------------------------------------------------------------------

➡️ dep_code:
Unique values count: 97
Null count: 0
Unique values (sample): ['973', '21', '77', '35', '974', '04', '83', '26', '2A', '62', '58', '16', '19', '72', '13', '73', '69', '51', '14', '05', '94', '92', '88', '54', '89', '64', '39', '45', '43', '22', '10', '08', '76', '65', '06', '972', '82', '95', '12', '48', '28', '55', '74', '42', '59', '30', '70', '80', '17', '11', '50', '87', '32', '27', '56', '52', '44', '66', '47', '24', '971', '41', '40', '03', '86', '63', '46', '37', '31', '29', '18', '93', '91', '60', '36', '84', '07', '38', '23', '61', '85', '49', '33', '53', '81', '25', '15', '2B', '02', '79', '78', '34', '71', '01', '75', '90', '09']
----------------------------------------------------------------------------------------------------

➡️ com_code:
Unique values count: 908
Null count: 0
Unique values (sample): ['759', '800', '316', '575', '535', '177', '818', '757', '796', '791', '322', '206', '185', '710', '450', '282', '270', '694', '723', '306', '553', '564', '35', '749', '716', '673', '446', '539', '405', '464', '258', '650', '302', '223', '848', '269', '354', '524', '194', '346', '19', '858', '615', '286', '148', '154', '394', '13', '466', '159', '483', '815', '871', '104', '323', '660', '835', '846', '444', '67', '200', '402', '704', '88', '215', '439', '742', '488', '388', '739', '505', '137', '903', '117', '379', '397', '336', '642', '64', '39', '480', '758', '469', '393', '212', '638', '281', '253', '163', '762', '868', '409', '482', '157', '509', '698', '620', '679', '612', '726', '332', '108', '162', '632', '616', '164', '461', '339', '705', '817', '594', '619', '121', '199', '123', '304', '431', '492', '883', '527']
----------------------------------------------------------------------------------------------------

➡️ section_prefix:
Unique values count: 759
Null count: 19147817
Unique values (sample): ['316', '575', '177', '818', '757', '322', '206', '185', '450', '282', '270', '694', '564', '553', '306', '35', '749', '539', '405', '258', '223', '302', '269', '354', '524', '194', '346', '19', '858', '615', '286', '148', '154', '13', '466', '159', '483', '815', '871', '104', '323', '835', '846', '444', '67', '200', '704', '402', '88', '505', '439', '488', '903', '388', '215', '137', '742', '117', '509', '379', '642', '64', '469', '480', '39', '638', '212', '393', '253', '281', '163', '868', '409', '482', '157', '620', '332', '108', '162', '632', '616', '164', '339', '594', '817', '121', '199', '123', '431', '304', '492', '883', '889', '729', '527', '861', '140', '139', '641', '595', '429', '901', '362', '28', '228', '606', '381', '854', '351', '150', '235', '400', '390', '378', '484', '365', '237', '284', '50', '160']
----------------------------------------------------------------------------------------------------

➡️ section:
Unique values count: 588
Null count: 725
Unique values (sample): ['CK', 'DA', 'EP', 'LX', 'KH', 'X', 'GB', 'DH', 'B', 'ED', 'A', 'WN', 'PI', 'SM', 'GE', 'OA', 'GN', 'VV', 'FK', 'TR', 'LB', 'TL', 'RV', 'FN', 'FY', 'MY', 'YT', 'PT', 'WC', 'VL', 'TI', 'HE', 'BY', 'JK', 'KA', 'CU', 'EB', 'PR', 'RZ', 'KS', 'MG', 'VC', 'DY', 'EN', 'TH', 'BD', 'MH', 'YV', 'OM', 'JE', 'HX', 'M', 'GS', 'GD', 'GC', 'RR', 'WS', 'EH', 'FL', 'KJ', 'C', 'ZY', 'SD', 'XR', 'G', 'IC', 'ZK', 'LN', 'LO', 'D', 'HU', 'DO', 'WD', 'MA', 'SK', 'DE', 'LL', 'OS', 'AW', 'OB', 'SL', 'EC', 'SR', 'KW', 'BI', 'WK', 'ND', 'ZD', 'YO', 'XY', 'NM', 'EE', 'XO', 'HP', 'EO', 'MN', 'H', 'ZT', 'LC', 'GI', 'YW', 'CN', 'SA', 'BV', 'DT', 'IY', 'JL', 'AS', 'PS', 'I', 'YN', 'TM', 'HK', 'KF', 'DZ', 'VW', 'HY', 'TX', 'PO', 'BC']
----------------------------------------------------------------------------------------------------

➡️ plot_number:
Unique values count: 8239
Null count: 0
Unique values (sample): ['4599', '177', '2335', '3739', '4553', '5951', '7332', '2018', '7160', '723', '6983', '4105', '6303', '8967', '3836', '650', '6167', '3052', '858', '2575', '5805', '3740', '7094', '4277', '5221', '6552', '4099', '7197', '6212', '2472', '1266', '4698', '6382', '1991', '5334', '5799', '5139', '253', '5662', '2478', '5020', '2808', '4716', '5668', '4674', '2498', '2035', '3314', '2128', '121', '5078', '7334', '3092', '889', '2624', '5108', '3936', '3901', '2059', '1859', '7503', '6432', '854', '4707', '7636', '484', '4880', '2118', '7684', '8475', '6093', '743', '1371', '3582', '4801', '1466', '5478', '7445', '8342', '6964', '7476', '6065', '3989', '8190', '2780', '6203', '7597', '4937', '6114', '3486', '7228', '6024', '364', '2751', '2921', '6000', '2374', '2193', '7013', '3332', '7732', '6518', '4547', '4940', '5540', '852', '6604', '1997', '550', '6674', '3882', '5864', '6699', '251', '1502', '3015', '1133', '4728', '1906', '1806']
----------------------------------------------------------------------------------------------------

➡️ volume_number:
Unique values count: 2068
Null count: 20057358

C:\Users\sboub\AppData\Local\Temp\ipykernel_11120\2539792997.py:23: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  chunk[col] = chunk[col].replace(missing_markers, pd.NA)

---
### **DEAL with INVALID VALUES**

In [ ]:
from pathlib import Path
import pandas as pd

INPUT_FILE = Path("../data/processed/STANDARD_ValeursFoncieres.csv")
OUTPUT_FILE = Path("../data/processed/INVALIDS_ValeursFoncieres.csv")

CHUNK_SIZE = 50_000

date_cols = [
    "transaction_date",
]

numeric_float_cols = [
    "property_value",
    "building_real_surface",
    "land_surface",
    "lot_1_surface",
    "lot_2_surface",
    "lot_3_surface",
    "lot_4_surface",
    "lot_5_surface",
]

numeric_int_cols = [
    "lots_count",
    "main_rooms_count",
]

categorical_cols = [
    "transaction_id",
    "transaction_type",
    "street_number",
    "btq_code",
    "street_type",
    "street_id",
    "street_name",
    "postal_code",
    "com_name",
    "dep_code",
    "com_code",
    "section_prefix",
    "section",
    "plot_number",
    "volume_number",
    "property_type_code",
    "property_type",
    "land_nature",
    "land_nature_special",
    "lot_1",
    "lot_2",
    "lot_3",
    "lot_4",
    "lot_5",
]

missing_markers = {
    "MISSING", "", " ", "NA", "N/A", "None", "null", "NULL", "nan", "NaN"
}


def clean_string_columns(chunk: pd.DataFrame) -> pd.DataFrame:
    object_cols = chunk.select_dtypes(include="object").columns

    for col in object_cols:
        chunk[col] = chunk[col].astype(str).str.strip()
        chunk[col] = chunk[col].replace(list(missing_markers), pd.NA)

    return chunk


def clean_date_columns(chunk: pd.DataFrame, cols: list[str]) -> pd.DataFrame:
    for col in cols:
        if col in chunk.columns:
            chunk[col] = pd.to_datetime(
                chunk[col],
                format="%d/%m/%Y",
                errors="coerce"
            )
    return chunk


def clean_float_columns(chunk: pd.DataFrame, cols: list[str]) -> pd.DataFrame:
    for col in cols:
        if col in chunk.columns:
            chunk[col] = (
                chunk[col]
                .astype("string")
                .str.replace(",", ".", regex=False)
            )
            chunk[col] = pd.to_numeric(chunk[col], errors="coerce")
    return chunk


def clean_int_columns(chunk: pd.DataFrame, cols: list[str]) -> pd.DataFrame:
    for col in cols:
        if col in chunk.columns:
            chunk[col] = pd.to_numeric(chunk[col], errors="coerce").astype("Int64")
    return chunk


def clean_categorical_columns(chunk: pd.DataFrame, cols: list[str]) -> pd.DataFrame:
    for col in cols:
        if col in chunk.columns:
            chunk[col] = chunk[col].astype("string").str.strip()
            chunk[col] = chunk[col].replace(list(missing_markers), pd.NA)
    return chunk


def apply_custom_invalid_rules(chunk: pd.DataFrame) -> pd.DataFrame:
    # ---------------------------------------------------
    # transaction_type: translate and standardize
    # ---------------------------------------------------
    if "transaction_type" in chunk.columns:
        chunk["transaction_type"] = chunk["transaction_type"].replace({
            "Vente": "Sale",
            "Vente en l'état futur d'achèvement": "Sale in future state of completion",
            "Vente terrain à bâtir": "Sale of unbuilt land",
            "Echange": "Exchange",
            "Adjudication": "Auction",
            "Expropriation": "Expropriation",
        })

    # ---------------------------------------------------
    # property_type: translate and standardize
    # ---------------------------------------------------
    if "property_type" in chunk.columns:
        chunk["property_type"] = chunk["property_type"].replace({
            "Maison": "House",
            "Appartement": "Apartment",
            "Terrain": "Land",
            "Local commercial": "Commercial",
            "Bureau": "Office",
            "Autre": "Other",
        })
    # ---------------------------------------------------
    # surface_type: translate and standardize
    # ---------------------------------------------------
    # surface_type = "building" if building_real_surface > 0 and land_surface is 0
    # surface_type = "land" if building_real_surface is 0 and land_surface > 0
    # surface_type = "combined" if building_real_surface > 0 and land_surface > 0

    # ---------------------------------------------------
    # btq_code: clean invalid codes and standardize case
    # ---------------------------------------------------
    if "btq_code" in chunk.columns:
        invalid_values = ["-", ".", "*"]
        chunk["btq_code"] = chunk["btq_code"].replace(invalid_values, pd.NA)
        chunk["btq_code"] = chunk["btq_code"].replace({"b": "B"})

    # ---------------------------------------------------
    # building_real_surface: fill missing with 0
    # ---------------------------------------------------
    if "building_real_surface" in chunk.columns:
        chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)

    # ---------------------------------------------------
    # main_rooms_count: fill missing with 0
    # ---------------------------------------------------
    if "main_rooms_count" in chunk.columns:
        chunk["main_rooms_count"] = chunk["main_rooms_count"].fillna(0)

    return chunk


def clean_chunk(chunk: pd.DataFrame) -> pd.DataFrame:
    chunk = clean_string_columns(chunk)
    chunk = clean_date_columns(chunk, date_cols)
    chunk = clean_float_columns(chunk, numeric_float_cols)
    chunk = clean_int_columns(chunk, numeric_int_cols)
    chunk = clean_categorical_columns(chunk, categorical_cols)
    chunk = apply_custom_invalid_rules(chunk)
    return chunk


def clean_file_chunked(input_file: Path, output_file: Path, chunk_size: int = 50_000) -> None:
    output_file.parent.mkdir(parents=True, exist_ok=True)

    first_write = True
    total_rows = 0

    for chunk_idx, chunk in enumerate(
        pd.read_csv(input_file, chunksize=chunk_size, dtype=str),
        start=1
    ):
        chunk = clean_chunk(chunk)

        chunk.to_csv(
            output_file,
            mode="w" if first_write else "a",
            index=False,
            header=first_write,
            encoding="utf-8"
        )

        first_write = False
        total_rows += len(chunk)

        print(f"Chunk {chunk_idx} written -> {len(chunk):,} rows | total: {total_rows:,}")

    print("\nDone! Handled invalid values")
    print(f"Saved file: {output_file}")
    print(f"Total rows written: {total_rows:,}")


clean_file_chunked(INPUT_FILE, OUTPUT_FILE, CHUNK_SIZE)

Chunk 1 written -> 50,000 rows | total: 50,000
Chunk 2 written -> 50,000 rows | total: 100,000
Chunk 3 written -> 50,000 rows | total: 150,000
Chunk 4 written -> 50,000 rows | total: 200,000
Chunk 5 written -> 50,000 rows | total: 250,000
Chunk 6 written -> 50,000 rows | total: 300,000
Chunk 7 written -> 50,000 rows | total: 350,000
Chunk 8 written -> 50,000 rows | total: 400,000
Chunk 9 written -> 50,000 rows | total: 450,000
Chunk 10 written -> 50,000 rows | total: 500,000
Chunk 11 written -> 50,000 rows | total: 550,000
Chunk 12 written -> 50,000 rows | total: 600,000
Chunk 13 written -> 50,000 rows | total: 650,000
Chunk 14 written -> 50,000 rows | total: 700,000
Chunk 15 written -> 50,000 rows | total: 750,000
Chunk 16 written -> 50,000 rows | total: 800,000
Chunk 17 written -> 50,000 rows | total: 850,000
Chunk 18 written -> 50,000 rows | total: 900,000
Chunk 19 written -> 50,000 rows | total: 950,000
Chunk 20 written -> 50,000 rows | total: 1,000,000
Chunk 21 written -> 50,000 rows | total: 1,050,000
Chunk 22 written -> 50,000 rows | total: 1,100,000
Chunk 23 written -> 50,000 rows | total: 1,150,000
Chunk 24 written -> 50,000 rows | total: 1,200,000
Chunk 25 written -> 50,000 rows | total: 1,250,000
Chunk 26 written -> 50,000 rows | total: 1,300,000
Chunk 27 written -> 50,000 rows | total: 1,350,000
Chunk 28 written -> 50,000 rows | total: 1,400,000
Chunk 29 written -> 50,000 rows | total: 1,450,000
Chunk 30 written -> 50,000 rows | total: 1,500,000
Chunk 31 written -> 50,000 rows | total: 1,550,000
Chunk 32 written -> 50,000 rows | total: 1,600,000
Chunk 33 written -> 50,000 rows | total: 1,650,000
Chunk 34 written -> 50,000 rows | total: 1,700,000
Chunk 35 written -> 50,000 rows | total: 1,750,000
Chunk 36 written -> 50,000 rows | total: 1,800,000
Chunk 37 written -> 50,000 rows | total: 1,850,000
Chunk 38 written -> 50,000 rows | total: 1,900,000
Chunk 39 written -> 50,000 rows | total: 1,950,000
Chunk 40 written -> 50,000 rows | total: 2,000,000
Chunk 41 written -> 50,000 rows | total: 2,050,000
Chunk 42 written -> 50,000 rows | total: 2,100,000
Chunk 43 written -> 50,000 rows | total: 2,150,000
Chunk 44 written -> 50,000 rows | total: 2,200,000
Chunk 45 written -> 50,000 rows | total: 2,250,000
Chunk 46 written -> 50,000 rows | total: 2,300,000
Chunk 47 written -> 50,000 rows | total: 2,350,000
Chunk 48 written -> 50,000 rows | total: 2,400,000
Chunk 49 written -> 50,000 rows | total: 2,450,000
Chunk 50 written -> 50,000 rows | total: 2,500,000
Chunk 51 written -> 50,000 rows | total: 2,550,000
Chunk 52 written -> 50,000 rows | total: 2,600,000
Chunk 53 written -> 50,000 rows | total: 2,650,000
Chunk 54 written -> 50,000 rows | total: 2,700,000
Chunk 55 written -> 50,000 rows | total: 2,750,000
Chunk 56 written -> 50,000 rows | total: 2,800,000
Chunk 57 written -> 50,000 rows | total: 2,850,000
Chunk 58 written -> 50,000 rows | total: 2,900,000
Chunk 59 written -> 50,000 rows | total: 2,950,000
Chunk 60 written -> 50,000 rows | total: 3,000,000
Chunk 61 written -> 50,000 rows | total: 3,050,000
Chunk 62 written -> 50,000 rows | total: 3,100,000
Chunk 63 written -> 50,000 rows | total: 3,150,000
Chunk 64 written -> 50,000 rows | total: 3,200,000
Chunk 65 written -> 50,000 rows | total: 3,250,000
Chunk 66 written -> 50,000 rows | total: 3,300,000
Chunk 67 written -> 50,000 rows | total: 3,350,000
Chunk 68 written -> 50,000 rows | total: 3,400,000
Chunk 69 written -> 50,000 rows | total: 3,450,000
Chunk 70 written -> 50,000 rows | total: 3,500,000
Chunk 71 written -> 50,000 rows | total: 3,550,000
Chunk 72 written -> 50,000 rows | total: 3,600,000
Chunk 73 written -> 50,000 rows | total: 3,650,000
Chunk 74 written -> 50,000 rows | total: 3,700,000
Chunk 75 written -> 50,000 rows | total: 3,750,000
Chunk 76 written -> 50,000 rows | total: 3,800,000
Chunk 77 written -> 50,000 rows | total: 3,850,000
Chunk 78 written -> 50,000 rows | total: 3,900,000
Chunk 79 written -> 50,000 rows | total: 3,950,000
Chunk 80 written -> 50,000 rows | total: 4,000,000
Chunk 81 written -> 50,000 rows | total: 4,050,000
Chunk 82 written -> 50,000 rows | total: 4,100,000
Chunk 83 written -> 50,000 rows | total: 4,150,000
Chunk 84 written -> 50,000 rows | total: 4,200,000
Chunk 85 written -> 50,000 rows | total: 4,250,000
Chunk 86 written -> 50,000 rows | total: 4,300,000
Chunk 87 written -> 50,000 rows | total: 4,350,000
Chunk 88 written -> 50,000 rows | total: 4,400,000
Chunk 89 written -> 50,000 rows | total: 4,450,000
Chunk 90 written -> 50,000 rows | total: 4,500,000
Chunk 91 written -> 50,000 rows | total: 4,550,000
Chunk 92 written -> 50,000 rows | total: 4,600,000
Chunk 93 written -> 50,000 rows | total: 4,650,000
Chunk 94 written -> 50,000 rows | total: 4,700,000
Chunk 95 written -> 50,000 rows | total: 4,750,000
Chunk 96 written -> 50,000 rows | total: 4,800,000
Chunk 97 written -> 50,000 rows | total: 4,850,000
Chunk 98 written -> 50,000 rows | total: 4,900,000
Chunk 99 written -> 50,000 rows | total: 4,950,000
Chunk 100 written -> 50,000 rows | total: 5,000,000
Chunk 101 written -> 50,000 rows | total: 5,050,000
Chunk 102 written -> 50,000 rows | total: 5,100,000
Chunk 103 written -> 50,000 rows | total: 5,150,000
Chunk 104 written -> 50,000 rows | total: 5,200,000
Chunk 105 written -> 50,000 rows | total: 5,250,000
Chunk 106 written -> 50,000 rows | total: 5,300,000
Chunk 107 written -> 50,000 rows | total: 5,350,000
Chunk 108 written -> 50,000 rows | total: 5,400,000
Chunk 109 written -> 50,000 rows | total: 5,450,000
Chunk 110 written -> 50,000 rows | total: 5,500,000
Chunk 111 written -> 50,000 rows | total: 5,550,000
Chunk 112 written -> 50,000 rows | total: 5,600,000
Chunk 113 written -> 50,000 rows | total: 5,650,000
Chunk 114 written -> 50,000 rows | total: 5,700,000
Chunk 115 written -> 50,000 rows | total: 5,750,000
Chunk 116 written -> 50,000 rows | total: 5,800,000
Chunk 117 written -> 50,000 rows | total: 5,850,000
Chunk 118 written -> 50,000 rows | total: 5,900,000
Chunk 119 written -> 50,000 rows | total: 5,950,000
Chunk 120 written -> 50,000 rows | total: 6,000,000
Chunk 121 written -> 50,000 rows | total: 6,050,000
Chunk 122 written -> 50,000 rows | total: 6,100,000
Chunk 123 written -> 50,000 rows | total: 6,150,000
Chunk 124 written -> 50,000 rows | total: 6,200,000
Chunk 125 written -> 50,000 rows | total: 6,250,000
Chunk 126 written -> 50,000 rows | total: 6,300,000
Chunk 127 written -> 50,000 rows | total: 6,350,000
Chunk 128 written -> 50,000 rows | total: 6,400,000
Chunk 129 written -> 50,000 rows | total: 6,450,000
Chunk 130 written -> 50,000 rows | total: 6,500,000
Chunk 131 written -> 50,000 rows | total: 6,550,000
Chunk 132 written -> 50,000 rows | total: 6,600,000
Chunk 133 written -> 50,000 rows | total: 6,650,000
Chunk 134 written -> 50,000 rows | total: 6,700,000
Chunk 135 written -> 50,000 rows | total: 6,750,000
Chunk 136 written -> 50,000 rows | total: 6,800,000
Chunk 137 written -> 50,000 rows | total: 6,850,000
Chunk 138 written -> 50,000 rows | total: 6,900,000
Chunk 139 written -> 50,000 rows | total: 6,950,000
Chunk 140 written -> 50,000 rows | total: 7,000,000
Chunk 141 written -> 50,000 rows | total: 7,050,000
Chunk 142 written -> 50,000 rows | total: 7,100,000
Chunk 143 written -> 50,000 rows | total: 7,150,000
Chunk 144 written -> 50,000 rows | total: 7,200,000
Chunk 145 written -> 50,000 rows | total: 7,250,000
Chunk 146 written -> 50,000 rows | total: 7,300,000
Chunk 147 written -> 50,000 rows | total: 7,350,000
Chunk 148 written -> 50,000 rows | total: 7,400,000
Chunk 149 written -> 50,000 rows | total: 7,450,000
Chunk 150 written -> 50,000 rows | total: 7,500,000
Chunk 151 written -> 50,000 rows | total: 7,550,000
Chunk 152 written -> 50,000 rows | total: 7,600,000
Chunk 153 written -> 50,000 rows | total: 7,650,000
Chunk 154 written -> 50,000 rows | total: 7,700,000
Chunk 155 written -> 50,000 rows | total: 7,750,000
Chunk 156 written -> 50,000 rows | total: 7,800,000
Chunk 157 written -> 50,000 rows | total: 7,850,000
Chunk 158 written -> 50,000 rows | total: 7,900,000
Chunk 159 written -> 50,000 rows | total: 7,950,000
Chunk 160 written -> 50,000 rows | total: 8,000,000
Chunk 161 written -> 50,000 rows | total: 8,050,000
Chunk 162 written -> 50,000 rows | total: 8,100,000
Chunk 163 written -> 50,000 rows | total: 8,150,000
Chunk 164 written -> 50,000 rows | total: 8,200,000
Chunk 165 written -> 50,000 rows | total: 8,250,000
Chunk 166 written -> 50,000 rows | total: 8,300,000
Chunk 167 written -> 50,000 rows | total: 8,350,000
Chunk 168 written -> 50,000 rows | total: 8,400,000
Chunk 169 written -> 50,000 rows | total: 8,450,000
Chunk 170 written -> 50,000 rows | total: 8,500,000
Chunk 171 written -> 50,000 rows | total: 8,550,000
Chunk 172 written -> 50,000 rows | total: 8,600,000
Chunk 173 written -> 50,000 rows | total: 8,650,000
Chunk 174 written -> 50,000 rows | total: 8,700,000
Chunk 175 written -> 50,000 rows | total: 8,750,000
Chunk 176 written -> 50,000 rows | total: 8,800,000
Chunk 177 written -> 50,000 rows | total: 8,850,000
Chunk 178 written -> 50,000 rows | total: 8,900,000
Chunk 179 written -> 50,000 rows | total: 8,950,000
Chunk 180 written -> 50,000 rows | total: 9,000,000
Chunk 181 written -> 50,000 rows | total: 9,050,000
Chunk 182 written -> 50,000 rows | total: 9,100,000
Chunk 183 written -> 50,000 rows | total: 9,150,000
Chunk 184 written -> 50,000 rows | total: 9,200,000
Chunk 185 written -> 50,000 rows | total: 9,250,000
Chunk 186 written -> 50,000 rows | total: 9,300,000
Chunk 187 written -> 50,000 rows | total: 9,350,000
Chunk 188 written -> 50,000 rows | total: 9,400,000
Chunk 189 written -> 50,000 rows | total: 9,450,000
Chunk 190 written -> 50,000 rows | total: 9,500,000
Chunk 191 written -> 50,000 rows | total: 9,550,000
Chunk 192 written -> 50,000 rows | total: 9,600,000
Chunk 193 written -> 50,000 rows | total: 9,650,000
Chunk 194 written -> 50,000 rows | total: 9,700,000
Chunk 195 written -> 50,000 rows | total: 9,750,000
Chunk 196 written -> 50,000 rows | total: 9,800,000
Chunk 197 written -> 50,000 rows | total: 9,850,000
Chunk 198 written -> 50,000 rows | total: 9,900,000
Chunk 199 written -> 50,000 rows | total: 9,950,000
Chunk 200 written -> 50,000 rows | total: 10,000,000
Chunk 201 written -> 50,000 rows | total: 10,050,000
Chunk 202 written -> 50,000 rows | total: 10,100,000
Chunk 203 written -> 50,000 rows | total: 10,150,000
Chunk 204 written -> 50,000 rows | total: 10,200,000
Chunk 205 written -> 50,000 rows | total: 10,250,000
Chunk 206 written -> 50,000 rows | total: 10,300,000
Chunk 207 written -> 50,000 rows | total: 10,350,000
Chunk 208 written -> 50,000 rows | total: 10,400,000
Chunk 209 written -> 50,000 rows | total: 10,450,000
Chunk 210 written -> 50,000 rows | total: 10,500,000
Chunk 211 written -> 50,000 rows | total: 10,550,000
Chunk 212 written -> 50,000 rows | total: 10,600,000
Chunk 213 written -> 50,000 rows | total: 10,650,000
Chunk 214 written -> 50,000 rows | total: 10,700,000
Chunk 215 written -> 50,000 rows | total: 10,750,000
Chunk 216 written -> 50,000 rows | total: 10,800,000
Chunk 217 written -> 50,000 rows | total: 10,850,000
Chunk 218 written -> 50,000 rows | total: 10,900,000
Chunk 219 written -> 50,000 rows | total: 10,950,000
Chunk 220 written -> 50,000 rows | total: 11,000,000
Chunk 221 written -> 50,000 rows | total: 11,050,000
Chunk 222 written -> 50,000 rows | total: 11,100,000
Chunk 223 written -> 50,000 rows | total: 11,150,000
Chunk 224 written -> 50,000 rows | total: 11,200,000
Chunk 225 written -> 50,000 rows | total: 11,250,000
Chunk 226 written -> 50,000 rows | total: 11,300,000
Chunk 227 written -> 50,000 rows | total: 11,350,000
Chunk 228 written -> 50,000 rows | total: 11,400,000
Chunk 229 written -> 50,000 rows | total: 11,450,000
Chunk 230 written -> 50,000 rows | total: 11,500,000
Chunk 231 written -> 50,000 rows | total: 11,550,000
Chunk 232 written -> 50,000 rows | total: 11,600,000
Chunk 233 written -> 50,000 rows | total: 11,650,000
Chunk 234 written -> 50,000 rows | total: 11,700,000
Chunk 235 written -> 50,000 rows | total: 11,750,000
Chunk 236 written -> 50,000 rows | total: 11,800,000
Chunk 237 written -> 50,000 rows | total: 11,850,000
Chunk 238 written -> 50,000 rows | total: 11,900,000
Chunk 239 written -> 50,000 rows | total: 11,950,000
Chunk 240 written -> 50,000 rows | total: 12,000,000
Chunk 241 written -> 50,000 rows | total: 12,050,000
Chunk 242 written -> 50,000 rows | total: 12,100,000
Chunk 243 written -> 50,000 rows | total: 12,150,000
Chunk 244 written -> 50,000 rows | total: 12,200,000
Chunk 245 written -> 50,000 rows | total: 12,250,000
Chunk 246 written -> 50,000 rows | total: 12,300,000
Chunk 247 written -> 50,000 rows | total: 12,350,000
Chunk 248 written -> 50,000 rows | total: 12,400,000
Chunk 249 written -> 50,000 rows | total: 12,450,000
Chunk 250 written -> 50,000 rows | total: 12,500,000
Chunk 251 written -> 50,000 rows | total: 12,550,000
Chunk 252 written -> 50,000 rows | total: 12,600,000
Chunk 253 written -> 50,000 rows | total: 12,650,000
Chunk 254 written -> 50,000 rows | total: 12,700,000
Chunk 255 written -> 50,000 rows | total: 12,750,000
Chunk 256 written -> 50,000 rows | total: 12,800,000
Chunk 257 written -> 50,000 rows | total: 12,850,000
Chunk 258 written -> 50,000 rows | total: 12,900,000
Chunk 259 written -> 50,000 rows | total: 12,950,000
Chunk 260 written -> 50,000 rows | total: 13,000,000
Chunk 261 written -> 50,000 rows | total: 13,050,000
Chunk 262 written -> 50,000 rows | total: 13,100,000
Chunk 263 written -> 50,000 rows | total: 13,150,000
Chunk 264 written -> 50,000 rows | total: 13,200,000
Chunk 265 written -> 50,000 rows | total: 13,250,000
Chunk 266 written -> 50,000 rows | total: 13,300,000
Chunk 267 written -> 50,000 rows | total: 13,350,000
Chunk 268 written -> 50,000 rows | total: 13,400,000
Chunk 269 written -> 50,000 rows | total: 13,450,000
Chunk 270 written -> 50,000 rows | total: 13,500,000
Chunk 271 written -> 50,000 rows | total: 13,550,000
Chunk 272 written -> 50,000 rows | total: 13,600,000
Chunk 273 written -> 50,000 rows | total: 13,650,000
Chunk 274 written -> 50,000 rows | total: 13,700,000
Chunk 275 written -> 50,000 rows | total: 13,750,000
Chunk 276 written -> 50,000 rows | total: 13,800,000
Chunk 277 written -> 50,000 rows | total: 13,850,000
Chunk 278 written -> 50,000 rows | total: 13,900,000
Chunk 279 written -> 50,000 rows | total: 13,950,000
Chunk 280 written -> 50,000 rows | total: 14,000,000
Chunk 281 written -> 50,000 rows | total: 14,050,000
Chunk 282 written -> 50,000 rows | total: 14,100,000
Chunk 283 written -> 50,000 rows | total: 14,150,000
Chunk 284 written -> 50,000 rows | total: 14,200,000
Chunk 285 written -> 50,000 rows | total: 14,250,000
Chunk 286 written -> 50,000 rows | total: 14,300,000
Chunk 287 written -> 50,000 rows | total: 14,350,000
Chunk 288 written -> 50,000 rows | total: 14,400,000
Chunk 289 written -> 50,000 rows | total: 14,450,000
Chunk 290 written -> 50,000 rows | total: 14,500,000
Chunk 291 written -> 50,000 rows | total: 14,550,000
Chunk 292 written -> 50,000 rows | total: 14,600,000
Chunk 293 written -> 50,000 rows | total: 14,650,000
Chunk 294 written -> 50,000 rows | total: 14,700,000
Chunk 295 written -> 50,000 rows | total: 14,750,000
Chunk 296 written -> 50,000 rows | total: 14,800,000
Chunk 297 written -> 50,000 rows | total: 14,850,000
Chunk 298 written -> 50,000 rows | total: 14,900,000
Chunk 299 written -> 50,000 rows | total: 14,950,000
Chunk 300 written -> 50,000 rows | total: 15,000,000
Chunk 301 written -> 50,000 rows | total: 15,050,000
Chunk 302 written -> 50,000 rows | total: 15,100,000
Chunk 303 written -> 50,000 rows | total: 15,150,000
Chunk 304 written -> 50,000 rows | total: 15,200,000
Chunk 305 written -> 50,000 rows | total: 15,250,000
Chunk 306 written -> 50,000 rows | total: 15,300,000
Chunk 307 written -> 50,000 rows | total: 15,350,000
Chunk 308 written -> 50,000 rows | total: 15,400,000
Chunk 309 written -> 50,000 rows | total: 15,450,000
Chunk 310 written -> 50,000 rows | total: 15,500,000
Chunk 311 written -> 50,000 rows | total: 15,550,000
Chunk 312 written -> 50,000 rows | total: 15,600,000
Chunk 313 written -> 50,000 rows | total: 15,650,000
Chunk 314 written -> 50,000 rows | total: 15,700,000
Chunk 315 written -> 50,000 rows | total: 15,750,000
Chunk 316 written -> 50,000 rows | total: 15,800,000
Chunk 317 written -> 50,000 rows | total: 15,850,000
Chunk 318 written -> 50,000 rows | total: 15,900,000
Chunk 319 written -> 50,000 rows | total: 15,950,000
Chunk 320 written -> 50,000 rows | total: 16,000,000
Chunk 321 written -> 50,000 rows | total: 16,050,000
Chunk 322 written -> 50,000 rows | total: 16,100,000
Chunk 323 written -> 50,000 rows | total: 16,150,000
Chunk 324 written -> 50,000 rows | total: 16,200,000
Chunk 325 written -> 50,000 rows | total: 16,250,000
Chunk 326 written -> 50,000 rows | total: 16,300,000
Chunk 327 written -> 50,000 rows | total: 16,350,000
Chunk 328 written -> 50,000 rows | total: 16,400,000
Chunk 329 written -> 50,000 rows | total: 16,450,000
Chunk 330 written -> 50,000 rows | total: 16,500,000
Chunk 331 written -> 50,000 rows | total: 16,550,000
Chunk 332 written -> 50,000 rows | total: 16,600,000
Chunk 333 written -> 50,000 rows | total: 16,650,000
Chunk 334 written -> 50,000 rows | total: 16,700,000
Chunk 335 written -> 50,000 rows | total: 16,750,000
Chunk 336 written -> 50,000 rows | total: 16,800,000
Chunk 337 written -> 50,000 rows | total: 16,850,000
Chunk 338 written -> 50,000 rows | total: 16,900,000
Chunk 339 written -> 50,000 rows | total: 16,950,000
Chunk 340 written -> 50,000 rows | total: 17,000,000
Chunk 341 written -> 50,000 rows | total: 17,050,000
Chunk 342 written -> 50,000 rows | total: 17,100,000
Chunk 343 written -> 50,000 rows | total: 17,150,000
Chunk 344 written -> 50,000 rows | total: 17,200,000
Chunk 345 written -> 50,000 rows | total: 17,250,000
Chunk 346 written -> 50,000 rows | total: 17,300,000
Chunk 347 written -> 50,000 rows | total: 17,350,000
Chunk 348 written -> 50,000 rows | total: 17,400,000
Chunk 349 written -> 50,000 rows | total: 17,450,000
Chunk 350 written -> 50,000 rows | total: 17,500,000
Chunk 351 written -> 50,000 rows | total: 17,550,000
Chunk 352 written -> 50,000 rows | total: 17,600,000
Chunk 353 written -> 50,000 rows | total: 17,650,000
Chunk 354 written -> 50,000 rows | total: 17,700,000
Chunk 355 written -> 50,000 rows | total: 17,750,000
Chunk 356 written -> 50,000 rows | total: 17,800,000
Chunk 357 written -> 50,000 rows | total: 17,850,000
Chunk 358 written -> 50,000 rows | total: 17,900,000
Chunk 359 written -> 50,000 rows | total: 17,950,000
Chunk 360 written -> 50,000 rows | total: 18,000,000
Chunk 361 written -> 50,000 rows | total: 18,050,000
Chunk 362 written -> 50,000 rows | total: 18,100,000
Chunk 363 written -> 50,000 rows | total: 18,150,000
Chunk 364 written -> 50,000 rows | total: 18,200,000
Chunk 365 written -> 50,000 rows | total: 18,250,000
Chunk 366 written -> 50,000 rows | total: 18,300,000
Chunk 367 written -> 50,000 rows | total: 18,350,000
Chunk 368 written -> 50,000 rows | total: 18,400,000
Chunk 369 written -> 50,000 rows | total: 18,450,000
Chunk 370 written -> 50,000 rows | total: 18,500,000
Chunk 371 written -> 50,000 rows | total: 18,550,000
Chunk 372 written -> 50,000 rows | total: 18,600,000
Chunk 373 written -> 50,000 rows | total: 18,650,000
Chunk 374 written -> 50,000 rows | total: 18,700,000
Chunk 375 written -> 50,000 rows | total: 18,750,000
Chunk 376 written -> 50,000 rows | total: 18,800,000
Chunk 377 written -> 50,000 rows | total: 18,850,000
Chunk 378 written -> 50,000 rows | total: 18,900,000
Chunk 379 written -> 50,000 rows | total: 18,950,000
Chunk 380 written -> 50,000 rows | total: 19,000,000
Chunk 381 written -> 50,000 rows | total: 19,050,000
Chunk 382 written -> 50,000 rows | total: 19,100,000
Chunk 383 written -> 50,000 rows | total: 19,150,000

---
###  **CREATE `df_com_dep`**

from `df_com` :
- ✔ COMTYPE → commune type
- ✔ COM → commune INSEE code
- ✔ NCCENR → official commune names in MAJ & "-" & ACCENT
- ✔ DEP → department code

from `df_dep` :
 - ✔ DEP → department code
 - ✔ NCCENR → official department names NAMES

combine: add dep_name using DEP

rename columns

save csv

#### **CREATE `df_com`**
- create df_com with select columns from v_communes_2026.csv
	- COM
	- TYPECOM
	- NCCENR (uppercase + encoding & decoding)
	- DEP
- rename df_com columns
	- insee_code = COM
	- com_type = TYPECOM 
	- com_name = NCCENR
	- dep_code = DEP

In [ ]:
# load raw communes dataset
try:
    df_com = pd.read_csv("../data/raw/v_commune_2026.csv", sep=",", encoding="utf-8")
except UnicodeDecodeError:
    df_com = pd.read_csv("../data/raw/v_commune_2026.csv", sep=",", encoding="latin-1")

# rename df_com columns
df_com.rename(columns={
    "COM": "insee_code",
    "TYPECOM": "com_type",
    "NCCENR": "com_name",
    "DEP": "dep_code"
}, inplace=True)

# uppercase + encoding & decoding of com_name
df_com["com_name"] = (
    df_com["com_name"]
    .astype(str)
    .str.upper()
)

# drop other columns except insee_code, com_type, com_name, dep_code
df_com = df_com[["insee_code", "com_type", "com_name", "dep_code"]]

# display df_com
print("Communes Dataset Shape:", df_com.shape[0], "rows and", df_com.shape[1], "columns")
display(df_com.head())
print(100 * "-")
# display unique values of com_name
print("Unique Values of `com_name`:")
display(df_com["com_name"].unique())

# save df_com in a new CSV file
df_com.to_csv("../data/processed/COM_2026.csv", index=False)

#### **CREATE `df_dep`**

In [ ]:
# load raw departement dataset
try:
    df_dep = pd.read_csv("../data/raw/v_departement_2026.csv", sep=",", encoding="utf-8")
except UnicodeDecodeError:
    df_dep = pd.read_csv("../data/raw/v_departement_2026.csv", sep=",", encoding="latin-1")

# rename df_dep columns
df_dep.rename(columns={
    "DEP": "dep_code",
    "NCCENR": "dep_name"
}, inplace=True)

# uppercase + encoding & decoding of dep_name
df_dep["dep_name"] = (
    df_dep["dep_name"]
    .astype(str)
    .str.upper()
)

# drop other columns except dep_code, dep_name
df_dep = df_dep[["dep_code", "dep_name"]]

# display df_dep
print("Departements Dataset Shape:", df_dep.shape[0], "rows and", df_dep.shape[1], "columns")
display(df_dep.head())
print(100 * "-")
# display unique values of dep_name
print("Unique Values of `dep_name`:")
display(df_dep["dep_name"].unique())

# save df_dep in a new CSV file
df_dep.to_csv("../data/processed/DEP_2026.csv", index=False)

#### **USE `com_name`**

In [ ]:
# create df_com_dep by merging df_com and df_dep on dep_code
df_com_dep = pd.merge(df_com, df_dep, on="dep_code", how="left")
# display df_com_dep
print("Combined Communes & Departements Dataset Shape:", df_com_dep.shape[0], "rows and", df_com_dep.shape[1], "columns")
display(df_com_dep.head())
print(100 * "-")
# display unique values of com_name and dep_name in df_com_dep
print("Unique Values of `com_name` in df_com_dep:")
display(df_com_dep["com_name"].unique())
print("Unique Values of `dep_name` in df_com_dep:")
display(df_com_dep["dep_name"].unique())
# save df_com_dep in a new CSV file
df_com_dep.to_csv("../data/processed/COM_DEP_2026.csv", index=False)

<hr>

## 3️⃣ DATA TYPES


<style>
h1 {
    text-align: center;
    color: black;
    font-weight: bold;
}
</style>

<style>
h2 {
    text-align: left;
    color: black;
    font-weight: bold;
}
</style>

<style>
h3 {
    text-align: left;
    color: black;
    font-weight: bold;
}
</style>

<style>
h4 {
    text-align: left;
    color: black;
    font-weight: bold;
}
</style>
<hr>

### **SHAPE & HEAD**

In [48]:
import pandas as pd

FILE = "../data/processed/INVALIDS_ValeursFoncieres.csv"
CHUNK_SIZE = 50_000

total_rows = 0
columns = None

for chunk in pd.read_csv(FILE, chunksize=CHUNK_SIZE, dtype=str):
    total_rows += len(chunk)
    if columns is None:
        columns = chunk.columns

print("Shape:", total_rows, "rows and", len(columns), "columns")

df_head = pd.read_csv(FILE, nrows=5, dtype=str)
display(df_head)

Shape: 20102739 rows and 35 columns

,transaction_id,transaction_date,transaction_type,property_value,street_number,btq_code,street_type,street_id,street_name,postal_code,com_name,dep_code,com_code,section_prefix,section,plot_number,volume_number,lot_1,lot_1_surface,lot_2,lot_2_surface,lot_3,lot_3_surface,lot_4,lot_4_surface,lot_5,lot_5_surface,lots_count,property_type_code,property_type,building_real_surface,main_rooms_count,land_nature,land_nature_special,land_surface
0,000001,2020-07-01,Sale,31234.16,NaN,NaN,NaN,B064,SAINT JULIEN,1560,SAINT-JULIEN-SUR-REYSSOUZE,01,367,NaN,A,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,0,0,AB,NaN,1192
1,000001,2020-07-01,Sale,278000.0,NaN,NaN,NaN,B188,A LA PEROUSE,1250,CORVEISSIAT,01,125,NaN,C,509,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,0,0,BS,NaN,10092
2,000001,2020-07-01,Sale,278000.0,NaN,NaN,NaN,B188,A LA PEROUSE,1250,CORVEISSIAT,01,125,NaN,C,510,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,0,0,L,NaN,4570
3,000001,2020-07-01,Sale,278000.0,NaN,NaN,NaN,B079,AUX COMMUNS,1250,CORVEISSIAT,01,125,NaN,ZL,96,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,0,0,BS,NaN,5750
4,000001,2020-07-01,Sale,278000.0,NaN,NaN,NaN,B033,EN COMBARNAUD,1250,SIMANDRE-SUR-SURAN,01,408,NaN,A,14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,0,0,BT,NaN,648170

### **NULL COUNT vs UNIQUE VALUES**

In [7]:
from collections import defaultdict
import pandas as pd

FILE = "../data/processed/INVALIDS_ValeursFoncieres.csv"

unique_values = defaultdict(set)
null_counts = defaultdict(int)
total_rows = 0

for chunk in pd.read_csv(
    FILE,
    chunksize=50_000,
    dtype=str,          # ✅ avoids mixed types warning
    low_memory=False
):
    total_rows += len(chunk)

    for col in chunk.columns:
        # ✅ Count nulls (DO NOT drop them)
        null_counts[col] += chunk[col].isna().sum()

        # ✅ Collect only non-null values (nulls are still preserved in dataset)
        unique_values[col].update(
            chunk.loc[chunk[col].notna(), col].unique()
        )

# --------------------------------------------------
# Display results
# --------------------------------------------------
print(f"\nTotal rows processed: {total_rows:,}")
print(100 * "-")

for col in unique_values:
    values = list(unique_values[col])
    null_pct = (null_counts[col] / total_rows) * 100

    print(f"\n➡️ {col}:")
    print(f"Unique values count: {len(values)}")
    print(f"Null count: {null_counts[col]} ({null_pct:.2f}%)")
    print(f"Sample values: {values[:120]}")

    print(100 * "-")

Total rows processed: 20,102,739
----------------------------------------------------------------------------------------------------

➡️ transaction_id:
Unique values count: 1204
Null count: 0 (0.00%)
Sample values: ['000449', '000627', '000663', '000302', '001216', '000539', '000591', '000822', '001168', '001094', '000246', '000692', '000929', '000645', '000197', '000604', '000306', '000701', '000785', '000937', '000133', '000403', '000922', '001081', '000070', '000696', '000429', '000094', '000196', '001171', '001200', '000451', '000712', '000994', '000052', '001170', '000312', '000675', '001183', '001071', '001116', '000817', '000615', '000533', '000846', '001132', '001026', '000980', '000924', '000073', '000898', '000986', '000006', '000063', '000466', '000470', '000198', '001164', '001227', '000528', '000425', '000968', '001175', '000435', '000609', '000830', '000758', '000248', '000697', '001073', '001144', '000523', '000109', '000744', '000123', '000943', '000055', '000062', '000933', '000467', '000289', '000867', '000495', '000545', '000337', '000729', '000786', '000869', '001035', '000475', '000679', '000733', '000382', '001196', '000512', '000549', '001199', '001033', '001194', '000749', '000736', '000480', '001090', '000526', '000972', '000008', '000235', '000321', '000732', '000713', '000894', '000594', '000121', '001079', '000322', '000771', '000769', '000170', '000693', '000919']
----------------------------------------------------------------------------------------------------

➡️ transaction_date:
Unique values count: 1806
Null count: 0 (0.00%)
Sample values: ['2024-05-21', '2023-12-25', '2023-11-29', '2023-12-05', '2024-11-13', '2021-10-29', '2022-03-23', '2025-05-26', '2021-07-12', '2021-11-11', '2023-02-24', '2022-08-03', '2022-06-12', '2025-04-12', '2024-03-05', '2020-10-28', '2023-11-27', '2022-03-30', '2020-09-28', '2024-07-05', '2021-03-27', '2023-10-28', '2024-08-26', '2021-10-08', '2024-10-05', '2020-11-24', '2020-12-21', '2021-04-16', '2023-08-03', '2024-06-14', '2022-06-24', '2025-04-15', '2021-11-23', '2022-09-24', '2024-09-12', '2021-04-10', '2024-12-03', '2023-11-11', '2025-01-04', '2020-10-16', '2023-06-14', '2022-04-10', '2022-05-08', '2025-01-21', '2022-04-17', '2024-06-13', '2023-07-28', '2023-03-24', '2022-03-15', '2024-04-07', '2020-09-18', '2023-10-16', '2025-05-22', '2025-05-21', '2024-02-20', '2024-08-05', '2022-01-21', '2022-04-09', '2021-05-11', '2024-04-28', '2023-08-17', '2023-09-19', '2021-03-12', '2024-11-04', '2024-10-15', '2022-04-22', '2025-05-06', '2021-01-21', '2024-04-18', '2024-09-15', '2024-09-11', '2021-03-23', '2021-10-31', '2023-11-22', '2024-04-11', '2024-09-26', '2022-03-21', '2023-03-14', '2024-10-06', '2021-06-02', '2024-06-05', '2023-02-23', '2025-02-06', '2023-09-13', '2023-02-03', '2024-06-03', '2020-07-14', '2020-07-21', '2020-09-27', '2022-09-17', '2021-12-20', '2024-10-09', '2021-10-16', '2022-04-30', '2025-01-20', '2021-11-17', '2024-09-25', '2025-06-14', '2021-04-03', '2024-01-10', '2024-09-16', '2022-11-25', '2025-04-20', '2021-07-08', '2023-11-03', '2024-04-08', '2022-02-13', '2023-12-18', '2022-01-16', '2022-05-03', '2023-07-12', '2020-11-30', '2022-04-21', '2024-07-18', '2021-06-19', '2021-03-21', '2021-05-30', '2021-02-23', '2020-09-16', '2024-03-17']
----------------------------------------------------------------------------------------------------

➡️ transaction_type:
Unique values count: 6
Null count: 0 (0.00%)
Sample values: ['Exchange', 'Sale in future state of completion', 'Expropriation', 'Sale', 'Auction', 'Sale of unbuilt land']
----------------------------------------------------------------------------------------------------

➡️ property_value:
Unique values count: 466667
Null count: 194390 (0.97%)
Sample values: ['1117.8', '34389.6', '187076.0', '1047.5', '48931.26', '1509220.0', '15760.0', '221962.0', '131094.27', '102997.29', '4925425.5', '203942.0', '103230.0', '41863.0', '198331.0', '1328490.0', '309790.0', '156546.0', '4198.2', '68534.4', '120230.0', '271522.22', '2088700.0', '209710.0', '725630.0', '75708.19', '598.25', '548438.0', '2720400.0', '782051.0', '9310.0', '126970.0', '4754.5', '4110.6', '252340.0', '7839000.0', '229095.0', '614955.2', '2159.3', '642785.0', '6897.3', '1267.2', '29982.69', '68116.0', '1814500.0', '3199314.2', '473554.6', '20062.04', '56107.0', '4925619.5', '21004.0', '876611.2', '364166.66', '12735.2', '4318.5', '208556.0', '198761.0', '359571.0', '181.17', '93524.83', '2608.5', '4190.7', '884607.6', '31756.98', '159963.0', '31876.51', '328758.4', '437449.0', '461329.0', '110362.0', '415425.0', '125240.0', '187017.0', '2802.5', '355010.0', '5346226.0', '677083.0', '18755430.0', '5812.24', '1244600.0', '8747.2', '75952.0', '1098540.0', '1105930.0', '37006.2', '172362.0', '156733.0', '516375.5', '800711.0', '98818.5', '322275.0', '537259.25', '91998.0', '6230.4', '801250.0', '26193.36', '196098.0', '37191.49', '893520.0', '856100.0', '89888.0', '468846.0', '5917422.0', '12196.0', '958000.0', '27016.0', '387855.0', '333215.0', '158239.0', '390841.0', '40163.0', '99325.0', '1308760.0', '314039.0', '408090.0', '483250.0', '16332.75', '546846.0', '1820.5', '34435.0']
----------------------------------------------------------------------------------------------------

➡️ street_number:
Unique values count: 9126
Null count: 7474511 (37.18%)
Sample values: ['4599', '177', '2335', '3739', '5951', '7407', '7332', '2018', '7160', '723', '8931', '6983', '6303', '4105', '9647', '3836', '650', '6167', '3052', '9981', '858', '2575', '5805', '7406', '3740', '7094', '4277', '5221', '6552', '7197', '4099', '6212', '2472', '1266', '6382', '4698', '1991', '5334', '5799', '5139', '9432', '253', '5662', '2478', '5020', '2808', '4716', '5668', '9042', '4674', '2498', '9610', '2035', '9918', '7716', '3314', '2128', '7598', '8667', '121', '5078', '7334', '3092', '5108', '889', '2624', '3936', '3901', '2059', '1859', '9499', '7911', '7503', '6432', '854', '9707', '7636', '484', '4880', '2118', '7684', '6787', '9769', '6093', '743', '1371', '3582', '4801', '1466', '5478', '7445', '8342', '6964', '7476', '6065', '3989', '2780', '6203', '7597', '4937', '6114', '3486', '7228', '6024', '364', '2751', '2921', '8155', '6000', '2374', '2193', '7013', '3332', '7732', '6518', '4547', '4940', '5540', '852', '6604']
----------------------------------------------------------------------------------------------------

➡️ btq_code:
Unique values count: 36
Null count: 19197741 (95.50%)
Sample values: ['2', 'X', 'T', 'O', 'V', 'Z', '6', 'I', '4', 'B', '8', 'A', '5', 'M', 'S', '3', 'F', 'W', 'Y', 'K', 'Q', 'C', 'N', '0', '7', 'H', 'G', 'R', 'U', '1', 'L', 'P', '9', 'D', 'J', 'E']
----------------------------------------------------------------------------------------------------

➡️ street_type:
Unique values count: 152
Null count: 7942059 (39.51%)
Sample values: ['CAN', 'VCHE', 'EMBR', 'VGE', 'PLCI', 'PARC', 'DIG', 'CC', 'VEN', 'PLAG', 'AV', 'RAC', 'PONT', 'PKG', 'CTR', 'CD', 'RES', 'CRX', 'GAL', 'CHT', 'HAB', 'CALL', 'RPT', 'ROC', 'QUAI', 'JARD', 'CHS', 'PL', 'CORO', 'PASS', 'PTTE', 'PAE', 'COTE', 'BRE', 'COR', 'PLAN', 'CAMI', 'CHL', 'ESP', 'RLE', 'ESC', 'VIA', 'VC', 'ZONE', 'ZAD', 'RUE', 'VAL', 'ILOT', 'ALL', 'BD', 'REM', 'SEN', 'PTE', 'TRA', 'QUA', 'JTE', 'TRAB', 'PLT', 'AGL', 'NTE', 'COL', 'MRN', 'ZUP', 'BRTL', 'SQ', 'TSSE', 'CPG', 'CAMP', 'VOUT', 'ART', 'CHE', 'PCH', 'BRG', 'FG', 'MAR', 'PTR', 'ZI', 'PLA', 'RTE', 'VLA', 'PIST', 'VOIE', 'ESPA', 'VOIR', 'ECL', 'D', 'ENC', 'PRV', 'PLE', 'DOM', 'RTD', 'BSN', 'CLOS', 'PAS', 'MAIL', 'LOT', 'TOUR', 'HLG', 'PROM', 'PRT', 'DSC', 'MAIS', 'CF', 'LEVE', 'COIN', 'COUR', 'IMP', 'CASR', 'RIVE', 'CHEM', 'ZAC', 'CAR', 'DRA', 'VALL', 'CLR', 'DEVI', 'BER', 'PORT', 'VOY', 'CRS']
----------------------------------------------------------------------------------------------------

➡️ street_id:
Unique values count: 20064
Null count: 150482 (0.75%)
Sample values: ['T383', '3739', 'W419', '5951', '7332', '0003', '7160', '7839', 'B071', 'J491', '7406', 'E916', 'D568', 'I015', '4277', '6552', 'H503', '4099', 'E365', '6212', 'D782', '5799', '9432', '5662', 'W308', 'F823', '5668', 'I324', '4674', 'G562', 'E915', '0124', 'J206', 'B770', 'X015', 'I931', 'R534', '0396', '8435', '2624', '5108', '1859', 'I904', '4707', '2118', 'G544', 'E802', '6787', '8475', 'E414', '6093', 'F270', '0973', 'D531', 'H796', '8151', '1466', '5478', 'I261', 'E125', 'C695', 'D009', '0824', '7228', '2751', 'B545', '2921', 'E420', 'H415', 'W364', 'P736', 'C461', '4547', '4940', 'F646', 'I952', '5540', '8602', 'E468', '4728', '1906', 'E829', '2155', '6962', 'W583', '6692', '1590', '8103', 'A095', '6353', 'D892', '7048', '0837', 'Q748', '0766', '6785', 'F941', '5857', '0854', '4250', 'F378', 'D068', 'B677', 'D105', '7780', 'H235', 'F819', 'Q443', '1842', 'G050', 'J209', 'B458', 'I138', 'E541', 'D154', '0657', '4518', 'B009', 'D417', 'F897']
----------------------------------------------------------------------------------------------------

➡️ street_name:
Unique values count: 1132199
Null count: 151263 (0.75%)
Sample values: ['MOULIN DE LA BOULE', 'LA RUSTE', 'LE PRE BECQUET', 'BORNILLON', 'LA BASSE VERRIERE', 'LE VERGER DE LA BROUSTIERE', 'SUR LE CHEMIN DE COURCHAMP', 'LES PERCIERES', 'LES BAS LORIOT', 'DU 22 JUIN 1944', 'BRETEUIL CENTRE', 'LA BARBAQUENNE', 'LES CHAUMES DE RISSAT', 'MONTBETON', 'LA CROIX PAQUET', 'LA VILLE PIQUANT', 'DU CHEMIN SONDROT', 'COUVIGNAC BAS', 'BOUZANNE', 'LES CRX', 'MEJOU KERVILLY', 'LE ROUTY ET LES LONGS 5 MU', 'LE ZIEN', 'DU BOIS DURET', 'DE ST LAURENT LA VERNEDE', 'BOURG DE RAVEL', 'SONGY SUD', 'TORTEILLAN', 'FAREDONDE', 'MEZ LORS', 'QUELERN EN BAS', 'PUCHULU', 'DE LA MEGRETTERIE', 'VALLOUREC SAINT SAULVE', 'URRETTE', 'LES LONGEURS', 'COLLAMBUTO', 'DE LA VILLE BALLET', 'EN POMMETIN', 'LA POIVRIE', 'DU CHANCELIER ADENAUER', 'DES PIVOLLES', 'DES FLAQUES', 'LE CLOS DE LA SAUVELLIERE', 'L HOTEL BONNET', 'LA CHARMAUDE', 'LABROUSSE SUD', 'LA POITEVIN', 'LAUBRAY', 'LE PONT DES QUESNOTS', 'SERRE BOUTONET', 'BAMBARA', 'LE DRESSAN', 'ENTRE RUE ORLEANS RLE ROQU', 'CLOS DERRIERE', 'LES GUILBAUDIERES', 'LES PATEZES', 'FUMADES', 'DU TUE VAQUES', 'CHER SOUBRANT', 'BASSE SAINT JEAN (MONTFAU', 'MARCEL BERNE', 'DE GOULMY', 'DU VIEUX JOUVENCON', 'DOC FRANCOIS', 'BOLLELONGUE', 'HT BILAIN', 'KERIHUEL EST', 'LA SAUVASSE', 'DE PECHPEYROU', 'SCUDERI', 'MALASSOUMADE', 'EN MALSARD A ROUSSOT', 'PROFESSEUR A P    BOUIN', 'DU SERRE DE CASSAGNES', 'EN JEAN', 'LA VAQUERESSE', 'LA CHAIGNEAU', 'CHEZ FILLAUX', 'BARRIERE DU TRONE', 'MARIUS CHALENDARD', 'LANNEC CRECH BIDAN', 'LA COMBRENEE', 'DES ETOQUIS', 'DES 7 FONTAINES', 'LE MOULIN DE FROMENTIERE', 'DE LA PETITE BOURGADE', 'LAIN HALLEC', 'TREVENANOU PARC AN AVALOU', 'LE PRE GOSSET', 'DES BRIGANTINS (PLAGE)', 'PRE A BOEUFS', "LES VIGNES D'ANTAN", 'FERME DU MAUNY', 'DU CASTEL OGI', 'CHARLES GODEFROY', 'LE CHAMP FAUDET', 'DE SENARENS', 'MOULIN DES VIGNES', 'CALA DI GIGLIO', 'LA COTE-SUD', 'DU HAUT GAUVIN', 'A LA CARRIERE DU CHEMIN D', 'VERS LE MOULIN DE ROUCOURT', 'AU FACHE', 'LA PINEDE DE GRIMAUD', 'HAUTE DES BAINS (VC93)', 'DE CANTO COUCUT', 'DU BARET', 'DESSOUS DE LA BUTTE', 'LES PRESIDANNES', 'CANTON DES NOUES', 'PLAGNES DE DESSUS', 'JACQUES-LOUIS BLOT', 'GERARD BAUMEL', 'GEORGES HELMINGER', 'PIECES DES METAIRIES', 'MAURICE RAIMBAUD', 'DE LIMITETAKO BIDEA', 'DE PACALON']
----------------------------------------------------------------------------------------------------

➡️ postal_code:
Unique values count: 5871
Null count: 151600 (0.75%)
Sample values: ['26330', '48260', '63200', '36400', '83260', '7160', '81360', '97130', '33860', '69150', '12780', '79160', '13360', '33141', '28410', '85660', '72530', '35500', '38490', '27860', '14114', '44200', '89113', '79290', '25260', '46330', '27750', '45420', '82410', '25160', '46190', '24470', '59125', '61440', '73530', '50000', '44115', '12580', '79800', '49112', '47500', '83870', '74120', '85560', '50620', '84300', '44410', '95110', '63260', '91160', '20137', '43210', '59239', '27910', '45400', '97330', '31360', '50480', '38450', '59530', '8190', '36290', '38370', '35320', '81440', '29510', '33170', '97450', '12360', '72350', '6000', '56410', '17570', '39230', '25210', '54810', '60940', '42840', '66820', '73520', '24360', '59231', '13810', '42600', '59117', '95280', '47000', '54580', '13100', '1590', '44260', '49220', '45260', '78570', '51240', '14670', '9000', '71670', '36330', '59181', '95700', '77860', '97280', '66500', '56350', '60540', '60100', '42155', '42920', '77630', '14112', '62800', '4250', '36250', '7100', '50810', '92400', '66680', '61140', '30820']
----------------------------------------------------------------------------------------------------

➡️ com_name:
Unique values count: 31569
Null count: 0 (0.00%)
Sample values: ['CESTAYROLS', 'COURTHIEZY', 'FRAISANS', 'MOUTIERS-EN-PUISAYE', 'ROCHE SUR YON (LA)', 'VILLIERS-EN-BIERE', 'MONTBETON', 'JOUAIGNES', 'LA DIGNE D AMONT', 'PAULIN', 'MONTREUIL-SOUS-PEROUSE', 'VAUX VILLAINE', 'BELVEDERE-CAMPOMORO', 'ROCHE-GUYON (LA)', 'LOUBAJAC', 'BEUZEVILLE-LA-GRENIER', 'BEUGNY', 'MATIGNICOURT-GONCOURT', 'LOUBIGNE', 'SAINT-MICHEL-SUR-ORGE', 'SALAZAC', 'SAVIGNY-POIL-FOL', 'CERNOY-EN-BERRY', 'MOUSTIERS-SAINTE-MARIE', 'SAINT YVI', 'SAINT GEORGES DE LA COUEE', 'SAINT-LEGER', 'LAREE', 'CARENCY', 'FERICY', 'CASTELNAU LE LEZ', 'RAILLENCOURT-SAINTE-OLLE', 'SAINT-CYR-SUR-MER', 'UROST', 'PLEUGRIFFET', 'CHILLY-LE-VIGNOBLE', 'NOVALE', 'OZOUER-LE-VOULGIS', 'BEAUFORT-EN-ANJOU', 'LE TOUVET', 'VALLE D OREZZA', 'DAGONVILLE', 'BELFONDS', 'MONCE EN SAOSNOIS', 'LOUVIERS', 'SAINT-ROMAIN-DE-POPEY', 'CAUVICOURT', 'ISSAMOULENC', 'CALONNE RICOUART', 'DEOLS', 'THEHILLAC', 'LES ISLETTES', 'ST-GERMAIN-LES-PAROISSES', 'AUREILLE', 'DANJOUTIN', 'LEMBRAS', 'MALVES-EN-MINERVOIS', 'PUY-DU-LAC', 'SAINT-BROING', 'GERARDMER', 'MARCIGNY', 'PELLEAUTIER', 'TERREBASSE', 'FONTAINE BONNELEAU', 'SAINT-LOUET-SUR-SEULLES', 'LA CHATRE-LANGLIN', 'MONTIGNY-LENCOUP', 'CROISILLES', 'SAINT VINCENT', 'SAINT-ILLIERS-LA-VILLE', 'BALAGUERES', 'TREMAOUEZAN', 'PALAVAS-LES-FLOTS', 'TREZILIDE', 'MAROLLETTE', 'LAVELINE-DU-HOUX', 'ST-PAUL-D OUEIL', 'BEZANCOURT', 'COURCELLES-SOUS-CHATENOIS', 'LE BOURG', 'VAROUVILLE', 'FORGES-LES-EAUX', 'BAUDRECOURT', 'POUILLY-SUR-VINGEANNE', 'PRUILLE LE CHETIF', 'LABOULE', 'OCCEY', 'CRENANS', 'MUNCQ-NIEURLET', 'GIBEAUMEIX', 'CHALEZEULE', 'LARNAUD', 'LE CHARMEL', 'DERNANCOURT', 'COUTEVROULT', 'THEUVILLE', 'LANDAVRAN', 'LE CHATEAU D OLERON', 'BROUSSE-LE-CHATEAU', 'RIGNY LE FERRON', 'SAINT-ESTEBEN', 'COSMES', 'GIVENCHY-LES-LA-BASSEE', 'BELBEZE-EN-COMMINGES', 'CUPERLY', 'GARDE-COLOMBE', 'LA CLUSAZ', 'RACHECOURT-SUZEMONT', 'CHAUSSY', 'EGLISOLLES', 'BURGARONNE', 'TREFFLEAN', 'SAINT-GERMAIN-LA-MONTAGNE', 'PROUVILLE', 'LANEUVELLE', 'JOU-SOUS-MONJOU', 'VANDONCOURT', 'SOULAIRES', 'LE BROUILH-MONBERT', 'COULOUVRAY-BOISBENATRE']
----------------------------------------------------------------------------------------------------

➡️ dep_code:
Unique values count: 97
Null count: 0 (0.00%)
Sample values: ['973', '21', '77', '35', '974', '04', '83', '26', '2A', '62', '58', '16', '19', '72', '13', '73', '69', '51', '14', '05', '94', '92', '88', '54', '89', '64', '39', '45', '43', '22', '10', '08', '76', '65', '06', '972', '82', '95', '12', '48', '28', '55', '74', '42', '59', '30', '70', '80', '17', '11', '50', '87', '32', '27', '56', '52', '44', '66', '47', '24', '971', '41', '40', '03', '86', '63', '46', '37', '31', '29', '18', '93', '91', '60', '36', '84', '07', '38', '23', '61', '85', '49', '33', '53', '81', '25', '15', '2B', '02', '79', '78', '34', '71', '01', '75', '90', '09']
----------------------------------------------------------------------------------------------------

➡️ com_code:
Unique values count: 908
Null count: 0 (0.00%)
Sample values: ['759', '800', '316', '575', '535', '177', '818', '757', '796', '791', '322', '206', '185', '710', '450', '282', '270', '694', '723', '306', '553', '564', '35', '749', '716', '673', '446', '539', '405', '464', '258', '650', '302', '223', '848', '269', '354', '524', '194', '346', '19', '858', '615', '286', '148', '154', '394', '13', '466', '159', '483', '815', '871', '104', '323', '660', '835', '846', '444', '67', '200', '402', '704', '88', '215', '439', '742', '488', '388', '739', '505', '137', '903', '117', '379', '397', '336', '642', '64', '39', '480', '758', '469', '393', '212', '638', '281', '253', '163', '762', '868', '409', '482', '157', '509', '698', '620', '679', '612', '726', '332', '108', '162', '632', '616', '164', '461', '339', '705', '817', '594', '619', '121', '199', '123', '304', '431', '492', '883', '527']
----------------------------------------------------------------------------------------------------

➡️ section_prefix:
Unique values count: 759
Null count: 19147817 (95.25%)
Sample values: ['316', '575', '177', '818', '757', '322', '206', '185', '450', '282', '270', '694', '564', '553', '306', '35', '749', '539', '405', '258', '223', '302', '269', '354', '524', '194', '346', '19', '858', '615', '286', '148', '154', '13', '466', '159', '483', '815', '871', '104', '323', '835', '846', '444', '67', '200', '704', '402', '88', '505', '439', '488', '903', '388', '215', '137', '742', '117', '509', '379', '642', '64', '469', '480', '39', '638', '212', '393', '253', '281', '163', '868', '409', '482', '157', '620', '332', '108', '162', '632', '616', '164', '339', '594', '817', '121', '199', '123', '431', '304', '492', '883', '889', '729', '527', '861', '140', '139', '641', '595', '429', '901', '362', '28', '228', '606', '381', '854', '351', '150', '235', '400', '390', '378', '484', '365', '237', '284', '50', '160']
----------------------------------------------------------------------------------------------------

➡️ section:
Unique values count: 588
Null count: 725 (0.00%)
Sample values: ['CK', 'DA', 'EP', 'LX', 'KH', 'X', 'GB', 'DH', 'B', 'ED', 'A', 'WN', 'PI', 'SM', 'GE', 'OA', 'GN', 'VV', 'FK', 'TR', 'LB', 'TL', 'RV', 'FN', 'FY', 'MY', 'YT', 'PT', 'WC', 'VL', 'TI', 'HE', 'BY', 'JK', 'KA', 'CU', 'EB', 'PR', 'RZ', 'KS', 'MG', 'VC', 'DY', 'EN', 'TH', 'BD', 'MH', 'YV', 'OM', 'JE', 'HX', 'M', 'GS', 'GD', 'GC', 'RR', 'WS', 'EH', 'FL', 'KJ', 'C', 'ZY', 'SD', 'XR', 'G', 'IC', 'ZK', 'LN', 'LO', 'D', 'HU', 'DO', 'WD', 'MA', 'SK', 'DE', 'LL', 'OS', 'AW', 'OB', 'SL', 'EC', 'SR', 'KW', 'BI', 'WK', 'ND', 'ZD', 'YO', 'XY', 'NM', 'EE', 'XO', 'HP', 'EO', 'MN', 'H', 'ZT', 'LC', 'GI', 'YW', 'CN', 'SA', 'BV', 'DT', 'IY', 'JL', 'AS', 'PS', 'I', 'YN', 'TM', 'HK', 'KF', 'DZ', 'VW', 'HY', 'TX', 'PO', 'BC']
----------------------------------------------------------------------------------------------------

➡️ plot_number:
Unique values count: 8239
Null count: 0 (0.00%)
Sample values: ['4599', '177', '2335', '3739', '4553', '5951', '7332', '2018', '7160', '723', '6983', '4105', '6303', '8967', '3836', '650', '6167', '3052', '858', '2575', '5805', '3740', '7094', '4277', '5221', '6552', '4099', '7197', '6212', '2472', '1266', '4698', '6382', '1991', '5334', '5799', '5139', '253', '5662', '2478', '5020', '2808', '4716', '5668', '4674', '2498', '2035', '3314', '2128', '121', '5078', '7334', '3092', '889', '2624', '5108', '3936', '3901', '2059', '1859', '7503', '6432', '854', '4707', '7636', '484', '4880', '2118', '7684', '8475', '6093', '743', '1371', '3582', '4801', '1466', '5478', '7445', '8342', '6964', '7476', '6065', '3989', '8190', '2780', '6203', '7597', '4937', '6114', '3486', '7228', '6024', '364', '2751', '2921', '6000', '2374', '2193', '7013', '3332', '7732', '6518', '4547', '4940', '5540', '852', '6604', '1997', '550', '6674', '3882', '5864', '6699', '251', '1502', '3015', '1133', '4728', '1906', '1806']
----------------------------------------------------------------------------------------------------

➡️ volume_number:
Unique values count: 2068
Null count: 20057358 (99.77%)

### **CONVERT DATA TYPES**

In [8]:
from pathlib import Path
import pandas as pd

INPUT_FILE = Path("../data/processed/INVALIDS_ValeursFoncieres.csv")
OUTPUT_FILE = Path("../data/processed/TYPES_ValeursFoncieres.csv")

CHUNK_SIZE = 50_000

# Columns by target type
string_cols = [
    "transaction_id",
    "transaction_type",
    "street_number",
    "btq_code",
    "street_type",
    "street_id",
    "street_name",
    "postal_code",
    "com_name",
    "dep_code",
    "com_code",
    "section_prefix",
    "section",
    "plot_number",
    "volume_number",
    "property_type_code",
    "property_type",
    "land_nature",
    "land_nature_special",
    "surface_type",
    "lot_1",
    "lot_2",
    "lot_3",
    "lot_4",
    "lot_5"
]

date_cols = [
    "transaction_date",
]

float_cols = [
    "property_value",
    "building_real_surface",
    "land_surface",
    "lot_1_surface",
    "lot_2_surface",
    "lot_3_surface",
    "lot_4_surface",
    "lot_5_surface"
]

int_cols = [
    "lots_count",
    "main_rooms_count",
]


def convert_chunk_types(chunk: pd.DataFrame) -> pd.DataFrame:
    # String / categorical columns
    for col in string_cols:
        if col in chunk.columns:
            chunk[col] = chunk[col].astype("string").str.strip()

    # Date columns
    for col in date_cols:
        if col in chunk.columns:
            chunk[col] = pd.to_datetime(
                chunk[col],
                errors="coerce"
            )

    # Float columns
    for col in float_cols:
        if col in chunk.columns:
            if chunk[col].dtype == "object" or str(chunk[col].dtype) == "string":
                chunk[col] = (
                    chunk[col]
                    .astype("string")
                    .str.replace(",", ".", regex=False)
                    .str.strip()
                )
            chunk[col] = pd.to_numeric(chunk[col], errors="coerce").astype("float64")

    # Integer columns
    for col in int_cols:
        if col in chunk.columns:
            if chunk[col].dtype == "object" or str(chunk[col].dtype) == "string":
                chunk[col] = chunk[col].astype("string").str.strip()
            chunk[col] = pd.to_numeric(chunk[col], errors="coerce").astype("Int64")

    return chunk


def convert_file_types_chunked(
    input_file: Path,
    output_file: Path,
    chunk_size: int = 50_000
) -> None:
    output_file.parent.mkdir(parents=True, exist_ok=True)

    first_write = True
    total_rows = 0

    for chunk_idx, chunk in enumerate(
        pd.read_csv(input_file, chunksize=chunk_size, dtype=str),
        start=1
    ):
        chunk = convert_chunk_types(chunk)

        chunk.to_csv(
            output_file,
            mode="w" if first_write else "a",
            index=False,
            header=first_write,
            encoding="utf-8"
        )

        first_write = False
        total_rows += len(chunk)

        print(f"Chunk {chunk_idx} written -> {len(chunk):,} rows | total: {total_rows:,}")

    print("\nDone! Converted column data types")
    print(f"Saved file: {output_file}")
    print(f"Total rows written: {total_rows:,}")


convert_file_types_chunked(INPUT_FILE, OUTPUT_FILE, CHUNK_SIZE)

Chunk 1 written -> 50,000 rows | total: 50,000
Chunk 2 written -> 50,000 rows | total: 100,000
Chunk 3 written -> 50,000 rows | total: 150,000
Chunk 4 written -> 50,000 rows | total: 200,000
Chunk 5 written -> 50,000 rows | total: 250,000
Chunk 6 written -> 50,000 rows | total: 300,000
Chunk 7 written -> 50,000 rows | total: 350,000
Chunk 8 written -> 50,000 rows | total: 400,000
Chunk 9 written -> 50,000 rows | total: 450,000
Chunk 10 written -> 50,000 rows | total: 500,000
Chunk 11 written -> 50,000 rows | total: 550,000
Chunk 12 written -> 50,000 rows | total: 600,000
Chunk 13 written -> 50,000 rows | total: 650,000
Chunk 14 written -> 50,000 rows | total: 700,000
Chunk 15 written -> 50,000 rows | total: 750,000
Chunk 16 written -> 50,000 rows | total: 800,000
Chunk 17 written -> 50,000 rows | total: 850,000
Chunk 18 written -> 50,000 rows | total: 900,000
Chunk 19 written -> 50,000 rows | total: 950,000
Chunk 20 written -> 50,000 rows | total: 1,000,000
Chunk 21 written -> 50,000 rows | total: 1,050,000
Chunk 22 written -> 50,000 rows | total: 1,100,000
Chunk 23 written -> 50,000 rows | total: 1,150,000
Chunk 24 written -> 50,000 rows | total: 1,200,000
Chunk 25 written -> 50,000 rows | total: 1,250,000
Chunk 26 written -> 50,000 rows | total: 1,300,000
Chunk 27 written -> 50,000 rows | total: 1,350,000
Chunk 28 written -> 50,000 rows | total: 1,400,000
Chunk 29 written -> 50,000 rows | total: 1,450,000
Chunk 30 written -> 50,000 rows | total: 1,500,000
Chunk 31 written -> 50,000 rows | total: 1,550,000
Chunk 32 written -> 50,000 rows | total: 1,600,000
Chunk 33 written -> 50,000 rows | total: 1,650,000
Chunk 34 written -> 50,000 rows | total: 1,700,000
Chunk 35 written -> 50,000 rows | total: 1,750,000
Chunk 36 written -> 50,000 rows | total: 1,800,000
Chunk 37 written -> 50,000 rows | total: 1,850,000
Chunk 38 written -> 50,000 rows | total: 1,900,000
Chunk 39 written -> 50,000 rows | total: 1,950,000
Chunk 40 written -> 50,000 rows | total: 2,000,000
Chunk 41 written -> 50,000 rows | total: 2,050,000
Chunk 42 written -> 50,000 rows | total: 2,100,000
Chunk 43 written -> 50,000 rows | total: 2,150,000
Chunk 44 written -> 50,000 rows | total: 2,200,000
Chunk 45 written -> 50,000 rows | total: 2,250,000
Chunk 46 written -> 50,000 rows | total: 2,300,000
Chunk 47 written -> 50,000 rows | total: 2,350,000
Chunk 48 written -> 50,000 rows | total: 2,400,000
Chunk 49 written -> 50,000 rows | total: 2,450,000
Chunk 50 written -> 50,000 rows | total: 2,500,000
Chunk 51 written -> 50,000 rows | total: 2,550,000
Chunk 52 written -> 50,000 rows | total: 2,600,000
Chunk 53 written -> 50,000 rows | total: 2,650,000
Chunk 54 written -> 50,000 rows | total: 2,700,000
Chunk 55 written -> 50,000 rows | total: 2,750,000
Chunk 56 written -> 50,000 rows | total: 2,800,000
Chunk 57 written -> 50,000 rows | total: 2,850,000
Chunk 58 written -> 50,000 rows | total: 2,900,000
Chunk 59 written -> 50,000 rows | total: 2,950,000
Chunk 60 written -> 50,000 rows | total: 3,000,000
Chunk 61 written -> 50,000 rows | total: 3,050,000
Chunk 62 written -> 50,000 rows | total: 3,100,000
Chunk 63 written -> 50,000 rows | total: 3,150,000
Chunk 64 written -> 50,000 rows | total: 3,200,000
Chunk 65 written -> 50,000 rows | total: 3,250,000
Chunk 66 written -> 50,000 rows | total: 3,300,000
Chunk 67 written -> 50,000 rows | total: 3,350,000
Chunk 68 written -> 50,000 rows | total: 3,400,000
Chunk 69 written -> 50,000 rows | total: 3,450,000
Chunk 70 written -> 50,000 rows | total: 3,500,000
Chunk 71 written -> 50,000 rows | total: 3,550,000
Chunk 72 written -> 50,000 rows | total: 3,600,000
Chunk 73 written -> 50,000 rows | total: 3,650,000
Chunk 74 written -> 50,000 rows | total: 3,700,000
Chunk 75 written -> 50,000 rows | total: 3,750,000
Chunk 76 written -> 50,000 rows | total: 3,800,000
Chunk 77 written -> 50,000 rows | total: 3,850,000
Chunk 78 written -> 50,000 rows | total: 3,900,000
Chunk 79 written -> 50,000 rows | total: 3,950,000
Chunk 80 written -> 50,000 rows | total: 4,000,000
Chunk 81 written -> 50,000 rows | total: 4,050,000
Chunk 82 written -> 50,000 rows | total: 4,100,000
Chunk 83 written -> 50,000 rows | total: 4,150,000
Chunk 84 written -> 50,000 rows | total: 4,200,000
Chunk 85 written -> 50,000 rows | total: 4,250,000
Chunk 86 written -> 50,000 rows | total: 4,300,000
Chunk 87 written -> 50,000 rows | total: 4,350,000
Chunk 88 written -> 50,000 rows | total: 4,400,000
Chunk 89 written -> 50,000 rows | total: 4,450,000
Chunk 90 written -> 50,000 rows | total: 4,500,000
Chunk 91 written -> 50,000 rows | total: 4,550,000
Chunk 92 written -> 50,000 rows | total: 4,600,000
Chunk 93 written -> 50,000 rows | total: 4,650,000
Chunk 94 written -> 50,000 rows | total: 4,700,000
Chunk 95 written -> 50,000 rows | total: 4,750,000
Chunk 96 written -> 50,000 rows | total: 4,800,000
Chunk 97 written -> 50,000 rows | total: 4,850,000
Chunk 98 written -> 50,000 rows | total: 4,900,000
Chunk 99 written -> 50,000 rows | total: 4,950,000
Chunk 100 written -> 50,000 rows | total: 5,000,000
Chunk 101 written -> 50,000 rows | total: 5,050,000
Chunk 102 written -> 50,000 rows | total: 5,100,000
Chunk 103 written -> 50,000 rows | total: 5,150,000
Chunk 104 written -> 50,000 rows | total: 5,200,000
Chunk 105 written -> 50,000 rows | total: 5,250,000
Chunk 106 written -> 50,000 rows | total: 5,300,000
Chunk 107 written -> 50,000 rows | total: 5,350,000
Chunk 108 written -> 50,000 rows | total: 5,400,000
Chunk 109 written -> 50,000 rows | total: 5,450,000
Chunk 110 written -> 50,000 rows | total: 5,500,000
Chunk 111 written -> 50,000 rows | total: 5,550,000
Chunk 112 written -> 50,000 rows | total: 5,600,000
Chunk 113 written -> 50,000 rows | total: 5,650,000
Chunk 114 written -> 50,000 rows | total: 5,700,000
Chunk 115 written -> 50,000 rows | total: 5,750,000
Chunk 116 written -> 50,000 rows | total: 5,800,000
Chunk 117 written -> 50,000 rows | total: 5,850,000
Chunk 118 written -> 50,000 rows | total: 5,900,000
Chunk 119 written -> 50,000 rows | total: 5,950,000
Chunk 120 written -> 50,000 rows | total: 6,000,000
Chunk 121 written -> 50,000 rows | total: 6,050,000
Chunk 122 written -> 50,000 rows | total: 6,100,000
Chunk 123 written -> 50,000 rows | total: 6,150,000
Chunk 124 written -> 50,000 rows | total: 6,200,000
Chunk 125 written -> 50,000 rows | total: 6,250,000
Chunk 126 written -> 50,000 rows | total: 6,300,000
Chunk 127 written -> 50,000 rows | total: 6,350,000
Chunk 128 written -> 50,000 rows | total: 6,400,000
Chunk 129 written -> 50,000 rows | total: 6,450,000
Chunk 130 written -> 50,000 rows | total: 6,500,000
Chunk 131 written -> 50,000 rows | total: 6,550,000
Chunk 132 written -> 50,000 rows | total: 6,600,000
Chunk 133 written -> 50,000 rows | total: 6,650,000
Chunk 134 written -> 50,000 rows | total: 6,700,000
Chunk 135 written -> 50,000 rows | total: 6,750,000
Chunk 136 written -> 50,000 rows | total: 6,800,000
Chunk 137 written -> 50,000 rows | total: 6,850,000
Chunk 138 written -> 50,000 rows | total: 6,900,000
Chunk 139 written -> 50,000 rows | total: 6,950,000
Chunk 140 written -> 50,000 rows | total: 7,000,000
Chunk 141 written -> 50,000 rows | total: 7,050,000
Chunk 142 written -> 50,000 rows | total: 7,100,000
Chunk 143 written -> 50,000 rows | total: 7,150,000
Chunk 144 written -> 50,000 rows | total: 7,200,000
Chunk 145 written -> 50,000 rows | total: 7,250,000
Chunk 146 written -> 50,000 rows | total: 7,300,000
Chunk 147 written -> 50,000 rows | total: 7,350,000
Chunk 148 written -> 50,000 rows | total: 7,400,000
Chunk 149 written -> 50,000 rows | total: 7,450,000
Chunk 150 written -> 50,000 rows | total: 7,500,000
Chunk 151 written -> 50,000 rows | total: 7,550,000
Chunk 152 written -> 50,000 rows | total: 7,600,000
Chunk 153 written -> 50,000 rows | total: 7,650,000
Chunk 154 written -> 50,000 rows | total: 7,700,000
Chunk 155 written -> 50,000 rows | total: 7,750,000
Chunk 156 written -> 50,000 rows | total: 7,800,000
Chunk 157 written -> 50,000 rows | total: 7,850,000
Chunk 158 written -> 50,000 rows | total: 7,900,000
Chunk 159 written -> 50,000 rows | total: 7,950,000
Chunk 160 written -> 50,000 rows | total: 8,000,000
Chunk 161 written -> 50,000 rows | total: 8,050,000
Chunk 162 written -> 50,000 rows | total: 8,100,000
Chunk 163 written -> 50,000 rows | total: 8,150,000
Chunk 164 written -> 50,000 rows | total: 8,200,000
Chunk 165 written -> 50,000 rows | total: 8,250,000
Chunk 166 written -> 50,000 rows | total: 8,300,000
Chunk 167 written -> 50,000 rows | total: 8,350,000
Chunk 168 written -> 50,000 rows | total: 8,400,000
Chunk 169 written -> 50,000 rows | total: 8,450,000
Chunk 170 written -> 50,000 rows | total: 8,500,000
Chunk 171 written -> 50,000 rows | total: 8,550,000
Chunk 172 written -> 50,000 rows | total: 8,600,000
Chunk 173 written -> 50,000 rows | total: 8,650,000
Chunk 174 written -> 50,000 rows | total: 8,700,000
Chunk 175 written -> 50,000 rows | total: 8,750,000
Chunk 176 written -> 50,000 rows | total: 8,800,000
Chunk 177 written -> 50,000 rows | total: 8,850,000
Chunk 178 written -> 50,000 rows | total: 8,900,000
Chunk 179 written -> 50,000 rows | total: 8,950,000
Chunk 180 written -> 50,000 rows | total: 9,000,000
Chunk 181 written -> 50,000 rows | total: 9,050,000
Chunk 182 written -> 50,000 rows | total: 9,100,000
Chunk 183 written -> 50,000 rows | total: 9,150,000
Chunk 184 written -> 50,000 rows | total: 9,200,000
Chunk 185 written -> 50,000 rows | total: 9,250,000
Chunk 186 written -> 50,000 rows | total: 9,300,000
Chunk 187 written -> 50,000 rows | total: 9,350,000
Chunk 188 written -> 50,000 rows | total: 9,400,000
Chunk 189 written -> 50,000 rows | total: 9,450,000
Chunk 190 written -> 50,000 rows | total: 9,500,000
Chunk 191 written -> 50,000 rows | total: 9,550,000
Chunk 192 written -> 50,000 rows | total: 9,600,000
Chunk 193 written -> 50,000 rows | total: 9,650,000
Chunk 194 written -> 50,000 rows | total: 9,700,000
Chunk 195 written -> 50,000 rows | total: 9,750,000
Chunk 196 written -> 50,000 rows | total: 9,800,000
Chunk 197 written -> 50,000 rows | total: 9,850,000
Chunk 198 written -> 50,000 rows | total: 9,900,000
Chunk 199 written -> 50,000 rows | total: 9,950,000
Chunk 200 written -> 50,000 rows | total: 10,000,000
Chunk 201 written -> 50,000 rows | total: 10,050,000
Chunk 202 written -> 50,000 rows | total: 10,100,000
Chunk 203 written -> 50,000 rows | total: 10,150,000
Chunk 204 written -> 50,000 rows | total: 10,200,000
Chunk 205 written -> 50,000 rows | total: 10,250,000
Chunk 206 written -> 50,000 rows | total: 10,300,000
Chunk 207 written -> 50,000 rows | total: 10,350,000
Chunk 208 written -> 50,000 rows | total: 10,400,000
Chunk 209 written -> 50,000 rows | total: 10,450,000
Chunk 210 written -> 50,000 rows | total: 10,500,000
Chunk 211 written -> 50,000 rows | total: 10,550,000
Chunk 212 written -> 50,000 rows | total: 10,600,000
Chunk 213 written -> 50,000 rows | total: 10,650,000
Chunk 214 written -> 50,000 rows | total: 10,700,000
Chunk 215 written -> 50,000 rows | total: 10,750,000
Chunk 216 written -> 50,000 rows | total: 10,800,000
Chunk 217 written -> 50,000 rows | total: 10,850,000
Chunk 218 written -> 50,000 rows | total: 10,900,000
Chunk 219 written -> 50,000 rows | total: 10,950,000
Chunk 220 written -> 50,000 rows | total: 11,000,000
Chunk 221 written -> 50,000 rows | total: 11,050,000
Chunk 222 written -> 50,000 rows | total: 11,100,000
Chunk 223 written -> 50,000 rows | total: 11,150,000
Chunk 224 written -> 50,000 rows | total: 11,200,000
Chunk 225 written -> 50,000 rows | total: 11,250,000
Chunk 226 written -> 50,000 rows | total: 11,300,000
Chunk 227 written -> 50,000 rows | total: 11,350,000
Chunk 228 written -> 50,000 rows | total: 11,400,000
Chunk 229 written -> 50,000 rows | total: 11,450,000
Chunk 230 written -> 50,000 rows | total: 11,500,000
Chunk 231 written -> 50,000 rows | total: 11,550,000
Chunk 232 written -> 50,000 rows | total: 11,600,000
Chunk 233 written -> 50,000 rows | total: 11,650,000
Chunk 234 written -> 50,000 rows | total: 11,700,000
Chunk 235 written -> 50,000 rows | total: 11,750,000
Chunk 236 written -> 50,000 rows | total: 11,800,000
Chunk 237 written -> 50,000 rows | total: 11,850,000
Chunk 238 written -> 50,000 rows | total: 11,900,000
Chunk 239 written -> 50,000 rows | total: 11,950,000
Chunk 240 written -> 50,000 rows | total: 12,000,000
Chunk 241 written -> 50,000 rows | total: 12,050,000
Chunk 242 written -> 50,000 rows | total: 12,100,000
Chunk 243 written -> 50,000 rows | total: 12,150,000
Chunk 244 written -> 50,000 rows | total: 12,200,000
Chunk 245 written -> 50,000 rows | total: 12,250,000
Chunk 246 written -> 50,000 rows | total: 12,300,000
Chunk 247 written -> 50,000 rows | total: 12,350,000
Chunk 248 written -> 50,000 rows | total: 12,400,000
Chunk 249 written -> 50,000 rows | total: 12,450,000
Chunk 250 written -> 50,000 rows | total: 12,500,000
Chunk 251 written -> 50,000 rows | total: 12,550,000
Chunk 252 written -> 50,000 rows | total: 12,600,000
Chunk 253 written -> 50,000 rows | total: 12,650,000
Chunk 254 written -> 50,000 rows | total: 12,700,000
Chunk 255 written -> 50,000 rows | total: 12,750,000
Chunk 256 written -> 50,000 rows | total: 12,800,000
Chunk 257 written -> 50,000 rows | total: 12,850,000
Chunk 258 written -> 50,000 rows | total: 12,900,000
Chunk 259 written -> 50,000 rows | total: 12,950,000
Chunk 260 written -> 50,000 rows | total: 13,000,000
Chunk 261 written -> 50,000 rows | total: 13,050,000
Chunk 262 written -> 50,000 rows | total: 13,100,000
Chunk 263 written -> 50,000 rows | total: 13,150,000
Chunk 264 written -> 50,000 rows | total: 13,200,000
Chunk 265 written -> 50,000 rows | total: 13,250,000
Chunk 266 written -> 50,000 rows | total: 13,300,000
Chunk 267 written -> 50,000 rows | total: 13,350,000
Chunk 268 written -> 50,000 rows | total: 13,400,000
Chunk 269 written -> 50,000 rows | total: 13,450,000
Chunk 270 written -> 50,000 rows | total: 13,500,000
Chunk 271 written -> 50,000 rows | total: 13,550,000
Chunk 272 written -> 50,000 rows | total: 13,600,000
Chunk 273 written -> 50,000 rows | total: 13,650,000
Chunk 274 written -> 50,000 rows | total: 13,700,000
Chunk 275 written -> 50,000 rows | total: 13,750,000
Chunk 276 written -> 50,000 rows | total: 13,800,000
Chunk 277 written -> 50,000 rows | total: 13,850,000
Chunk 278 written -> 50,000 rows | total: 13,900,000
Chunk 279 written -> 50,000 rows | total: 13,950,000
Chunk 280 written -> 50,000 rows | total: 14,000,000
Chunk 281 written -> 50,000 rows | total: 14,050,000
Chunk 282 written -> 50,000 rows | total: 14,100,000
Chunk 283 written -> 50,000 rows | total: 14,150,000
Chunk 284 written -> 50,000 rows | total: 14,200,000
Chunk 285 written -> 50,000 rows | total: 14,250,000
Chunk 286 written -> 50,000 rows | total: 14,300,000
Chunk 287 written -> 50,000 rows | total: 14,350,000
Chunk 288 written -> 50,000 rows | total: 14,400,000
Chunk 289 written -> 50,000 rows | total: 14,450,000
Chunk 290 written -> 50,000 rows | total: 14,500,000
Chunk 291 written -> 50,000 rows | total: 14,550,000
Chunk 292 written -> 50,000 rows | total: 14,600,000
Chunk 293 written -> 50,000 rows | total: 14,650,000
Chunk 294 written -> 50,000 rows | total: 14,700,000
Chunk 295 written -> 50,000 rows | total: 14,750,000
Chunk 296 written -> 50,000 rows | total: 14,800,000
Chunk 297 written -> 50,000 rows | total: 14,850,000
Chunk 298 written -> 50,000 rows | total: 14,900,000
Chunk 299 written -> 50,000 rows | total: 14,950,000
Chunk 300 written -> 50,000 rows | total: 15,000,000
Chunk 301 written -> 50,000 rows | total: 15,050,000
Chunk 302 written -> 50,000 rows | total: 15,100,000
Chunk 303 written -> 50,000 rows | total: 15,150,000
Chunk 304 written -> 50,000 rows | total: 15,200,000
Chunk 305 written -> 50,000 rows | total: 15,250,000
Chunk 306 written -> 50,000 rows | total: 15,300,000
Chunk 307 written -> 50,000 rows | total: 15,350,000
Chunk 308 written -> 50,000 rows | total: 15,400,000
Chunk 309 written -> 50,000 rows | total: 15,450,000
Chunk 310 written -> 50,000 rows | total: 15,500,000
Chunk 311 written -> 50,000 rows | total: 15,550,000
Chunk 312 written -> 50,000 rows | total: 15,600,000
Chunk 313 written -> 50,000 rows | total: 15,650,000
Chunk 314 written -> 50,000 rows | total: 15,700,000
Chunk 315 written -> 50,000 rows | total: 15,750,000
Chunk 316 written -> 50,000 rows | total: 15,800,000
Chunk 317 written -> 50,000 rows | total: 15,850,000
Chunk 318 written -> 50,000 rows | total: 15,900,000
Chunk 319 written -> 50,000 rows | total: 15,950,000
Chunk 320 written -> 50,000 rows | total: 16,000,000
Chunk 321 written -> 50,000 rows | total: 16,050,000
Chunk 322 written -> 50,000 rows | total: 16,100,000
Chunk 323 written -> 50,000 rows | total: 16,150,000
Chunk 324 written -> 50,000 rows | total: 16,200,000
Chunk 325 written -> 50,000 rows | total: 16,250,000
Chunk 326 written -> 50,000 rows | total: 16,300,000
Chunk 327 written -> 50,000 rows | total: 16,350,000
Chunk 328 written -> 50,000 rows | total: 16,400,000
Chunk 329 written -> 50,000 rows | total: 16,450,000
Chunk 330 written -> 50,000 rows | total: 16,500,000
Chunk 331 written -> 50,000 rows | total: 16,550,000
Chunk 332 written -> 50,000 rows | total: 16,600,000
Chunk 333 written -> 50,000 rows | total: 16,650,000
Chunk 334 written -> 50,000 rows | total: 16,700,000
Chunk 335 written -> 50,000 rows | total: 16,750,000
Chunk 336 written -> 50,000 rows | total: 16,800,000
Chunk 337 written -> 50,000 rows | total: 16,850,000
Chunk 338 written -> 50,000 rows | total: 16,900,000
Chunk 339 written -> 50,000 rows | total: 16,950,000
Chunk 340 written -> 50,000 rows | total: 17,000,000
Chunk 341 written -> 50,000 rows | total: 17,050,000
Chunk 342 written -> 50,000 rows | total: 17,100,000
Chunk 343 written -> 50,000 rows | total: 17,150,000
Chunk 344 written -> 50,000 rows | total: 17,200,000
Chunk 345 written -> 50,000 rows | total: 17,250,000
Chunk 346 written -> 50,000 rows | total: 17,300,000
Chunk 347 written -> 50,000 rows | total: 17,350,000
Chunk 348 written -> 50,000 rows | total: 17,400,000
Chunk 349 written -> 50,000 rows | total: 17,450,000
Chunk 350 written -> 50,000 rows | total: 17,500,000
Chunk 351 written -> 50,000 rows | total: 17,550,000
Chunk 352 written -> 50,000 rows | total: 17,600,000
Chunk 353 written -> 50,000 rows | total: 17,650,000
Chunk 354 written -> 50,000 rows | total: 17,700,000
Chunk 355 written -> 50,000 rows | total: 17,750,000
Chunk 356 written -> 50,000 rows | total: 17,800,000
Chunk 357 written -> 50,000 rows | total: 17,850,000
Chunk 358 written -> 50,000 rows | total: 17,900,000
Chunk 359 written -> 50,000 rows | total: 17,950,000
Chunk 360 written -> 50,000 rows | total: 18,000,000
Chunk 361 written -> 50,000 rows | total: 18,050,000
Chunk 362 written -> 50,000 rows | total: 18,100,000
Chunk 363 written -> 50,000 rows | total: 18,150,000
Chunk 364 written -> 50,000 rows | total: 18,200,000
Chunk 365 written -> 50,000 rows | total: 18,250,000
Chunk 366 written -> 50,000 rows | total: 18,300,000
Chunk 367 written -> 50,000 rows | total: 18,350,000
Chunk 368 written -> 50,000 rows | total: 18,400,000
Chunk 369 written -> 50,000 rows | total: 18,450,000
Chunk 370 written -> 50,000 rows | total: 18,500,000
Chunk 371 written -> 50,000 rows | total: 18,550,000
Chunk 372 written -> 50,000 rows | total: 18,600,000
Chunk 373 written -> 50,000 rows | total: 18,650,000
Chunk 374 written -> 50,000 rows | total: 18,700,000
Chunk 375 written -> 50,000 rows | total: 18,750,000
Chunk 376 written -> 50,000 rows | total: 18,800,000
Chunk 377 written -> 50,000 rows | total: 18,850,000
Chunk 378 written -> 50,000 rows | total: 18,900,000
Chunk 379 written -> 50,000 rows | total: 18,950,000
Chunk 380 written -> 50,000 rows | total: 19,000,000
Chunk 381 written -> 50,000 rows | total: 19,050,000
Chunk 382 written -> 50,000 rows | total: 19,100,000
Chunk 383 written -> 50,000 rows | total: 19,150,000

| Original Column Name           | Standardized            | Description                                       | Data Type | Type                 |
| ------------------------------ | ----------------------- | ------------------------------------------------- | --------- | -------------------- |
| **No disposition**             | `transaction_id`        | Unique identifier of the transaction              | string    | Categorical          |
| **Date mutation**              | `transaction_date`      | Date when the property was sold                   | string    | Temporal             |
| **Nature mutation**            | `transaction_type`      | Nature of transaction (sale, exchange, etc.)      | string    | Categorical          |
| **Valeur fonciere**            | `property_value`        | Transaction price in euros                        | float     | Numeric (**TARGET**) |
| **No voie**                    | `street_number`         | Street number of the property                     | string    | Categorical          |
| **B/T/Q**                      | `btq_code`              | Building / Type / Quarter code                    | string    | Categorical          |
| **Type de voie**               | `street_type`           | Type of street (Rue, Avenue, etc.)                | string    | Categorical          |
| **Code voie**                  | `street_id`             | Street identifier code                            | string    | Categorical          |
| **Voie**                       | `street_name`           | Full street name                                  | string    | Categorical          |
| **Code postal**                | `postal_code`           | Postal code                                       | string    | Categorical          |
| **Commune**                    | `com_name`              | Commune name                                      | string    | Categorical          |
| **Code departement**           | `dep_code`              | Department code                                   | string    | Categorical          |
| **Code commune**               | `com_code`              | Commune code                                      | string    | Categorical          |
| **Prefixe de section**         | `section_prefix`        | Section prefix used in cadastral identification   | string    | Categorical          |
| **Section**                    | `section`               | Cadastral section identifier                      | string    | Categorical          |
| **No plan**                    | `plot_number`           | Parcel / plot number                              | string    | Categorical          |
| **No Volume**                  | `volume_number`         | Volume number for special cadastral cases         | string    | Categorical          |
| **1er lot**                    | `lot_1`                 | Identifier of the first lot                       | string    | Categorical          |
| **Surface Carrez du 1er lot**  | `lot_1_carrez_surface`  | Carrez surface of the first lot in square meters  | float     | Numeric              |
| **2eme lot**                   | `lot_2`                 | Identifier of the second lot                      | string    | Categorical          |
| **Surface Carrez du 2eme lot** | `lot_2_carrez_surface`  | Carrez surface of the second lot in square meters | float     | Numeric              |
| **3eme lot**                   | `lot_3`                 | Identifier of the third lot                       | string    | Categorical          |
| **Surface Carrez du 3eme lot** | `lot_3_carrez_surface`  | Carrez surface of the third lot in square meters  | float     | Numeric              |
| **4eme lot**                   | `lot_4`                 | Identifier of the fourth lot                      | string    | Categorical          |
| **Surface Carrez du 4eme lot** | `lot_4_carrez_surface`  | Carrez surface of the fourth lot in square meters | float     | Numeric              |
| **5eme lot**                   | `lot_5`                 | Identifier of the fifth lot                       | string    | Categorical          |
| **Surface Carrez du 5eme lot** | `lot_5_carrez_surface`  | Carrez surface of the fifth lot in square meters  | float     | Numeric              |
| **Nombre de lots**             | `lots_count`            | Number of lots in the transaction                 | integer   | Numeric              |
| **Code type local**            | `property_type_code`    | Code for property type                            | string    | Categorical          |
| **Type local**                 | `property_type`         | Property type (Apartment, House, etc.)            | string    | Categorical          |
| **Surface reelle bati**        | `building_real_surface` | Built area in square meters                       | float     | Numeric              |
| **Nombre pieces principales**  | `main_rooms_count`      | Number of main rooms                              | integer   | Numeric              |
| **Nature culture**             | `land_nature`           | General type of land usage                        | string    | Categorical          |
| **Nature culture speciale**    | `land_nature_special`   | Specific type of land usage                       | string    | Categorical          |
| **Surface terrain**            | `land_surface`          | Land area in square meters                        | float     | Numeric              |
| *(derived)*                    | `surface_type`          | Type of surface: building / land / combined       | string    | Derived Categorical  |

<hr>

## 4️⃣ NULL VALUES


<style>
h1 {
    text-align: center;
    color: black;
    font-weight: bold;
}
</style>

<style>
h2 {
    text-align: left;
    color: black;
    font-weight: bold;
}
</style>

<style>
h3 {
    text-align: left;
    color: black;
    font-weight: bold;
}
</style>

<style>
h4 {
    text-align: left;
    color: black;
    font-weight: bold;
}
</style>
<hr>

### **INFO - NULLS COUNT (BEFORE)**

In [ ]:
import pandas as pd

FILE = "../data/processed/TYPES_ValeursFoncieres.csv"
CHUNK_SIZE = 50_000

dtype_map = {
    "transaction_id": "string",
    "transaction_date": "string",
    "transaction_type": "string",
    "street_number": "string",
    "btq_code": "string",
    "street_type": "string",
    "street_id": "string",
    "street_name": "string",
    "postal_code": "string",
    "com_name": "string",
    "dep_code": "string",
    "com_code": "string",
    "section_prefix": "string",
    "section": "string",
    "plot_number": "string",
    "volume_number": "string",
    "property_type_code": "string",
    "property_type": "string",
    "land_nature": "string",
    "land_nature_special": "string",
    "surface_type": "string",
    "lot_1": "string",
    "lot_2": "string",
    "lot_3": "string",
    "lot_4": "string",
    "lot_5": "string",

    # float columns
    "property_value": "float64",
    "building_real_surface": "float64",
    "land_surface": "float64",
    "lot_1_surface": "float64",
    "lot_2_surface": "float64",
    "lot_3_surface": "float64",
    "lot_4_surface": "float64",
    "lot_5_surface": "float64",
    
    # int columns
    "lots_count": "Int64",
    "main_rooms_count": "Int64"
}


total_rows = 0
columns = None
non_null_counts = None
dtypes = None

for chunk in pd.read_csv(
    FILE,
    chunksize=CHUNK_SIZE,
    dtype=dtype_map,
    #parse_dates=["transaction_date"],
    #dayfirst=True,        # IMPORTANT for the date format (dd/mm/yyyy)
    low_memory=False      # removes DtypeWarning
):
    if columns is None:
        columns = chunk.columns.tolist()
        non_null_counts = {col: 0 for col in columns}
        dtypes = chunk.dtypes.astype(str).to_dict()

    total_rows += len(chunk)

    for col in columns:
        non_null_counts[col] += chunk[col].notna().sum()

info_df = pd.DataFrame({
    "column": columns,
    "non_null_count": [non_null_counts[col] for col in columns],
    "null_count": [total_rows - non_null_counts[col] for col in columns],
    "dtype": [dtypes[col] for col in columns]
})

print(f"RangeIndex: {total_rows} entries, 0 to {total_rows - 1}")
print(f"Data columns (total {len(columns)} columns):")
display(info_df)
print(f"dtypes: {info_df['dtype'].value_counts().to_dict()}")
print("memory usage: not computed (chunked mode)")

### **DEAL with NULLS HERE**

In [9]:
from pathlib import Path
import pandas as pd

INPUT_FILE = Path("../data/processed/TYPES_ValeursFoncieres.csv")
OUTPUT_FILE = Path("../data/processed/NULLS_ValeursFoncieres.csv")

CHUNK_SIZE = 50_000

dtype_map = {
    "transaction_id": "string",
    "transaction_date": "string",
    "transaction_type": "string",
    "property_value": "float64",
    "street_number": "string",
    "btq_code": "string",
    "street_type": "string",
    "street_id": "string",
    "street_name": "string",
    "postal_code": "string",
    "com_name": "string",
    "dep_code": "string",
    "com_code": "string",
    "section_prefix": "string",
    "section": "string",
    "plot_number": "string",
    "volume_number": "string",
    "lot_1": "string",
    "lot_1_surface": "float64",
    "lot_2": "string",
    "lot_2_surface": "float64",
    "lot_3": "string",
    "lot_3_surface": "float64",
    "lot_4": "string",
    "lot_4_surface": "float64",
    "lot_5": "string",
    "lot_5_surface": "float64",
    "lots_count": "Int64",
    "property_type_code": "string",
    "property_type": "string",
    "building_real_surface": "float64",
    "main_rooms_count": "Int64",
    "land_nature": "string",
    "land_nature_special": "string",
    "land_surface": "float64",
    "surface_type": "string",
}

categorical_cols = [
    "transaction_id",
    "transaction_date",
    "transaction_type",
    "street_number",
    "btq_code",
    "street_type",
    "street_id",
    "street_name",
    "postal_code",
    "com_name",
    "dep_code",
    "com_code",
    "section_prefix",
    "section",
    "plot_number",
    "volume_number",
    "lot_1",
    "lot_2",
    "lot_3",
    "lot_4",
    "lot_5",
    "property_type_code",
    "property_type",
    "land_nature",
    "land_nature_special",
    "surface_type",
]

numeric_float_cols = [
    "property_value",
    "lot_1_surface",
    "lot_2_surface",
    "lot_3_surface",
    "lot_4_surface",
    "lot_5_surface",
    "building_real_surface",
    "land_surface",
]

numeric_int_cols = [
    "lots_count",
    "main_rooms_count",
]


def handle_nulls(chunk: pd.DataFrame) -> pd.DataFrame:
    # target cannot be imputed safely
    chunk = chunk.dropna(subset=["property_value"]).copy()

    # numeric: smarter fills first
    chunk.loc[:, "building_real_surface"] = chunk["building_real_surface"].fillna(0.0)

    for col in ["lot_1_surface", "lot_2_surface", "lot_3_surface", "lot_4_surface", "lot_5_surface"]:
        if col in chunk.columns:
            chunk.loc[:, col] = chunk[col].fillna(0.0)

    # main_rooms_count:
    # if missing and building_real_surface exists =>0, set main_rooms_count = 0
    mask_rooms = (
        chunk["main_rooms_count"].isna() &
        (chunk["building_real_surface"] >= 0)
    )
    chunk.loc[mask_rooms, "main_rooms_count"] = 0
    


    # land_surface:
    # if missing and building_real_surface exists, set to 0
    mask_land = (
        chunk["land_surface"].isna() &
        (chunk["building_real_surface"] > 0)
    )
    chunk.loc[mask_land, "land_surface"] = 0.0

    # fallback numeric fills
    for col in numeric_float_cols:
        if col in chunk.columns and col != "property_value":
            chunk.loc[:, col] = chunk[col].fillna(0.0)

    for col in numeric_int_cols:
        if col in chunk.columns:
            chunk.loc[:, col] = chunk[col].fillna(0)

    # categorical fills
    for col in categorical_cols:
        if col in chunk.columns:
            chunk.loc[:, col] = chunk[col].fillna("Unknown")

    # restore numeric dtypes
    for col in numeric_float_cols:
        if col in chunk.columns:
            chunk.loc[:, col] = pd.to_numeric(chunk[col], errors="coerce")

    for col in numeric_int_cols:
        if col in chunk.columns:
            chunk.loc[:, col] = pd.to_numeric(chunk[col], errors="coerce").astype("Int64")

    return chunk


def process_nulls_chunked(input_file: Path, output_file: Path, chunk_size: int = 50_000) -> None:
    output_file.parent.mkdir(parents=True, exist_ok=True)

    first_write = True
    total_rows_read = 0
    total_rows_written = 0
    total_rows_dropped = 0

    for i, chunk in enumerate(
        pd.read_csv(
            input_file,
            chunksize=chunk_size,
            dtype=dtype_map,
            low_memory=False
        ),
        start=1
    ):
        rows_before = len(chunk)
        total_rows_read += rows_before

        chunk = handle_nulls(chunk)

        rows_after = len(chunk)
        total_rows_written += rows_after
        total_rows_dropped += (rows_before - rows_after)

        chunk.to_csv(
            output_file,
            mode="w" if first_write else "a",
            index=False,
            header=first_write,
            encoding="utf-8"
        )

        first_write = False

        print(
            f"Chunk {i} processed -> "
            f"read: {rows_before:,} | kept: {rows_after:,} | "
            f"dropped: {rows_before - rows_after:,} | total kept: {total_rows_written:,}"
        )

    print("\nDone! Null values handled")
    print(f"Saved file: {output_file}")
    print(f"Total rows read: {total_rows_read:,}")
    print(f"Total rows dropped: {total_rows_dropped:,}")
    print(f"Total rows written: {total_rows_written:,}")


process_nulls_chunked(INPUT_FILE, OUTPUT_FILE, CHUNK_SIZE)

Chunk 1 processed -> read: 50,000 | kept: 49,207 | dropped: 793 | total kept: 49,207
Chunk 2 processed -> read: 50,000 | kept: 49,885 | dropped: 115 | total kept: 99,092
Chunk 3 processed -> read: 50,000 | kept: 49,799 | dropped: 201 | total kept: 148,891
Chunk 4 processed -> read: 50,000 | kept: 49,703 | dropped: 297 | total kept: 198,594
Chunk 5 processed -> read: 50,000 | kept: 49,717 | dropped: 283 | total kept: 248,311
Chunk 6 processed -> read: 50,000 | kept: 49,526 | dropped: 474 | total kept: 297,837
Chunk 7 processed -> read: 50,000 | kept: 49,920 | dropped: 80 | total kept: 347,757
Chunk 8 processed -> read: 50,000 | kept: 49,543 | dropped: 457 | total kept: 397,300
Chunk 9 processed -> read: 50,000 | kept: 49,605 | dropped: 395 | total kept: 446,905
Chunk 10 processed -> read: 50,000 | kept: 49,751 | dropped: 249 | total kept: 496,656
Chunk 11 processed -> read: 50,000 | kept: 49,252 | dropped: 748 | total kept: 545,908
Chunk 12 processed -> read: 50,000 | kept: 49,895 | dropped: 105 | total kept: 595,803
Chunk 13 processed -> read: 50,000 | kept: 49,790 | dropped: 210 | total kept: 645,593
Chunk 14 processed -> read: 50,000 | kept: 49,771 | dropped: 229 | total kept: 695,364
Chunk 15 processed -> read: 50,000 | kept: 49,759 | dropped: 241 | total kept: 745,123
Chunk 16 processed -> read: 50,000 | kept: 49,774 | dropped: 226 | total kept: 794,897
Chunk 17 processed -> read: 50,000 | kept: 49,777 | dropped: 223 | total kept: 844,674
Chunk 18 processed -> read: 50,000 | kept: 49,364 | dropped: 636 | total kept: 894,038
Chunk 19 processed -> read: 50,000 | kept: 49,612 | dropped: 388 | total kept: 943,650
Chunk 20 processed -> read: 50,000 | kept: 49,795 | dropped: 205 | total kept: 993,445
Chunk 21 processed -> read: 50,000 | kept: 48,745 | dropped: 1,255 | total kept: 1,042,190
Chunk 22 processed -> read: 50,000 | kept: 48,986 | dropped: 1,014 | total kept: 1,091,176
Chunk 23 processed -> read: 50,000 | kept: 49,817 | dropped: 183 | total kept: 1,140,993
Chunk 24 processed -> read: 50,000 | kept: 49,636 | dropped: 364 | total kept: 1,190,629
Chunk 25 processed -> read: 50,000 | kept: 46,253 | dropped: 3,747 | total kept: 1,236,882
Chunk 26 processed -> read: 50,000 | kept: 43,514 | dropped: 6,486 | total kept: 1,280,396
Chunk 27 processed -> read: 50,000 | kept: 49,540 | dropped: 460 | total kept: 1,329,936
Chunk 28 processed -> read: 50,000 | kept: 49,838 | dropped: 162 | total kept: 1,379,774
Chunk 29 processed -> read: 50,000 | kept: 49,433 | dropped: 567 | total kept: 1,429,207
Chunk 30 processed -> read: 50,000 | kept: 49,555 | dropped: 445 | total kept: 1,478,762
Chunk 31 processed -> read: 50,000 | kept: 49,817 | dropped: 183 | total kept: 1,528,579
Chunk 32 processed -> read: 50,000 | kept: 49,797 | dropped: 203 | total kept: 1,578,376
Chunk 33 processed -> read: 50,000 | kept: 49,820 | dropped: 180 | total kept: 1,628,196
Chunk 34 processed -> read: 50,000 | kept: 49,591 | dropped: 409 | total kept: 1,677,787
Chunk 35 processed -> read: 50,000 | kept: 49,945 | dropped: 55 | total kept: 1,727,732
Chunk 36 processed -> read: 50,000 | kept: 49,654 | dropped: 346 | total kept: 1,777,386
Chunk 37 processed -> read: 50,000 | kept: 49,462 | dropped: 538 | total kept: 1,826,848
Chunk 38 processed -> read: 50,000 | kept: 49,658 | dropped: 342 | total kept: 1,876,506
Chunk 39 processed -> read: 50,000 | kept: 40,574 | dropped: 9,426 | total kept: 1,917,080
Chunk 40 processed -> read: 50,000 | kept: 49,316 | dropped: 684 | total kept: 1,966,396
Chunk 41 processed -> read: 50,000 | kept: 49,597 | dropped: 403 | total kept: 2,015,993
Chunk 42 processed -> read: 50,000 | kept: 49,714 | dropped: 286 | total kept: 2,065,707
Chunk 43 processed -> read: 50,000 | kept: 49,431 | dropped: 569 | total kept: 2,115,138
Chunk 44 processed -> read: 50,000 | kept: 49,758 | dropped: 242 | total kept: 2,164,896
Chunk 45 processed -> read: 50,000 | kept: 49,891 | dropped: 109 | total kept: 2,214,787
Chunk 46 processed -> read: 50,000 | kept: 49,779 | dropped: 221 | total kept: 2,264,566
Chunk 47 processed -> read: 50,000 | kept: 49,861 | dropped: 139 | total kept: 2,314,427
Chunk 48 processed -> read: 50,000 | kept: 49,846 | dropped: 154 | total kept: 2,364,273
Chunk 49 processed -> read: 50,000 | kept: 49,868 | dropped: 132 | total kept: 2,414,141
Chunk 50 processed -> read: 50,000 | kept: 49,676 | dropped: 324 | total kept: 2,463,817
Chunk 51 processed -> read: 50,000 | kept: 49,914 | dropped: 86 | total kept: 2,513,731
Chunk 52 processed -> read: 50,000 | kept: 49,839 | dropped: 161 | total kept: 2,563,570
Chunk 53 processed -> read: 50,000 | kept: 49,734 | dropped: 266 | total kept: 2,613,304
Chunk 54 processed -> read: 50,000 | kept: 49,634 | dropped: 366 | total kept: 2,662,938
Chunk 55 processed -> read: 50,000 | kept: 49,853 | dropped: 147 | total kept: 2,712,791
Chunk 56 processed -> read: 50,000 | kept: 49,679 | dropped: 321 | total kept: 2,762,470
Chunk 57 processed -> read: 50,000 | kept: 49,789 | dropped: 211 | total kept: 2,812,259
Chunk 58 processed -> read: 50,000 | kept: 49,932 | dropped: 68 | total kept: 2,862,191
Chunk 59 processed -> read: 50,000 | kept: 49,457 | dropped: 543 | total kept: 2,911,648
Chunk 60 processed -> read: 50,000 | kept: 49,580 | dropped: 420 | total kept: 2,961,228
Chunk 61 processed -> read: 50,000 | kept: 49,909 | dropped: 91 | total kept: 3,011,137
Chunk 62 processed -> read: 50,000 | kept: 36,526 | dropped: 13,474 | total kept: 3,047,663
Chunk 63 processed -> read: 50,000 | kept: 49,872 | dropped: 128 | total kept: 3,097,535
Chunk 64 processed -> read: 50,000 | kept: 49,891 | dropped: 109 | total kept: 3,147,426
Chunk 65 processed -> read: 50,000 | kept: 49,728 | dropped: 272 | total kept: 3,197,154
Chunk 66 processed -> read: 50,000 | kept: 49,386 | dropped: 614 | total kept: 3,246,540
Chunk 67 processed -> read: 50,000 | kept: 49,293 | dropped: 707 | total kept: 3,295,833
Chunk 68 processed -> read: 50,000 | kept: 49,900 | dropped: 100 | total kept: 3,345,733
Chunk 69 processed -> read: 50,000 | kept: 49,921 | dropped: 79 | total kept: 3,395,654
Chunk 70 processed -> read: 50,000 | kept: 49,859 | dropped: 141 | total kept: 3,445,513
Chunk 71 processed -> read: 50,000 | kept: 49,824 | dropped: 176 | total kept: 3,495,337
Chunk 72 processed -> read: 50,000 | kept: 49,650 | dropped: 350 | total kept: 3,544,987
Chunk 73 processed -> read: 50,000 | kept: 49,766 | dropped: 234 | total kept: 3,594,753
Chunk 74 processed -> read: 50,000 | kept: 49,802 | dropped: 198 | total kept: 3,644,555
Chunk 75 processed -> read: 50,000 | kept: 49,922 | dropped: 78 | total kept: 3,694,477
Chunk 76 processed -> read: 50,000 | kept: 49,663 | dropped: 337 | total kept: 3,744,140
Chunk 77 processed -> read: 50,000 | kept: 49,825 | dropped: 175 | total kept: 3,793,965
Chunk 78 processed -> read: 50,000 | kept: 49,832 | dropped: 168 | total kept: 3,843,797
Chunk 79 processed -> read: 50,000 | kept: 49,905 | dropped: 95 | total kept: 3,893,702
Chunk 80 processed -> read: 50,000 | kept: 49,862 | dropped: 138 | total kept: 3,943,564
Chunk 81 processed -> read: 50,000 | kept: 49,691 | dropped: 309 | total kept: 3,993,255
Chunk 82 processed -> read: 50,000 | kept: 49,610 | dropped: 390 | total kept: 4,042,865
Chunk 83 processed -> read: 50,000 | kept: 49,931 | dropped: 69 | total kept: 4,092,796
Chunk 84 processed -> read: 50,000 | kept: 49,761 | dropped: 239 | total kept: 4,142,557
Chunk 85 processed -> read: 50,000 | kept: 49,498 | dropped: 502 | total kept: 4,192,055
Chunk 86 processed -> read: 50,000 | kept: 49,607 | dropped: 393 | total kept: 4,241,662
Chunk 87 processed -> read: 50,000 | kept: 49,737 | dropped: 263 | total kept: 4,291,399
Chunk 88 processed -> read: 50,000 | kept: 49,727 | dropped: 273 | total kept: 4,341,126
Chunk 89 processed -> read: 50,000 | kept: 49,308 | dropped: 692 | total kept: 4,390,434
Chunk 90 processed -> read: 50,000 | kept: 49,139 | dropped: 861 | total kept: 4,439,573
Chunk 91 processed -> read: 50,000 | kept: 49,647 | dropped: 353 | total kept: 4,489,220
Chunk 92 processed -> read: 50,000 | kept: 48,887 | dropped: 1,113 | total kept: 4,538,107
Chunk 93 processed -> read: 50,000 | kept: 49,588 | dropped: 412 | total kept: 4,587,695
Chunk 94 processed -> read: 50,000 | kept: 49,699 | dropped: 301 | total kept: 4,637,394
Chunk 95 processed -> read: 50,000 | kept: 49,811 | dropped: 189 | total kept: 4,687,205
Chunk 96 processed -> read: 50,000 | kept: 49,747 | dropped: 253 | total kept: 4,736,952
Chunk 97 processed -> read: 50,000 | kept: 49,688 | dropped: 312 | total kept: 4,786,640
Chunk 98 processed -> read: 50,000 | kept: 49,846 | dropped: 154 | total kept: 4,836,486
Chunk 99 processed -> read: 50,000 | kept: 49,542 | dropped: 458 | total kept: 4,886,028
Chunk 100 processed -> read: 50,000 | kept: 49,721 | dropped: 279 | total kept: 4,935,749
Chunk 101 processed -> read: 50,000 | kept: 49,478 | dropped: 522 | total kept: 4,985,227
Chunk 102 processed -> read: 50,000 | kept: 49,528 | dropped: 472 | total kept: 5,034,755
Chunk 103 processed -> read: 50,000 | kept: 49,739 | dropped: 261 | total kept: 5,084,494
Chunk 104 processed -> read: 50,000 | kept: 49,761 | dropped: 239 | total kept: 5,134,255
Chunk 105 processed -> read: 50,000 | kept: 49,903 | dropped: 97 | total kept: 5,184,158
Chunk 106 processed -> read: 50,000 | kept: 49,918 | dropped: 82 | total kept: 5,234,076
Chunk 107 processed -> read: 50,000 | kept: 49,844 | dropped: 156 | total kept: 5,283,920
Chunk 108 processed -> read: 50,000 | kept: 49,446 | dropped: 554 | total kept: 5,333,366
Chunk 109 processed -> read: 50,000 | kept: 49,359 | dropped: 641 | total kept: 5,382,725
Chunk 110 processed -> read: 50,000 | kept: 48,791 | dropped: 1,209 | total kept: 5,431,516
Chunk 111 processed -> read: 50,000 | kept: 49,839 | dropped: 161 | total kept: 5,481,355
Chunk 112 processed -> read: 50,000 | kept: 49,378 | dropped: 622 | total kept: 5,530,733
Chunk 113 processed -> read: 50,000 | kept: 49,545 | dropped: 455 | total kept: 5,580,278
Chunk 114 processed -> read: 50,000 | kept: 49,434 | dropped: 566 | total kept: 5,629,712
Chunk 115 processed -> read: 50,000 | kept: 49,890 | dropped: 110 | total kept: 5,679,602
Chunk 116 processed -> read: 50,000 | kept: 49,719 | dropped: 281 | total kept: 5,729,321
Chunk 117 processed -> read: 50,000 | kept: 49,739 | dropped: 261 | total kept: 5,779,060
Chunk 118 processed -> read: 50,000 | kept: 49,804 | dropped: 196 | total kept: 5,828,864
Chunk 119 processed -> read: 50,000 | kept: 49,912 | dropped: 88 | total kept: 5,878,776
Chunk 120 processed -> read: 50,000 | kept: 49,898 | dropped: 102 | total kept: 5,928,674
Chunk 121 processed -> read: 50,000 | kept: 49,955 | dropped: 45 | total kept: 5,978,629
Chunk 122 processed -> read: 50,000 | kept: 49,735 | dropped: 265 | total kept: 6,028,364
Chunk 123 processed -> read: 50,000 | kept: 49,663 | dropped: 337 | total kept: 6,078,027
Chunk 124 processed -> read: 50,000 | kept: 49,854 | dropped: 146 | total kept: 6,127,881
Chunk 125 processed -> read: 50,000 | kept: 49,392 | dropped: 608 | total kept: 6,177,273
Chunk 126 processed -> read: 50,000 | kept: 49,189 | dropped: 811 | total kept: 6,226,462
Chunk 127 processed -> read: 50,000 | kept: 49,844 | dropped: 156 | total kept: 6,276,306
Chunk 128 processed -> read: 50,000 | kept: 49,740 | dropped: 260 | total kept: 6,326,046
Chunk 129 processed -> read: 50,000 | kept: 49,811 | dropped: 189 | total kept: 6,375,857
Chunk 130 processed -> read: 50,000 | kept: 49,595 | dropped: 405 | total kept: 6,425,452
Chunk 131 processed -> read: 50,000 | kept: 49,977 | dropped: 23 | total kept: 6,475,429
Chunk 132 processed -> read: 50,000 | kept: 49,687 | dropped: 313 | total kept: 6,525,116
Chunk 133 processed -> read: 50,000 | kept: 49,426 | dropped: 574 | total kept: 6,574,542
Chunk 134 processed -> read: 50,000 | kept: 48,604 | dropped: 1,396 | total kept: 6,623,146
Chunk 135 processed -> read: 50,000 | kept: 49,838 | dropped: 162 | total kept: 6,672,984
Chunk 136 processed -> read: 50,000 | kept: 49,824 | dropped: 176 | total kept: 6,722,808
Chunk 137 processed -> read: 50,000 | kept: 49,833 | dropped: 167 | total kept: 6,772,641
Chunk 138 processed -> read: 50,000 | kept: 49,361 | dropped: 639 | total kept: 6,822,002
Chunk 139 processed -> read: 50,000 | kept: 49,942 | dropped: 58 | total kept: 6,871,944
Chunk 140 processed -> read: 50,000 | kept: 49,979 | dropped: 21 | total kept: 6,921,923
Chunk 141 processed -> read: 50,000 | kept: 49,837 | dropped: 163 | total kept: 6,971,760
Chunk 142 processed -> read: 50,000 | kept: 49,923 | dropped: 77 | total kept: 7,021,683
Chunk 143 processed -> read: 50,000 | kept: 49,791 | dropped: 209 | total kept: 7,071,474
Chunk 144 processed -> read: 50,000 | kept: 49,733 | dropped: 267 | total kept: 7,121,207
Chunk 145 processed -> read: 50,000 | kept: 49,933 | dropped: 67 | total kept: 7,171,140
Chunk 146 processed -> read: 50,000 | kept: 49,912 | dropped: 88 | total kept: 7,221,052
Chunk 147 processed -> read: 50,000 | kept: 49,680 | dropped: 320 | total kept: 7,270,732
Chunk 148 processed -> read: 50,000 | kept: 49,798 | dropped: 202 | total kept: 7,320,530
Chunk 149 processed -> read: 50,000 | kept: 49,874 | dropped: 126 | total kept: 7,370,404
Chunk 150 processed -> read: 50,000 | kept: 49,543 | dropped: 457 | total kept: 7,419,947
Chunk 151 processed -> read: 50,000 | kept: 49,822 | dropped: 178 | total kept: 7,469,769
Chunk 152 processed -> read: 50,000 | kept: 49,662 | dropped: 338 | total kept: 7,519,431
Chunk 153 processed -> read: 50,000 | kept: 49,538 | dropped: 462 | total kept: 7,568,969
Chunk 154 processed -> read: 50,000 | kept: 49,425 | dropped: 575 | total kept: 7,618,394
Chunk 155 processed -> read: 50,000 | kept: 49,590 | dropped: 410 | total kept: 7,667,984
Chunk 156 processed -> read: 50,000 | kept: 49,779 | dropped: 221 | total kept: 7,717,763
Chunk 157 processed -> read: 50,000 | kept: 49,864 | dropped: 136 | total kept: 7,767,627
Chunk 158 processed -> read: 50,000 | kept: 49,739 | dropped: 261 | total kept: 7,817,366
Chunk 159 processed -> read: 50,000 | kept: 49,745 | dropped: 255 | total kept: 7,867,111
Chunk 160 processed -> read: 50,000 | kept: 49,088 | dropped: 912 | total kept: 7,916,199
Chunk 161 processed -> read: 50,000 | kept: 49,659 | dropped: 341 | total kept: 7,965,858
Chunk 162 processed -> read: 50,000 | kept: 49,885 | dropped: 115 | total kept: 8,015,743
Chunk 163 processed -> read: 50,000 | kept: 49,735 | dropped: 265 | total kept: 8,065,478
Chunk 164 processed -> read: 50,000 | kept: 49,763 | dropped: 237 | total kept: 8,115,241
Chunk 165 processed -> read: 50,000 | kept: 49,749 | dropped: 251 | total kept: 8,164,990
Chunk 166 processed -> read: 50,000 | kept: 49,841 | dropped: 159 | total kept: 8,214,831
Chunk 167 processed -> read: 50,000 | kept: 49,956 | dropped: 44 | total kept: 8,264,787
Chunk 168 processed -> read: 50,000 | kept: 49,934 | dropped: 66 | total kept: 8,314,721
Chunk 169 processed -> read: 50,000 | kept: 49,553 | dropped: 447 | total kept: 8,364,274
Chunk 170 processed -> read: 50,000 | kept: 49,698 | dropped: 302 | total kept: 8,413,972
Chunk 171 processed -> read: 50,000 | kept: 49,672 | dropped: 328 | total kept: 8,463,644
Chunk 172 processed -> read: 50,000 | kept: 49,867 | dropped: 133 | total kept: 8,513,511
Chunk 173 processed -> read: 50,000 | kept: 49,470 | dropped: 530 | total kept: 8,562,981
Chunk 174 processed -> read: 50,000 | kept: 49,877 | dropped: 123 | total kept: 8,612,858
Chunk 175 processed -> read: 50,000 | kept: 47,796 | dropped: 2,204 | total kept: 8,660,654
Chunk 176 processed -> read: 50,000 | kept: 49,896 | dropped: 104 | total kept: 8,710,550
Chunk 177 processed -> read: 50,000 | kept: 49,588 | dropped: 412 | total kept: 8,760,138
Chunk 178 processed -> read: 50,000 | kept: 49,575 | dropped: 425 | total kept: 8,809,713
Chunk 179 processed -> read: 50,000 | kept: 49,819 | dropped: 181 | total kept: 8,859,532
Chunk 180 processed -> read: 50,000 | kept: 49,862 | dropped: 138 | total kept: 8,909,394
Chunk 181 processed -> read: 50,000 | kept: 48,902 | dropped: 1,098 | total kept: 8,958,296
Chunk 182 processed -> read: 50,000 | kept: 49,679 | dropped: 321 | total kept: 9,007,975
Chunk 183 processed -> read: 50,000 | kept: 48,967 | dropped: 1,033 | total kept: 9,056,942
Chunk 184 processed -> read: 50,000 | kept: 48,710 | dropped: 1,290 | total kept: 9,105,652
Chunk 185 processed -> read: 50,000 | kept: 49,307 | dropped: 693 | total kept: 9,154,959
Chunk 186 processed -> read: 50,000 | kept: 49,554 | dropped: 446 | total kept: 9,204,513
Chunk 187 processed -> read: 50,000 | kept: 49,857 | dropped: 143 | total kept: 9,254,370
Chunk 188 processed -> read: 50,000 | kept: 49,606 | dropped: 394 | total kept: 9,303,976
Chunk 189 processed -> read: 50,000 | kept: 49,823 | dropped: 177 | total kept: 9,353,799
Chunk 190 processed -> read: 50,000 | kept: 49,702 | dropped: 298 | total kept: 9,403,501
Chunk 191 processed -> read: 50,000 | kept: 49,832 | dropped: 168 | total kept: 9,453,333
Chunk 192 processed -> read: 50,000 | kept: 49,678 | dropped: 322 | total kept: 9,503,011
Chunk 193 processed -> read: 50,000 | kept: 48,837 | dropped: 1,163 | total kept: 9,551,848
Chunk 194 processed -> read: 50,000 | kept: 49,703 | dropped: 297 | total kept: 9,601,551
Chunk 195 processed -> read: 50,000 | kept: 49,718 | dropped: 282 | total kept: 9,651,269
Chunk 196 processed -> read: 50,000 | kept: 49,653 | dropped: 347 | total kept: 9,700,922
Chunk 197 processed -> read: 50,000 | kept: 49,846 | dropped: 154 | total kept: 9,750,768
Chunk 198 processed -> read: 50,000 | kept: 49,852 | dropped: 148 | total kept: 9,800,620
Chunk 199 processed -> read: 50,000 | kept: 49,901 | dropped: 99 | total kept: 9,850,521
Chunk 200 processed -> read: 50,000 | kept: 49,927 | dropped: 73 | total kept: 9,900,448
Chunk 201 processed -> read: 50,000 | kept: 49,716 | dropped: 284 | total kept: 9,950,164
Chunk 202 processed -> read: 50,000 | kept: 49,790 | dropped: 210 | total kept: 9,999,954
Chunk 203 processed -> read: 50,000 | kept: 48,711 | dropped: 1,289 | total kept: 10,048,665
Chunk 204 processed -> read: 50,000 | kept: 49,854 | dropped: 146 | total kept: 10,098,519
Chunk 205 processed -> read: 50,000 | kept: 49,757 | dropped: 243 | total kept: 10,148,276
Chunk 206 processed -> read: 50,000 | kept: 49,536 | dropped: 464 | total kept: 10,197,812
Chunk 207 processed -> read: 50,000 | kept: 49,839 | dropped: 161 | total kept: 10,247,651
Chunk 208 processed -> read: 50,000 | kept: 49,857 | dropped: 143 | total kept: 10,297,508
Chunk 209 processed -> read: 50,000 | kept: 49,841 | dropped: 159 | total kept: 10,347,349
Chunk 210 processed -> read: 50,000 | kept: 49,188 | dropped: 812 | total kept: 10,396,537
Chunk 211 processed -> read: 50,000 | kept: 49,819 | dropped: 181 | total kept: 10,446,356
Chunk 212 processed -> read: 50,000 | kept: 49,714 | dropped: 286 | total kept: 10,496,070
Chunk 213 processed -> read: 50,000 | kept: 49,931 | dropped: 69 | total kept: 10,546,001
Chunk 214 processed -> read: 50,000 | kept: 49,958 | dropped: 42 | total kept: 10,595,959
Chunk 215 processed -> read: 50,000 | kept: 49,670 | dropped: 330 | total kept: 10,645,629
Chunk 216 processed -> read: 50,000 | kept: 49,690 | dropped: 310 | total kept: 10,695,319
Chunk 217 processed -> read: 50,000 | kept: 49,673 | dropped: 327 | total kept: 10,744,992
Chunk 218 processed -> read: 50,000 | kept: 49,740 | dropped: 260 | total kept: 10,794,732
Chunk 219 processed -> read: 50,000 | kept: 49,320 | dropped: 680 | total kept: 10,844,052
Chunk 220 processed -> read: 50,000 | kept: 49,893 | dropped: 107 | total kept: 10,893,945
Chunk 221 processed -> read: 50,000 | kept: 49,904 | dropped: 96 | total kept: 10,943,849
Chunk 222 processed -> read: 50,000 | kept: 49,910 | dropped: 90 | total kept: 10,993,759
Chunk 223 processed -> read: 50,000 | kept: 49,874 | dropped: 126 | total kept: 11,043,633

### **Old method to deal with NULLS**

In [ ]:
from pathlib import Path
import pandas as pd

INPUT_FILE = Path("../data/processed/TYPES_ValeursFoncieres.csv")
OUTPUT_FILE = Path("../data/processed/NULLS_ValeursFoncieres.csv")

CHUNK_SIZE = 50_000


def handle_nulls(chunk: pd.DataFrame) -> pd.DataFrame:
    # --------------------------------------------------------------------------------
    # Column: property_value (TARGET)
    # --------------------------------------------------------------------------------
    chunk = chunk.dropna(subset=["property_value"])

    # --------------------------------------------------------------------------------
    # Column: btq_code
    # --------------------------------------------------------------------------------
    chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")

    # --------------------------------------------------------------------------------
    # Column: street_name, street_id, street_number, street_type
    # --------------------------------------------------------------------------------
    chunk["street_name"] = chunk["street_name"].fillna("Unknown")

    chunk["street_id"] = chunk["street_id"].fillna("Unknown")

    chunk["street_number"] = chunk["street_number"].fillna("Unknown")

    chunk["street_type"] = chunk["street_type"].fillna("Unknown")

    # --------------------------------------------------------------------------------
    # Column: section, section_prefix
    # --------------------------------------------------------------------------------
    chunk["section"] = chunk["section"].fillna("Unknown")
    
    chunk["section_prefix"] = chunk["section_prefix"].fillna("Unknown")
    

    # --------------------------------------------------------------------------------
    # Column: volume_number
    # --------------------------------------------------------------------------------
    chunk["volume_number"] = chunk["volume_number"].fillna("Unknown")


    # --------------------------------------------------------------------------------
    # Column: property_type
    # --------------------------------------------------------------------------------
    chunk["property_type"] = chunk["property_type"].fillna("Unknown")

    # --------------------------------------------------------------------------------
    # Column: property_type_code
    # --------------------------------------------------------------------------------
    chunk["property_type_code"] = chunk["property_type_code"].fillna("Unknown")



    # --------------------------------------------------------------------------------
    # Columns: lot_1, lot_2, lot_3, lot_4, lot_5
    # --------------------------------------------------------------------------------
    chunk["lot_1"] = chunk["lot_1"].fillna("Unknown")
    chunk["lot_2"] = chunk["lot_2"].fillna("Unknown")
    chunk["lot_3"] = chunk["lot_3"].fillna("Unknown")
    chunk["lot_4"] = chunk["lot_4"].fillna("Unknown")
    chunk["lot_5"] = chunk["lot_5"].fillna("Unknown")


    # --------------------------------------------------------------------------------
    # Columns: lot_1_surface, lot_2_surface, lot_3_surface, lot_4_surface, lot_5_surface
    # --------------------------------------------------------------------------------
    chunk["lot_1_surface"] = chunk["lot_1_surface"].fillna("0")
    chunk["lot_2_surface"] = chunk["lot_2_surface"].fillna("0")
    chunk["lot_3_surface"] = chunk["lot_3_surface"].fillna("0")
    chunk["lot_4_surface"] = chunk["lot_4_surface"].fillna("0")
    chunk["lot_5_surface"] = chunk["lot_5_surface"].fillna("0")

    # --------------------------------------------------------------------------------
    # Column: main_rooms_count
    # --------------------------------------------------------------------------------
    # if surface_type is "building" and main_rooms_count is missing, fill with 0
    mask = (
        (chunk["surface_type"] == "building") & 
        (chunk["main_rooms_count"].isna())
    )
    chunk.loc[mask, "main_rooms_count"] = 0

    # --------------------------------------------------------------------------------
    # Column: land_surface
    # --------------------------------------------------------------------------------
    mask = (
        chunk["building_real_surface"].notna() &
        chunk["land_surface"].isna()
    )
    chunk.loc[mask, "land_surface"] = 0

    # --------------------------------------------------------------------------------
    # Column: land_nature
    # --------------------------------------------------------------------------------
    chunk["land_nature"] = chunk["land_nature"].fillna("Unknown")

    # --------------------------------------------------------------------------------
    # Column: land_nature_special
    # --------------------------------------------------------------------------------
    chunk["land_nature_special"] = chunk["land_nature_special"].fillna("Unknown")

    # --------------------------------------------------------------------------------
    # Column: land_surface
    # --------------------------------------------------------------------------------
    chunk["land_surface"] = chunk["land_surface"].fillna(0)


    # --------------------------------------------------------------------------------
    # Column: btq_code
    # --------------------------------------------------------------------------------
    chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")

    # --------------------------------------------------------------------------------
    # Column: street_name
    # --------------------------------------------------------------------------------
    chunk["street_name"] = chunk["street_name"].fillna("Unknown")

    # --------------------------------------------------------------------------------
    # Column: postal_code
    # --------------------------------------------------------------------------------
    chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

    return chunk


def process_nulls_chunked(input_file, output_file, chunk_size):
    output_file.parent.mkdir(parents=True, exist_ok=True)

    first_write = True
    total_rows = 0

    for i, chunk in enumerate(
        pd.read_csv(input_file, chunksize=chunk_size),
        start=1
    ):
        chunk = handle_nulls(chunk)

        chunk.to_csv(
            output_file,
            mode="w" if first_write else "a",
            index=False,
            header=first_write,
            encoding="utf-8"
        )

        first_write = False
        total_rows += len(chunk)

        print(f"Chunk {i} processed -> {len(chunk):,} rows | total: {total_rows:,}")

    print("\nDone! Null values handled")
    print(f"Saved file: {output_file}")
    print(f"Total rows written: {total_rows:,}")


process_nulls_chunked(INPUT_FILE, OUTPUT_FILE, CHUNK_SIZE)

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (16,17,19) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 1 processed -> 49,207 rows | total: 49,207

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17,19,21) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 2 processed -> 49,885 rows | total: 99,092

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 3 processed -> 49,799 rows | total: 148,891

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (16,17) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 4 processed -> 49,703 rows | total: 198,594

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 5 processed -> 49,717 rows | total: 248,311

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (16,17,19) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 6 processed -> 49,526 rows | total: 297,837

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 7 processed -> 49,920 rows | total: 347,757

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 8 processed -> 49,543 rows | total: 397,300

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (16,19) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 9 processed -> 49,605 rows | total: 446,905

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (16,19) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 10 processed -> 49,751 rows | total: 496,656

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (11,17,19) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 11 processed -> 49,252 rows | total: 545,908

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (11) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 12 processed -> 49,895 rows | total: 595,803

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 13 processed -> 49,790 rows | total: 645,593

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 14 processed -> 49,771 rows | total: 695,364

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (16,17) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 15 processed -> 49,759 rows | total: 745,123

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 16 processed -> 49,774 rows | total: 794,897

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 17 processed -> 49,777 rows | total: 844,674

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 18 processed -> 49,364 rows | total: 894,038

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 19 processed -> 49,612 rows | total: 943,650

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 20 processed -> 49,795 rows | total: 993,445

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 21 processed -> 48,745 rows | total: 1,042,190

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (16,17,19) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 22 processed -> 48,986 rows | total: 1,091,176

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (16,17) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 23 processed -> 49,817 rows | total: 1,140,993

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17,19,21) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 24 processed -> 49,636 rows | total: 1,190,629

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (16,33) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 25 processed -> 46,253 rows | total: 1,236,882

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 26 processed -> 43,514 rows | total: 1,280,396

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (16,17) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 27 processed -> 49,540 rows | total: 1,329,936

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17,19) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 28 processed -> 49,838 rows | total: 1,379,774

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 29 processed -> 49,433 rows | total: 1,429,207

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17,19) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 30 processed -> 49,555 rows | total: 1,478,762

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17,19) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 31 processed -> 49,817 rows | total: 1,528,579

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 32 processed -> 49,797 rows | total: 1,578,376

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 33 processed -> 49,820 rows | total: 1,628,196

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (16,17,19) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 34 processed -> 49,591 rows | total: 1,677,787

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 35 processed -> 49,945 rows | total: 1,727,732

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17,19) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 36 processed -> 49,654 rows | total: 1,777,386

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (16,17,19) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 37 processed -> 49,462 rows | total: 1,826,848

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (16,33) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 38 processed -> 49,658 rows | total: 1,876,506

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 39 processed -> 40,574 rows | total: 1,917,080

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 40 processed -> 49,316 rows | total: 1,966,396

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17,33) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 41 processed -> 49,597 rows | total: 2,015,993

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17,19) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 42 processed -> 49,714 rows | total: 2,065,707

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (16,17) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 43 processed -> 49,431 rows | total: 2,115,138

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17,19,21,23) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 44 processed -> 49,758 rows | total: 2,164,896

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17,19,21) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 45 processed -> 49,891 rows | total: 2,214,787

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17,19) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 46 processed -> 49,779 rows | total: 2,264,566

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 47 processed -> 49,861 rows | total: 2,314,427

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 48 processed -> 49,846 rows | total: 2,364,273

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 49 processed -> 49,868 rows | total: 2,414,141

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 50 processed -> 49,676 rows | total: 2,463,817

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 51 processed -> 49,914 rows | total: 2,513,731

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 52 processed -> 49,839 rows | total: 2,563,570

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (16,17) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 53 processed -> 49,734 rows | total: 2,613,304

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 54 processed -> 49,634 rows | total: 2,662,938

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (16,17,19) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 55 processed -> 49,853 rows | total: 2,712,791

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17,19) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 56 processed -> 49,679 rows | total: 2,762,470

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 57 processed -> 49,789 rows | total: 2,812,259

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 58 processed -> 49,932 rows | total: 2,862,191

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 59 processed -> 49,457 rows | total: 2,911,648

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 60 processed -> 49,580 rows | total: 2,961,228

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 61 processed -> 49,909 rows | total: 3,011,137

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 62 processed -> 36,526 rows | total: 3,047,663

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 63 processed -> 49,872 rows | total: 3,097,535

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 64 processed -> 49,891 rows | total: 3,147,426

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (19) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 65 processed -> 49,728 rows | total: 3,197,154

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (16,19) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 66 processed -> 49,386 rows | total: 3,246,540

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (11,17,19) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 67 processed -> 49,293 rows | total: 3,295,833

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 68 processed -> 49,900 rows | total: 3,345,733

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 69 processed -> 49,921 rows | total: 3,395,654

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 70 processed -> 49,859 rows | total: 3,445,513

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 71 processed -> 49,824 rows | total: 3,495,337

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17,19) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 72 processed -> 49,650 rows | total: 3,544,987

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 73 processed -> 49,766 rows | total: 3,594,753

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (16,17,19,21,23) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 74 processed -> 49,802 rows | total: 3,644,555

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17,19,21) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 75 processed -> 49,922 rows | total: 3,694,477

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (16,17,19) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 76 processed -> 49,663 rows | total: 3,744,140

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 77 processed -> 49,825 rows | total: 3,793,965

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 78 processed -> 49,832 rows | total: 3,843,797

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 79 processed -> 49,905 rows | total: 3,893,702

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 80 processed -> 49,862 rows | total: 3,943,564

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (16,17) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 81 processed -> 49,691 rows | total: 3,993,255

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (16,17,19) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 82 processed -> 49,610 rows | total: 4,042,865

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (16,17) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 83 processed -> 49,931 rows | total: 4,092,796

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 84 processed -> 49,761 rows | total: 4,142,557

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 85 processed -> 49,498 rows | total: 4,192,055

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 86 processed -> 49,607 rows | total: 4,241,662

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 87 processed -> 49,737 rows | total: 4,291,399

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 88 processed -> 49,727 rows | total: 4,341,126

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 89 processed -> 49,308 rows | total: 4,390,434

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (16,17,19) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 90 processed -> 49,139 rows | total: 4,439,573

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (16,17,19) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 91 processed -> 49,647 rows | total: 4,489,220

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 92 processed -> 48,887 rows | total: 4,538,107

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 93 processed -> 49,588 rows | total: 4,587,695

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17,19) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 94 processed -> 49,699 rows | total: 4,637,394

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17,19) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 95 processed -> 49,811 rows | total: 4,687,205

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 96 processed -> 49,747 rows | total: 4,736,952

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 97 processed -> 49,688 rows | total: 4,786,640

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 98 processed -> 49,846 rows | total: 4,836,486

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (19,21) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 99 processed -> 49,542 rows | total: 4,886,028

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 100 processed -> 49,721 rows | total: 4,935,749

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 101 processed -> 49,478 rows | total: 4,985,227

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 102 processed -> 49,528 rows | total: 5,034,755

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 103 processed -> 49,739 rows | total: 5,084,494

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17,19) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 104 processed -> 49,761 rows | total: 5,134,255

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 105 processed -> 49,903 rows | total: 5,184,158

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 106 processed -> 49,918 rows | total: 5,234,076

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 107 processed -> 49,844 rows | total: 5,283,920

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 108 processed -> 49,446 rows | total: 5,333,366

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17,19) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 109 processed -> 49,359 rows | total: 5,382,725

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17,19) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 110 processed -> 48,791 rows | total: 5,431,516

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 111 processed -> 49,839 rows | total: 5,481,355

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 112 processed -> 49,378 rows | total: 5,530,733

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 113 processed -> 49,545 rows | total: 5,580,278

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 114 processed -> 49,434 rows | total: 5,629,712

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (19) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 115 processed -> 49,890 rows | total: 5,679,602

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 116 processed -> 49,719 rows | total: 5,729,321

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 117 processed -> 49,739 rows | total: 5,779,060

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 118 processed -> 49,804 rows | total: 5,828,864

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 119 processed -> 49,912 rows | total: 5,878,776

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 120 processed -> 49,898 rows | total: 5,928,674

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 121 processed -> 49,955 rows | total: 5,978,629

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 122 processed -> 49,735 rows | total: 6,028,364

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17,19) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 123 processed -> 49,663 rows | total: 6,078,027

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 124 processed -> 49,854 rows | total: 6,127,881

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17,19) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 125 processed -> 49,392 rows | total: 6,177,273

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 126 processed -> 49,189 rows | total: 6,226,462

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17,19,21,23) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 127 processed -> 49,844 rows | total: 6,276,306

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 128 processed -> 49,740 rows | total: 6,326,046

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (7,33) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 129 processed -> 49,811 rows | total: 6,375,857

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 130 processed -> 49,595 rows | total: 6,425,452

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 131 processed -> 49,977 rows | total: 6,475,429

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 132 processed -> 49,687 rows | total: 6,525,116

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17,19) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 133 processed -> 49,426 rows | total: 6,574,542

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (7,17,33) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 134 processed -> 48,604 rows | total: 6,623,146

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17,19,21,33) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 135 processed -> 49,838 rows | total: 6,672,984

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 136 processed -> 49,824 rows | total: 6,722,808

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17,19) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 137 processed -> 49,833 rows | total: 6,772,641

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17,19) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 138 processed -> 49,361 rows | total: 6,822,002

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17,19) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 139 processed -> 49,942 rows | total: 6,871,944

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 140 processed -> 49,979 rows | total: 6,921,923

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 141 processed -> 49,837 rows | total: 6,971,760

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 142 processed -> 49,923 rows | total: 7,021,683

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 143 processed -> 49,791 rows | total: 7,071,474

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 144 processed -> 49,733 rows | total: 7,121,207

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 145 processed -> 49,933 rows | total: 7,171,140

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 146 processed -> 49,912 rows | total: 7,221,052

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 147 processed -> 49,680 rows | total: 7,270,732

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 148 processed -> 49,798 rows | total: 7,320,530

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (16,17,19) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 149 processed -> 49,874 rows | total: 7,370,404

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 150 processed -> 49,543 rows | total: 7,419,947

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 151 processed -> 49,822 rows | total: 7,469,769

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 152 processed -> 49,662 rows | total: 7,519,431

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 153 processed -> 49,538 rows | total: 7,568,969

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 154 processed -> 49,425 rows | total: 7,618,394

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 155 processed -> 49,590 rows | total: 7,667,984

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 156 processed -> 49,779 rows | total: 7,717,763

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 157 processed -> 49,864 rows | total: 7,767,627

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 158 processed -> 49,739 rows | total: 7,817,366

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (19) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 159 processed -> 49,745 rows | total: 7,867,111

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (11,17,19,21) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 160 processed -> 49,088 rows | total: 7,916,199

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 161 processed -> 49,659 rows | total: 7,965,858

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 162 processed -> 49,885 rows | total: 8,015,743

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 163 processed -> 49,735 rows | total: 8,065,478

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 164 processed -> 49,763 rows | total: 8,115,241

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 165 processed -> 49,749 rows | total: 8,164,990

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 166 processed -> 49,841 rows | total: 8,214,831

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 167 processed -> 49,956 rows | total: 8,264,787

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17,19) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 168 processed -> 49,934 rows | total: 8,314,721

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17,19) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 169 processed -> 49,553 rows | total: 8,364,274

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 170 processed -> 49,698 rows | total: 8,413,972

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 171 processed -> 49,672 rows | total: 8,463,644

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 172 processed -> 49,867 rows | total: 8,513,511

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (16,17) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 173 processed -> 49,470 rows | total: 8,562,981

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 174 processed -> 49,877 rows | total: 8,612,858

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 175 processed -> 47,796 rows | total: 8,660,654

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (16,17) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 176 processed -> 49,896 rows | total: 8,710,550

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 177 processed -> 49,588 rows | total: 8,760,138

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 178 processed -> 49,575 rows | total: 8,809,713

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 179 processed -> 49,819 rows | total: 8,859,532

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 180 processed -> 49,862 rows | total: 8,909,394

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 181 processed -> 48,902 rows | total: 8,958,296

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (16,21) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 182 processed -> 49,679 rows | total: 9,007,975

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (16,17,19) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 183 processed -> 48,967 rows | total: 9,056,942

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (5,6,16,17,19,29) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 184 processed -> 48,710 rows | total: 9,105,652

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 185 processed -> 49,307 rows | total: 9,154,959

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 186 processed -> 49,554 rows | total: 9,204,513

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17,33) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 187 processed -> 49,857 rows | total: 9,254,370

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17,19,21) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 188 processed -> 49,606 rows | total: 9,303,976

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 189 processed -> 49,823 rows | total: 9,353,799

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 190 processed -> 49,702 rows | total: 9,403,501

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 191 processed -> 49,832 rows | total: 9,453,333

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 192 processed -> 49,678 rows | total: 9,503,011

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 193 processed -> 48,837 rows | total: 9,551,848

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 194 processed -> 49,703 rows | total: 9,601,551

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 195 processed -> 49,718 rows | total: 9,651,269

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 196 processed -> 49,653 rows | total: 9,700,922

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17,19) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 197 processed -> 49,846 rows | total: 9,750,768

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 198 processed -> 49,852 rows | total: 9,800,620

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 199 processed -> 49,901 rows | total: 9,850,521

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 200 processed -> 49,927 rows | total: 9,900,448

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 201 processed -> 49,716 rows | total: 9,950,164

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (16,17,19) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 202 processed -> 49,790 rows | total: 9,999,954

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (16,17,19,21) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 203 processed -> 48,711 rows | total: 10,048,665

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17,19) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 204 processed -> 49,854 rows | total: 10,098,519

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 205 processed -> 49,757 rows | total: 10,148,276

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 206 processed -> 49,536 rows | total: 10,197,812

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 207 processed -> 49,839 rows | total: 10,247,651

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 208 processed -> 49,857 rows | total: 10,297,508

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 209 processed -> 49,841 rows | total: 10,347,349

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 210 processed -> 49,188 rows | total: 10,396,537

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 211 processed -> 49,819 rows | total: 10,446,356

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 212 processed -> 49,714 rows | total: 10,496,070

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 213 processed -> 49,931 rows | total: 10,546,001

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 214 processed -> 49,958 rows | total: 10,595,959

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (16,17) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 215 processed -> 49,670 rows | total: 10,645,629

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (16,17,19) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 216 processed -> 49,690 rows | total: 10,695,319

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 217 processed -> 49,673 rows | total: 10,744,992

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17,19) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 218 processed -> 49,740 rows | total: 10,794,732

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (16,17,19) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 219 processed -> 49,320 rows | total: 10,844,052

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 220 processed -> 49,893 rows | total: 10,893,945

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (33) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 221 processed -> 49,904 rows | total: 10,943,849

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (16,17,19) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 222 processed -> 49,910 rows | total: 10,993,759

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (33) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 223 processed -> 49,874 rows | total: 11,043,633

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 224 processed -> 49,884 rows | total: 11,093,517

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (19) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 225 processed -> 49,972 rows | total: 11,143,489

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 226 processed -> 49,844 rows | total: 11,193,333

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (7,17,33) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 227 processed -> 48,913 rows | total: 11,242,246

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (7,19,33) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 228 processed -> 48,940 rows | total: 11,291,186

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 229 processed -> 49,773 rows | total: 11,340,959

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17,19) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 230 processed -> 49,771 rows | total: 11,390,730

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17,19) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 231 processed -> 49,883 rows | total: 11,440,613

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17,19,21) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 232 processed -> 49,904 rows | total: 11,490,517

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17,19) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 233 processed -> 49,953 rows | total: 11,540,470

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 234 processed -> 49,824 rows | total: 11,590,294

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 235 processed -> 49,062 rows | total: 11,639,356

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 236 processed -> 49,616 rows | total: 11,688,972

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 237 processed -> 49,746 rows | total: 11,738,718

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (33) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 238 processed -> 49,587 rows | total: 11,788,305

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 239 processed -> 49,833 rows | total: 11,838,138

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17,19) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 240 processed -> 49,676 rows | total: 11,887,814

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17,19) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 241 processed -> 49,595 rows | total: 11,937,409

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 242 processed -> 49,885 rows | total: 11,987,294

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 243 processed -> 49,781 rows | total: 12,037,075

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 244 processed -> 49,275 rows | total: 12,086,350

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 245 processed -> 48,757 rows | total: 12,135,107

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 246 processed -> 49,692 rows | total: 12,184,799

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 247 processed -> 49,819 rows | total: 12,234,618

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17,19) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 248 processed -> 49,767 rows | total: 12,284,385

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (11,17,19) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 249 processed -> 49,498 rows | total: 12,333,883

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (11,17) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 250 processed -> 49,495 rows | total: 12,383,378

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 251 processed -> 49,794 rows | total: 12,433,172

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 252 processed -> 49,611 rows | total: 12,482,783

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 253 processed -> 49,658 rows | total: 12,532,441

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 254 processed -> 49,271 rows | total: 12,581,712

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 255 processed -> 49,478 rows | total: 12,631,190

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 256 processed -> 49,700 rows | total: 12,680,890

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (16,17,19) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 257 processed -> 49,317 rows | total: 12,730,207

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 258 processed -> 49,776 rows | total: 12,779,983

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 259 processed -> 49,840 rows | total: 12,829,823

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (16,17) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 260 processed -> 49,528 rows | total: 12,879,351

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17,19,21) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 261 processed -> 49,674 rows | total: 12,929,025

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17,19,21) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 262 processed -> 49,605 rows | total: 12,978,630

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 263 processed -> 49,424 rows | total: 13,028,054

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (16,17) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 264 processed -> 49,277 rows | total: 13,077,331

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 265 processed -> 49,532 rows | total: 13,126,863

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 266 processed -> 49,781 rows | total: 13,176,644

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 267 processed -> 49,799 rows | total: 13,226,443

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17,19) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 268 processed -> 47,921 rows | total: 13,274,364

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (19,25) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 269 processed -> 49,199 rows | total: 13,323,563

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17,19,21) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 270 processed -> 49,836 rows | total: 13,373,399

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (16,17) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 271 processed -> 49,641 rows | total: 13,423,040

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (16,17,19) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 272 processed -> 49,662 rows | total: 13,472,702

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 273 processed -> 49,251 rows | total: 13,521,953

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 274 processed -> 49,634 rows | total: 13,571,587

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 275 processed -> 49,767 rows | total: 13,621,354

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 276 processed -> 49,661 rows | total: 13,671,015

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 277 processed -> 49,750 rows | total: 13,720,765

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 278 processed -> 49,685 rows | total: 13,770,450

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (16,17,19) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 279 processed -> 49,766 rows | total: 13,820,216

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (16,17) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 280 processed -> 49,687 rows | total: 13,869,903

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 281 processed -> 49,643 rows | total: 13,919,546

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 282 processed -> 49,880 rows | total: 13,969,426

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17,19) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 283 processed -> 49,528 rows | total: 14,018,954

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17,19) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 284 processed -> 49,614 rows | total: 14,068,568

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 285 processed -> 49,612 rows | total: 14,118,180

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 286 processed -> 49,496 rows | total: 14,167,676

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 287 processed -> 49,652 rows | total: 14,217,328

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 288 processed -> 49,853 rows | total: 14,267,181

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 289 processed -> 49,670 rows | total: 14,316,851

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 290 processed -> 49,344 rows | total: 14,366,195

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 291 processed -> 49,886 rows | total: 14,416,081

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 292 processed -> 49,912 rows | total: 14,465,993

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 293 processed -> 49,914 rows | total: 14,515,907

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (16,17) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 294 processed -> 49,018 rows | total: 14,564,925

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 295 processed -> 49,705 rows | total: 14,614,630

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17,19,21) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 296 processed -> 49,274 rows | total: 14,663,904

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (16,17,19) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 297 processed -> 49,735 rows | total: 14,713,639

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 298 processed -> 49,690 rows | total: 14,763,329

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 299 processed -> 49,699 rows | total: 14,813,028

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (7,17,19) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 300 processed -> 49,714 rows | total: 14,862,742

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 301 processed -> 45,288 rows | total: 14,908,030

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 302 processed -> 49,843 rows | total: 14,957,873

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (7,17,33) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 303 processed -> 49,678 rows | total: 15,007,551

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (7,17,19) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 304 processed -> 49,455 rows | total: 15,057,006

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17,19,33) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 305 processed -> 49,765 rows | total: 15,106,771

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17,19,21,23) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 306 processed -> 49,535 rows | total: 15,156,306

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17,19) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 307 processed -> 49,921 rows | total: 15,206,227

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17,19,21) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 308 processed -> 49,894 rows | total: 15,256,121

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 309 processed -> 49,806 rows | total: 15,305,927

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 310 processed -> 46,697 rows | total: 15,352,624

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 311 processed -> 49,764 rows | total: 15,402,388

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 312 processed -> 49,790 rows | total: 15,452,178

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 313 processed -> 49,877 rows | total: 15,502,055

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 314 processed -> 49,740 rows | total: 15,551,795

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17,19) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 315 processed -> 49,858 rows | total: 15,601,653

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17,19) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 316 processed -> 49,714 rows | total: 15,651,367

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 317 processed -> 49,855 rows | total: 15,701,222

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 318 processed -> 49,212 rows | total: 15,750,434

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 319 processed -> 49,266 rows | total: 15,799,700

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (19,21) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 320 processed -> 49,654 rows | total: 15,849,354

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (16,17,19) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 321 processed -> 49,769 rows | total: 15,899,123

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 322 processed -> 49,854 rows | total: 15,948,977

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 323 processed -> 49,375 rows | total: 15,998,352

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (11,17) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 324 processed -> 47,343 rows | total: 16,045,695

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 325 processed -> 49,767 rows | total: 16,095,462

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 326 processed -> 49,783 rows | total: 16,145,245

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 327 processed -> 49,696 rows | total: 16,194,941

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 328 processed -> 49,676 rows | total: 16,244,617

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 329 processed -> 49,710 rows | total: 16,294,327

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 330 processed -> 49,319 rows | total: 16,343,646

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 331 processed -> 49,560 rows | total: 16,393,206

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 332 processed -> 48,930 rows | total: 16,442,136

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 333 processed -> 49,725 rows | total: 16,491,861

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17,19) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 334 processed -> 49,707 rows | total: 16,541,568

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (19) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 335 processed -> 49,806 rows | total: 16,591,374

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 336 processed -> 49,344 rows | total: 16,640,718

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 337 processed -> 49,469 rows | total: 16,690,187

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 338 processed -> 49,780 rows | total: 16,739,967

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 339 processed -> 49,749 rows | total: 16,789,716

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17,19) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 340 processed -> 48,549 rows | total: 16,838,265

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17,19) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 341 processed -> 47,635 rows | total: 16,885,900

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (16,17,19) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 342 processed -> 49,156 rows | total: 16,935,056

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 343 processed -> 49,635 rows | total: 16,984,691

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17,19) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 344 processed -> 49,473 rows | total: 17,034,164

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 345 processed -> 49,430 rows | total: 17,083,594

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 346 processed -> 49,467 rows | total: 17,133,061

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 347 processed -> 49,376 rows | total: 17,182,437

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 348 processed -> 48,240 rows | total: 17,230,677

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 349 processed -> 48,347 rows | total: 17,279,024

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 350 processed -> 49,109 rows | total: 17,328,133

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (16,17,19) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 351 processed -> 49,516 rows | total: 17,377,649

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 352 processed -> 49,757 rows | total: 17,427,406

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (16,17) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 353 processed -> 49,904 rows | total: 17,477,310

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 354 processed -> 49,354 rows | total: 17,526,664

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (16,17,19) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 355 processed -> 49,566 rows | total: 17,576,230

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (16,17,19) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 356 processed -> 49,603 rows | total: 17,625,833

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 357 processed -> 49,610 rows | total: 17,675,443

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 358 processed -> 49,509 rows | total: 17,724,952

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 359 processed -> 49,112 rows | total: 17,774,064

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 360 processed -> 49,756 rows | total: 17,823,820

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 361 processed -> 49,194 rows | total: 17,873,014

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 362 processed -> 49,837 rows | total: 17,922,851

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 363 processed -> 49,820 rows | total: 17,972,671

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 364 processed -> 49,812 rows | total: 18,022,483

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (16,17,19) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 365 processed -> 49,690 rows | total: 18,072,173

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 366 processed -> 49,556 rows | total: 18,121,729

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17,19) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 367 processed -> 49,792 rows | total: 18,171,521

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 368 processed -> 49,562 rows | total: 18,221,083

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17,19,21,23,33) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 369 processed -> 49,710 rows | total: 18,270,793

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 370 processed -> 49,733 rows | total: 18,320,526

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 371 processed -> 49,763 rows | total: 18,370,289

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 372 processed -> 49,646 rows | total: 18,419,935

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17,33) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 373 processed -> 49,762 rows | total: 18,469,697

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (7,17,19,33) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 374 processed -> 49,922 rows | total: 18,519,619

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17,19) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 375 processed -> 49,829 rows | total: 18,569,448

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17,19,21) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 376 processed -> 49,940 rows | total: 18,619,388

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 377 processed -> 49,845 rows | total: 18,669,233

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 378 processed -> 49,842 rows | total: 18,719,075

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 379 processed -> 49,346 rows | total: 18,768,421

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 380 processed -> 49,316 rows | total: 18,817,737

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 381 processed -> 49,837 rows | total: 18,867,574

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (11,17,19) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 382 processed -> 49,682 rows | total: 18,917,256

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 383 processed -> 49,800 rows | total: 18,967,056

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 384 processed -> 49,452 rows | total: 19,016,508

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 385 processed -> 49,410 rows | total: 19,065,918

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 386 processed -> 49,643 rows | total: 19,115,561

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 387 processed -> 49,666 rows | total: 19,165,227

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 388 processed -> 49,775 rows | total: 19,215,002

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (16,17,19) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 389 processed -> 48,746 rows | total: 19,263,748

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17,19,21) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 390 processed -> 49,667 rows | total: 19,313,415

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 391 processed -> 49,651 rows | total: 19,363,066

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 392 processed -> 48,178 rows | total: 19,411,244

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17,19) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 393 processed -> 49,033 rows | total: 19,460,277

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 394 processed -> 49,809 rows | total: 19,510,086

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17,19) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 395 processed -> 48,520 rows | total: 19,558,606

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17,19) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 396 processed -> 49,684 rows | total: 19,608,290

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 397 processed -> 49,718 rows | total: 19,658,008

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 398 processed -> 49,872 rows | total: 19,707,880

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (16,17,19) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 399 processed -> 49,457 rows | total: 19,757,337

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (17,19) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 400 processed -> 49,717 rows | total: 19,807,054

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 401 processed -> 49,840 rows | total: 19,856,894

C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:74: DtypeWarning: Columns (7,17,19,33) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_number"] = chunk["street_number"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0)
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["property_type"] = chunk["property_type"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["street_name"] = chunk["street_name"].fillna("Unknown")
C:\Users\sboub\AppData\Local\Temp\ipykernel_7700\975989312.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

Chunk 402 processed -> 48,716 rows | total: 19,905,610
Chunk 403 processed -> 2,739 rows | total: 19,908,349

Done! Null values handled
Saved file: ..\data\processed\NULLS_ValeursFoncieres.csv
Total rows written: 19,908,349

### **INFO - NULLS COUNT (AFTER)**

In [12]:
import pandas as pd

print("Re-checking data types and null counts after null handling...")

FILE = "../data/processed/NULLS_ValeursFoncieres.csv"
CHUNK_SIZE = 50_000

dtype_map = {
    # categorical columns
    "transaction_id": "string",
    "transaction_date": "string",
    "transaction_type": "string",
    "street_number": "string",
    "btq_code": "string",
    "street_type": "string",
    "street_id": "string",
    "street_name": "string",
    "postal_code": "string",
    "com_name": "string",
    "dep_code": "string",
    "com_code": "string",
    "section_prefix": "string",
    "section": "string",
    "plot_number": "string",
    "volume_number": "string",
    "property_type_code": "string",
    "property_type": "string",
    "land_nature": "string",
    "land_nature_special": "string",
    "surface_type": "string",

    # numeric columns
    "property_value": "float64",
    "building_real_surface": "float64",
    "land_surface": "float64",
    "lots_count": "Int64",
    "main_rooms_count": "Int64",
}


total_rows = 0
columns = None
non_null_counts = None
dtypes = None

for chunk in pd.read_csv(
    FILE,
    chunksize=CHUNK_SIZE,
    dtype=dtype_map,
    #parse_dates=["transaction_date"],
    #dayfirst=True,        # IMPORTANT for the date format (dd/mm/yyyy)
    low_memory=False      # removes DtypeWarning
):
    if columns is None:
        columns = chunk.columns.tolist()
        non_null_counts = {col: 0 for col in columns}
        dtypes = chunk.dtypes.astype(str).to_dict()

    total_rows += len(chunk)

    for col in columns:
        non_null_counts[col] += chunk[col].notna().sum()

info_df = pd.DataFrame({
    "column": columns,
    "non_null_count": [non_null_counts[col] for col in columns],
    "null_count": [total_rows - non_null_counts[col] for col in columns],
    "dtype": [dtypes[col] for col in columns]
})

print(f"RangeIndex: {total_rows} entries, 0 to {total_rows - 1}")
print(f"Data columns (total {len(columns)} columns):")
display(info_df)
print(f"dtypes: {info_df['dtype'].value_counts().to_dict()}")
print("memory usage: not computed (chunked mode)")

Re-checking data types and null counts after null handling...
RangeIndex: 19908349 entries, 0 to 19908348
Data columns (total 36 columns):

                   column  non_null_count  null_count    dtype
0          transaction_id        19908349           0   string
1        transaction_date        19908349           0   string
2        transaction_type        19908349           0   string
3          property_value        19908349           0  float64
4           street_number        19908349           0   string
5                btq_code        19908349           0   string
6             street_type        19908349           0   string
7               street_id        19908349           0   string
8             street_name        19908349           0   string
9             postal_code        19908349           0   string
10               com_name        19908349           0   string
11               dep_code        19908349           0   string
12               com_code        19908349           0   string
13         section_prefix        19908349           0   string
14                section        19908349           0   string
15            plot_number        19908349           0   string
16          volume_number        19908349           0   string
17                  lot_1        19908349           0   object
18          lot_1_surface        19908349           0  float64
19                  lot_2        19908349           0   object
20          lot_2_surface        19908349           0  float64
21                  lot_3        19908349           0   object
22          lot_3_surface        19908349           0  float64
23                  lot_4        19908349           0   object
24          lot_4_surface        19908349           0  float64
25                  lot_5        19908349           0   object
26          lot_5_surface        19908349           0  float64
27             lots_count        19908349           0    Int64
28     property_type_code        19908349           0   string
29          property_type        19908349           0   string
30  building_real_surface        19908349           0  float64
31       main_rooms_count        19908349           0    Int64
32            land_nature        19908349           0   string
33    land_nature_special        19908349           0   string
34           land_surface        19908349           0  float64
35           surface_type        19908349           0   string

dtypes: {'string': 21, 'float64': 8, 'object': 5, 'Int64': 2}
memory usage: not computed (chunked mode)

<hr>

## 5️⃣ DUPLICATES


<style>
h1 {
    text-align: center;
    color: black;
    font-weight: bold;
}
</style>

<style>
h2 {
    text-align: left;
    color: black;
    font-weight: bold;
}
</style>

<style>
h3 {
    text-align: left;
    color: black;
    font-weight: bold;
}
</style>

<style>
h4 {
    text-align: left;
    color: black;
    font-weight: bold;
}
</style>
<hr>

### **SHAPE & HEAD - BEFORE Dealing with Duplicates**

In [ ]:
import pandas as pd

FILE = "../data/processed/NULLS_ValeursFoncieres.csv"
CHUNK_SIZE = 50_000

dtype_map = {
    # categorical columns
    "transaction_id": "string",
    "transaction_date": "string",
    "transaction_type": "string",
    "street_number": "string",
    "btq_code": "string",
    "street_type": "string",
    "street_id": "string",
    "street_name": "string",
    "postal_code": "string",
    "com_name": "string",
    "dep_code": "string",
    "com_code": "string",
    "section_prefix": "string",
    "section": "string",
    "plot_number": "string",
    "volume_number": "string",
    "property_type_code": "string",
    "property_type": "string",
    "land_nature": "string",
    "land_nature_special": "string",
    "surface_type": "string",
    "lot_1": "string",
    "lot_2": "string",
    "lot_3": "string",
    "lot_4": "string",
    "lot_5": "string",
    "lots_count": "Int64",
    # numeric columns
    "property_value": "float64",
    "building_real_surface": "float64",
    "land_surface": "float64",
    "main_rooms_count": "Int64",
    "lot_1_surface": "float64",
    "lot_2_surface": "float64",
    "lot_3_surface": "float64",
    "lot_4_surface": "float64",
    "lot_5_surface": "float64"
}

# ---------------------------
# Get full dataset shape
# ---------------------------
total_rows = 0
columns = None

for chunk in pd.read_csv(
    FILE,
    chunksize=CHUNK_SIZE,
    dtype=dtype_map,
    low_memory=False
):
    total_rows += len(chunk)
    if columns is None:
        columns = chunk.columns

print("Shape:", total_rows, "rows and", len(columns), "columns")

# ---------------------------
# Display head (correct types)
# ---------------------------
df_head = pd.read_csv(
    FILE,
    nrows=5,
    dtype=dtype_map,
    low_memory=False
)

display(df_head)

Shape: 19908349 rows and 36 columns

,transaction_id,transaction_date,transaction_type,property_value,street_number,btq_code,street_type,street_id,street_name,postal_code,com_name,dep_code,com_code,section_prefix,section,plot_number,volume_number,lot_1,lot_1_surface,lot_2,lot_2_surface,lot_3,lot_3_surface,lot_4,lot_4_surface,lot_5,lot_5_surface,lots_count,property_type_code,property_type,building_real_surface,main_rooms_count,land_nature,land_nature_special,land_surface,surface_type
0,000001,2020-07-01,Sale,31234.16,Unknown,Unknown,Unknown,B064,SAINT JULIEN,1560,SAINT-JULIEN-SUR-REYSSOUZE,01,367,Unknown,A,8,Unknown,Unknown,0.0,Unknown,0.0,Unknown,0.0,Unknown,0.0,Unknown,0.0,0,Unknown,Unknown,0.0,0,AB,Unknown,1192.0,land
1,000001,2020-07-01,Sale,278000.00,Unknown,Unknown,Unknown,B188,A LA PEROUSE,1250,CORVEISSIAT,01,125,Unknown,C,509,Unknown,Unknown,0.0,Unknown,0.0,Unknown,0.0,Unknown,0.0,Unknown,0.0,0,Unknown,Unknown,0.0,0,BS,Unknown,10092.0,land
2,000001,2020-07-01,Sale,278000.00,Unknown,Unknown,Unknown,B188,A LA PEROUSE,1250,CORVEISSIAT,01,125,Unknown,C,510,Unknown,Unknown,0.0,Unknown,0.0,Unknown,0.0,Unknown,0.0,Unknown,0.0,0,Unknown,Unknown,0.0,0,L,Unknown,4570.0,land
3,000001,2020-07-01,Sale,278000.00,Unknown,Unknown,Unknown,B079,AUX COMMUNS,1250,CORVEISSIAT,01,125,Unknown,ZL,96,Unknown,Unknown,0.0,Unknown,0.0,Unknown,0.0,Unknown,0.0,Unknown,0.0,0,Unknown,Unknown,0.0,0,BS,Unknown,5750.0,land
4,000001,2020-07-01,Sale,278000.00,Unknown,Unknown,Unknown,B033,EN COMBARNAUD,1250,SIMANDRE-SUR-SURAN,01,408,Unknown,A,14,Unknown,Unknown,0.0,Unknown,0.0,Unknown,0.0,Unknown,0.0,Unknown,0.0,0,Unknown,Unknown,0.0,0,BT,Unknown,648170.0,land

### **DUPLICATE ROWS**

In [ ]:
from pathlib import Path
import pandas as pd
import hashlib

FILE = Path("../data/processed/NULLS_ValeursFoncieres.csv")
CHUNK_SIZE = 50_000

dtype_map = {
    # categorical columns
    "transaction_id": "string",
    "transaction_date": "string",
    "transaction_type": "string",
    "street_number": "string",
    "btq_code": "string",
    "street_type": "string",
    "street_id": "string",
    "street_name": "string",
    "postal_code": "string",
    "com_name": "string",
    "dep_code": "string",
    "com_code": "string",
    "section_prefix": "string",
    "section": "string",
    "plot_number": "string",
    "volume_number": "string",
    "property_type_code": "string",
    "property_type": "string",
    "land_nature": "string",
    "land_nature_special": "string",
    "surface_type": "string",
    # numeric columns
    "property_value": "float64",
    "building_real_surface": "float64",
    "land_surface": "float64",
    "lots_count": "Int64",
    "main_rooms_count": "Int64",
}

def row_hash(row: pd.Series) -> str:
    values = row.fillna("<NA>").astype(str).tolist()
    row_str = "||".join(values)
    return hashlib.md5(row_str.encode("utf-8")).hexdigest()

total_rows = 0
duplicate_rows_count = 0
seen_hashes = set()

null_counts = None
columns = None
duplicate_samples = []

for chunk in pd.read_csv(
    FILE,
    chunksize=CHUNK_SIZE,
    dtype=dtype_map,
    low_memory=False
):
    if columns is None:
        columns = chunk.columns.tolist()
        null_counts = {col: 0 for col in columns}

    total_rows += len(chunk)

    # Null counts
    for col in columns:
        null_counts[col] += chunk[col].isna().sum()

    # Duplicate detection across all chunks
    chunk_hashes = chunk.apply(row_hash, axis=1)

    is_duplicate = chunk_hashes.isin(seen_hashes)
    duplicate_rows_count += is_duplicate.sum()

    # Save a few duplicate row samples for display
    if is_duplicate.any() and len(duplicate_samples) < 20:
        sample_dups = chunk.loc[is_duplicate].head(20 - len(duplicate_samples))
        duplicate_samples.append(sample_dups)

    # Add only new hashes
    new_hashes = chunk_hashes.loc[~is_duplicate]
    seen_hashes.update(new_hashes.tolist())

# Build null percentage summary
null_pct = {
    col: round(null_counts[col] / total_rows * 100, 2)
    for col in columns
}

nulls_df = pd.DataFrame({
    "column": columns,
    "null_count": [null_counts[col] for col in columns],
    "null_pct": [null_pct[col] for col in columns]
}).sort_values("null_pct", ascending=False)

# Print results
print(f"Number of duplicate rows: {duplicate_rows_count}")
print(100 * "-")
print("Nulls percentage in each column:")
display(nulls_df)
print(100 * "-")
print(f"Duplicate rows percentage: {duplicate_rows_count / total_rows * 100:.2f}%")
print(100 * "-")

# Display duplicate samples if any
if duplicate_rows_count > 0:
    print("\nDuplicate row samples:")
    display(pd.concat(duplicate_samples, ignore_index=True))
else:
    print("\nNo duplicate rows found.")

### **DEAL with DUPLICATE ROWS**

In [13]:
from pathlib import Path
import pandas as pd
import hashlib

INPUT_FILE = Path("../data/processed/NULLS_ValeursFoncieres.csv")
OUTPUT_FILE = Path("../data/processed/DUPLICATES_ValeursFoncieres.csv")

CHUNK_SIZE = 50_000

dtype_map = {
    "transaction_id": "string",
    "transaction_date": "string",
    "transaction_type": "string",
    "property_value": "float64",
    "street_number": "string",
    "btq_code": "string",
    "street_type": "string",
    "street_id": "string",
    "street_name": "string",
    "postal_code": "string",
    "com_name": "string",
    "dep_code": "string",
    "com_code": "string",
    "section_prefix": "string",
    "section": "string",
    "plot_number": "string",
    "volume_number": "string",
    "lot_1": "string",
    "lot_1_surface": "float64",
    "lot_2": "string",
    "lot_2_surface": "float64",
    "lot_3": "string",
    "lot_3_surface": "float64",
    "lot_4": "string",
    "lot_4_surface": "float64",
    "lot_5": "string",
    "lot_5_surface": "float64",
    "lots_count": "Int64",
    "property_type_code": "string",
    "property_type": "string",
    "building_real_surface": "float64",
    "main_rooms_count": "Int64",
    "land_nature": "string",
    "land_nature_special": "string",
    "land_surface": "float64",
    "surface_type": "string",
}

def row_hash(row: pd.Series) -> str:
    values = row.fillna("<NA>").astype(str).tolist()
    row_str = "||".join(values)
    return hashlib.md5(row_str.encode("utf-8")).hexdigest()

def remove_true_duplicates_chunked(input_file: Path, output_file: Path, chunk_size: int = 50_000) -> None:
    output_file.parent.mkdir(parents=True, exist_ok=True)

    seen_hashes = set()
    first_write = True

    total_rows_read = 0
    total_rows_written = 0
    total_duplicates_removed = 0

    for chunk_idx, chunk in enumerate(
        pd.read_csv(
            input_file,
            chunksize=chunk_size,
            dtype=dtype_map,
            low_memory=False
        ),
        start=1
    ):
        rows_before = len(chunk)
        total_rows_read += rows_before

        # Remove exact duplicates inside the chunk
        chunk = chunk.drop_duplicates().copy()

        # Hash full rows
        hashes = chunk.apply(row_hash, axis=1)

        # Keep only rows not seen before
        keep_mask = ~hashes.isin(seen_hashes)
        chunk_kept = chunk.loc[keep_mask].copy()

        # Update seen hashes
        seen_hashes.update(hashes.loc[keep_mask].tolist())

        rows_after = len(chunk_kept)
        removed_here = rows_before - rows_after

        total_rows_written += rows_after
        total_duplicates_removed += removed_here

        chunk_kept.to_csv(
            output_file,
            mode="w" if first_write else "a",
            index=False,
            header=first_write,
            encoding="utf-8"
        )

        first_write = False

        print(
            f"Chunk {chunk_idx} processed -> "
            f"read: {rows_before:,} | kept: {rows_after:,} | "
            f"removed: {removed_here:,} | total kept: {total_rows_written:,}"
        )

    print("\nDone! Removed true duplicates only")
    print(f"Saved file: {output_file}")
    print(f"Total rows read: {total_rows_read:,}")
    print(f"Total duplicates removed: {total_duplicates_removed:,}")
    print(f"Total rows written: {total_rows_written:,}")

remove_true_duplicates_chunked(INPUT_FILE, OUTPUT_FILE, CHUNK_SIZE)

Chunk 1 processed -> read: 50,000 | kept: 48,678 | removed: 1,322 | total kept: 48,678
Chunk 2 processed -> read: 50,000 | kept: 48,648 | removed: 1,352 | total kept: 97,326
Chunk 3 processed -> read: 50,000 | kept: 48,522 | removed: 1,478 | total kept: 145,848
Chunk 4 processed -> read: 50,000 | kept: 48,033 | removed: 1,967 | total kept: 193,881
Chunk 5 processed -> read: 50,000 | kept: 47,813 | removed: 2,187 | total kept: 241,694
Chunk 6 processed -> read: 50,000 | kept: 48,297 | removed: 1,703 | total kept: 289,991
Chunk 7 processed -> read: 50,000 | kept: 48,230 | removed: 1,770 | total kept: 338,221
Chunk 8 processed -> read: 50,000 | kept: 48,552 | removed: 1,448 | total kept: 386,773
Chunk 9 processed -> read: 50,000 | kept: 43,612 | removed: 6,388 | total kept: 430,385
Chunk 10 processed -> read: 50,000 | kept: 47,144 | removed: 2,856 | total kept: 477,529
Chunk 11 processed -> read: 50,000 | kept: 48,211 | removed: 1,789 | total kept: 525,740
Chunk 12 processed -> read: 50,000 | kept: 48,375 | removed: 1,625 | total kept: 574,115
Chunk 13 processed -> read: 50,000 | kept: 48,160 | removed: 1,840 | total kept: 622,275
Chunk 14 processed -> read: 50,000 | kept: 48,851 | removed: 1,149 | total kept: 671,126
Chunk 15 processed -> read: 50,000 | kept: 48,272 | removed: 1,728 | total kept: 719,398
Chunk 16 processed -> read: 50,000 | kept: 48,672 | removed: 1,328 | total kept: 768,070
Chunk 17 processed -> read: 50,000 | kept: 48,197 | removed: 1,803 | total kept: 816,267
Chunk 18 processed -> read: 50,000 | kept: 48,392 | removed: 1,608 | total kept: 864,659
Chunk 19 processed -> read: 50,000 | kept: 49,192 | removed: 808 | total kept: 913,851
Chunk 20 processed -> read: 50,000 | kept: 48,110 | removed: 1,890 | total kept: 961,961
Chunk 21 processed -> read: 50,000 | kept: 49,040 | removed: 960 | total kept: 1,011,001
Chunk 22 processed -> read: 50,000 | kept: 47,647 | removed: 2,353 | total kept: 1,058,648
Chunk 23 processed -> read: 50,000 | kept: 47,980 | removed: 2,020 | total kept: 1,106,628
Chunk 24 processed -> read: 50,000 | kept: 47,718 | removed: 2,282 | total kept: 1,154,346
Chunk 25 processed -> read: 50,000 | kept: 48,493 | removed: 1,507 | total kept: 1,202,839
Chunk 26 processed -> read: 50,000 | kept: 47,363 | removed: 2,637 | total kept: 1,250,202
Chunk 27 processed -> read: 50,000 | kept: 48,301 | removed: 1,699 | total kept: 1,298,503
Chunk 28 processed -> read: 50,000 | kept: 47,257 | removed: 2,743 | total kept: 1,345,760
Chunk 29 processed -> read: 50,000 | kept: 47,377 | removed: 2,623 | total kept: 1,393,137
Chunk 30 processed -> read: 50,000 | kept: 48,858 | removed: 1,142 | total kept: 1,441,995
Chunk 31 processed -> read: 50,000 | kept: 47,434 | removed: 2,566 | total kept: 1,489,429
Chunk 32 processed -> read: 50,000 | kept: 48,621 | removed: 1,379 | total kept: 1,538,050
Chunk 33 processed -> read: 50,000 | kept: 48,780 | removed: 1,220 | total kept: 1,586,830
Chunk 34 processed -> read: 50,000 | kept: 46,995 | removed: 3,005 | total kept: 1,633,825
Chunk 35 processed -> read: 50,000 | kept: 47,944 | removed: 2,056 | total kept: 1,681,769
Chunk 36 processed -> read: 50,000 | kept: 49,095 | removed: 905 | total kept: 1,730,864
Chunk 37 processed -> read: 50,000 | kept: 48,296 | removed: 1,704 | total kept: 1,779,160
Chunk 38 processed -> read: 50,000 | kept: 46,357 | removed: 3,643 | total kept: 1,825,517
Chunk 39 processed -> read: 50,000 | kept: 46,741 | removed: 3,259 | total kept: 1,872,258
Chunk 40 processed -> read: 50,000 | kept: 42,913 | removed: 7,087 | total kept: 1,915,171
Chunk 41 processed -> read: 50,000 | kept: 47,477 | removed: 2,523 | total kept: 1,962,648
Chunk 42 processed -> read: 50,000 | kept: 46,979 | removed: 3,021 | total kept: 2,009,627
Chunk 43 processed -> read: 50,000 | kept: 45,082 | removed: 4,918 | total kept: 2,054,709
Chunk 44 processed -> read: 50,000 | kept: 47,886 | removed: 2,114 | total kept: 2,102,595
Chunk 45 processed -> read: 50,000 | kept: 46,952 | removed: 3,048 | total kept: 2,149,547
Chunk 46 processed -> read: 50,000 | kept: 46,629 | removed: 3,371 | total kept: 2,196,176
Chunk 47 processed -> read: 50,000 | kept: 47,043 | removed: 2,957 | total kept: 2,243,219
Chunk 48 processed -> read: 50,000 | kept: 47,173 | removed: 2,827 | total kept: 2,290,392
Chunk 49 processed -> read: 50,000 | kept: 47,507 | removed: 2,493 | total kept: 2,337,899
Chunk 50 processed -> read: 50,000 | kept: 46,427 | removed: 3,573 | total kept: 2,384,326
Chunk 51 processed -> read: 50,000 | kept: 46,979 | removed: 3,021 | total kept: 2,431,305
Chunk 52 processed -> read: 50,000 | kept: 46,783 | removed: 3,217 | total kept: 2,478,088
Chunk 53 processed -> read: 50,000 | kept: 44,312 | removed: 5,688 | total kept: 2,522,400
Chunk 54 processed -> read: 50,000 | kept: 47,718 | removed: 2,282 | total kept: 2,570,118
Chunk 55 processed -> read: 50,000 | kept: 46,942 | removed: 3,058 | total kept: 2,617,060
Chunk 56 processed -> read: 50,000 | kept: 47,415 | removed: 2,585 | total kept: 2,664,475
Chunk 57 processed -> read: 50,000 | kept: 46,518 | removed: 3,482 | total kept: 2,710,993
Chunk 58 processed -> read: 50,000 | kept: 46,820 | removed: 3,180 | total kept: 2,757,813
Chunk 59 processed -> read: 50,000 | kept: 47,808 | removed: 2,192 | total kept: 2,805,621
Chunk 60 processed -> read: 50,000 | kept: 47,374 | removed: 2,626 | total kept: 2,852,995
Chunk 61 processed -> read: 50,000 | kept: 46,527 | removed: 3,473 | total kept: 2,899,522
Chunk 62 processed -> read: 50,000 | kept: 46,205 | removed: 3,795 | total kept: 2,945,727
Chunk 63 processed -> read: 50,000 | kept: 46,388 | removed: 3,612 | total kept: 2,992,115
Chunk 64 processed -> read: 50,000 | kept: 47,015 | removed: 2,985 | total kept: 3,039,130
Chunk 65 processed -> read: 50,000 | kept: 47,959 | removed: 2,041 | total kept: 3,087,089
Chunk 66 processed -> read: 50,000 | kept: 47,854 | removed: 2,146 | total kept: 3,134,943
Chunk 67 processed -> read: 50,000 | kept: 46,350 | removed: 3,650 | total kept: 3,181,293
Chunk 68 processed -> read: 50,000 | kept: 46,651 | removed: 3,349 | total kept: 3,227,944
Chunk 69 processed -> read: 50,000 | kept: 47,931 | removed: 2,069 | total kept: 3,275,875
Chunk 70 processed -> read: 50,000 | kept: 47,718 | removed: 2,282 | total kept: 3,323,593
Chunk 71 processed -> read: 50,000 | kept: 47,969 | removed: 2,031 | total kept: 3,371,562
Chunk 72 processed -> read: 50,000 | kept: 47,315 | removed: 2,685 | total kept: 3,418,877
Chunk 73 processed -> read: 50,000 | kept: 47,322 | removed: 2,678 | total kept: 3,466,199
Chunk 74 processed -> read: 50,000 | kept: 47,872 | removed: 2,128 | total kept: 3,514,071
Chunk 75 processed -> read: 50,000 | kept: 47,520 | removed: 2,480 | total kept: 3,561,591
Chunk 76 processed -> read: 50,000 | kept: 47,007 | removed: 2,993 | total kept: 3,608,598
Chunk 77 processed -> read: 50,000 | kept: 47,197 | removed: 2,803 | total kept: 3,655,795
Chunk 78 processed -> read: 50,000 | kept: 47,358 | removed: 2,642 | total kept: 3,703,153
Chunk 79 processed -> read: 50,000 | kept: 32,083 | removed: 17,917 | total kept: 3,735,236
Chunk 80 processed -> read: 50,000 | kept: 47,456 | removed: 2,544 | total kept: 3,782,692
Chunk 81 processed -> read: 50,000 | kept: 45,621 | removed: 4,379 | total kept: 3,828,313
Chunk 82 processed -> read: 50,000 | kept: 43,781 | removed: 6,219 | total kept: 3,872,094
Chunk 83 processed -> read: 50,000 | kept: 47,627 | removed: 2,373 | total kept: 3,919,721
Chunk 84 processed -> read: 50,000 | kept: 47,870 | removed: 2,130 | total kept: 3,967,591
Chunk 85 processed -> read: 50,000 | kept: 46,658 | removed: 3,342 | total kept: 4,014,249
Chunk 86 processed -> read: 50,000 | kept: 46,457 | removed: 3,543 | total kept: 4,060,706
Chunk 87 processed -> read: 50,000 | kept: 47,248 | removed: 2,752 | total kept: 4,107,954
Chunk 88 processed -> read: 50,000 | kept: 47,444 | removed: 2,556 | total kept: 4,155,398
Chunk 89 processed -> read: 50,000 | kept: 47,832 | removed: 2,168 | total kept: 4,203,230
Chunk 90 processed -> read: 50,000 | kept: 37,992 | removed: 12,008 | total kept: 4,241,222
Chunk 91 processed -> read: 50,000 | kept: 47,208 | removed: 2,792 | total kept: 4,288,430
Chunk 92 processed -> read: 50,000 | kept: 46,074 | removed: 3,926 | total kept: 4,334,504
Chunk 93 processed -> read: 50,000 | kept: 47,947 | removed: 2,053 | total kept: 4,382,451
Chunk 94 processed -> read: 50,000 | kept: 46,759 | removed: 3,241 | total kept: 4,429,210
Chunk 95 processed -> read: 50,000 | kept: 46,286 | removed: 3,714 | total kept: 4,475,496
Chunk 96 processed -> read: 50,000 | kept: 44,054 | removed: 5,946 | total kept: 4,519,550
Chunk 97 processed -> read: 50,000 | kept: 44,830 | removed: 5,170 | total kept: 4,564,380
Chunk 98 processed -> read: 50,000 | kept: 46,249 | removed: 3,751 | total kept: 4,610,629
Chunk 99 processed -> read: 50,000 | kept: 45,943 | removed: 4,057 | total kept: 4,656,572
Chunk 100 processed -> read: 50,000 | kept: 46,662 | removed: 3,338 | total kept: 4,703,234
Chunk 101 processed -> read: 50,000 | kept: 46,694 | removed: 3,306 | total kept: 4,749,928
Chunk 102 processed -> read: 50,000 | kept: 47,166 | removed: 2,834 | total kept: 4,797,094
Chunk 103 processed -> read: 50,000 | kept: 47,997 | removed: 2,003 | total kept: 4,845,091
Chunk 104 processed -> read: 50,000 | kept: 45,501 | removed: 4,499 | total kept: 4,890,592
Chunk 105 processed -> read: 50,000 | kept: 47,099 | removed: 2,901 | total kept: 4,937,691
Chunk 106 processed -> read: 50,000 | kept: 46,071 | removed: 3,929 | total kept: 4,983,762
Chunk 107 processed -> read: 50,000 | kept: 46,349 | removed: 3,651 | total kept: 5,030,111
Chunk 108 processed -> read: 50,000 | kept: 46,566 | removed: 3,434 | total kept: 5,076,677
Chunk 109 processed -> read: 50,000 | kept: 47,857 | removed: 2,143 | total kept: 5,124,534
Chunk 110 processed -> read: 50,000 | kept: 47,916 | removed: 2,084 | total kept: 5,172,450
Chunk 111 processed -> read: 50,000 | kept: 45,345 | removed: 4,655 | total kept: 5,217,795
Chunk 112 processed -> read: 50,000 | kept: 46,618 | removed: 3,382 | total kept: 5,264,413
Chunk 113 processed -> read: 50,000 | kept: 45,032 | removed: 4,968 | total kept: 5,309,445
Chunk 114 processed -> read: 50,000 | kept: 47,303 | removed: 2,697 | total kept: 5,356,748
Chunk 115 processed -> read: 50,000 | kept: 47,290 | removed: 2,710 | total kept: 5,404,038
Chunk 116 processed -> read: 50,000 | kept: 46,086 | removed: 3,914 | total kept: 5,450,124
Chunk 117 processed -> read: 50,000 | kept: 47,204 | removed: 2,796 | total kept: 5,497,328
Chunk 118 processed -> read: 50,000 | kept: 46,246 | removed: 3,754 | total kept: 5,543,574
Chunk 119 processed -> read: 50,000 | kept: 45,103 | removed: 4,897 | total kept: 5,588,677
Chunk 120 processed -> read: 50,000 | kept: 41,404 | removed: 8,596 | total kept: 5,630,081
Chunk 121 processed -> read: 50,000 | kept: 47,582 | removed: 2,418 | total kept: 5,677,663
Chunk 122 processed -> read: 50,000 | kept: 47,819 | removed: 2,181 | total kept: 5,725,482
Chunk 123 processed -> read: 50,000 | kept: 47,378 | removed: 2,622 | total kept: 5,772,860
Chunk 124 processed -> read: 50,000 | kept: 46,399 | removed: 3,601 | total kept: 5,819,259
Chunk 125 processed -> read: 50,000 | kept: 46,323 | removed: 3,677 | total kept: 5,865,582
Chunk 126 processed -> read: 50,000 | kept: 46,777 | removed: 3,223 | total kept: 5,912,359
Chunk 127 processed -> read: 50,000 | kept: 47,192 | removed: 2,808 | total kept: 5,959,551
Chunk 128 processed -> read: 50,000 | kept: 45,725 | removed: 4,275 | total kept: 6,005,276
Chunk 129 processed -> read: 50,000 | kept: 47,426 | removed: 2,574 | total kept: 6,052,702
Chunk 130 processed -> read: 50,000 | kept: 46,675 | removed: 3,325 | total kept: 6,099,377
Chunk 131 processed -> read: 50,000 | kept: 45,324 | removed: 4,676 | total kept: 6,144,701
Chunk 132 processed -> read: 50,000 | kept: 43,604 | removed: 6,396 | total kept: 6,188,305
Chunk 133 processed -> read: 50,000 | kept: 46,106 | removed: 3,894 | total kept: 6,234,411
Chunk 134 processed -> read: 50,000 | kept: 47,326 | removed: 2,674 | total kept: 6,281,737
Chunk 135 processed -> read: 50,000 | kept: 45,600 | removed: 4,400 | total kept: 6,327,337
Chunk 136 processed -> read: 50,000 | kept: 45,580 | removed: 4,420 | total kept: 6,372,917
Chunk 137 processed -> read: 50,000 | kept: 46,454 | removed: 3,546 | total kept: 6,419,371
Chunk 138 processed -> read: 50,000 | kept: 46,812 | removed: 3,188 | total kept: 6,466,183
Chunk 139 processed -> read: 50,000 | kept: 47,303 | removed: 2,697 | total kept: 6,513,486
Chunk 140 processed -> read: 50,000 | kept: 46,881 | removed: 3,119 | total kept: 6,560,367
Chunk 141 processed -> read: 50,000 | kept: 47,113 | removed: 2,887 | total kept: 6,607,480
Chunk 142 processed -> read: 50,000 | kept: 47,411 | removed: 2,589 | total kept: 6,654,891
Chunk 143 processed -> read: 50,000 | kept: 46,065 | removed: 3,935 | total kept: 6,700,956
Chunk 144 processed -> read: 50,000 | kept: 46,052 | removed: 3,948 | total kept: 6,747,008
Chunk 145 processed -> read: 50,000 | kept: 46,557 | removed: 3,443 | total kept: 6,793,565
Chunk 146 processed -> read: 50,000 | kept: 46,624 | removed: 3,376 | total kept: 6,840,189
Chunk 147 processed -> read: 50,000 | kept: 47,418 | removed: 2,582 | total kept: 6,887,607
Chunk 148 processed -> read: 50,000 | kept: 47,232 | removed: 2,768 | total kept: 6,934,839
Chunk 149 processed -> read: 50,000 | kept: 46,040 | removed: 3,960 | total kept: 6,980,879
Chunk 150 processed -> read: 50,000 | kept: 46,181 | removed: 3,819 | total kept: 7,027,060
Chunk 151 processed -> read: 50,000 | kept: 41,157 | removed: 8,843 | total kept: 7,068,217
Chunk 152 processed -> read: 50,000 | kept: 47,155 | removed: 2,845 | total kept: 7,115,372
Chunk 153 processed -> read: 50,000 | kept: 47,182 | removed: 2,818 | total kept: 7,162,554
Chunk 154 processed -> read: 50,000 | kept: 45,712 | removed: 4,288 | total kept: 7,208,266
Chunk 155 processed -> read: 50,000 | kept: 46,820 | removed: 3,180 | total kept: 7,255,086
Chunk 156 processed -> read: 50,000 | kept: 45,354 | removed: 4,646 | total kept: 7,300,440
Chunk 157 processed -> read: 50,000 | kept: 47,197 | removed: 2,803 | total kept: 7,347,637
Chunk 158 processed -> read: 50,000 | kept: 47,635 | removed: 2,365 | total kept: 7,395,272
Chunk 159 processed -> read: 50,000 | kept: 47,009 | removed: 2,991 | total kept: 7,442,281
Chunk 160 processed -> read: 50,000 | kept: 47,418 | removed: 2,582 | total kept: 7,489,699
Chunk 161 processed -> read: 50,000 | kept: 46,934 | removed: 3,066 | total kept: 7,536,633
Chunk 162 processed -> read: 50,000 | kept: 47,265 | removed: 2,735 | total kept: 7,583,898
Chunk 163 processed -> read: 50,000 | kept: 46,972 | removed: 3,028 | total kept: 7,630,870
Chunk 164 processed -> read: 50,000 | kept: 47,132 | removed: 2,868 | total kept: 7,678,002
Chunk 165 processed -> read: 50,000 | kept: 47,714 | removed: 2,286 | total kept: 7,725,716
Chunk 166 processed -> read: 50,000 | kept: 47,773 | removed: 2,227 | total kept: 7,773,489
Chunk 167 processed -> read: 50,000 | kept: 47,648 | removed: 2,352 | total kept: 7,821,137
Chunk 168 processed -> read: 50,000 | kept: 47,357 | removed: 2,643 | total kept: 7,868,494
Chunk 169 processed -> read: 50,000 | kept: 46,683 | removed: 3,317 | total kept: 7,915,177
Chunk 170 processed -> read: 50,000 | kept: 47,365 | removed: 2,635 | total kept: 7,962,542
Chunk 171 processed -> read: 50,000 | kept: 47,138 | removed: 2,862 | total kept: 8,009,680
Chunk 172 processed -> read: 50,000 | kept: 46,461 | removed: 3,539 | total kept: 8,056,141
Chunk 173 processed -> read: 50,000 | kept: 46,548 | removed: 3,452 | total kept: 8,102,689
Chunk 174 processed -> read: 50,000 | kept: 44,187 | removed: 5,813 | total kept: 8,146,876
Chunk 175 processed -> read: 50,000 | kept: 46,985 | removed: 3,015 | total kept: 8,193,861
Chunk 176 processed -> read: 50,000 | kept: 47,401 | removed: 2,599 | total kept: 8,241,262
Chunk 177 processed -> read: 50,000 | kept: 46,799 | removed: 3,201 | total kept: 8,288,061
Chunk 178 processed -> read: 50,000 | kept: 46,063 | removed: 3,937 | total kept: 8,334,124
Chunk 179 processed -> read: 50,000 | kept: 46,878 | removed: 3,122 | total kept: 8,381,002
Chunk 180 processed -> read: 50,000 | kept: 46,853 | removed: 3,147 | total kept: 8,427,855
Chunk 181 processed -> read: 50,000 | kept: 46,934 | removed: 3,066 | total kept: 8,474,789
Chunk 182 processed -> read: 50,000 | kept: 45,829 | removed: 4,171 | total kept: 8,520,618
Chunk 183 processed -> read: 50,000 | kept: 46,728 | removed: 3,272 | total kept: 8,567,346
Chunk 184 processed -> read: 50,000 | kept: 45,034 | removed: 4,966 | total kept: 8,612,380
Chunk 185 processed -> read: 50,000 | kept: 44,279 | removed: 5,721 | total kept: 8,656,659
Chunk 186 processed -> read: 50,000 | kept: 28,799 | removed: 21,201 | total kept: 8,685,458
Chunk 187 processed -> read: 50,000 | kept: 46,415 | removed: 3,585 | total kept: 8,731,873
Chunk 188 processed -> read: 50,000 | kept: 46,112 | removed: 3,888 | total kept: 8,777,985
Chunk 189 processed -> read: 50,000 | kept: 45,365 | removed: 4,635 | total kept: 8,823,350
Chunk 190 processed -> read: 50,000 | kept: 46,496 | removed: 3,504 | total kept: 8,869,846
Chunk 191 processed -> read: 50,000 | kept: 46,182 | removed: 3,818 | total kept: 8,916,028
Chunk 192 processed -> read: 50,000 | kept: 45,958 | removed: 4,042 | total kept: 8,961,986
Chunk 193 processed -> read: 50,000 | kept: 46,776 | removed: 3,224 | total kept: 9,008,762
Chunk 194 processed -> read: 50,000 | kept: 47,273 | removed: 2,727 | total kept: 9,056,035
Chunk 195 processed -> read: 50,000 | kept: 46,479 | removed: 3,521 | total kept: 9,102,514
Chunk 196 processed -> read: 50,000 | kept: 47,204 | removed: 2,796 | total kept: 9,149,718
Chunk 197 processed -> read: 50,000 | kept: 45,771 | removed: 4,229 | total kept: 9,195,489
Chunk 198 processed -> read: 50,000 | kept: 45,945 | removed: 4,055 | total kept: 9,241,434
Chunk 199 processed -> read: 50,000 | kept: 45,548 | removed: 4,452 | total kept: 9,286,982
Chunk 200 processed -> read: 50,000 | kept: 45,768 | removed: 4,232 | total kept: 9,332,750
Chunk 201 processed -> read: 50,000 | kept: 47,339 | removed: 2,661 | total kept: 9,380,089
Chunk 202 processed -> read: 50,000 | kept: 47,996 | removed: 2,004 | total kept: 9,428,085
Chunk 203 processed -> read: 50,000 | kept: 46,633 | removed: 3,367 | total kept: 9,474,718
Chunk 204 processed -> read: 50,000 | kept: 46,331 | removed: 3,669 | total kept: 9,521,049
Chunk 205 processed -> read: 50,000 | kept: 47,164 | removed: 2,836 | total kept: 9,568,213
Chunk 206 processed -> read: 50,000 | kept: 47,059 | removed: 2,941 | total kept: 9,615,272
Chunk 207 processed -> read: 50,000 | kept: 46,874 | removed: 3,126 | total kept: 9,662,146
Chunk 208 processed -> read: 50,000 | kept: 45,709 | removed: 4,291 | total kept: 9,707,855
Chunk 209 processed -> read: 50,000 | kept: 46,462 | removed: 3,538 | total kept: 9,754,317
Chunk 210 processed -> read: 50,000 | kept: 46,973 | removed: 3,027 | total kept: 9,801,290
Chunk 211 processed -> read: 50,000 | kept: 45,753 | removed: 4,247 | total kept: 9,847,043
Chunk 212 processed -> read: 50,000 | kept: 46,293 | removed: 3,707 | total kept: 9,893,336
Chunk 213 processed -> read: 50,000 | kept: 46,976 | removed: 3,024 | total kept: 9,940,312
Chunk 214 processed -> read: 50,000 | kept: 47,263 | removed: 2,737 | total kept: 9,987,575
Chunk 215 processed -> read: 50,000 | kept: 47,161 | removed: 2,839 | total kept: 10,034,736
Chunk 216 processed -> read: 50,000 | kept: 46,190 | removed: 3,810 | total kept: 10,080,926
Chunk 217 processed -> read: 50,000 | kept: 45,292 | removed: 4,708 | total kept: 10,126,218
Chunk 218 processed -> read: 50,000 | kept: 46,650 | removed: 3,350 | total kept: 10,172,868
Chunk 219 processed -> read: 50,000 | kept: 45,386 | removed: 4,614 | total kept: 10,218,254

PermissionError: [Errno 13] Permission denied: '..\\data\\processed\\DUPLICATES_ValeursFoncieres.csv'

In [ ]:
from pathlib import Path
import pandas as pd

INPUT_FILE = Path("../data/processed/NULLS_ValeursFoncieres.csv")
OUTPUT_FILE = Path("../data/processed/DUPLICATES_ValeursFoncieres.csv")

CHUNK_SIZE = 50_000

dtype_map = {
    "transaction_id": "string",
    "transaction_date": "string",
    "transaction_type": "string",
    "property_value": "float64",
    "street_number": "string",
    "btq_code": "string",
    "street_type": "string",
    "street_id": "string",
    "street_name": "string",
    "postal_code": "string",
    "com_name": "string",
    "dep_code": "string",
    "com_code": "string",
    "section_prefix": "string",
    "section": "string",
    "plot_number": "string",
    "volume_number": "string",
    "lot_1": "string",
    "lot_1_surface": "float64",
    "lot_2": "string",
    "lot_2_surface": "float64",
    "lot_3": "string",
    "lot_3_surface": "float64",
    "lot_4": "string",
    "lot_4_surface": "float64",
    "lot_5": "string",
    "lot_5_surface": "float64",
    "lots_count": "Int64",
    "property_type_code": "string",
    "property_type": "string",
    "building_real_surface": "float64",
    "main_rooms_count": "Int64",
    "land_nature": "string",
    "land_nature_special": "string",
    "land_surface": "float64",
    "surface_type": "string",
}

def remove_duplicates_chunked(input_file, output_file, chunk_size):
    output_file.parent.mkdir(parents=True, exist_ok=True)

    seen = set()
    first_write = True
    total_kept = 0

    for i, chunk in enumerate(
        pd.read_csv(
            input_file,
            chunksize=chunk_size,
            dtype=dtype_map,
            low_memory=False
        ),
        start=1
    ):
        # Convert rows to tuples (fast + consistent)
        rows = chunk.astype(str).agg(tuple, axis=1)

        # Keep first occurrence only
        mask = ~rows.isin(seen)
        chunk = chunk.loc[mask]

        # Update seen rows
        seen.update(rows[mask])

        total_kept += len(chunk)

        chunk.to_csv(
            output_file,
            mode="w" if first_write else "a",
            index=False,
            header=first_write,
            encoding="utf-8"
        )

        first_write = False

        print(f"Chunk {i} -> kept: {len(chunk):,} | total: {total_kept:,}")

    print("\nDone! Removed true duplicate rows")
    print(f"Saved file: {output_file}")
    print(f"Total rows written: {total_kept:,}")

remove_duplicates_chunked(INPUT_FILE, OUTPUT_FILE, CHUNK_SIZE)

Chunk 1 -> kept: 50,000 | total: 50,000
Chunk 2 -> kept: 50,000 | total: 100,000
Chunk 3 -> kept: 50,000 | total: 150,000
Chunk 4 -> kept: 50,000 | total: 200,000
Chunk 5 -> kept: 50,000 | total: 250,000
Chunk 6 -> kept: 50,000 | total: 300,000
Chunk 7 -> kept: 50,000 | total: 350,000
Chunk 8 -> kept: 49,999 | total: 399,999
Chunk 9 -> kept: 50,000 | total: 449,999
Chunk 10 -> kept: 50,000 | total: 499,999
Chunk 11 -> kept: 50,000 | total: 549,999
Chunk 12 -> kept: 49,992 | total: 599,991
Chunk 13 -> kept: 50,000 | total: 649,991
Chunk 14 -> kept: 50,000 | total: 699,991
Chunk 15 -> kept: 50,000 | total: 749,991
Chunk 16 -> kept: 50,000 | total: 799,991
Chunk 17 -> kept: 50,000 | total: 849,991
Chunk 18 -> kept: 50,000 | total: 899,991
Chunk 19 -> kept: 50,000 | total: 949,991
Chunk 20 -> kept: 50,000 | total: 999,991
Chunk 21 -> kept: 50,000 | total: 1,049,991
Chunk 22 -> kept: 50,000 | total: 1,099,991
Chunk 23 -> kept: 50,000 | total: 1,149,991
Chunk 24 -> kept: 50,000 | total: 1,199,991
Chunk 25 -> kept: 50,000 | total: 1,249,991
Chunk 26 -> kept: 50,000 | total: 1,299,991
Chunk 27 -> kept: 50,000 | total: 1,349,991
Chunk 28 -> kept: 50,000 | total: 1,399,991
Chunk 29 -> kept: 50,000 | total: 1,449,991
Chunk 30 -> kept: 50,000 | total: 1,499,991
Chunk 31 -> kept: 50,000 | total: 1,549,991
Chunk 32 -> kept: 50,000 | total: 1,599,991
Chunk 33 -> kept: 50,000 | total: 1,649,991
Chunk 34 -> kept: 50,000 | total: 1,699,991
Chunk 35 -> kept: 50,000 | total: 1,749,991
Chunk 36 -> kept: 50,000 | total: 1,799,991
Chunk 37 -> kept: 49,998 | total: 1,849,989
Chunk 38 -> kept: 50,000 | total: 1,899,989
Chunk 39 -> kept: 50,000 | total: 1,949,989
Chunk 40 -> kept: 49,955 | total: 1,999,944
Chunk 41 -> kept: 49,982 | total: 2,049,926
Chunk 42 -> kept: 50,000 | total: 2,099,926
Chunk 43 -> kept: 50,000 | total: 2,149,926
Chunk 44 -> kept: 49,995 | total: 2,199,921
Chunk 45 -> kept: 49,998 | total: 2,249,919
Chunk 46 -> kept: 50,000 | total: 2,299,919
Chunk 47 -> kept: 50,000 | total: 2,349,919
Chunk 48 -> kept: 50,000 | total: 2,399,919
Chunk 49 -> kept: 50,000 | total: 2,449,919
Chunk 50 -> kept: 50,000 | total: 2,499,919
Chunk 51 -> kept: 50,000 | total: 2,549,919
Chunk 52 -> kept: 50,000 | total: 2,599,919
Chunk 53 -> kept: 50,000 | total: 2,649,919
Chunk 54 -> kept: 50,000 | total: 2,699,919
Chunk 55 -> kept: 50,000 | total: 2,749,919
Chunk 56 -> kept: 50,000 | total: 2,799,919
Chunk 57 -> kept: 50,000 | total: 2,849,919
Chunk 58 -> kept: 50,000 | total: 2,899,919
Chunk 59 -> kept: 49,989 | total: 2,949,908
Chunk 60 -> kept: 50,000 | total: 2,999,908
Chunk 61 -> kept: 50,000 | total: 3,049,908
Chunk 62 -> kept: 50,000 | total: 3,099,908
Chunk 63 -> kept: 50,000 | total: 3,149,908
Chunk 64 -> kept: 50,000 | total: 3,199,908
Chunk 65 -> kept: 50,000 | total: 3,249,908
Chunk 66 -> kept: 50,000 | total: 3,299,908
Chunk 67 -> kept: 50,000 | total: 3,349,908
Chunk 68 -> kept: 50,000 | total: 3,399,908
Chunk 69 -> kept: 50,000 | total: 3,449,908
Chunk 70 -> kept: 50,000 | total: 3,499,908
Chunk 71 -> kept: 49,997 | total: 3,549,905
Chunk 72 -> kept: 49,998 | total: 3,599,903
Chunk 73 -> kept: 50,000 | total: 3,649,903
Chunk 74 -> kept: 50,000 | total: 3,699,903
Chunk 75 -> kept: 50,000 | total: 3,749,903
Chunk 76 -> kept: 50,000 | total: 3,799,903
Chunk 77 -> kept: 50,000 | total: 3,849,903
Chunk 78 -> kept: 50,000 | total: 3,899,903
Chunk 79 -> kept: 50,000 | total: 3,949,903
Chunk 80 -> kept: 50,000 | total: 3,999,903
Chunk 81 -> kept: 50,000 | total: 4,049,903
Chunk 82 -> kept: 49,999 | total: 4,099,902
Chunk 83 -> kept: 50,000 | total: 4,149,902
Chunk 84 -> kept: 50,000 | total: 4,199,902
Chunk 85 -> kept: 50,000 | total: 4,249,902
Chunk 86 -> kept: 50,000 | total: 4,299,902
Chunk 87 -> kept: 50,000 | total: 4,349,902
Chunk 88 -> kept: 50,000 | total: 4,399,902
Chunk 89 -> kept: 50,000 | total: 4,449,902
Chunk 90 -> kept: 50,000 | total: 4,499,902
Chunk 91 -> kept: 50,000 | total: 4,549,902
Chunk 92 -> kept: 50,000 | total: 4,599,902
Chunk 93 -> kept: 50,000 | total: 4,649,902
Chunk 94 -> kept: 49,998 | total: 4,699,900
Chunk 95 -> kept: 50,000 | total: 4,749,900
Chunk 96 -> kept: 50,000 | total: 4,799,900
Chunk 97 -> kept: 50,000 | total: 4,849,900
Chunk 98 -> kept: 50,000 | total: 4,899,900
Chunk 99 -> kept: 50,000 | total: 4,949,900
Chunk 100 -> kept: 49,999 | total: 4,999,899
Chunk 101 -> kept: 49,999 | total: 5,049,898
Chunk 102 -> kept: 50,000 | total: 5,099,898
Chunk 103 -> kept: 49,999 | total: 5,149,897
Chunk 104 -> kept: 50,000 | total: 5,199,897
Chunk 105 -> kept: 49,999 | total: 5,249,896
Chunk 106 -> kept: 50,000 | total: 5,299,896
Chunk 107 -> kept: 50,000 | total: 5,349,896
Chunk 108 -> kept: 50,000 | total: 5,399,896
Chunk 109 -> kept: 50,000 | total: 5,449,896
Chunk 110 -> kept: 50,000 | total: 5,499,896
Chunk 111 -> kept: 50,000 | total: 5,549,896
Chunk 112 -> kept: 50,000 | total: 5,599,896
Chunk 113 -> kept: 50,000 | total: 5,649,896
Chunk 114 -> kept: 50,000 | total: 5,699,896
Chunk 115 -> kept: 50,000 | total: 5,749,896
Chunk 116 -> kept: 50,000 | total: 5,799,896
Chunk 117 -> kept: 50,000 | total: 5,849,896
Chunk 118 -> kept: 50,000 | total: 5,899,896
Chunk 119 -> kept: 50,000 | total: 5,949,896

In [ ]:
# drop duplicates rows from df_nulls and keep only the first occurrence


dtype_map = {
    "transaction_id": "string",
    "transaction_date": "string",
    "transaction_type": "string",
    "property_value": "float64",
    "street_number": "string",
    "btq_code": "string",
    "street_type": "string",
    "street_id": "string",
    "street_name": "string",
    "postal_code": "string",
    "com_name": "string",
    "dep_code": "string",
    "com_code": "string",
    
    "section_prefix": "string",
    "section": "string",
    "plot_number": "string",
    "volume_number": "string",

    "lots_count": "Int64",
    "lots_surfaces_sum": "float64",
    ""
    "property_type_code": "string",
    "property_type": "string",
    "building_real_surface": "float64",
    "main_rooms_count": "Int64",
    "land_nature": "string",
    "land_nature_special": "string",
    "land_surface": "float64",
    "surface_type": "string",
}

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt

FILE = "../data/processed/CLEAN_ValeursFoncieres.csv"
CHUNK_SIZE = 50_000

# columns to include in correlation
cols = [
    "property_value",
    "property_type",
    "building_real_surface",
    "land_surface",
    "land_nature",
    "land_nature_special",
    "surface_type",
    "building_real_surface",
    "land_surface",
    "lots_count",
    "main_rooms_count",
    "lots_count",
    "com_name",
    "dep_code",
    "com_code",
    
    ""
]

# accumulate data
df_list = []

for chunk in pd.read_csv(FILE, chunksize=CHUNK_SIZE, usecols=cols):
    df_list.append(chunk)

# concatenate (safe because only few columns)
df = pd.concat(df_list, ignore_index=True)

# compute correlation
corr = df.corr(numeric_only=True)

# plot
plt.figure(figsize=(8,6))
plt.imshow(corr)
plt.colorbar()
plt.xticks(range(len(corr.columns)), corr.columns, rotation=45)
plt.yticks(range(len(corr.columns)), corr.columns)
plt.title("Correlation Matrix")
plt.show()

### **Dtype MAPPING**

In [ ]:

dtype_map = {
    "transaction_id": "string",
    "transaction_date": "string",
    "transaction_type": "string",
    "property_value": "float64",
    "street_number": "string",
    "btq_code": "string",
    "street_type": "string",
    "street_id": "string",
    "street_name": "string",
    "postal_code": "string",
    "com_name": "string",
    "dep_code": "string",
    "com_code": "string",
    "section_prefix": "string",
    "section": "string",
    "plot_number": "string",
    "volume_number": "string",
    "lot_1": "string",
    "lot_1_surface": "float64",
    "lot_2": "string",
    "lot_2_surface": "float64",
    "lot_3": "string",
    "lot_3_surface": "float64",
    "lot_4": "string",
    "lot_4_surface": "float64",
    "lot_5": "string",
    "lot_5_surface": "float64",
    "lots_count": "Int64",
    "property_type_code": "string",
    "property_type": "string",
    "building_real_surface": "float64",
    "main_rooms_count": "Int64",
    "land_nature": "string",
    "land_nature_special": "string",
    "land_surface": "float64",
    "surface_type": "string",
}

### **SHAPE & HEAD - AFTER Dealing with Duplicates**

In [ ]:
import pandas as pd

FILE = "../data/processed/DUPLICATES_ValeursFoncieres.csv"
CHUNK_SIZE = 50_000

total_rows = 0
columns = None

for chunk in pd.read_csv(FILE, chunksize=CHUNK_SIZE, dtype=dtype_map, low_memory=False):
    total_rows += len(chunk)
    if columns is None:
        columns = chunk.columns

print("Shape:", total_rows, "rows and", len(columns), "columns")

df_head = pd.read_csv(FILE, nrows=5, dtype=dtype_map, low_memory=False)
display(df_head)

# MACHINE LEARNING

In [ ]:
from pathlib import Path
import pandas as pd

INPUT_FILE = Path("../data/processed/CLEAN_ValeursFoncieres.csv")
OUTPUT_FILE = Path("../data/processed/ML_ValeursFoncieres.csv")

CHUNK_SIZE = 50_000


def preprocess_ml(chunk: pd.DataFrame) -> pd.DataFrame:
    # ---------------------------------------------------
    # Drop columns that leak target or are not useful
    # ---------------------------------------------------
    cols_to_drop = [
        "value_per_m2",      # TARGET LEAKAGE: property_value / property_surface
        "transaction_date",  # not needed for your app goal
        "com_name",          # free-text location label, redundant with codes
    ]

    chunk = chunk.drop(columns=[c for c in cols_to_drop if c in chunk.columns])

    # ---------------------------------------------------
    # Keep only rows where target exists
    # ---------------------------------------------------
    chunk = chunk.dropna(subset=["property_value"]).copy()

    return chunk


def process_ml_chunked(input_file: Path, output_file: Path, chunk_size: int = 50_000) -> None:
    output_file.parent.mkdir(parents=True, exist_ok=True)

    first_write = True
    total_rows = 0

    for i, chunk in enumerate(
        pd.read_csv(input_file, chunksize=chunk_size, low_memory=False),
        start=1
    ):
        chunk = preprocess_ml(chunk)

        chunk.to_csv(
            output_file,
            mode="w" if first_write else "a",
            index=False,
            header=first_write,
            encoding="utf-8"
        )

        first_write = False
        total_rows += len(chunk)

        print(f"Chunk {i} processed -> {len(chunk):,} rows | total: {total_rows:,}")

    print("\nDone! ML dataset created")
    print(f"Saved file: {output_file}")
    print(f"Total rows written: {total_rows:,}")


process_ml_chunked(INPUT_FILE, OUTPUT_FILE, CHUNK_SIZE)

---
# ANALYSIS

### CREATE ANALYSIS_ValeursFoncieres.csv

In [ ]:
from pathlib import Path
import pandas as pd
import numpy as np

INPUT_FILE = Path("../data/processed/CLEAN_ValeursFoncieres.csv")
OUTPUT_FILE = Path("../data/processed/ANALYSIS_ValeursFoncieres.csv")

CHUNK_SIZE = 50_000


def preprocess_analysis(chunk: pd.DataFrame) -> pd.DataFrame:

    # ---------------------------------------------------
    # DROP USELESS COLUMNS
    # ---------------------------------------------------
    cols_to_drop = [
        "transaction_id",
        "street_name",
        "street_id",
        "street_number",
        "btq_code",
        "plot_number",
        "volume_number",
        "section",
        "section_prefix",
        "lot_1", "lot_2", "lot_3", "lot_4", "lot_5",
        "lot_1_surface", "lot_2_surface", "lot_3_surface",
        "lot_4_surface", "lot_5_surface",
    ]

    chunk = chunk.drop(columns=[c for c in cols_to_drop if c in chunk.columns])

    # ---------------------------------------------------
    # FEATURE ENGINEERING (for analysis)
    # ---------------------------------------------------

    # Property surface
    chunk["property_surface"] = (
        chunk["building_real_surface"].fillna(0) +
        chunk["land_surface"].fillna(0)
    )

    # €/m²
    chunk["value_per_m2"] = chunk["property_value"] / chunk["property_surface"]

    # Avoid inf values
    chunk["value_per_m2"] = chunk["value_per_m2"].replace([np.inf, -np.inf], np.nan)

    # INSEE code (VERY IMPORTANT)
    chunk["insee_code"] = chunk["dep_code"] + chunk["com_code"]

    return chunk


def process_analysis_chunked(input_file, output_file, chunk_size):

    output_file.parent.mkdir(parents=True, exist_ok=True)

    first_write = True
    total_rows = 0

    for i, chunk in enumerate(
        pd.read_csv(input_file, chunksize=chunk_size),
        start=1
    ):
        chunk = preprocess_analysis(chunk)

        chunk.to_csv(
            output_file,
            mode="w" if first_write else "a",
            index=False,
            header=first_write,
            encoding="utf-8"
        )

        first_write = False
        total_rows += len(chunk)

        print(f"Chunk {i} processed -> {len(chunk):,} rows | total: {total_rows:,}")

    print("\nDone! ANALYSIS dataset created")
    print(f"Saved file: {output_file}")
    print(f"Total rows: {total_rows:,}")


process_analysis_chunked(INPUT_FILE, OUTPUT_FILE, CHUNK_SIZE)

- **👉 Where is cheapest?**
- **👉 Which property type is expensive?**
- **👉 Where is best €/m²?**
- **👉 How strong is surface vs price?**
- **👉 Which departments are overpriced?**

🧠 What we'll get:

📊 Market structure
- price distribution (skewed or not)
- surface distribution

📍 Location insights
- cheapest vs expensive departments

🏠 Property insights
- which property types are expensive
- which give best €/m²

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from collections import defaultdict

FILE = "../data/processed/ANALYSIS_ValeursFoncieres.csv"
CHUNK_SIZE = 100_000

# -----------------------------
# Aggregators
# -----------------------------
count_total = 0

sum_price = 0
sum_price_sq = 0

# Group stats
price_by_dep = defaultdict(float)
count_by_dep = defaultdict(int)

price_by_type = defaultdict(float)
count_by_type = defaultdict(int)

price_m2_sum = defaultdict(float)
price_m2_count = defaultdict(int)

# For histogram (approx)
price_sample = []
surface_sample = []
m2_sample = []

# -----------------------------
# Process chunks
# -----------------------------
for i, chunk in enumerate(pd.read_csv(FILE, chunksize=CHUNK_SIZE), start=1):

    # -------------------------
    # Feature engineering
    # -------------------------
    chunk["property_surface"] = (
        chunk["building_real_surface"].fillna(0) +
        chunk["land_surface"].fillna(0)
    )

    chunk["value_per_m2"] = chunk["property_value"] / chunk["property_surface"]
    chunk = chunk.replace([np.inf, -np.inf], np.nan)

    # -------------------------
    # Global stats
    # -------------------------
    valid_price = chunk["property_value"].dropna()

    count_total += len(valid_price)
    sum_price += valid_price.sum()
    sum_price_sq += (valid_price ** 2).sum()

    # -------------------------
    # Sample for histograms
    # -------------------------
    if len(price_sample) < 200_000:
        price_sample.extend(valid_price.values[:20_000])

    if len(surface_sample) < 200_000:
        surface_sample.extend(chunk["property_surface"].dropna().values[:20_000])

    if len(m2_sample) < 200_000:
        m2_sample.extend(chunk["value_per_m2"].dropna().values[:20_000])

    # -------------------------
    # Department aggregation
    # -------------------------
    grp_dep = chunk.groupby("dep_code")["property_value"].agg(["sum", "count"])
    for dep, row in grp_dep.iterrows():
        price_by_dep[dep] += row["sum"]
        count_by_dep[dep] += row["count"]

    # -------------------------
    # Property type aggregation
    # -------------------------
    grp_type = chunk.groupby("property_type")["property_value"].agg(["sum", "count"])
    for typ, row in grp_type.iterrows():
        price_by_type[typ] += row["sum"]
        count_by_type[typ] += row["count"]

    # -------------------------
    # €/m² aggregation
    # -------------------------
    valid = chunk.dropna(subset=["value_per_m2", "property_type"])
    grp_m2 = valid.groupby("property_type")["value_per_m2"].agg(["sum", "count"])

    for typ, row in grp_m2.iterrows():
        price_m2_sum[typ] += row["sum"]
        price_m2_count[typ] += row["count"]

    print(f"Chunk {i} processed")

# -----------------------------
# Final stats
# -----------------------------
mean_price = sum_price / count_total
std_price = np.sqrt((sum_price_sq / count_total) - mean_price**2)

print("\n===== GLOBAL STATS =====")
print(f"Mean price: {mean_price:,.0f} €")
print(f"Std price: {std_price:,.0f} €")

# -----------------------------
# Build series
# -----------------------------
df_dep = pd.Series({
    dep: price_by_dep[dep] / count_by_dep[dep]
    for dep in price_by_dep
}).sort_values()

df_type = pd.Series({
    typ: price_by_type[typ] / count_by_type[typ]
    for typ in price_by_type
}).sort_values()

df_m2 = pd.Series({
    typ: price_m2_sum[typ] / price_m2_count[typ]
    for typ in price_m2_sum
}).sort_values()

# -----------------------------
# PLOTS
# -----------------------------

# Price distribution
plt.figure(figsize=(10,5))
plt.hist(price_sample, bins=100)
plt.title("Property Value Distribution")
plt.show()

# Log price
plt.figure(figsize=(10,5))
plt.hist(np.log1p(price_sample), bins=100)
plt.title("Log Price Distribution")
plt.show()

# Surface distribution
plt.figure(figsize=(10,5))
plt.hist(surface_sample, bins=100)
plt.title("Surface Distribution")
plt.show()

# €/m² distribution
plt.figure(figsize=(10,5))
plt.hist(np.clip(m2_sample, 0, 20000), bins=100)
plt.title("€/m² Distribution")
plt.show()

# Price by department
df_dep.plot(kind="bar", figsize=(12,5))
plt.title("Average Price by Department")
plt.show()

# Price by property type
df_type.plot(kind="bar", figsize=(8,5))
plt.title("Average Price by Property Type")
plt.show()

# €/m² by type
df_m2.plot(kind="bar", figsize=(8,5))
plt.title("€/m² by Property Type")
plt.show()

🧠 Core idea

You don’t store all rows → you accumulate statistics

We’ll compute:

- distributions
- averages
- counts
- correlations (approx)
- price per m²
- group stats (location, property type)

### 🚀 1. Setup aggregators

In [ ]:
from collections import defaultdict
import pandas as pd
import numpy as np

FILE = "../data/processed/ANALYSIS_ValeursFoncieres.csv"
CHUNK_SIZE = 100_000

# Global aggregations
count_total = 0

# Numeric stats
sum_price = 0
sum_price_sq = 0

sum_surface = 0
sum_surface_sq = 0

# Group aggregations
price_by_dep = defaultdict(float)
count_by_dep = defaultdict(int)

price_by_type = defaultdict(float)
count_by_type = defaultdict(int)

price_per_m2_sum = defaultdict(float)
price_per_m2_count = defaultdict(int)

### 📦 2. Process chunks

In [ ]:
for chunk in pd.read_csv(FILE, chunksize=CHUNK_SIZE):

    # -------------------------
    # Basic cleanup
    # -------------------------
    chunk["property_surface"] = (
        chunk["building_real_surface"].fillna(0) +
        chunk["land_surface"].fillna(0)
    )

    chunk["value_per_m2"] = chunk["property_value"] / chunk["property_surface"]

    # Remove division issues
    chunk = chunk.replace([np.inf, -np.inf], np.nan)

    # -------------------------
    # Global stats
    # -------------------------
    valid_price = chunk["property_value"].dropna()
    valid_surface = chunk["property_surface"].dropna()

    count_total += len(valid_price)

    sum_price += valid_price.sum()
    sum_price_sq += (valid_price ** 2).sum()

    sum_surface += valid_surface.sum()
    sum_surface_sq += (valid_surface ** 2).sum()

    # -------------------------
    # Aggregation by department
    # -------------------------
    grp_dep = chunk.groupby("dep_code")["property_value"].agg(["sum", "count"])

    for dep, row in grp_dep.iterrows():
        price_by_dep[dep] += row["sum"]
        count_by_dep[dep] += row["count"]

    # -------------------------
    # Aggregation by property type
    # -------------------------
    grp_type = chunk.groupby("property_type")["property_value"].agg(["sum", "count"])

    for typ, row in grp_type.iterrows():
        price_by_type[typ] += row["sum"]
        count_by_type[typ] += row["count"]

    # -------------------------
    # €/m² aggregation
    # -------------------------
    valid = chunk.dropna(subset=["value_per_m2", "property_type"])

    grp_m2 = valid.groupby("property_type")["value_per_m2"].agg(["sum", "count"])

    for typ, row in grp_m2.iterrows():
        price_per_m2_sum[typ] += row["sum"]
        price_per_m2_count[typ] += row["count"]

    print(f"Processed {count_total:,} rows")

### 📊 3. Compute final stats

#### Global stats

In [ ]:
mean_price = sum_price / count_total
std_price = np.sqrt((sum_price_sq / count_total) - mean_price**2)

print("Mean price:", mean_price)
print("Std price:", std_price)

#### Department prices

In [ ]:
avg_price_dep = {
    dep: price_by_dep[dep] / count_by_dep[dep]
    for dep in price_by_dep
}

df_dep = pd.Series(avg_price_dep).sort_values()

#### Property type prices

In [ ]:
avg_price_type = {
    typ: price_by_type[typ] / count_by_type[typ]
    for typ in price_by_type
}

df_type = pd.Series(avg_price_type).sort_values()

#### €/m² by type

In [ ]:
avg_m2_type = {
    typ: price_per_m2_sum[typ] / price_per_m2_count[typ]
    for typ in price_per_m2_sum
}

df_m2 = pd.Series(avg_m2_type).sort_values()

### 📈 4. Plot results

#### Price by department

In [ ]:
import matplotlib.pyplot as plt

df_dep.plot(kind="bar", figsize=(12, 5))
plt.title("Average Price by Department")
plt.show()

#### Price by property type

In [ ]:
df_type.plot(kind="bar", figsize=(8, 5))
plt.title("Average Price by Property Type")
plt.show()

#### €/m² by property type

In [ ]:
df_m2.plot(kind="bar", figsize=(8, 5))
plt.title("€/m² by Property Type")
plt.show()

### INSEE-level aggregation (best for the streamlit app)

In [ ]:
price_by_insee = defaultdict(float)
count_by_insee = defaultdict(int)

for chunk in pd.read_csv(FILE, chunksize=CHUNK_SIZE):

    chunk["insee_code"] = chunk["dep_code"] + chunk["com_code"]

    grp = chunk.groupby("insee_code")["property_value"].agg(["sum", "count"])

    for code, row in grp.iterrows():
        price_by_insee[code] += row["sum"]
        count_by_insee[code] += row["count"]

### Then:

In [ ]:
price_by_insee = defaultdict(float)
count_by_insee = defaultdict(int)

for chunk in pd.read_csv(FILE, chunksize=CHUNK_SIZE):

    chunk["insee_code"] = chunk["dep_code"] + chunk["com_code"]

    grp = chunk.groupby("insee_code")["property_value"].agg(["sum", "count"])

    for code, row in grp.iterrows():
        price_by_insee[code] += row["sum"]
        count_by_insee[code] += row["count"]