<hr>

# 🧫 DATA CLEANING 


<style>
h1 {
    text-align: left;
    color: blue;
    font-weight: bold;
}

</style>
<hr>

<style>
h3 {
    margin-top: 0px;
    margin-bottom: 0px;
    font-weight: bold;
}
</style>

### 📂 IMPORTs

In [1]:
# import necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import display
import seaborn as sns

plt.style.use('ggplot')
pd.set_option('display.max_columns', 200) # to display all columns in the dataframe

<style>
h4 {
    margin-top: 0px;
    margin-bottom: 0px;
    font-weight: bold;
}
</style>

#### DISPLAY_DATA FUNCTION

In [ ]:
import pandas as pd
# define function display_data to explore each dataset
def display_data(df: pd.DataFrame):
    # ----------------------------------------
    # Display shape and head of the dataframe
    # ----------------------------------------
    print(f"{df.name} Dataset Shape: {df.shape[0]} rows and {df.shape[1]} columns\n")
    display(df.head(3))
    print(100*"-" + "\n")

    # ----------------------------------------------------------
    # Display data types & missing values of each column in df
    # ----------------------------------------------------------
    print("Data Types & Missing Values of Each Column:")
    display(df.info())

    # ---------------------------------------------------
    # Display Info & unique values for each column in df    
    # ---------------------------------------------------
    for col in df.columns:
        unique_vals = df[col].unique()
        print(f"Column: {col}")
        print(f"Unique values ({len(unique_vals)}): {unique_vals}\n")

    print(f"\nData types check:")
    for col in df.columns:
        dtype = df[col].dtype
        unique_vals = df[col].nunique()
        print(f"  ➡️{col:<25} {str(dtype):<10} [{unique_vals}] unique values")

<hr>

## 0 - DATA CLEANING OVERVIEW


<style>
h1 {
    text-align: center;
    color: black;
    font-weight: bold;
}
</style>

<style>
h2 {
    text-align: left;
    color: black;
    font-weight: bold;
}
</style>

<style>
h3 {
    text-align: left;
    color: black;
    font-weight: bold;
}
</style>

<style>
h4 {
    text-align: left;
    color: black;
    font-weight: bold;
}
</style>
<hr>

Note observations and changes to be made on the data:
- note a
- note b
- note c
- change 1
- change 2
- change 3

<hr>

## 1 - STANDARDIZE NAMES


<style>
h1 {
    text-align: center;
    color: black;
    font-weight: bold;
}
</style>

<style>
h2 {
    text-align: left;
    color: black;
    font-weight: bold;
}
</style>

<style>
h3 {
    text-align: left;
    color: black;
    font-weight: bold;
}
</style>

<style>
h4 {
    text-align: left;
    color: black;
    font-weight: bold;
}
</style>
<hr>

<style>
h4 {
    margin-top: 0px;
    margin-bottom: 0px;
    font-weight: bold;
}
</style>

#### ➕ COMBINE - 6 TXT FILES INTO 1 CSV
Dropped unnecessary columns

In [2]:
import pandas as pd

# List of DVF files
dvf_files = [
    "../data/raw/ValeursFoncieres-2020-S2.txt",
    "../data/raw/ValeursFoncieres-2021.txt",
    "../data/raw/ValeursFoncieres-2022.txt",
    "../data/raw/ValeursFoncieres-2023.txt",
    "../data/raw/ValeursFoncieres-2024.txt",
    "../data/raw/ValeursFoncieres-2025-S1.txt"
]

# Columns to keep
usecols = [
    "Date mutation",
    "Nature mutation",
    "Valeur fonciere",
    "Commune",
    "Type local",
    "Surface reelle bati",
    "Nombre pieces principales",
    "Nombre de lots",
    "Surface terrain", 
    "No voie",    # street number
    "B/T/Q",      # building / type / quartier
    "Voie",       # street name
    "Code postal" # postal code
]

# Output CSV
output_file = "../data/processed/RAW_ValeursFoncieres_2020-S2_2025-S1.csv"

# Fix mixed types
dtype_dict = {
    "Code postal": str,
    "Voie": str,
    "No voie": str,
    "B/T/Q": str,
    "Type local": str,
    "department_code": str,
    "surface_type": str

}

with open(output_file, "w", newline="", encoding="utf-8") as f_out:
    header_written = False

    for file in dvf_files:
        print(f"Processing: {file}")

        for chunk in pd.read_csv(
            file,
            sep="|",
            usecols=usecols,
            chunksize=50_000,
            encoding="latin-1",
            decimal=",",
            low_memory=False,
            dtype=dtype_dict
        ):
            # -------------------------
            # FIX ENCODING
            # -------------------------
            chunk["Type local"] = (
                chunk["Type local"]
                .astype(str)
                .str.encode("latin-1", errors="ignore")
                .str.decode("utf-8", errors="ignore")
                .str.strip()
            )

            # -------------------------
            # CONVERT NUMERIC
            # -------------------------
            chunk["Valeur fonciere"] = pd.to_numeric(chunk["Valeur fonciere"], errors="coerce")
            chunk["Surface reelle bati"] = pd.to_numeric(chunk["Surface reelle bati"], errors="coerce")
            chunk["Surface terrain"] = pd.to_numeric(chunk["Surface terrain"], errors="coerce")

            # Drop rows with missing price
            chunk = chunk.dropna(subset=["Valeur fonciere"])

            # -------------------------
            # PRICE PER M² (SMART FALLBACK)
            # -------------------------
            chunk["effective_surface"] = chunk["Surface reelle bati"]

            # If built surface is missing or zero → use terrain
            mask = chunk["effective_surface"].isna() | (chunk["effective_surface"] == 0)
            chunk.loc[mask, "effective_surface"] = chunk.loc[mask, "Surface terrain"]

            # Compute price per m²
            chunk["value_per_m2"] = chunk["Valeur fonciere"] / chunk["effective_surface"]

            # Clean invalid values
            chunk.loc[
                chunk["effective_surface"].isna() | (chunk["effective_surface"] == 0),
                "value_per_m2"
            ] = None

            # Optional: track which surface was used
            chunk["surface_type"] = "bati"
            chunk.loc[mask, "surface_type"] = "terrain"

            # -------------------------
            # EXTRACT DEPARTEMENT
            # -------------------------
            chunk["department_code"] = chunk["Code postal"].astype(str).str[:2]

            # -------------------------
            # WRITE TO CSV
            # -------------------------
            chunk.to_csv(
                f_out,
                index=False,
                header=not header_written
            )

            header_written = True
            del chunk  # free memory

print(f"✅ TXT Files aggregated & converted into one CSV File")
print(f"✅ CSV File saved at {output_file}")

Processing: ../data/raw/ValeursFoncieres-2020-S2.txt
Processing: ../data/raw/ValeursFoncieres-2021.txt
Processing: ../data/raw/ValeursFoncieres-2022.txt
Processing: ../data/raw/ValeursFoncieres-2023.txt
Processing: ../data/raw/ValeursFoncieres-2024.txt
Processing: ../data/raw/ValeursFoncieres-2025-S1.txt
✅ TXT Files aggregated & converted into one CSV File
✅ CSV File saved at ../data/processed/RAW_ValeursFoncieres_2020-S2_2025-S1.csv

### ⭐ **Valeurs Foncieres 2020-2025**
Standardize column names

| Original Column Name      |      Standardized      | Notes / Description                                           |
| ------------------------- | ---------------------- | ------------------------------------------------------------ |
| **Date mutation**             | `transaction_date`       | Date when the property was sold                        |
| **Nature mutation**           | `transaction_type`       | Nature of transaction (sale, donation, etc.)                 |
| **Valeur fonciere**           | `property_value`         | Transaction price in euros                                   |
| **No voie**                   | `street_number`          | Street number of the property                                |
| **B/T/Q**                     | `btq_code`               | Bâtiment / Type / Quartier code for identification           |
| **Voie**                      | `street_name`            | Full street name                                             |
| **Code postal**               | `postal_code`            | Postal code (categorical, not numeric)                       |
| **Commune**                   | `commune_name`                | Commune name                                                 |
| **Nombre de lots**            | `number_of_lots`         | Number of lots in the property                               |
| **Type local**                | `property_type`          | Property type (Apartment, House, etc.)                       |
| **Surface reelle bati**       | `building_real_surface`  | Built area in square meters                                  |
| **Nombre pieces principales** | `main_rooms_count`        | Number of main rooms (living / bedrooms)                     |
| **Surface terrain**           | `land_surface`           | Land area in square meters                                   |
| **effective_surface**              | `effective_surface`      | Surface used to calculate price/m² (building or land)        |
| **value_per_m2**                   | `value_per_m2`           | Value per m² in euros                                        |
| **surface_type**              | `surface_type`           | Indicates if effective_surface comes from a building or land |
| **departement**               | `department_code`        | 2-digit INSEE department code                                |

<style>
h4 {
    margin-top: 0px;
    margin-bottom: 0px;
    font-weight: bold;
}
</style>

#### DISPLAY HEAD - RAW Valeurs Foncieres

In [3]:
import pandas as pd
df = pd.read_csv("../data/processed/RAW_ValeursFoncieres_2020-S2_2025-S1.csv")

# Display df DataFrame
print("RAW Valeur Foncieres:")
display(df.head())
print("Dataset Shape:", df.shape[0], "rows and", df.shape[1], "columns\n")

C:\Users\sboub\AppData\Local\Temp\ipykernel_8064\3339224207.py:2: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../data/processed/RAW_ValeursFoncieres_2020-S2_2025-S1.csv")

RAW Valeur Foncieres:

,Date mutation,Nature mutation,Valeur fonciere,No voie,B/T/Q,Voie,Code postal,Commune,Nombre de lots,Type local,Surface reelle bati,Nombre pieces principales,Surface terrain,effective_surface,value_per_m2,surface_type,department_code
0,01/07/2020,Vente,31234.16,NaN,NaN,SAINT JULIEN,1560.0,SAINT-JULIEN-SUR-REYSSOUZE,0,NaN,NaN,NaN,1192.0,1192.0,26.203154,terrain,15
1,01/07/2020,Vente,278000.00,NaN,NaN,A LA PEROUSE,1250.0,CORVEISSIAT,0,NaN,NaN,NaN,10092.0,10092.0,27.546572,terrain,12
2,01/07/2020,Vente,278000.00,NaN,NaN,A LA PEROUSE,1250.0,CORVEISSIAT,0,NaN,NaN,NaN,4570.0,4570.0,60.831510,terrain,12
3,01/07/2020,Vente,278000.00,NaN,NaN,AUX COMMUNS,1250.0,CORVEISSIAT,0,NaN,NaN,NaN,5750.0,5750.0,48.347826,terrain,12
4,01/07/2020,Vente,278000.00,NaN,NaN,EN COMBARNAUD,1250.0,SIMANDRE-SUR-SURAN,0,NaN,NaN,NaN,648170.0,648170.0,0.428900,terrain,12

Dataset Shape: 19908349 rows and 17 columns

<style>
h4 {
    margin-top: 0px;
    margin-bottom: 0px;
    font-weight: bold;
}
</style>

#### DISPLAY UNIQUE VALUES - RAW Valeurs Foncieres

In [4]:
# Display data types & missing values of each column in df
print("Data Types & Missing Values of Each Column:")
display(df.info())

# Loop through each column and print unique values
for col in df.columns:
    unique_vals = df[col].unique()
    print(f"Column: {col}")
    print(f"Unique values ({len(unique_vals)}): {unique_vals}\n")

print(f"\nData types check:")
for col in df.columns:
    dtype = df[col].dtype
    unique_vals = df[col].nunique()
    print(f"  ➡️{col:<25} {str(dtype):<10} [{unique_vals}] unique values")

Data Types & Missing Values of Each Column:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19908349 entries, 0 to 19908348
Data columns (total 17 columns):
 #   Column                     Dtype
---  ------                     -----
 0   Date mutation              object
 1   Nature mutation            object
 2   Valeur fonciere            float64
 3   No voie                    float64
 4   B/T/Q                      object
 5   Voie                       object
 6   Code postal                float64
 7   Commune                    object
 8   Nombre de lots             int64
 9   Type local                 object
 10  Surface reelle bati        float64
 11  Nombre pieces principales  float64
 12  Surface terrain            float64
 13  effective_surface          float64
 14  value_per_m2               float64
 15  surface_type               object
 16  department_code            object
dtypes: float64(8), int64(1), object(8)
memory usage: 2.5+ GB

None

Column: Date mutation
Unique values (1804): ['01/07/2020' '04/07/2020' '02/07/2020' ... '01/05/2025' '18/05/2025'
 '05/01/2025']

Column: Nature mutation
Unique values (6): ['Vente' "Vente en l'Ã©tat futur d'achÃ¨vement"
 'Vente terrain Ã\xa0 bÃ¢tir' 'Echange' 'Adjudication' 'Expropriation']

Column: Valeur fonciere
Unique values (466667): [3.123416e+04 2.780000e+05 3.985000e+03 ... 7.088090e+05 5.503861e+05
 2.441758e+07]

Column: No voie
Unique values (9121): [  nan  347. 1084. ... 8562. 8301. 8423.]

Column: B/T/Q
Unique values (41): [nan 'B' 'C' 'A' 'F' 'L' 'T' 'X' 'O' 'Z' 'D' 'G' 'Q' 'Y' 'I' 'E' 'N' 'H'
 '1' 'W' 'V' 'U' 'S' 'R' 'P' 'M' 'K' 'J' '0' '5' '9' '8' 'b' '7' '2' '4'
 '3' '6' '-' '.' '*']

Column: Voie
Unique values (1125220): ['SAINT JULIEN' 'A LA PEROUSE' 'AUX COMMUNS' ... 'SAINT PIERRE AMELOT'
 'SAINT HONORE D EYLAU' 'DES FOSSES SAINT MARCEL']

Column: Code postal
Unique values (5872): [ 1560.  1250.  1310. ... 97380. 97314. 97330.]

Column: Commune
Unique values (31569): ['SAINT-JULIEN-SUR-REYSSOUZE' 'CORVEISSIAT' 'SIMANDRE-SUR-SURAN' ...
 'BEAUMONT SUR OISE' 'FRETTE SUR SEINE (LA)' 'CAMOPI']

Column: Nombre de lots
Unique values (123): [  0   1   2   3   7   5   4   6  13  12  11  42   8   9  15  20  10  14
 108  17  38  22  16  19  34  23  29  43  28  18  63  33  58  61  30  71
  26  50  83  37  27  90  92  31  49  40  81  53  51  21  54 119  24 150
  66  36 121 100  35  25  32  44  68 106  76  46 122  55  65  74  47  56
 141  75  72  45  60  39  48  79  57  62 126 116  98 175 111  73 138 103
  82 190  80 188  89  93  69  59 107  78  52 149  96 120  95 157 152 136
  91 110  64  41 139 132  94 125 105 161 101 236 114  70  85]

Column: Type local
Unique values (5): [nan 'Maison' 'Dépendance' 'Appartement'
 'Local industriel. commercial ou assimilé']

Column: Surface reelle bati
Unique values (9185): [   nan   115.     0. ...  8168. 28132.  8827.]

Column: Nombre pieces principales
Unique values (76): [ nan   2.   0.   5.   3.   4.   6.   1.   7.  15.   8.  10.   9.  11.
  19.  12.  13.  16.  20.  23.  17.  54.  30.  14.  18.  24.  44.  34.
  55.  22.  21.  40.  70.  35.  25.  51.  33.  26.  27.  71.  84. 109.
  38.  28.  32.  97.  53.  36.  43.  29.  31.  56.  57.  50.  89.  95.
  61.  41.  73.  63.  49.  90.  37.  62.  80.  78.  68.  42.  52.  39.
  64.  46. 198.  83.  77.  82.]

Column: Surface terrain
Unique values (85687): [  1192.  10092.   4570. ...  77614. 186988. 530850.]

Column: effective_surface
Unique values (85083): [  1192.  10092.   4570. ...  77614. 186988. 530850.]

Column: value_per_m2
Unique values (3967903): [   26.20315436    27.54657154    60.83150985 ... 20847.32352941
 13126.09259259 11710.34255319]

Column: surface_type
Unique values (2): ['terrain' 'bati']

Column: department_code
Unique values (95): ['15' '12' '13' '14' '10' '17' '11' 'na' '19' '18' '16' '28' '23' '22'
 '20' '21' '24' '27' '26' '25' '31' '34' '33' '32' '30' '35' '42' '36'
 '38' '37' '43' '41' '44' '51' '48' '45' '40' '47' '46' '62' '52' '55'
 '50' '53' '57' '56' '58' '54' '63' '60' '61' '67' '69' '64' '66' '65'
 '68' '73' '78' '71' '72' '77' '70' '74' '75' '76' '88' '80' '84' '82'
 '81' '83' '87' '86' '85' '95' '93' '91' '90' '92' '96' '94' '97' '98'
 '29' '39' '49' '59' '79' '89' 88 89 17 18 87]


Data types check:
  ➡️Date mutation             object     [1804] unique values
  ➡️Nature mutation           object     [6] unique values
  ➡️Valeur fonciere           float64    [466667] unique values
  ➡️No voie                   float64    [9120] unique values
  ➡️B/T/Q                     object     [40] unique values
  ➡️Voie                      object     [1125219] unique values
  ➡️Code postal               float64    [5871] unique values
  ➡️Commune                   object     [31569] unique values
  ➡️Nombre de lots            int64      [123] unique values
  ➡️Type local                object     [4] unique values
  ➡️Surface reelle bati       float64    [9184] unique values
  ➡️Nombre pieces principales float64    [75] unique values
  ➡️Surface terrain           float64    [85686] unique values
  ➡️effective_surface         float64    [85082] unique values
  ➡️value_per_m2              float64    [3967902] unique values
  ➡️surface_type              object     [2] unique values
  ➡️department_code           object     [95] unique values

<style>
h4 {
    margin-top: 0px;
    margin-bottom: 0px;
    font-weight: bold;
}
</style>

#### ✏️ RENAME - COLUMNS

In [5]:
import pandas as pd

# -------------------
# Load main dataset
# -------------------
df = pd.read_csv("../data/processed/RAW_ValeursFoncieres_2020-S2_2025-S1.csv")

# ---------------------------------------------
# Define the Renaming Dictionary
# ---------------------------------------------
rename_columns = {
    "Date mutation": "transaction_date",
    "Nature mutation": "transaction_type",
    "Valeur fonciere": "property_value",
    "No voie": "street_number",
    "B/T/Q": "btq_code",
    "Voie": "street_name",
    "Code postal": "postal_code",
    "Commune": "commune_name",
    "Nombre de lots": "number_of_lots",
    "Type local": "property_type",
    "Surface reelle bati": "building_real_surface",
    "Nombre pieces principales": "main_rooms_count",
    "Surface terrain": "land_surface",
    "surface_used": "effective_surface",
    "Prix_m2": "value_per_m2",
    "surface_type": "surface_type",
    "departement": "department_code"
}

# ---------------------------------------------
# Rename columns using the rename Dictionary
# ---------------------------------------------
df.rename(columns=rename_columns, inplace=True)

# --------------------------------
# Save dataset in a new CSV file
# --------------------------------
df.to_csv("../data/processed/INTERIM_01_standard_ValeursFoncieres.csv", index=False)

print(f"✅ Dataset standardized and saved at ../data/processed/INTERIM_01_standard_ValeursFoncieres.csv")

C:\Users\sboub\AppData\Local\Temp\ipykernel_8064\2975596484.py:6: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../data/processed/RAW_ValeursFoncieres_2020-S2_2025-S1.csv")

✅ Dataset standardized and saved at ../data/processed/INTERIM_01_standard_ValeursFoncieres.csv

In [ ]:
### ⭐ **Valeurs Foncieres 2020-2025**
Standardize column names

| Original Column Name      |      Standardized      | Notes / Description                                           |
| ------------------------- | ---------------------- | ------------------------------------------------------------ |
| Date mutation             | transaction_date       | Date when the property was sold                              |
| Nature mutation           | transaction_type       | Nature of transaction (sale, donation, etc.)                 |
| Valeur fonciere           | property_value         | Transaction price in euros                                   |
| No voie                   | street_number          | Street number of the property                                |
| B/T/Q                     | btq_code               | Bâtiment / Type / Quartier code for identification           |
| Voie                      | street_name            | Full street name                                             |
| Code postal               | postal_code            | Postal code (categorical, not numeric)                       |
| Commune                   | commune_name           | Commune name                                                 |
| Nombre de lots            | number_of_lots         | Number of lots in the property                               |
| Type local                | property_type          | Property type (Apartment, House, etc.)                       |
| Surface reelle bati       | building_real_surface  | Built area in square meters                                  |
| Nombre pieces principales | main_rooms_count       | Number of main rooms (living / bedrooms)                     |
| Surface terrain           | land_surface           | Land area in square meters                                   |
| surface_used              | effective_surface      | Surface used to calculate price/m² (building or land)        |
| Prix_m2                   | value_per_m2           | Value per m² in euros                                        |
| surface_type              | surface_type           | Indicates if effective_surface comes from a building or land |
| departement               | department_code        | 2-digit INSEE department code                                |

<style>
h4 {
    margin-top: 0px;
    margin-bottom: 0px;
    font-weight: bold;
}
</style>

#### 🟨 DISPLAY - Standard ValeursFoncieres

<hr>

## 2 - INVALID VALUES


<style>
h1 {
    text-align: center;
    color: black;
    font-weight: bold;
}
</style>

<style>
h2 {
    text-align: left;
    color: black;
    font-weight: bold;
}
</style>

<style>
h3 {
    text-align: left;
    color: black;
    font-weight: bold;
}
</style>

<style>
h4 {
    text-align: left;
    color: black;
    font-weight: bold;
}
</style>
<hr>

<style>
h4 {
    margin-top: 0px;
    margin-bottom: 0px;
    font-weight: bold;
}
</style>

#### LOAD & DISPLAY STANDARDIZED - Valeurs Foncieres

In [ ]:
import pandas as pd
df = pd.read_csv("../data/processed/INTERIM_01_standard_ValeursFoncieres.csv")
print("Standardized Valeurs Foncieres Dataset Shape:", df.shape[0], "rows and", df.shape[1], "columns")
display(df.head())

In [ ]:
# Display Standardized DataFrame
print("Standardized DataFrame:")
print(df.shape[0], "rows and", df.shape[1], "columns")
display(df.head())

# Display standardized column names
print("Standardized Column Names:")
display(df.info())

Standardized DataFrame:
19908349 rows and 17 columns

,transaction_date,transaction_type,property_value,street_number,btq_code,street_name,postal_code,commune_name,number_of_lots,property_type,building_real_surface,main_rooms_count,land_surface,effective_surface,value_per_m2,surface_type,department_code
0,01/07/2020,Vente,31234.16,NaN,NaN,SAINT JULIEN,1560.0,SAINT-JULIEN-SUR-REYSSOUZE,0,NaN,NaN,NaN,1192.0,1192.0,26.203154,terrain,15
1,01/07/2020,Vente,278000.00,NaN,NaN,A LA PEROUSE,1250.0,CORVEISSIAT,0,NaN,NaN,NaN,10092.0,10092.0,27.546572,terrain,12
2,01/07/2020,Vente,278000.00,NaN,NaN,A LA PEROUSE,1250.0,CORVEISSIAT,0,NaN,NaN,NaN,4570.0,4570.0,60.831510,terrain,12
3,01/07/2020,Vente,278000.00,NaN,NaN,AUX COMMUNS,1250.0,CORVEISSIAT,0,NaN,NaN,NaN,5750.0,5750.0,48.347826,terrain,12
4,01/07/2020,Vente,278000.00,NaN,NaN,EN COMBARNAUD,1250.0,SIMANDRE-SUR-SURAN,0,NaN,NaN,NaN,648170.0,648170.0,0.428900,terrain,12

Standardized Column Names:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19908349 entries, 0 to 19908348
Data columns (total 17 columns):
 #   Column                 Dtype
---  ------                 -----
 0   transaction_date       object
 1   transaction_type       object
 2   property_value         float64
 3   street_number          float64
 4   btq_code               object
 5   street_name            object
 6   postal_code            float64
 7   commune_name           object
 8   number_of_lots         int64
 9   property_type          object
 10  building_real_surface  float64
 11  main_rooms_count       float64
 12  land_surface           float64
 13  effective_surface      float64
 14  value_per_m2           float64
 15  surface_type           object
 16  department_code        object
dtypes: float64(8), int64(1), object(8)
memory usage: 2.5+ GB

None

<style>
h4 {
    margin-top: 0px;
    margin-bottom: 0px;
    font-weight: bold;
}
</style>

#### DISPLAY UNIQUE VALUES - Valeurs Foncieres

In [ ]:
# Loop through each column and print unique values
print(100 * "-")
for col in df.columns:
    unique_vals = df[col].unique()
    print(f"➡️ {col} ({len(unique_vals)}) 🧾 unique values:")
    print(f"{unique_vals}")
    print(100 * "-")

----------------------------------------------------------------------------------------------------
➡️ transaction_date (1804) 🧾 unique values:
['01/07/2020' '04/07/2020' '02/07/2020' ... '01/05/2025' '18/05/2025'
 '05/01/2025']
----------------------------------------------------------------------------------------------------
➡️ transaction_type (6) 🧾 unique values:
['Vente' "Vente en l'Ã©tat futur d'achÃ¨vement"
 'Vente terrain Ã\xa0 bÃ¢tir' 'Echange' 'Adjudication' 'Expropriation']
----------------------------------------------------------------------------------------------------
➡️ property_value (466667) 🧾 unique values:
[3.123416e+04 2.780000e+05 3.985000e+03 ... 7.088090e+05 5.503861e+05
 2.441758e+07]
----------------------------------------------------------------------------------------------------
➡️ street_number (9121) 🧾 unique values:
[  nan  347. 1084. ... 8562. 8301. 8423.]
----------------------------------------------------------------------------------------------------
➡️ btq_code (41) 🧾 unique values:
[nan 'B' 'C' 'A' 'F' 'L' 'T' 'X' 'O' 'Z' 'D' 'G' 'Q' 'Y' 'I' 'E' 'N' 'H'
 '1' 'W' 'V' 'U' 'S' 'R' 'P' 'M' 'K' 'J' '0' '5' '9' '8' 'b' '7' '2' '4'
 '3' '6' '-' '.' '*']
----------------------------------------------------------------------------------------------------
➡️ street_name (1125220) 🧾 unique values:
['SAINT JULIEN' 'A LA PEROUSE' 'AUX COMMUNS' ... 'SAINT PIERRE AMELOT'
 'SAINT HONORE D EYLAU' 'DES FOSSES SAINT MARCEL']
----------------------------------------------------------------------------------------------------
➡️ postal_code (5872) 🧾 unique values:
[ 1560.  1250.  1310. ... 97380. 97314. 97330.]
----------------------------------------------------------------------------------------------------
➡️ commune_name (31569) 🧾 unique values:
['SAINT-JULIEN-SUR-REYSSOUZE' 'CORVEISSIAT' 'SIMANDRE-SUR-SURAN' ...
 'BEAUMONT SUR OISE' 'FRETTE SUR SEINE (LA)' 'CAMOPI']
----------------------------------------------------------------------------------------------------
➡️ number_of_lots (123) 🧾 unique values:
[  0   1   2   3   7   5   4   6  13  12  11  42   8   9  15  20  10  14
 108  17  38  22  16  19  34  23  29  43  28  18  63  33  58  61  30  71
  26  50  83  37  27  90  92  31  49  40  81  53  51  21  54 119  24 150
  66  36 121 100  35  25  32  44  68 106  76  46 122  55  65  74  47  56
 141  75  72  45  60  39  48  79  57  62 126 116  98 175 111  73 138 103
  82 190  80 188  89  93  69  59 107  78  52 149  96 120  95 157 152 136
  91 110  64  41 139 132  94 125 105 161 101 236 114  70  85]
----------------------------------------------------------------------------------------------------
➡️ property_type (5) 🧾 unique values:
[nan 'Maison' 'Dépendance' 'Appartement'
 'Local industriel. commercial ou assimilé']
----------------------------------------------------------------------------------------------------
➡️ building_real_surface (9185) 🧾 unique values:
[   nan   115.     0. ...  8168. 28132.  8827.]
----------------------------------------------------------------------------------------------------
➡️ main_rooms_count (76) 🧾 unique values:
[ nan   2.   0.   5.   3.   4.   6.   1.   7.  15.   8.  10.   9.  11.
  19.  12.  13.  16.  20.  23.  17.  54.  30.  14.  18.  24.  44.  34.
  55.  22.  21.  40.  70.  35.  25.  51.  33.  26.  27.  71.  84. 109.
  38.  28.  32.  97.  53.  36.  43.  29.  31.  56.  57.  50.  89.  95.
  61.  41.  73.  63.  49.  90.  37.  62.  80.  78.  68.  42.  52.  39.
  64.  46. 198.  83.  77.  82.]
----------------------------------------------------------------------------------------------------
➡️ land_surface (85687) 🧾 unique values:
[  1192.  10092.   4570. ...  77614. 186988. 530850.]
----------------------------------------------------------------------------------------------------
➡️ effective_surface (85083) 🧾 unique values:
[  1192.  10092.   4570. ...  77614. 186988. 530850.]
----------------------------------------------------------------------------------------------------
➡️ value_per_m2 (3967903) 🧾 unique values:
[   26.20315436    27.54657154    60.83150985 ... 20847.32352941
 13126.09259259 11710.34255319]
----------------------------------------------------------------------------------------------------
➡️ surface_type (2) 🧾 unique values:
['terrain' 'bati']
----------------------------------------------------------------------------------------------------
➡️ department_code (95) 🧾 unique values:
['15' '12' '13' '14' '10' '17' '11' 'na' '19' '18' '16' '28' '23' '22'
 '20' '21' '24' '27' '26' '25' '31' '34' '33' '32' '30' '35' '42' '36'
 '38' '37' '43' '41' '44' '51' '48' '45' '40' '47' '46' '62' '52' '55'
 '50' '53' '57' '56' '58' '54' '63' '60' '61' '67' '69' '64' '66' '65'
 '68' '73' '78' '71' '72' '77' '70' '74' '75' '76' '88' '80' '84' '82'
 '81' '83' '87' '86' '85' '95' '93' '91' '90' '92' '96' '94' '97' '98'
 '29' '39' '49' '59' '79' '89' 88 89 17 18 87]
----------------------------------------------------------------------------------------------------

#### COMMUNES CSV (for consistency in commune_name values)

In [ ]:
df_communes = pd.read_csv("../data/raw/communes-france-2025.csv")
df_communes = df_communes.drop(columns=["Unnamed: 0"])
display(df_communes.head())
df_communes.info()

# Loop through each column and print unique values
print(100 * "-")
for col in df_communes.columns:
    unique_vals = df_communes[col].unique()
    print(f"➡️ {col} ({len(unique_vals)}) 🧾 unique values:")
    print(f"{unique_vals}")
    print(100 * "-")


# keep these columns
# code_insee
# nom_standard
# nom_sans_pronom
# nom_a
# nom_de
# nom_sans_accent
# nom_standard_majuscule
code_insee	nom_standard	nom_sans_pronom	nom_a	nom_de	nom_sans_accent	nom_standard_majuscule
reg_code
dep_code
dep_nom
code_postal

df_communes_clean = df_communes[["Nom officiel de la commune", "Code INSEE"]].copy()

C:\Users\sboub\AppData\Local\Temp\ipykernel_8064\3610903181.py:1: DtypeWarning: Columns (1,12,14,16,23,24) have mixed types. Specify dtype option on import or set low_memory=False.
  df_communes = pd.read_csv("../data/raw/communes-france-2025.csv")

,code_insee,nom_standard,nom_sans_pronom,nom_a,nom_de,nom_sans_accent,nom_standard_majuscule,typecom,typecom_texte,reg_code,reg_nom,dep_code,dep_nom,canton_code,canton_nom,epci_code,epci_nom,academie_code,academie_nom,code_postal,codes_postaux,zone_emploi,code_insee_centre_zone_emploi,code_unite_urbaine,nom_unite_urbaine,taille_unite_urbaine,type_commune_unite_urbaine,statut_commune_unite_urbaine,population,superficie_hectare,superficie_km2,densite,altitude_moyenne,altitude_minimale,altitude_maximale,latitude_mairie,longitude_mairie,latitude_centre,longitude_centre,grille_densite,grille_densite_texte,niveau_equipements_services,niveau_equipements_services_texte,gentile,url_wikipedia,url_villedereve
0,01001,L'Abergement-Clémenciat,Abergement-Clémenciat,à Abergement-Clémenciat,de l'Abergement-Clémenciat,l-abergement-clemenciat,L'ABERGEMENT-CLÉMENCIAT,COM,commune,84,Auvergne-Rhône-Alpes,01,Ain,0108,Châtillon-sur-Chalaronne,200069193,CC de la Dombes,10,Lyon,1400.0,01400,8405.0,01053,01000,NaN,0.0,HORS UNITE URBAINE,H,832,1565,16,53.0,242,206.0,272.0,46.151,4.921,46.153,4.926,6,Rural à habitat dispersé,0.0,communes non pôle,NaN,https://fr.wikipedia.org/wiki/fr:L'Abergement-...,https://villedereve.fr/ville/01001-l-abergemen...
1,01002,L'Abergement-de-Varey,Abergement-de-Varey,à Abergement-de-Varey,de l'Abergement-de-Varey,l-abergement-de-varey,L'ABERGEMENT-DE-VAREY,COM,commune,84,Auvergne-Rhône-Alpes,01,Ain,0101,Ambérieu-en-Bugey,240100883,CC de la Plaine de l'Ain,10,Lyon,1640.0,01640,8405.0,01053,01000,NaN,0.0,HORS UNITE URBAINE,H,267,912,9,29.0,483,290.0,748.0,46.007,5.423,46.009,5.428,6,Rural à habitat dispersé,0.0,communes non pôle,"Abergementais, Abergementaises",https://fr.wikipedia.org/wiki/fr:L'Abergement-...,https://villedereve.fr/ville/01002-l-abergemen...
2,01004,Ambérieu-en-Bugey,Ambérieu-en-Bugey,à Ambérieu-en-Bugey,d'Ambérieu-en-Bugey,amberieu-en-bugey,AMBÉRIEU-EN-BUGEY,COM,commune,84,Auvergne-Rhône-Alpes,01,Ain,0101,Ambérieu-en-Bugey,240100883,CC de la Plaine de l'Ain,10,Lyon,1500.0,"01500, 01501, 01504, 01503, 01502, 01505, 01506",8405.0,01053,01303,Ambérieu-en-Bugey,3.0,UNITE URBAINE,C,14854,2448,24,607.0,379,237.0,753.0,45.958,5.360,45.961,5.373,2,Centres urbains intermédiaires,3.0,centres structurants d'équipements et de services,"Ambarrois, Ambarroises",https://fr.wikipedia.org/wiki/fr:Ambérieu-en-B...,https://villedereve.fr/ville/01004-amberieu-en...
3,01005,Ambérieux-en-Dombes,Ambérieux-en-Dombes,à Ambérieux-en-Dombes,d'Ambérieux-en-Dombes,amberieux-en-dombes,AMBÉRIEUX-EN-DOMBES,COM,commune,84,Auvergne-Rhône-Alpes,01,Ain,0122,Villars-les-Dombes,200042497,CC Dombes Saône Vallée,10,Lyon,1330.0,01330,8434.0,69264,01000,NaN,0.0,HORS UNITE URBAINE,H,1897,1605,16,118.0,290,265.0,302.0,45.996,4.903,45.996,4.912,5,Bourgs ruraux,1.0,centres locaux d'équipements et de services,Ambarrois,https://fr.wikipedia.org/wiki/fr:Ambérieux-en-...,https://villedereve.fr/ville/01005-amberieux-e...
4,01006,Ambléon,Ambléon,à Ambléon,d'Ambléon,ambleon,AMBLÉON,COM,commune,84,Auvergne-Rhône-Alpes,01,Ain,0104,Belley,200040350,CC Bugey Sud,10,Lyon,1300.0,01300,8404.0,01034,01000,NaN,0.0,HORS UNITE URBAINE,H,113,602,6,19.0,589,330.0,940.0,45.748,5.601,45.750,5.594,6,Rural à habitat dispersé,0.0,communes non pôle,Ambléonais,https://fr.wikipedia.org/wiki/fr:Ambléon,https://villedereve.fr/ville/01006-ambleon

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34935 entries, 0 to 34934
Data columns (total 46 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   code_insee                         34935 non-null  object
 1   nom_standard                       34935 non-null  object
 2   nom_sans_pronom                    34935 non-null  object
 3   nom_a                              34935 non-null  object
 4   nom_de                             34935 non-null  object
 5   nom_sans_accent                    34935 non-null  object
 6   nom_standard_majuscule             34935 non-null  object
 7   typecom                            34935 non-null  object
 8   typecom_texte                      34935 non-null  object
 9   reg_code                           34935 non-null  int64
 10  reg_nom                            34935 non-null  object
 11  dep_code                           34935 non-null  object
 12  dep_nom                            34935 non-null  object
 13  canton_code                        34879 non-null  object
 14  canton_nom                         34879 non-null  object
 15  epci_code                          34932 non-null  object
 16  epci_nom                           34932 non-null  object
 17  academie_code                      34935 non-null  int64
 18  academie_nom                       34935 non-null  object
 19  code_postal                        34932 non-null  float64
 20  codes_postaux                      34932 non-null  object
 21  zone_emploi                        34932 non-null  float64
 22  code_insee_centre_zone_emploi      34803 non-null  object
 23  code_unite_urbaine                 34932 non-null  object
 24  nom_unite_urbaine                  7576 non-null   object
 25  taille_unite_urbaine               34932 non-null  float64
 26  type_commune_unite_urbaine         34932 non-null  object
 27  statut_commune_unite_urbaine       34932 non-null  object
 28  population                         34935 non-null  int64
 29  superficie_hectare                 34935 non-null  int64
 30  superficie_km2                     34935 non-null  int64
 31  densite                            34932 non-null  float64
 32  altitude_moyenne                   34935 non-null  int64
 33  altitude_minimale                  34935 non-null  float64
 34  altitude_maximale                  34935 non-null  float64
 35  latitude_mairie                    34935 non-null  float64
 36  longitude_mairie                   34935 non-null  float64
 37  latitude_centre                    34926 non-null  float64
 38  longitude_centre                   34926 non-null  float64
 39  grille_densite                     34935 non-null  int64
 40  grille_densite_texte               34935 non-null  object
 41  niveau_equipements_services        34803 non-null  float64
 42  niveau_equipements_services_texte  34803 non-null  object
 43  gentile                            24065 non-null  object
 44  url_wikipedia                      34878 non-null  object
 45  url_villedereve                    34935 non-null  object
dtypes: float64(11), int64(7), object(28)
memory usage: 12.3+ MB
----------------------------------------------------------------------------------------------------
➡️ code_insee (34935) 🧾 unique values:
['01001' '01002' '01004' ... 97615 97616 97617]
----------------------------------------------------------------------------------------------------
➡️ nom_standard (32688) 🧾 unique values:
["L'Abergement-Clémenciat" "L'Abergement-de-Varey" 'Ambérieu-en-Bugey' ...
 'Pamandzi' 'Sada' 'Tsingoni']
----------------------------------------------------------------------------------------------------
➡️ nom_sans_pronom (32535) 🧾 unique values:
['Abergement-Clémenciat' 'Abergement-de-Varey' 'Ambérieu-en-Bugey' ...
 'Pamandzi' 'Sada' 'Tsingoni']
----------------------------------------------------------------------------------------------------
➡️ nom_a (32637) 🧾 unique values:
['à Abergement-Clémenciat' 'à Abergement-de-Varey' 'à Ambérieu-en-Bugey'
 ... 'à Pamandzi' 'à Sada' 'à Tsingoni']
----------------------------------------------------------------------------------------------------
➡️ nom_de (32698) 🧾 unique values:
["de l'Abergement-Clémenciat" "de l'Abergement-de-Varey"
 "d'Ambérieu-en-Bugey" ... 'de Pamandzi' 'de Sada' 'de Tsingoni']
----------------------------------------------------------------------------------------------------
➡️ nom_sans_accent (32630) 🧾 unique values:
['l-abergement-clemenciat' 'l-abergement-de-varey' 'amberieu-en-bugey' ...
 'pamandzi' 'sada' 'tsingoni']
----------------------------------------------------------------------------------------------------
➡️ nom_standard_majuscule (32688) 🧾 unique values:
["L'ABERGEMENT-CLÉMENCIAT" "L'ABERGEMENT-DE-VAREY" 'AMBÉRIEU-EN-BUGEY' ...
 'PAMANDZI' 'SADA' 'TSINGONI']
----------------------------------------------------------------------------------------------------
➡️ typecom (1) 🧾 unique values:
['COM']
----------------------------------------------------------------------------------------------------
➡️ typecom_texte (1) 🧾 unique values:
['commune']
----------------------------------------------------------------------------------------------------
➡️ reg_code (18) 🧾 unique values:
[84 32 93 44 76 28 75 24 27 53 94 52 11  1  2  3  4  6]
----------------------------------------------------------------------------------------------------
➡️ reg_nom (18) 🧾 unique values:
['Auvergne-Rhône-Alpes' 'Hauts-de-France' "Provence-Alpes-Côte d'Azur"
 'Grand Est' 'Occitanie' 'Normandie' 'Nouvelle-Aquitaine'
 'Centre-Val de Loire' 'Bourgogne-Franche-Comté' 'Bretagne' 'Corse'
 'Pays de la Loire' 'Île-de-France' 'Guadeloupe' 'Martinique' 'Guyane'
 'La Réunion' 'Mayotte']
----------------------------------------------------------------------------------------------------
➡️ dep_code (102) 🧾 unique values:
['01' '02' '03' '04' '05' '06' '07' '08' '09' '10' '11' '12' '13' '14'
 '15' '16' '17' '18' '19' '21' '22' '23' '24' '25' '26' '27' '28' '29'
 '2A' '2B' '30' '31' '32' '33' '34' '35' '36' '37' '38' '39' '40' '41'
 '42' '43' '44' 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62
 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86
 87 88 89 90 91 92 93 94 95 971 972 973 974 976]
----------------------------------------------------------------------------------------------------
➡️ dep_nom (101) 🧾 unique values:
['Ain' 'Aisne' 'Allier' 'Alpes-de-Haute-Provence' 'Hautes-Alpes'
 'Alpes-Maritimes' 'Ardèche' 'Ardennes' 'Ariège' 'Aube' 'Aude' 'Aveyron'
 'Bouches-du-Rhône' 'Calvados' 'Cantal' 'Charente' 'Charente-Maritime'
 'Cher' 'Corrèze' "Côte-d'Or" "Côtes-d'Armor" 'Creuse' 'Dordogne' 'Doubs'
 'Drôme' 'Eure' 'Eure-et-Loir' 'Finistère' 'Corse-du-Sud' 'Haute-Corse'
 'Gard' 'Haute-Garonne' 'Gers' 'Gironde' 'Hérault' 'Ille-et-Vilaine'
 'Indre' 'Indre-et-Loire' 'Isère' 'Jura' 'Landes' 'Loir-et-Cher' 'Loire'
 'Haute-Loire' 'Loire-Atlantique' 'Loiret' 'Lot' 'Lot-et-Garonne' 'Lozère'
 'Maine-et-Loire' 'Manche' 'Marne' 'Haute-Marne' 'Mayenne'
 'Meurthe-et-Moselle' 'Meuse' 'Morbihan' 'Moselle' 'Nièvre' 'Nord' 'Oise'
 'Orne' 'Pas-de-Calais' 'Puy-de-Dôme' 'Pyrénées-Atlantiques'
 'Hautes-Pyrénées' 'Pyrénées-Orientales' 'Bas-Rhin' 'Haut-Rhin' 'Rhône'
 'Haute-Saône' 'Saône-et-Loire' 'Sarthe' 'Savoie' 'Haute-Savoie' 'Paris'
 'Seine-Maritime' 'Seine-et-Marne' 'Yvelines' 'Deux-Sèvres' 'Somme' 'Tarn'
 'Tarn-et-Garonne' 'Var' 'Vaucluse' 'Vendée' 'Vienne' 'Haute-Vienne'
 'Vosges' 'Yonne' 'Territoire de Belfort' 'Essonne' 'Hauts-de-Seine'
 'Seine-Saint-Denis' 'Val-de-Marne' "Val-d'Oise" 'Guadeloupe' 'Martinique'
 'Guyane' 'La Réunion' 'Mayotte']
----------------------------------------------------------------------------------------------------
➡️ canton_code (2055) 🧾 unique values:
['0108' '0101' '0122' ... 97699.0 97613.0 97611.0]
----------------------------------------------------------------------------------------------------
➡️ canton_nom (2024) 🧾 unique values:
['Châtillon-sur-Chalaronne' 'Ambérieu-en-Bugey' 'Villars-les-Dombes' ...
 'Mamoudzou' 'Tsingoni' 'Pamandzi']
----------------------------------------------------------------------------------------------------
➡️ epci_code (1287) 🧾 unique values:
['200069193' '240100883' '200042497' ... 200059871 200060457 200050532]
----------------------------------------------------------------------------------------------------
➡️ epci_nom (1255) 🧾 unique values:
['CC de la Dombes' "CC de la Plaine de l'Ain" 'CC Dombes Saône Vallée' ...
 'CC du Centre-Ouest' 'CA de Dembeni / Mamoudzou' 'CC de Petite-Terre']
----------------------------------------------------------------------------------------------------
➡️ academie_code (30) 🧾 unique values:
[10 20  6  2 23  8 19 16 11 70 13 18 22  7 14  4  3 27 17 12  9 15  1 24
 25 32 31 33 28 43]
----------------------------------------------------------------------------------------------------
➡️ academie_nom (30) 🧾 unique values:
['Lyon' 'Amiens' 'Clermont-Ferrand' 'Aix-Marseille' 'Nice' 'Grenoble'
 'Reims' 'Toulouse' 'Montpellier' 'Normandie' 'Poitiers' 'Orléans-Tours'
 'Limoges' 'Dijon' 'Rennes' 'Bordeaux' 'Besançon' 'Corse' 'Nantes'
 'Nancy-Metz' 'Lille' 'Strasbourg' 'Paris' 'Créteil' 'Versailles'
 'Guadeloupe' 'Martinique' 'Guyane' 'La Réunion' 'Mayotte']
----------------------------------------------------------------------------------------------------
➡️ code_postal (6012) 🧾 unique values:
[ 1400.  1640.  1500. ... 97600. 97640. 97680.]
----------------------------------------------------------------------------------------------------
➡️ codes_postaux (8289) 🧾 unique values:
['01400' '01640' '01500, 01501, 01504, 01503, 01502, 01505, 01506' ...
 '97680, 97650, 97605, 97600' '97640' '97680']
----------------------------------------------------------------------------------------------------
➡️ zone_emploi (307) 🧾 unique values:
[8405. 8434. 8404. 8416. 8425.   59. 8421. 3220. 3221. 3214. 3217. 3209.
 8432. 8424. 8423. 9307. 9311. 9315. 9310. 9306. 9304. 9302. 9314. 8420.
 8402. 8422. 8431. 8433. 8419.   55. 4413. 4403. 4421. 7612. 7622. 7608.
 7625. 4425. 4427. 4415. 7617. 7610. 7620. 7621. 7614. 7611. 7602. 9301.
 9312. 9313.   52.   53. 2811. 2804. 2814. 2818. 2816. 2809. 8429.   63.
 8403. 8410. 7527. 7502. 7509. 7523. 7516. 7512. 7525. 7528. 7526. 7520.
 7505. 2402.   60. 2407.   56. 2405. 2415. 7531. 7507. 7517. 2704. 2711.
 2709. 2701. 2712. 2702. 5316. 5307. 5304. 5306. 5308. 5303. 5312. 5317.
 5310. 7511. 7529. 7504. 7532. 2706. 2718. 2714. 2715. 2716. 2713.   64.
 8427. 2803.   57. 2808. 2817. 2815. 2812. 2403. 2404.   61. 2410. 5302.
 5314. 5313. 9401. 9407. 9406. 9405. 9404. 9403. 9402. 7618. 7616. 7605.
 7603. 7604. 7615. 7624. 7609. 7514. 7513. 7515. 7518. 7606. 7601. 7623.
 5315. 5305. 5319.   62. 5311. 2412. 2408. 2413. 2406. 8406. 8409. 8435.
 7519. 7510. 7503. 7501. 7522. 2414. 2401. 8428. 8412. 8426. 8430. 8417.
 5205. 5216. 5201. 5217. 5219. 5203. 2409. 2411. 7607. 7619. 7613. 5220.
 5202. 5221. 5206. 5209. 5218. 2806. 2810. 2805. 2802. 4402. 4406. 4404.
 5211. 5215. 5204.   51. 4412. 4410. 4424. 4419. 4417. 4401. 4426. 5318.
 5301. 5309. 4416. 4420. 4408. 2703. 2708. 3208. 3222. 3216. 3212. 3213.
 3219. 3218. 3205.   54. 3211. 3210.   nan 2801. 3215. 3203. 3204. 3207.
 3206. 8408. 7521. 4423. 4422. 4409. 4405. 4411. 4418. 2705. 2707. 2710.
 5212. 5208. 8407. 8413. 8401. 8411. 8418. 8415. 8414. 1109. 2819. 2807.
 2813.   58. 1105. 1102. 1108. 1107. 1110. 1106. 1104. 1112. 1111. 1114.
 1115. 1101. 7506. 7530. 7524. 3201. 3202. 9308. 9309. 9318. 9303. 9317.
 9305. 9316. 5207. 5210. 5214. 5213. 7508. 4407. 4414. 2717. 1103. 1113.
  104.  102.  105.  101.  103.  203.  206.  204.  202.  205.  201.  301.
  303.  302.  404.  401.  402.  403.  601.]
----------------------------------------------------------------------------------------------------
➡️ code_insee_centre_zone_emploi (374) 🧾 unique values:
['01053' '69264' '01034' '74012' '01283' '71270' '69123' '02691' '02722'
 '02408' '59392' '02168' '03310' '03190' '03185' '04070' '04112' '06088'
 '05061' '84035' '06029' '05023' '06083' '43137' '07019' '26198' '26362'
 '38544' '43157' '84019' '51454' '08105' '08409' '09225' '31483' '11069'
 '31555' '10387' '52448' '10323' '11262' '81065' '66136' '12202' '12145'
 '12300' '81004' '13001' '13055' '13056' '13004' '84007' '27467' '14118'
 '14366' '14762' '50502' '61169' '15187' '19275' '15014' '63178' '87154'
 '16015' '16102' '24322' '33243' '17300' '17299' '17415' '17306' '79191'
 '33063' '18033' '58194' '45155' '58086' '36044' '18279' '19272' '19031'
 '87085' '21054' '21231' '21154' '71014' '39198' '89024' '22278' '22093'
 '22050' '22070' '22113' '29024' '56178' '35288' '29151' '23096' '24520'
 '24037' '47323' '25056' '70550' '25388' '25462' '39478' '39300' '84138'
 '26281' '27056' '28134' '27229' '27681' '76540' '61214' '28085' '28088'
 '28280' '45234' '29019' '29233' '29232' '2A004' '2A249' '2A247' '2B123'
 '2B096' '2B050' '2B033' '30189' '34172' '30028' '30007' '32013' '82121'
 '65440' '82033' '33227' '33529' '33240' '47157' '34032' '34003' '34301'
 '35238' '35115' '35360' '35236' '56165' '41194' '37132' '37261' '37072'
 '38053' '38185' '38563' '40192' '40088' '64102' '47001' '64445' '41269'
 '41018' '42218' '42147' '42187' '69243' '63430' '44036' '44109' '49244'
 '44131' '44184' '85047' 85047.0 49244.0 44036.0 44109.0 44184.0 45155.0
 45208.0 45252.0 45234.0 46042.0 46128.0 12300.0 47001.0 47157.0 47323.0
 24037.0 48095.0 30007.0 49328.0 49007.0 49331.0 49099.0 72154.0 72264.0
 50502.0 50147.0 50218.0 50129.0 50025.0 14762.0 61169.0 51108.0 51230.0
 10323.0 52448.0 51454.0 52121.0 53130.0 53147.0 53062.0 61001.0 54395.0
 57463.0 57672.0 57630.0 88413.0 8409.0 55029.0 55545.0 35236.0 56260.0
 56165.0 56007.0 56178.0 56121.0 22093.0 29024.0 29233.0 57606.0 57631.0
 57227.0 58194.0 58086.0 89025.0 71342.0 71014.0 89024.0 59122.0 59606.0
 59392.0 59350.0 59178.0 59183.0 59295.0 59599.0 62119.0 60057.0 2722.0
 60175.0 60159.0 nan 61006.0 28280.0 61214.0 14366.0 62498.0 62041.0
 62108.0 62193.0 62160.0 63113.0 63430.0 63178.0 3185.0 19275.0 3310.0
 64445.0 64422.0 64102.0 40088.0 40192.0 65440.0 31483.0 32013.0 66136.0
 67482.0 67462.0 67180.0 68066.0 68224.0 68297.0 69243.0 69264.0 69123.0
 38544.0 42218.0 70550.0 25056.0 90010.0 21231.0 25388.0 71270.0 71076.0
 39198.0 71153.0 39300.0 21054.0 72181.0 72132.0 73065.0 73011.0 74010.0
 73248.0 38053.0 1034.0 74256.0 74281.0 74012.0 74081.0 75056.0 76758.0
 76217.0 76540.0 76351.0 76255.0 77305.0 77131.0 77288.0 77284.0 77379.0
 77108.0 91228.0 93005.0 78517.0 78586.0 78646.0 95127.0 79049.0 79191.0
 79329.0 86194.0 80001.0 2691.0 80021.0 81065.0 81004.0 31555.0 82121.0
 82033.0 6029.0 83050.0 13001.0 83061.0 83137.0 83023.0 4070.0 83115.0
 4112.0 13055.0 84007.0 84035.0 84031.0 84138.0 84019.0 84087.0 85092.0
 85191.0 85194.0 85146.0 87154.0 86066.0 16015.0 87085.0 23096.0 19272.0
 88160.0 88196.0 89387.0 91223.0 91377.0]
----------------------------------------------------------------------------------------------------
➡️ code_unite_urbaine (2612) 🧾 unique values:
['01000' '01303' '01402' ... '9F301' '9F303' '9F304']
----------------------------------------------------------------------------------------------------
➡️ nom_unite_urbaine (2459) 🧾 unique values:
[nan 'Ambérieu-en-Bugey' 'Oyonnax' ... 'Ouangani' 'Sada' 'Tsingoni']
----------------------------------------------------------------------------------------------------
➡️ taille_unite_urbaine (10) 🧾 unique values:
[ 0.  3.  4.  1.  2.  7.  5.  6. nan  8.]
----------------------------------------------------------------------------------------------------
➡️ type_commune_unite_urbaine (3) 🧾 unique values:
['HORS UNITE URBAINE' 'UNITE URBAINE' nan]
----------------------------------------------------------------------------------------------------
➡️ statut_commune_unite_urbaine (5) 🧾 unique values:
['H' 'C' 'B' 'I' nan]
----------------------------------------------------------------------------------------------------
➡️ population (5868) 🧾 unique values:
[  832   267 14854 ...  6432 10203 11156]
----------------------------------------------------------------------------------------------------
➡️ superficie_hectare (5198) 🧾 unique values:
[ 1565   912  2448 ... 18102  8439  3769]
----------------------------------------------------------------------------------------------------
➡️ superficie_km2 (199) 🧾 unique values:
[   16     9    24     6    34     5     7    29    15    22    14    13
    18     8     3    19    40     1    23    20    11    12    26    17
     4    10    33    32    46    27    21    28    51    30     2    25
    36    42    45     0    49    54    60    64    35    47    55    44
    37    48    31    71    50    41    39    72    53    58    57    38
    43   117   126   122    82    56   110    61    70   108    67    65
    90   167   128   206    86    68    99   109   136    78    73    96
   102    92    91   123   127   135   191   100    74    59    76    75
    80    81   173    97    52    84    62    93    94   177    69   154
   163    87    63   175   170   111    77    79    66   188   758    89
   114   241    83   372   215   118   106    88   141   101   169   202
   124   185   149   137   121   161   152    98   107   156   120   201
   223   219   138   129    85   178   237   193   104   103   160   115
   132   162   148   112   105    95   249   158   143   119   184   153
   182   180   245   172   116   113   134   133   131 11564  2563  2285
   309  6708  2828  3694  4151  1294   626  1039  4456 18718 10405  2233
  5778  2154  2582   230   142   240   181]
----------------------------------------------------------------------------------------------------
➡️ densite (1720) 🧾 unique values:
[  53.   29.  607. ... 1005. 1161. 1687.]
----------------------------------------------------------------------------------------------------
➡️ altitude_moyenne (1629) 🧾 unique values:
[ 242  483  379 ... 1347 1386 1282]
----------------------------------------------------------------------------------------------------
➡️ altitude_minimale (1123) 🧾 unique values:
[206. 290. 237. ... 876. 904. 583.]
----------------------------------------------------------------------------------------------------
➡️ altitude_maximale (2145) 🧾 unique values:
[ 272.  748.  753. ... 2955. 2630. 3071.]
----------------------------------------------------------------------------------------------------
➡️ latitude_mairie (8420) 🧾 unique values:
[ 46.151  46.007  45.958 ... -12.798 -12.847 -12.79 ]
----------------------------------------------------------------------------------------------------
➡️ longitude_mairie (10340) 🧾 unique values:
[ 4.921  5.423  5.36  ... 45.275 45.106 45.105]
----------------------------------------------------------------------------------------------------
➡️ latitude_centre (8421) 🧾 unique values:
[ 46.153  46.009  45.961 ... -12.796 -12.861 -12.782]
----------------------------------------------------------------------------------------------------
➡️ longitude_centre (10343) 🧾 unique values:
[ 4.926  5.428  5.373 ... 45.284 45.119 45.134]
----------------------------------------------------------------------------------------------------
➡️ grille_densite (7) 🧾 unique values:
[6 2 5 4 7 3 1]
----------------------------------------------------------------------------------------------------
➡️ grille_densite_texte (7) 🧾 unique values:
['Rural à habitat dispersé' 'Centres urbains intermédiaires'
 'Bourgs ruraux' 'Ceintures urbaines' 'Rural à habitat très dispersé'
 'Petites villes' 'Grands centres urbains']
----------------------------------------------------------------------------------------------------
➡️ niveau_equipements_services (6) 🧾 unique values:
[ 0.  3.  1.  2.  4. nan]
----------------------------------------------------------------------------------------------------

In [12]:
communes = df_communes[[
    "code_insee",
    "nom_standard",
    "code_postal",
    "dep_code",   # optional
    "dep_nom"     # optional
]].copy()

# Standardize text for matching
communes["nom_standard"] = communes["nom_standard"].str.upper().str.strip()
communes["code_postal"] = communes["code_postal"].astype(str).str.zfill(5)

In [13]:
communes.head()

  code_insee             nom_standard code_postal dep_code dep_nom
0      01001  L'ABERGEMENT-CLÉMENCIAT      1400.0       01     Ain
1      01002    L'ABERGEMENT-DE-VAREY      1640.0       01     Ain
2      01004        AMBÉRIEU-EN-BUGEY      1500.0       01     Ain
3      01005      AMBÉRIEUX-EN-DOMBES      1330.0       01     Ain
4      01006                  AMBLÉON      1300.0       01     Ain

In [17]:
import pandas as pd
# create a dataframe with these columns:
# columns: code_insee,	nom_standard,	nom_sans_pronom,	nom_a,	nom_de,	nom_sans_accent,	nom_standard_majuscule, reg_code,	reg_nom,	dep_code,	dep_nom
df_communes_names = df_communes[[
    "code_insee",	
    "nom_standard",	
    "nom_sans_pronom",	
    "nom_a",
    "nom_de",
    "nom_sans_accent",
    "nom_standard_majuscule",
    "reg_code",
    "reg_nom",
    "dep_code",
    "dep_nom"
    ]].copy()

display(df_communes_names.head())
# save in csv
df_communes_names.to_csv("../data/processed/communes_names.csv", index=False)

,code_insee,nom_standard,nom_sans_pronom,nom_a,nom_de,nom_sans_accent,nom_standard_majuscule,reg_code,reg_nom,dep_code,dep_nom
0,01001,L'Abergement-Clémenciat,Abergement-Clémenciat,à Abergement-Clémenciat,de l'Abergement-Clémenciat,l-abergement-clemenciat,L'ABERGEMENT-CLÉMENCIAT,84,Auvergne-Rhône-Alpes,01,Ain
1,01002,L'Abergement-de-Varey,Abergement-de-Varey,à Abergement-de-Varey,de l'Abergement-de-Varey,l-abergement-de-varey,L'ABERGEMENT-DE-VAREY,84,Auvergne-Rhône-Alpes,01,Ain
2,01004,Ambérieu-en-Bugey,Ambérieu-en-Bugey,à Ambérieu-en-Bugey,d'Ambérieu-en-Bugey,amberieu-en-bugey,AMBÉRIEU-EN-BUGEY,84,Auvergne-Rhône-Alpes,01,Ain
3,01005,Ambérieux-en-Dombes,Ambérieux-en-Dombes,à Ambérieux-en-Dombes,d'Ambérieux-en-Dombes,amberieux-en-dombes,AMBÉRIEUX-EN-DOMBES,84,Auvergne-Rhône-Alpes,01,Ain
4,01006,Ambléon,Ambléon,à Ambléon,d'Ambléon,ambleon,AMBLÉON,84,Auvergne-Rhône-Alpes,01,Ain

<style>
h3 {
    margin-top: 0px;
    margin-bottom: 0px;
    font-weight: bold;
}
</style>

### DEAL with INVALID VALUES - Valeurs Foncieres

In [19]:
# ----------------------------------------
# Column: transaction_type
# ----------------------------------------
# fix transaction_type encoding issues to ensure consistent values
# replace values to english
df['transaction_type'] = df['transaction_type'].replace({
        "Vente": "Sale",
        "Vente en l'Ã©tat futur d'achÃ¨vement": "Sale in future state of completion",
        "Vente terrain Ã\xa0 bÃ¢tir": "Sale of unbuilt land",
        "Echange": "Exchange",
        "Adjudication": "Auction",
        "Expropriation": "Expropriation"})


# --------------------------
# Column: street_number
# --------------------------
# nulls in street_number are common and not necessarily invalid, so we will keep them as is for now



# ------------------------
# Column: btq_code
# ------------------------
# fix btq_code inconsistencies: replace invalid values with NaN and standardize 'b' to 'B'
invalid_values = ['-', '.', '*']
df["btq_code"] = df["btq_code"].replace(invalid_values, pd.NA)
df['btq_code'] = df['btq_code'].replace({ 'b': 'B'})


# --------------------------------------------------------------------------------------
# Column: commune_name
# --------------------------------------------------------------------------------------

# --- REPLACE COMMUNE NAMES in DataFrame with OFFICIAL NAMES FROM COMMUNES DATASET TO ENSURE CONSISTENCY ---
# load communes dataset with INSEE codes and official names
commune_names = pd.read_csv("../data/processed/communes_names.csv")

# create mapping for verifying commune_name in dataframe
#commune_mapping = 

# replace commune names in the main dataset using the mapping dictionary
#df["commune_name"] = df["commune_name"].replace(commune_mapping)

# -------------------------------
# Column: building_real_surface
# -------------------------------
# because it is probably not a built property if building_real_surface is NaN
# as building area is not relevant for land sales
# fill NaN with 0 
df["building_real_surface"] = df["building_real_surface"].fillna(0)

# --------------------------
# Column: main_rooms_count
# --------------------------
# because it is probably not a built property if main_rooms_count is NaN
# fill NaN with 0 
df["main_rooms_count"] = df["main_rooms_count"].fillna(0)

# -----------------------
# Column: surface_type
# -----------------------
# surface_type: replace 'bati' with 'built' and 'terrain' with 'land'
df['surface_type'] = df['surface_type'].replace({
    "bati": "built",    
    "terrain": "land"})


# --------------------------------------------------------------------------------------------
# SAVE - InvalidValues ValeursFoncieres
# --------------------------------------------------------------------------------------------
df.to_csv("../data/processed/INTERIM_02_InvalidValues_ValeursFoncieres.csv", index=False)
print(f"✅ Dataset with invalid values handled and saved at ../data/processed/INTERIM_02_InvalidValues_ValeursFoncieres.csv")

✅ Dataset with invalid values handled and saved at ../data/processed/INTERIM_02_InvalidValues_ValeursFoncieres.csv

<hr>

## 3 - DATA TYPES


<style>
h1 {
    text-align: center;
    color: black;
    font-weight: bold;
}
</style>

<style>
h2 {
    text-align: left;
    color: black;
    font-weight: bold;
}
</style>

<style>
h3 {
    text-align: left;
    color: black;
    font-weight: bold;
}
</style>

<style>
h4 {
    text-align: left;
    color: black;
    font-weight: bold;
}
</style>
<hr>

<style>
h4 {
    margin-top: 0px;
    margin-bottom: 0px;
    font-weight: bold;
}
</style>

#### DISPLAY TYPES - Valeurs Foncieres

In [2]:
# Load the dataset
df = pd.read_csv("../data/processed/INTERIM_02_InvalidValues_ValeursFoncieres.csv")

# Display DataFrame
print("DataFrame:")
print(df.shape[0], "rows and", df.shape[1], "columns")
display(df.head())

C:\Users\sboub\AppData\Local\Temp\ipykernel_13488\2642735328.py:2: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../data/processed/INTERIM_02_InvalidValues_ValeursFoncieres.csv")

DataFrame:
19908349 rows and 17 columns

,transaction_date,transaction_type,property_value,street_number,btq_code,street_name,postal_code,commune_name,number_of_lots,property_type,building_real_surface,main_rooms_count,land_surface,effective_surface,value_per_m2,surface_type,department_code
0,01/07/2020,Sale,31234.16,NaN,NaN,SAINT JULIEN,1560.0,SAINT-JULIEN-SUR-REYSSOUZE,0,NaN,0.0,0.0,1192.0,1192.0,26.203154,land,15
1,01/07/2020,Sale,278000.00,NaN,NaN,A LA PEROUSE,1250.0,CORVEISSIAT,0,NaN,0.0,0.0,10092.0,10092.0,27.546572,land,12
2,01/07/2020,Sale,278000.00,NaN,NaN,A LA PEROUSE,1250.0,CORVEISSIAT,0,NaN,0.0,0.0,4570.0,4570.0,60.831510,land,12
3,01/07/2020,Sale,278000.00,NaN,NaN,AUX COMMUNS,1250.0,CORVEISSIAT,0,NaN,0.0,0.0,5750.0,5750.0,48.347826,land,12
4,01/07/2020,Sale,278000.00,NaN,NaN,EN COMBARNAUD,1250.0,SIMANDRE-SUR-SURAN,0,NaN,0.0,0.0,648170.0,648170.0,0.428900,land,12

In [3]:
# print data types and unique values count for each column in df
print("Data types check:")
for col in df.columns:
    dtype = df[col].dtype
    unique_vals = df[col].nunique()
    print(f"  ➡️{col:<25} {str(dtype):<10} [{unique_vals}] unique values")

Data types check:
  ➡️transaction_date          object     [1804] unique values
  ➡️transaction_type          object     [6] unique values
  ➡️property_value            float64    [466667] unique values
  ➡️street_number             float64    [9120] unique values
  ➡️btq_code                  object     [36] unique values
  ➡️street_name               object     [1125219] unique values
  ➡️postal_code               float64    [5871] unique values
  ➡️commune_name              object     [31569] unique values
  ➡️number_of_lots            int64      [123] unique values
  ➡️property_type             object     [4] unique values
  ➡️building_real_surface     float64    [9184] unique values
  ➡️main_rooms_count          float64    [75] unique values
  ➡️land_surface              float64    [85686] unique values
  ➡️effective_surface         float64    [85082] unique values
  ➡️value_per_m2              float64    [3967896] unique values
  ➡️surface_type              object     [2] unique values
  ➡️department_code           object     [95] unique values

In [4]:
# Loop through each column and print unique values
print(100 * "-")
for col in df.columns:
    unique_vals = df[col].unique()
    print(f"➡️ {col} ({len(unique_vals)}) 🧾 unique values:")
    print(f"{unique_vals}")
    print(100 * "-")

----------------------------------------------------------------------------------------------------
➡️ transaction_date (1804) 🧾 unique values:
['01/07/2020' '04/07/2020' '02/07/2020' ... '01/05/2025' '18/05/2025'
 '05/01/2025']
----------------------------------------------------------------------------------------------------
➡️ transaction_type (6) 🧾 unique values:
['Sale' 'Sale in future state of completion' 'Sale of unbuilt land'
 'Exchange' 'Auction' 'Expropriation']
----------------------------------------------------------------------------------------------------
➡️ property_value (466667) 🧾 unique values:
[3.123416e+04 2.780000e+05 3.985000e+03 ... 7.088090e+05 5.503861e+05
 2.441758e+07]
----------------------------------------------------------------------------------------------------
➡️ street_number (9121) 🧾 unique values:
[  nan  347. 1084. ... 8562. 8301. 8423.]
----------------------------------------------------------------------------------------------------
➡️ btq_code (37) 🧾 unique values:
[nan 'B' 'C' 'A' 'F' 'L' 'T' 'X' 'O' 'Z' 'D' 'G' 'Q' 'Y' 'I' 'E' 'N' 'H'
 '1' 'W' 'V' 'U' 'S' 'R' 'P' 'M' 'K' 'J' '0' '5' '9' '8' '7' '2' '4' '3'
 '6']
----------------------------------------------------------------------------------------------------
➡️ street_name (1125220) 🧾 unique values:
['SAINT JULIEN' 'A LA PEROUSE' 'AUX COMMUNS' ... 'SAINT PIERRE AMELOT'
 'SAINT HONORE D EYLAU' 'DES FOSSES SAINT MARCEL']
----------------------------------------------------------------------------------------------------
➡️ postal_code (5872) 🧾 unique values:
[ 1560.  1250.  1310. ... 97380. 97314. 97330.]
----------------------------------------------------------------------------------------------------
➡️ commune_name (31569) 🧾 unique values:
['SAINT-JULIEN-SUR-REYSSOUZE' 'CORVEISSIAT' 'SIMANDRE-SUR-SURAN' ...
 'BEAUMONT SUR OISE' 'FRETTE SUR SEINE (LA)' 'CAMOPI']
----------------------------------------------------------------------------------------------------
➡️ number_of_lots (123) 🧾 unique values:
[  0   1   2   3   7   5   4   6  13  12  11  42   8   9  15  20  10  14
 108  17  38  22  16  19  34  23  29  43  28  18  63  33  58  61  30  71
  26  50  83  37  27  90  92  31  49  40  81  53  51  21  54 119  24 150
  66  36 121 100  35  25  32  44  68 106  76  46 122  55  65  74  47  56
 141  75  72  45  60  39  48  79  57  62 126 116  98 175 111  73 138 103
  82 190  80 188  89  93  69  59 107  78  52 149  96 120  95 157 152 136
  91 110  64  41 139 132  94 125 105 161 101 236 114  70  85]
----------------------------------------------------------------------------------------------------
➡️ property_type (5) 🧾 unique values:
[nan 'Maison' 'Dépendance' 'Appartement'
 'Local industriel. commercial ou assimilé']
----------------------------------------------------------------------------------------------------
➡️ building_real_surface (9184) 🧾 unique values:
[    0.   115.   122. ...  8168. 28132.  8827.]
----------------------------------------------------------------------------------------------------
➡️ main_rooms_count (75) 🧾 unique values:
[  0.   2.   5.   3.   4.   6.   1.   7.  15.   8.  10.   9.  11.  19.
  12.  13.  16.  20.  23.  17.  54.  30.  14.  18.  24.  44.  34.  55.
  22.  21.  40.  70.  35.  25.  51.  33.  26.  27.  71.  84. 109.  38.
  28.  32.  97.  53.  36.  43.  29.  31.  56.  57.  50.  89.  95.  61.
  41.  73.  63.  49.  90.  37.  62.  80.  78.  68.  42.  52.  39.  64.
  46. 198.  83.  77.  82.]
----------------------------------------------------------------------------------------------------
➡️ land_surface (85687) 🧾 unique values:
[  1192.  10092.   4570. ...  77614. 186988. 530850.]
----------------------------------------------------------------------------------------------------
➡️ effective_surface (85083) 🧾 unique values:
[  1192.  10092.   4570. ...  77614. 186988. 530850.]
----------------------------------------------------------------------------------------------------
➡️ value_per_m2 (3967897) 🧾 unique values:
[   26.20315436    27.54657154    60.83150985 ... 20847.32352941
 13126.09259259 11710.34255319]
----------------------------------------------------------------------------------------------------
➡️ surface_type (2) 🧾 unique values:
['land' 'built']
----------------------------------------------------------------------------------------------------
➡️ department_code (95) 🧾 unique values:
['15' '12' '13' '14' '10' '17' '11' 'na' '19' '18' '16' '28' '23' '22'
 '20' '21' '24' '27' '26' '25' '31' '34' '33' '32' '30' '35' '42' '36'
 '38' '37' '43' '41' '44' '51' '48' '45' '40' '47' '46' '62' '52' '55'
 '50' '53' '57' '56' '58' '54' '63' '60' '61' '67' '69' '64' '66' '65'
 '68' '73' '78' '71' '72' '77' '70' '74' '75' '76' '88' '80' '84' '82'
 '81' '83' '87' '86' '85' '95' '93' '91' '90' '92' '96' '94' '97' '98'
 '29' '39' '49' '59' '79' '89' 88 89 17 18 87]
----------------------------------------------------------------------------------------------------

<style>
h4 {
    margin-top: 0px;
    margin-bottom: 0px;
    font-weight: bold;
}
</style>

#### CONVERT - Valeurs Foncieres

| Field Name                                 | Python data type             |
|--------------------------------------------|------------------------------|
| **transaction_date**                          | `object` to `date`??           |
| **street_number**                                | `float64` to `object`         |
| **postal_code**                            | `float64` to `object`        |
| **main_rooms**              | `float64` to `int64`         |

In [ ]:
# convert df columns types as follows:
#df["transaction_date"] = pd.to_datetime(df["transaction_date"], errors='coerce')
df["street_number"] = df["street_number"].astype('object')
df["postal_code"] = df["postal_code"].astype('object')
df["main_rooms_count"] = df["main_rooms_count"].astype('int64')


# Display Converted column names
print("Converted column names:")
display(df.info())

# Save dataset in a new CSV file
df.to_csv("../data/processed/INTERIM_03_DataType_ValeursFoncieres.csv", index=False)
print(f"✅ Dataset converted to appropriate data types and saved at ../data/processed/INTERIM_03_DataType_ValeursFoncieres.csv")

Converted column names:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19908349 entries, 0 to 19908348
Data columns (total 17 columns):
 #   Column                 Dtype
---  ------                 -----
 0   transaction_date       object
 1   transaction_type       object
 2   property_value         float64
 3   street_number          float64
 4   btq_code               object
 5   street_name            object
 6   postal_code            object
 7   commune_name           object
 8   number_of_lots         int64
 9   property_type          object
 10  building_real_surface  float64
 11  main_rooms_count       int64
 12  land_surface           float64
 13  effective_surface      float64
 14  value_per_m2           float64
 15  surface_type           object
 16  department_code        object
dtypes: float64(6), int64(2), object(9)
memory usage: 2.5+ GB

None

✅ Dataset converted to appropriate data types and saved at ../data/processed/INTERIM_03_DataType_ValeursFoncieres.csv

<hr>

## 4 - NULL VALUES


<style>
h1 {
    text-align: center;
    color: black;
    font-weight: bold;
}
</style>

<style>
h2 {
    text-align: left;
    color: black;
    font-weight: bold;
}
</style>

<style>
h3 {
    text-align: left;
    color: black;
    font-weight: bold;
}
</style>

<style>
h4 {
    text-align: left;
    color: black;
    font-weight: bold;
}
</style>
<hr>

<style>
h4 {
    margin-top: 0px;
    margin-bottom: 0px;
    font-weight: bold;
}
</style>

#### DISPLAY NULLs - Valeurs Foncieres

In [1]:
import pandas as pd

# Load dataset with converted data types
df = pd.read_csv("../data/processed/INTERIM_03_DataType_ValeursFoncieres.csv")

# Loop through each column and print the number of nulls in each column
for col in df.columns:
    null_count = df[col].isnull().sum()
    print(f"[{col}]: [{null_count}] null values")

print(100*"-")
# display data types and missing values of each column in df
df.info()

C:\Users\sboub\AppData\Local\Temp\ipykernel_8308\2047978848.py:4: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../data/processed/INTERIM_03_DataType_ValeursFoncieres.csv")

[transaction_date]: [0] null values
[transaction_type]: [0] null values
[property_value]: [0] null values
[street_number]: [7360821] null values
[btq_code]: [19012414] null values
[street_name]: [150834] null values
[postal_code]: [151147] null values
[commune_name]: [0] null values
[number_of_lots]: [0] null values
[property_type]: [8091437] null values
[building_real_surface]: [0] null values
[main_rooms_count]: [0] null values
[land_surface]: [6383746] null values
[effective_surface]: [3733648] null values
[value_per_m2]: [3734243] null values
[surface_type]: [0] null values
[department_code]: [0] null values
----------------------------------------------------------------------------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19908349 entries, 0 to 19908348
Data columns (total 17 columns):
 #   Column                 Dtype
---  ------                 -----
 0   transaction_date       object
 1   transaction_type       object
 2   property_value         float64
 3   street_number          float64
 4   btq_code               object
 5   street_name            object
 6   postal_code            float64
 7   commune_name           object
 8   number_of_lots         int64
 9   property_type          object
 10  building_real_surface  float64
 11  main_rooms_count       int64
 12  land_surface           float64
 13  effective_surface      float64
 14  value_per_m2           float64
 15  surface_type           object
 16  department_code        object
dtypes: float64(7), int64(2), object(8)
memory usage: 2.5+ GB

<style>
h4 {
    margin-top: 0px;
    margin-bottom: 0px;
    font-weight: bold;
}
</style>

#### DEAL with NULLs - Valeur Foncieres

In [ ]:
# --------------------------------------------------------------------------------
# Column: property_value (euros)
# --------------------------------------------------------------------------------
# drop nulls in sale_price_eur column as it's a critical column for analysis
df = df.dropna(subset=["property_value"])

# --------------------------------------------------------------------------------
# Column: building_real_surface
# --------------------------------------------------------------------------------
# Fill NaN with 0
df["building_real_surface"] = df["building_real_surface"].fillna(0)

# --------------------------------------------------------------------------------
# Column: property_type
# --------------------------------------------------------------------------------
# Fill NaN with "Unknown" to keep all rows for analysis, 
# as property_type is important for analysis and we don't want to drop rows with missing property_type
df["property_type"] = df["property_type"].fillna("Unknown")

# --------------------------------------------------------------------------------
# Column: street_number
# --------------------------------------------------------------------------------
# convert type to object
df["street_number"] = df["street_number"].astype('object')
# Fill NaN with "Unknown" & type as object
df["street_number"] = df["street_number"].fillna("Unknown")


# --------------------------------------------------------------------------------
# Column: main_rooms_count
# --------------------------------------------------------------------------------
# main_rooms is only relevant for houses/apartments
# fill NaN with 0 if property_type is terrain
df["main_rooms_count"] = df.apply(lambda row: 0 if pd.isna(row["main_rooms_count"]) and row["property_type"] == "land" else row["main_rooms_count"], axis=1)


# --------------------------------------------------------------------------------
# Column: property_value (euros)
# --------------------------------------------------------------------------------
# drop nulls in sale_price_eur column as it's a critical column for analysis
df = df.dropna(subset=["property_value"])


# --------------------------------------------------------------------------------
# Column: land_surface
# --------------------------------------------------------------------------------
# Fill NaN with 0 if building_real_surface is not null
df["land_surface"] = df.apply(lambda row: 0 if pd.isna(row["land_surface"]) and not pd.isna(row["building_real_surface"]) else row["land_surface"], axis=1)

# --------------------------------------------------------------------------------
# Column: building_real_surface
# --------------------------------------------------------------------------------
# Fill NaN with 0
df["building_real_surface"] = df["building_real_surface"].fillna(0)

# --------------------------------------------------------------------------------
# Column: property_type
# --------------------------------------------------------------------------------
# Fill NaN with "Unknown" to keep all rows for analysis, 
# as property_type is important for analysis and we don't want to drop rows with missing property_type
df["property_type"] = df["property_type"].fillna("Unknown")

# --------------------------------------------------------------------------------
# Column: street_number
# --------------------------------------------------------------------------------
# convert type to object
df["street_number"] = df["street_number"].astype('object')
# Fill NaN with "Unknown" & type as object
df["street_number"] = df["street_number"].fillna("Unknown")


# --------------------------------------------------------------------------------
# Column: main_rooms_count
# --------------------------------------------------------------------------------
# main_rooms is only relevant for houses/apartments
# fill NaN with 0 if property_type is terrain
df["main_rooms_count"] = df.apply(lambda row: 0 if pd.isna(row["main_rooms_count"]) and row["property_type"] == "land" else row["main_rooms_count"], axis=1)

# --------------------------------------------------------------------------------
# Column: btq_code
# --------------------------------------------------------------------------------
df["btq_code"] = df["btq_code"].fillna("None")

# --------------------------------------------------------------------------------
# Column: street_name
# --------------------------------------------------------------------------------
df["street_name"] = df["street_name"].fillna("Unknown")

# --------------------------------------------------------------------------------
# Column: postal_code
# --------------------------------------------------------------------------------
df["postal_code"] = df["postal_code"].fillna("Unknown")


# --------------------------------------------------------------------------------
# Save dataset in a new CSV file
# --------------------------------------------------------------------------------
df.to_csv("../data/processed/INTERIM_04_Nulls_ValeursFoncieres.csv", index=False)
print(f"✅ Dataset with null values handled and saved at ../data/processed/INTERIM_04_Nulls_ValeursFoncieres.csv")

✅ Dataset with null values handled and saved at ../data/processed/INTERIM_04_Nulls_ValeursFoncieres.csv

In [2]:
import pandas as pd

# Load dataset with nulls handled
df = pd.read_csv("../data/processed/INTERIM_04_Nulls_ValeursFoncieres.csv")

# Loop through each column and print the number of nulls in each column
for col in df.columns:
    null_count = df[col].isnull().sum()
    print(f"[{col}]: [{null_count}] null values")

print(100*"-")
# display data types and missing values of each column in df
df.info()

C:\Users\sboub\AppData\Local\Temp\ipykernel_17304\2309171356.py:4: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../data/processed/INTERIM_04_Nulls_ValeursFoncieres.csv")

[transaction_date]: [0] null values
[transaction_type]: [0] null values
[property_value]: [0] null values
[street_number]: [0] null values
[btq_code]: [19012414] null values
[street_name]: [150834] null values
[postal_code]: [151147] null values
[commune_name]: [0] null values
[number_of_lots]: [0] null values
[property_type]: [0] null values
[building_real_surface]: [0] null values
[main_rooms_count]: [0] null values
[land_surface]: [6383746] null values
[effective_surface]: [3733648] null values
[value_per_m2]: [3734243] null values
[surface_type]: [0] null values
[department_code]: [0] null values
----------------------------------------------------------------------------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19908349 entries, 0 to 19908348
Data columns (total 17 columns):
 #   Column                 Dtype
---  ------                 -----
 0   transaction_date       object
 1   transaction_type       object
 2   property_value         float64
 3   street_number          object
 4   btq_code               object
 5   street_name            object
 6   postal_code            float64
 7   commune_name           object
 8   number_of_lots         int64
 9   property_type          object
 10  building_real_surface  float64
 11  main_rooms_count       int64
 12  land_surface           float64
 13  effective_surface      float64
 14  value_per_m2           float64
 15  surface_type           object
 16  department_code        object
dtypes: float64(6), int64(2), object(9)
memory usage: 2.5+ GB

<hr>

## 5 - DUPLICATES


<style>
h1 {
    text-align: center;
    color: black;
    font-weight: bold;
}
</style>

<style>
h2 {
    text-align: left;
    color: black;
    font-weight: bold;
}
</style>

<style>
h3 {
    text-align: left;
    color: black;
    font-weight: bold;
}
</style>

<style>
h4 {
    text-align: left;
    color: black;
    font-weight: bold;
}
</style>
<hr>

<style>
h4 {
    margin-top: 0px;
    margin-bottom: 0px;
    font-weight: bold;
}
</style>

#### DISPLAY DUPLICATE ROWS - Valeurs Foncieres

In [3]:
import pandas as pd

# load dataset with nulls handled
df = pd.read_csv("../data/processed/INTERIM_04_Nulls_ValeursFoncieres.csv")

# Check for duplicate rows in the DataFrame
duplicate_rows = df[df.duplicated()]

# Print the number of duplicate rows
print(f"Number of duplicate rows: {duplicate_rows.shape[0]}")

# Display the duplicate rows if any exist
if not duplicate_rows.empty:
    print("\nDuplicate rows:")
    display(duplicate_rows)
else:
    print("\nNo duplicate  rows found.")

C:\Users\sboub\AppData\Local\Temp\ipykernel_17304\158086586.py:4: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../data/processed/INTERIM_04_Nulls_ValeursFoncieres.csv")

Number of duplicate rows: 2538771

Duplicate rows:

,transaction_date,transaction_type,property_value,street_number,btq_code,street_name,postal_code,commune_name,number_of_lots,property_type,building_real_surface,main_rooms_count,land_surface,effective_surface,value_per_m2,surface_type,department_code
44,02/07/2020,Sale in future state of completion,360000.0,12.0,NaN,DU 23EME R.I.,1000.0,BOURG-EN-BRESSE,1,Dépendance,0.0,0,NaN,NaN,NaN,land,10
60,01/07/2020,Sale,270000.0,6.0,NaN,CREVE COEUR,1000.0,BOURG-EN-BRESSE,1,Dépendance,0.0,0,NaN,NaN,NaN,land,10
91,09/07/2020,Sale in future state of completion,20000.0,street_number,NaN,NaN,NaN,SAINT-DENIS-LES-BOURG,1,Unknown,0.0,0,NaN,NaN,NaN,land,na
95,09/07/2020,Sale in future state of completion,45000.0,street_number,NaN,NaN,NaN,SAINT-DENIS-LES-BOURG,1,Unknown,0.0,0,NaN,NaN,NaN,land,na
96,09/07/2020,Sale in future state of completion,45000.0,street_number,NaN,NaN,NaN,SAINT-DENIS-LES-BOURG,1,Unknown,0.0,0,NaN,NaN,NaN,land,na
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19908303,30/06/2025,Sale,250000.0,8.0,NaN,SAINT SEBASTIEN,75011.0,PARIS 11,1,Appartement,15.0,1,NaN,15.0,16666.666667,built,75
19908312,17/06/2025,Sale,700000.0,3.0,NaN,DE LA NATION,75011.0,PARIS 11,1,Dépendance,0.0,0,NaN,NaN,NaN,land,75
19908326,26/06/2025,Sale,540000.0,88.0,NaN,VICTOR HUGO,75016.0,PARIS 16,2,Dépendance,0.0,0,NaN,NaN,NaN,land,75
19908330,17/06/2025,Sale,592028.0,59.0,NaN,ERLANGER,75016.0,PARIS 16,2,Dépendance,0.0,0,NaN,NaN,NaN,land,75
19908348,25/06/2025,Sale,24417580.0,street_number,NaN,NaN,NaN,PARIS 15,0,Unknown,0.0,0,NaN,NaN,NaN,land,na

<style>
h4 {
    margin-top: 0px;
    margin-bottom: 0px;
    font-weight: bold;
}
</style>

#### DEAL with DUPLICATE ROWS - Valeurs Foncieres

In [ ]:
# drop duplicate rows in df
#df = df.drop_duplicates()

# Save dataset in a new CSV file
df.to_csv("../data/processed/INTERIM_05_duplicates_ValeursFoncieres.csv", index=False)
print(f"✅ Dataset with duplicates handled and saved at ../data/processed/INTERIM_05_duplicates_ValeursFoncieres.csv")

<hr>

## 🕵️ REVISE & SAVE CLEAN DATA


<style>
h1 {
    text-align: center;
    color: black;
    font-weight: bold;
}
</style>

<style>
h2 {
    text-align: left;
    color: black;
    font-weight: bold;
}
</style>

<style>
h3 {
    text-align: left;
    color: black;
    font-weight: bold;
}
</style>

<style>
h4 {
    text-align: left;
    color: black;
    font-weight: bold;
}
</style>
<hr>

```text
- display head
- display info
- check unique values
- check data types
- check for nulls
- check for duplicates
```

In [ ]:
import pandas as pd

# --------------------------------------------
# Load dataset with duplicates handled
# --------------------------------------------
df = pd.read_csv("../data/processed/INTERIM_05_duplicates_ValeursFoncieres.csv")

# --------------------
# 🔲 DISPLAY - HEAD
# --------------------
# Display df DataFrame
print("Data Revision:")
display(df.head())
print("Dataset Shape:", df.shape[0], "rows and", df.shape[1], "columns\n")
print(100*"-")

# --------------------
# 🔲 DISPLAY - INFO
# --------------------
# display data types and missing values of each column in df
df.info()
print(100*"-")

# -----------------------------
# 🕵️ CHECK - UNIQUE VALUES
# -----------------------------
# Display data types & missing values of each column in df
print("Data Types & Missing Values of Each Column:")
display(df.info())

# Loop through each column and print unique values
for col in df.columns:
    unique_vals = df[col].unique()
    print(f"Column: {col}")
    print(f"Unique values ({len(unique_vals)}): {unique_vals}\n")
print(100*"-")

# -----------------------------
# 🕵️ CHECK - DATA TYPES
# -----------------------------
print(f"\nData types check:")
for col in df.columns:
    dtype = df[col].dtype
    unique_vals = df[col].nunique()
    print(f"  ➡️{col:<25} {str(dtype):<10} [{unique_vals}] unique values")
print(100*"-")

# -----------------------------
# 🕵️ CHECK - NULLS
# -----------------------------
# Loop through each column and print the number of nulls in each column
for col in df.columns:
    null_count = df[col].isnull().sum()
    print(f"[{col}]: [{null_count}] null values")
print(100*"-")


# -----------------------------
# 🕵️ CHECK - DUPLICATES
# -----------------------------
# Check for duplicate rows in the DataFrame
duplicate_rows = df[df.duplicated()]

# Print the number of duplicate rows
print(f"Number of duplicate rows: {duplicate_rows.shape[0]}")
print(100*"-")

# Display the duplicate rows if any exist
if not duplicate_rows.empty:
    print("\nDuplicate rows:")
    display(duplicate_rows)
else:
    print("\nNo duplicate  rows found.")
print(100*"-")

# --------------------------------------------
# Save CLEAN data in a new CSV file
# --------------------------------------------
df.to_csv("../data/processed/CLEAN_ValeursFoncieres_2020-S2_2025-S1.csv", index=False)
print(f"✅ Dataset cleaned and saved at ../data/processed/CLEAN_ValeursFoncieres_2020-S2_2025-S1.csv")