<hr>

# 🧫 DATA CLEANING - Valeurs Foncieres


<style>
h1 {
    text-align: left;
    color: blue;
    font-weight: bold;
}

</style>
<hr>

```text
STEPS:
- Create unique transaction_id where 1 transaction can have N rows
- CONCATINATE from 6 txt files into 1 csv
- DROP columns
- STANDARDIZE column names
- INVALID VALUES
- Convert DATA TYPES
- Deal with NULLS
- Deal with DUPLICATES
- Deal with OUTLIERS
- Save CLEAN CSV
```

<style>
h3 {
    margin-top: 0px;
    margin-bottom: 0px;
    font-weight: bold;
}
</style>

### 📂 IMPORTs

In [1]:
# import necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import display
import seaborn as sns

plt.style.use('ggplot')
pd.set_option('display.max_columns', 200) # to display all columns in the dataframe
print("✅ Libraries imported successfully")

✅ Libraries imported successfully

<hr>

## 0️⃣ CONCATINATE 

<style>
h1 {
    text-align: center;
    color: black;
    font-weight: bold;
}
</style>

<style>
h2 {
    text-align: left;
    color: black;
    font-weight: bold;
}
</style>

<style>
h3 {
    text-align: left;
    color: black;
    font-weight: bold;
}
</style>

<style>
h4 {
    text-align: left;
    color: black;
    font-weight: bold;
}
</style>
<hr>

### `No disposition` **UNIQUE VALUES**

- load each txt file into a pandas dataframe
- then convert each to a CSV and save to output directory
- using chunk processing to handle large files
- We need to check each file unique values of column "No disposition"
- We need to create a unique identifier for each transaction where:
1 transaction can have N rows

In [ ]:
from pathlib import Path
import pandas as pd

RAW_DIR = Path("../data/raw")
OUTPUT_DIR = Path("../data/processed")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

FILES = [
    "ValeursFoncieres-2020-S2.txt",
    "ValeursFoncieres-2021.txt",
    "ValeursFoncieres-2022.txt",
    "ValeursFoncieres-2023.txt",
    "ValeursFoncieres-2024.txt",
    "ValeursFoncieres-2025-S1.txt",
]

COLUMN = "No disposition"
CHUNKSIZE = 500_000

for file in FILES:
    input_path = RAW_DIR / file
    output_path = OUTPUT_DIR / file.replace(".txt", ".csv")

    unique_values = set()
    first_chunk = True

    for chunk in pd.read_csv(
        input_path,
        sep="|",
        dtype=str,
        chunksize=CHUNKSIZE,
        encoding="utf-8",
        low_memory=False
    ):
        if COLUMN in chunk.columns:
            unique_values.update(chunk[COLUMN].dropna().unique())

        chunk.to_csv(
            output_path,
            index=False,
            mode="w" if first_chunk else "a",
            header=first_chunk
        )

        first_chunk = False

    print(f"\n{file}")
    print(f"Unique values in '{COLUMN}':")
    print(sorted(unique_values))

ValeursFoncieres-2020-S2.txt
Unique values in 'No disposition':
['000001', '000002', '000003', '000004', '000005', '000006', '000007', '000008', '000009', '000010', '000011', '000012', '000013', '000014', '000015', '000016', '000017', '000018', '000019', '000020', '000021', '000022', '000023', '000024', '000025', '000026', '000027', '000028', '000029', '000030', '000031', '000032', '000033', '000034', '000035', '000036', '000037', '000038', '000039', '000040', '000041', '000042', '000043', '000044', '000045', '000046', '000047', '000048', '000049', '000050', '000051', '000052', '000053', '000054', '000055', '000056', '000057', '000058', '000059', '000060', '000061', '000062', '000063', '000064', '000065', '000066', '000067', '000068', '000069', '000070', '000071', '000072', '000073', '000074', '000075', '000076', '000077', '000078', '000079', '000080', '000081', '000082', '000083', '000084', '000085', '000086', '000087', '000088', '000089', '000090', '000091', '000092', '000093', '000094', '000095', '000096', '000097', '000098', '000099', '000100', '000101', '000102', '000103', '000104', '000105', '000106', '000107', '000108', '000109', '000110', '000111', '000112', '000113', '000114', '000115', '000116', '000117', '000118', '000119', '000120', '000121', '000122', '000123', '000124', '000125', '000126', '000127', '000128', '000129', '000130', '000131', '000132', '000133', '000134', '000135', '000136', '000137', '000138', '000139', '000140', '000141', '000142', '000143', '000144', '000145', '000146', '000147', '000148', '000149', '000150', '000151', '000152', '000153', '000154', '000155', '000156', '000157', '000158', '000159', '000160', '000161', '000162', '000163', '000164', '000165', '000166', '000167']

ValeursFoncieres-2021.txt
Unique values in 'No disposition':
['000001', '000002', '000003', '000004', '000005', '000006', '000007', '000008', '000009', '000010', '000011', '000012', '000013', '000014', '000015', '000016', '000017', '000018', '000019', '000020', '000021', '000022', '000023', '000024', '000025', '000026', '000027', '000028', '000029', '000030', '000031', '000032', '000033', '000034', '000035', '000036', '000037', '000038', '000039', '000040', '000041', '000042', '000043', '000044', '000045', '000046', '000047', '000048', '000049', '000050', '000051', '000052', '000053', '000054', '000055', '000056', '000057', '000058', '000059', '000060', '000061', '000062', '000063', '000064', '000065', '000066', '000067', '000068', '000069', '000070', '000071', '000072', '000073', '000074', '000075', '000076', '000077', '000078', '000079', '000080', '000081', '000082', '000083', '000084', '000085', '000086', '000087', '000088', '000089', '000090', '000091', '000092', '000093', '000094', '000095', '000096', '000097', '000098', '000099', '000100', '000101', '000102', '000103', '000104', '000105', '000106', '000107', '000108', '000109', '000110', '000111', '000112', '000113', '000114', '000115', '000117', '000118', '000119', '000120', '000121', '000122', '000123', '000124', '000125', '000126', '000127', '000128', '000129', '000130', '000131', '000132', '000133', '000134', '000135', '000136', '000137', '000138', '000139', '000140', '000141', '000142', '000143', '000144', '000145', '000146', '000147', '000148', '000149', '000150', '000151', '000152', '000153', '000154', '000155', '000156', '000157', '000158', '000159', '000160', '000161', '000162', '000163', '000164', '000165', '000166', '000167', '000168', '000169', '000170', '000171', '000172', '000173', '000174', '000176', '000177', '000178', '000179', '000180', '000181', '000182', '000183', '000184', '000185', '000186', '000187', '000188', '000189', '000190', '000191', '000192', '000193', '000194', '000195', '000196', '000197', '000198']

ValeursFoncieres-2022.txt
Unique values in 'No disposition':
['000001', '000002', '000003', '000004', '000005', '000006', '000007', '000008', '000009', '000010', '000011', '000012', '000013', '000014', '000015', '000016', '000017', '000018', '000019', '000020', '000021', '000022', '000023', '000024', '000025', '000026', '000027', '000028', '000029', '000030', '000031', '000032', '000033', '000034', '000035', '000036', '000037', '000038', '000039', '000040', '000041', '000042', '000043', '000044', '000045', '000046', '000047', '000048', '000049', '000050', '000051', '000052', '000053', '000054', '000055', '000056', '000057', '000058', '000059', '000060', '000061', '000062', '000063', '000064', '000065', '000066', '000067', '000068', '000069', '000070', '000071', '000072', '000073', '000074', '000075', '000076', '000077', '000078', '000079', '000080', '000081', '000082', '000083', '000084', '000085', '000086', '000087', '000088', '000089', '000090', '000091', '000092', '000093', '000094', '000095', '000096', '000097', '000098', '000099', '000100', '000101', '000102', '000103', '000104', '000105', '000106', '000107', '000108', '000109', '000110', '000111', '000112', '000113', '000114', '000115', '000116', '000117', '000118', '000119', '000120', '000121', '000122', '000123', '000124', '000125', '000126', '000127', '000128', '000129', '000130', '000131', '000132', '000133', '000134', '000135', '000136', '000137', '000138', '000139', '000140', '000141', '000142', '000143', '000144', '000145', '000146', '000147', '000148', '000149', '000150', '000151', '000152', '000153', '000154', '000155', '000156', '000157', '000158', '000160', '000161', '000162', '000163', '000164', '000165', '000166', '000167', '000168', '000169', '000170', '000171', '000172', '000173', '000174', '000175', '000176', '000177', '000178', '000179', '000180', '000181', '000182', '000183', '000184', '000185', '000186', '000187', '000188', '000189', '000190', '000191', '000192', '000193', '000194', '000195', '000196', '000197', '000198', '000199', '000200', '000201', '000202', '000203', '000204', '000205', '000206', '000207', '000208', '000209', '000210', '000211', '000212', '000213', '000214', '000215', '000216', '000217', '000218', '000219', '000220', '000221', '000222', '000223', '000224', '000225', '000226', '000227', '000228', '000229', '000230', '000231', '000232', '000233', '000234', '000235', '000236', '000237', '000238', '000239', '000240', '000241', '000242', '000243', '000244', '000245', '000246', '000247', '000248', '000249', '000250', '000251', '000252', '000253', '000254', '000255', '000256', '000257', '000258', '000259', '000260', '000261', '000262', '000263', '000264', '000265', '000266', '000267', '000268', '000269', '000270', '000271', '000272', '000273', '000274', '000275', '000276', '000277', '000278', '000279', '000280', '000281', '000282', '000283', '000284', '000285', '000286', '000287', '000288', '000289', '000290', '000291', '000292', '000293', '000294', '000295', '000296', '000297', '000298', '000299', '000300', '000301', '000302', '000303', '000304', '000305', '000306', '000307', '000308', '000309', '000310', '000311', '000312', '000313', '000314', '000315', '000316', '000317', '000318', '000319', '000320', '000321', '000322', '000323', '000324', '000325', '000326', '000327', '000328', '000329', '000330', '000331', '000332', '000333', '000334', '000335', '000336', '000337', '000338', '000339', '000340', '000341', '000342', '000343', '000344', '000345', '000346', '000347', '000348', '000349', '000350', '000351', '000352', '000353', '000354', '000355', '000356', '000357', '000358', '000359', '000360', '000361', '000362', '000363', '000364', '000365', '000366', '000367', '000368', '000369', '000370', '000371', '000372', '000373', '000374', '000375', '000376', '000377', '000378', '000379', '000380', '000381', '000382', '000383', '000384', '000385', '000386', '000387', '000388', '000389', '000390', '000391', '000392', '000393', '000394', '000395', '000396', '000397', '000398', '000399', '000400', '000401', '000402', '000403', '000404', '000405', '000406', '000407', '000408', '000409', '000410', '000411', '000412', '000413', '000414', '000415', '000416', '000417', '000418', '000419', '000420', '000421', '000422', '000423', '000424', '000425', '000426', '000427', '000428', '000429', '000430', '000431', '000432', '000433', '000434', '000435', '000436', '000437', '000438', '000439', '000440', '000441', '000442', '000443', '000444', '000445', '000446', '000447', '000448', '000449', '000450', '000451', '000452', '000453', '000454', '000455', '000456', '000457', '000458', '000459', '000460', '000461', '000462', '000463', '000464', '000465', '000466', '000467', '000468', '000469', '000470', '000471', '000472', '000473', '000474', '000475', '000476', '000477', '000478', '000479', '000480', '000481', '000482', '000483', '000484', '000485', '000486', '000487', '000488', '000489', '000490', '000491', '000492', '000493', '000494', '000495', '000496', '000497', '000498', '000499', '000500', '000501', '000502', '000503', '000504', '000505', '000506', '000507', '000508', '000509', '000510', '000511', '000512', '000513', '000514', '000515', '000516', '000517', '000518', '000519', '000520', '000521', '000522', '000523', '000524', '000525', '000526', '000527', '000528', '000529', '000530', '000531', '000532', '000533', '000534', '000535', '000536', '000537', '000538', '000539', '000540', '000541', '000542', '000543', '000544', '000545', '000546', '000547', '000548', '000549', '000550', '000551', '000552', '000553', '000554', '000555', '000556', '000557', '000558', '000559', '000560', '000561', '000562', '000563', '000564', '000565', '000566', '000567', '000568', '000569', '000570', '000571', '000572', '000573', '000574', '000575', '000576', '000577', '000578', '000579', '000580', '000581', '000582', '000583', '000584', '000585', '000586', '000587', '000588', '000589', '000590', '000591', '000592', '000593', '000594', '000595', '000596', '000597', '000598', '000599', '000600', '000601', '000602', '000604', '000606', '000607', '000608', '000609', '000610', '000611', '000613', '000614', '000615', '000616', '000617', '000618', '000619', '000620', '000621', '000622', '000623', '000624', '000625', '000626', '000627', '000628', '000629', '000630', '000631', '000632', '000633', '000634', '000635', '000636', '000637', '000638', '000639', '000640', '000641', '000642', '000643', '000644', '000645', '000646', '000647', '000648', '000650', '000652', '000653', '000654', '000657', '000658', '000659', '000660', '000661', '000662', '000663', '000664', '000665', '000666', '000667', '000668', '000669', '000670', '000671', '000672', '000673', '000674', '000675', '000676', '000677', '000678', '000679', '000680', '000681', '000682', '000683', '000684', '000685', '000686', '000687', '000688', '000689', '000690', '000691', '000692', '000693', '000694', '000695', '000696', '000697', '000698', '000699', '000700', '000701', '000702', '000703', '000704', '000705', '000706', '000707', '000708', '000709', '000710', '000711', '000712', '000713', '000714', '000715', '000716', '000717', '000718', '000719', '000720', '000721', '000722', '000723', '000724', '000725', '000726', '000727', '000728', '000729', '000730', '000731', '000732', '000733', '000734', '000735', '000736', '000737', '000738', '000739', '000740', '000741', '000742', '000743', '000744', '000745', '000746', '000747', '000748', '000749', '000750', '000752', '000753', '000754', '000755', '000756', '000757', '000758', '000759', '000761', '000762', '000763', '000764', '000765', '000767', '000768', '000769', '000770', '000771', '000772', '000773', '000774', '000775', '000776', '000777', '000778', '000779', '000781', '000783', '000784', '000785', '000786', '000788', '000789', '000790', '000792', '000793', '000794', '000795', '000796', '000797', '000798', '000800', '000801', '000802', '000803', '000804', '000805', '000806', '000808', '000809', '000810', '000811', '000813', '000814', '000815', '000816', '000817', '000818', '000819', '000820', '000821', '000822', '000823', '000824', '000825', '000826', '000827', '000828', '000829', '000830', '000831', '000832', '000833', '000834', '000835', '000836', '000837', '000838', '000839', '000840', '000841', '000842', '000843', '000844', '000845', '000846', '000847', '000848', '000849', '000850', '000851', '000852', '000853', '000854', '000855', '000857', '000858', '000859', '000860', '000861', '000862', '000863', '000864', '000865', '000866', '000867', '000868', '000869', '000870', '000871', '000873', '000874', '000875', '000876', '000877', '000878', '000879', '000880', '000881', '000882', '000883', '000884', '000885', '000886', '000887', '000888', '000889', '000890', '000892', '000893', '000894', '000895', '000896', '000897', '000898', '000899', '000900', '000901', '000902', '000903', '000904', '000905', '000906', '000907', '000908', '000909', '000910', '000911', '000912', '000913', '000914', '000915', '000916', '000917', '000918', '000919', '000920', '000921', '000922', '000924', '000925', '000926', '000927', '000928', '000929', '000930', '000931', '000932', '000933', '000934', '000935', '000936', '000937', '000938', '000939', '000940', '000941', '000942', '000943', '000944', '000945', '000946', '000947', '000948', '000949', '000950', '000951', '000952', '000953', '000954', '000955', '000956', '000957', '000958', '000959', '000960', '000961', '000962', '000963', '000964', '000965', '000966', '000967', '000968', '000969', '000970', '000972', '000973', '000974', '000976', '000977', '000978', '000979', '000980', '000981', '000982', '000983', '000984', '000985', '000986', '000987', '000988', '000989', '000990', '000991', '000992', '000993', '000994', '000995', '000996', '000997', '000998', '000999', '001000', '001002', '001003', '001004', '001006', '001007', '001008', '001009', '001010', '001011', '001012', '001014', '001015', '001016', '001017', '001018', '001019', '001020', '001021', '001022', '001023', '001024', '001025', '001026', '001027', '001028', '001029', '001030', '001031', '001033', '001034', '001035', '001036', '001037', '001040', '001041', '001043', '001044', '001045', '001046', '001047', '001048', '001049', '001050', '001051', '001052', '001053', '001054', '001055', '001056', '001057', '001058', '001059', '001060', '001061', '001062', '001063', '001064', '001066', '001067', '001068', '001069', '001070', '001071', '001072', '001073', '001074', '001075', '001076', '001077', '001078', '001079', '001080', '001081', '001082', '001083', '001084', '001085', '001086', '001087', '001088', '001089', '001090', '001091', '001093', '001094', '001095', '001096', '001097', '001098', '001099', '001101', '001102', '001103', '001104', '001105', '001106', '001107', '001108', '001109', '001110', '001111', '001112', '001113', '001114', '001115', '001116', '001117', '001118', '001121', '001122', '001123', '001124', '001125', '001126', '001127', '001128', '001129', '001130', '001131', '001132', '001133', '001134', '001135', '001136', '001137', '001138', '001139', '001140', '001141', '001142', '001143', '001144', '001145', '001146', '001147', '001148', '001149', '001152', '001153', '001154', '001156', '001157', '001158', '001159', '001160', '001161', '001162', '001163', '001164', '001166', '001167', '001168', '001169', '001170', '001171', '001172', '001173', '001174', '001175', '001176', '001177', '001178', '001179', '001180', '001181', '001182', '001183', '001184', '001185', '001186', '001187', '001188', '001189', '001190', '001191', '001192', '001193', '001194', '001195', '001196', '001197', '001198', '001199', '001200', '001201', '001202', '001203', '001204', '001205', '001206', '001207', '001208', '001209', '001210', '001211', '001212', '001213', '001214', '001216', '001217', '001218', '001219', '001220', '001221', '001222', '001223', '001224', '001225', '001226', '001227', '001228', '001229', '001230', '001231', '001232', '001233', '001234', '001236', '001237', '001238', '001239', '001240', '001241', '001242', '001243', '001244', '001246']

ValeursFoncieres-2023.txt
Unique values in 'No disposition':
['000001', '000002', '000003', '000004', '000005', '000006', '000007', '000008', '000009', '000010', '000011', '000012', '000013', '000014', '000015', '000016', '000017', '000018', '000019', '000020', '000021', '000022', '000023', '000024', '000025', '000026', '000027', '000028', '000029', '000030', '000031', '000032', '000033', '000034', '000035', '000036', '000037', '000038', '000039', '000040', '000041', '000042', '000043', '000044', '000045', '000046', '000047', '000048', '000049', '000050', '000051', '000052', '000053', '000054', '000055', '000056', '000057', '000058', '000059', '000060', '000061', '000062', '000063', '000064', '000065', '000066', '000067', '000068', '000069', '000070', '000071', '000072', '000073', '000074', '000075', '000076', '000077', '000078', '000079', '000080', '000081', '000082', '000083', '000084', '000085', '000086', '000087', '000088', '000089', '000090', '000091', '000092', '000093', '000094', '000095', '000096', '000097', '000098', '000099', '000100', '000101', '000102', '000103', '000104', '000105', '000106', '000107', '000108', '000109', '000110', '000111', '000112', '000113', '000114', '000115', '000116', '000117', '000118', '000119', '000120', '000121', '000122', '000123', '000124', '000125', '000126', '000127', '000128', '000129', '000130', '000131', '000132', '000133', '000134', '000135', '000136', '000137', '000138', '000139', '000140', '000141', '000142', '000143', '000144', '000145', '000146', '000147', '000148', '000149', '000150', '000151', '000152', '000153', '000154', '000155', '000156', '000157', '000158', '000159', '000160', '000161', '000162', '000163', '000164', '000165', '000166', '000167', '000168', '000169', '000170', '000171', '000172', '000173', '000174', '000175', '000176', '000177', '000178', '000179', '000180', '000181', '000182', '000183', '000184', '000185', '000186', '000187', '000188', '000189', '000190', '000191', '000192', '000193', '000194']

ValeursFoncieres-2024.txt
Unique values in 'No disposition':

### #️⃣ **CREATE unique ID: `transaction_id` & save each file as a CSV** 
**1 transaction → 1 to N rows**

Since No dispostion is reset every year and not quite expressive as an identifier we shall create our own unique transaction_id by combining these columns:

- date: transaction_date ()
- address: insee_code (combine dep_code with com_code)
- transaction_type: "Sale", "Sale in future state of completion", "Sale of unbuilt land","Exchange", "Auction", "Expropriation"
- property_value: use the float number without comma ","
- property_type: "House", "Apartment", "Outbuilding", "Industrial or commercial premises"
- surface_type: "Building", "Land", "Combined"
- property_surface (real_building_surface + land_surface)

**Make sure to drop No disposition in each file**

In [ ]:
Each file loop:
- convert file to csv 
- generate an ID column transaction_id
- drop No disposition column
- save :
ID_ValeursFoncieres_2020_S2.csv
ID_ValeursFoncieres_2021.csv
ID_ValeursFoncieres_2022.csv
ID_ValeursFoncieres_2023.csv
ID_ValeursFoncieres_2024.csv
ID_ValeursFoncieres_2025_S1.csv
- concat csv files into 1 big file call it CANCAT_ValeursFoncieres.csv

### **FROM 6 FILES to 1 - SAVE**

In [ ]:
save as CONCAT_ValeursFoncieres.csv

<hr>

## 1️⃣ STANDARDIZE NAMES


<style>
h1 {
    text-align: center;
    color: black;
    font-weight: bold;
}
</style>

<style>
h2 {
    text-align: left;
    color: black;
    font-weight: bold;
}
</style>

<style>
h3 {
    text-align: left;
    color: black;
    font-weight: bold;
}
</style>

<style>
h4 {
    text-align: left;
    color: black;
    font-weight: bold;
}
</style>
<hr>

→ WHY?  Ensure consistent naming style; Prevent coding errors and improve readability and collaboration with same standardized column names.

### **SHAPE & HEAD**

In [ ]:
import pandas as pd

FILE = "../data/processed/CONCAT_ValeursFoncieres.csv"
CHUNK_SIZE = 500_000

total_rows = 0
columns = None

for chunk in pd.read_csv(FILE, chunksize=CHUNK_SIZE, dtype=str):
    total_rows += len(chunk)
    if columns is None:
        columns = chunk.columns

print("Shape:", total_rows, "rows and", len(columns), "columns")

df_head = pd.read_csv(FILE, nrows=5, dtype=str)
display(df_head)

Shape: 20102739 rows and 43 columns

,Identifiant de document,Reference document,1 Articles CGI,2 Articles CGI,3 Articles CGI,4 Articles CGI,5 Articles CGI,No disposition,Date mutation,Nature mutation,Valeur fonciere,No voie,B/T/Q,Type de voie,Code voie,Voie,Code postal,Commune,Code departement,Code commune,Prefixe de section,Section,No plan,No Volume,1er lot,Surface Carrez du 1er lot,2eme lot,Surface Carrez du 2eme lot,3eme lot,Surface Carrez du 3eme lot,4eme lot,Surface Carrez du 4eme lot,5eme lot,Surface Carrez du 5eme lot,Nombre de lots,Code type local,Type local,Identifiant local,Surface reelle bati,Nombre pieces principales,Nature culture,Nature culture speciale,Surface terrain
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,000001,01/07/2020,Vente,"31234,16",NaN,NaN,NaN,B064,SAINT JULIEN,1560,SAINT-JULIEN-SUR-REYSSOUZE,01,367,NaN,A,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,AB,NaN,1192
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,000001,01/07/2020,Vente,"278000,00",NaN,NaN,NaN,B188,A LA PEROUSE,1250,CORVEISSIAT,01,125,NaN,C,509,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,BS,NaN,10092
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,000001,01/07/2020,Vente,"278000,00",NaN,NaN,NaN,B188,A LA PEROUSE,1250,CORVEISSIAT,01,125,NaN,C,510,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,L,NaN,4570
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,000001,01/07/2020,Vente,"278000,00",NaN,NaN,NaN,B079,AUX COMMUNS,1250,CORVEISSIAT,01,125,NaN,ZL,96,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,BS,NaN,5750
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,000001,01/07/2020,Vente,"278000,00",NaN,NaN,NaN,B033,EN COMBARNAUD,1250,SIMANDRE-SUR-SURAN,01,408,NaN,A,14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,BT,NaN,648170

### **INFO (sample)**

In [ ]:
FILE = "../data/processed/CONCAT_ValeursFoncieres.csv"
df_sample = pd.read_csv(FILE, nrows=100_000, dtype=str)
df_sample.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 35 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   No disposition              100000 non-null  object
 1   Date mutation               100000 non-null  object
 2   Nature mutation             100000 non-null  object
 3   Valeur fonciere             99092 non-null   object
 4   No voie                     59909 non-null   object
 5   B/T/Q                       3940 non-null    object
 6   Type de voie                56183 non-null   object
 7   Code voie                   98826 non-null   object
 8   Voie                        98826 non-null   object
 9   Code postal                 98826 non-null   object
 10  Commune                     100000 non-null  object
 11  Code departement            100000 non-null  object
 12  Code commune                100000 non-null  object
 13  Prefixe de section          1808 non-null    object
 14  Section                     99983 non-null   object
 15  No plan                     100000 non-null  object
 16  No Volume                   244 non-null     object
 17  1er lot                     37744 non-null   object
 18  Surface Carrez du 1er lot   11365 non-null   object
 19  2eme lot                    8057 non-null    object
 20  Surface Carrez du 2eme lot  3421 non-null    object
 21  3eme lot                    893 non-null     object
 22  Surface Carrez du 3eme lot  208 non-null     object
 23  4eme lot                    318 non-null     object
 24  Surface Carrez du 4eme lot  48 non-null      object
 25  5eme lot                    125 non-null     object
 26  Surface Carrez du 5eme lot  20 non-null      object
 27  Nombre de lots              100000 non-null  object
 28  Code type local             57654 non-null   object
 29  Type local                  57654 non-null   object
 30  Surface reelle bati         57573 non-null   object
 31  Nombre pieces principales   57573 non-null   object
 32  Nature culture              61772 non-null   object
 33  Nature culture speciale     2920 non-null    object
 34  Surface terrain             61772 non-null   object
dtypes: object(35)
memory usage: 26.7+ MB

### **INFO**

In [ ]:
import pandas as pd

FILE = "../data/processed/CONCAT_ValeursFoncieres.csv"
CHUNK_SIZE = 500_000

total_rows = 0
columns = None
non_null_counts = None
dtypes = None

for chunk in pd.read_csv(FILE, chunksize=CHUNK_SIZE, dtype=str):
    if columns is None:
        columns = chunk.columns.tolist()
        non_null_counts = {col: 0 for col in columns}
        dtypes = chunk.dtypes.astype(str).to_dict()

    total_rows += len(chunk)

    for col in columns:
        non_null_counts[col] += chunk[col].notna().sum()

# Build info-style summary
info_df = pd.DataFrame({
    "column": columns,
    "non_null_count": [non_null_counts[col] for col in columns],
    "null_count": [total_rows - non_null_counts[col] for col in columns],
    "dtype": [dtypes[col] for col in columns]
})

print(f"RangeIndex: {total_rows} entries, 0 to {total_rows - 1}")
print(f"Data columns (total {len(columns)} columns):")
display(info_df)
print(f"dtypes: {info_df['dtype'].value_counts().to_dict()}")
print(f"memory usage: not computed (chunked mode)")

RangeIndex: 20102739 entries, 0 to 20102738
Data columns (total 35 columns):

                        column  non_null_count  null_count   dtype
0               No disposition        20102739           0  object
1                Date mutation        20102739           0  object
2              Nature mutation        20102739           0  object
3              Valeur fonciere        19908349      194390  object
4                      No voie        12628228     7474511  object
5                        B/T/Q          905080    19197659  object
6                 Type de voie        12160680     7942059  object
7                    Code voie        19952257      150482  object
8                         Voie        19951476      151263  object
9                  Code postal        19951139      151600  object
10                     Commune        20102739           0  object
11            Code departement        20102739           0  object
12                Code commune        20102739           0  object
13          Prefixe de section          954922    19147817  object
14                     Section        20102014         725  object
15                     No plan        20102739           0  object
16                   No Volume           45381    20057358  object
17                     1er lot         6304273    13798466  object
18   Surface Carrez du 1er lot         1772926    18329813  object
19                    2eme lot         1848289    18254450  object
20  Surface Carrez du 2eme lot          570300    19532439  object
21                    3eme lot          331965    19770774  object
22  Surface Carrez du 3eme lot           64116    20038623  object
23                    4eme lot          108005    19994734  object
24  Surface Carrez du 4eme lot           15935    20086804  object
25                    5eme lot           48066    20054673  object
26  Surface Carrez du 5eme lot            5697    20097042  object
27              Nombre de lots        20102739           0  object
28             Code type local        11890422     8212317  object
29                  Type local        11890422     8212317  object
30         Surface reelle bati        11877616     8225123  object
31   Nombre pieces principales        11877616     8225123  object
32              Nature culture        13706037     6396702  object
33     Nature culture speciale          863125    19239614  object
34             Surface terrain        13706037     6396702  object

dtypes: {'object': 35}
memory usage: not computed (chunked mode)

### **UNIQUE VALUES & NULLS**

In [ ]:
from collections import defaultdict
import pandas as pd

FILE = "../data/processed/CONCAT_ValeursFoncieres.csv"

unique_values = defaultdict(set)
null_counts = defaultdict(int)
total_rows = 0

for chunk in pd.read_csv(
    FILE,
    chunksize=500_000,
    dtype=str,          # ✅ avoids mixed types warning
    low_memory=False
):
    total_rows += len(chunk)

    for col in chunk.columns:
        # ✅ Count nulls (DO NOT drop them)
        null_counts[col] += chunk[col].isna().sum()

        # ✅ Collect only non-null values (nulls are still preserved in dataset)
        unique_values[col].update(
            chunk.loc[chunk[col].notna(), col].unique()
        )

# --------------------------------------------------
# Display results
# --------------------------------------------------
print(f"\nTotal rows processed: {total_rows:,}")
print(100 * "-")

for col in unique_values:
    values = list(unique_values[col])
    null_pct = (null_counts[col] / total_rows) * 100

    print(f"➡️ {col}:")
    print(f"Unique values count: {len(values)}")
    print(f"Null count: {null_counts[col]} ({null_pct:.2f}%)")
    print(f"Sample values: {values[:120]}")
    print(100 * "-")

Total rows processed: 20,102,739
----------------------------------------------------------------------------------------------------
➡️ No disposition:
Unique values count: 1204
Null count: 0 (0.00%)
Sample values: ['000576', '000189', '000145', '000546', '000951', '001152', '001186', '000358', '001194', '000797', '000915', '000261', '000925', '001052', '000988', '000115', '001043', '000855', '000422', '000830', '000232', '000411', '001132', '001148', '000440', '001011', '000494', '000462', '000475', '001021', '001154', '000183', '000312', '001017', '001110', '000852', '000511', '000645', '000918', '000629', '000398', '000361', '001074', '000420', '000141', '000164', '000085', '000697', '000126', '000308', '000672', '001055', '000755', '000283', '000470', '000586', '000043', '000432', '001108', '000122', '000153', '000493', '001121', '000055', '000031', '000223', '000143', '000229', '000694', '000707', '000714', '001030', '000776', '000949', '000712', '000483', '000167', '000341', '000022', '000074', '000722', '000831', '001236', '000521', '000954', '001173', '000051', '000534', '000372', '000200', '000386', '000434', '000381', '000219', '000150', '000015', '000111', '000635', '000574', '000763', '000953', '000723', '000458', '001116', '000468', '000587', '000675', '001081', '001036', '000291', '001050', '000007', '000340', '000897', '001029', '000274', '000426', '001157', '000235', '000818']
----------------------------------------------------------------------------------------------------
➡️ Date mutation:
Unique values count: 1806
Null count: 0 (0.00%)
Sample values: ['05/11/2024', '10/12/2022', '16/08/2021', '14/09/2021', '21/12/2021', '17/04/2021', '11/12/2023', '28/08/2022', '18/11/2020', '10/07/2020', '01/03/2025', '29/10/2020', '07/08/2023', '04/03/2025', '14/01/2021', '10/10/2020', '24/05/2025', '22/12/2020', '08/09/2021', '09/12/2020', '19/11/2020', '05/04/2022', '18/08/2024', '27/11/2024', '20/01/2025', '25/12/2024', '27/05/2024', '02/09/2021', '03/08/2024', '05/10/2020', '16/06/2021', '22/02/2022', '11/08/2022', '22/07/2020', '25/05/2021', '09/12/2022', '09/03/2021', '05/06/2021', '04/02/2021', '03/01/2021', '26/12/2021', '10/04/2022', '01/05/2024', '22/08/2021', '31/10/2022', '28/05/2022', '26/12/2020', '07/02/2024', '20/08/2024', '01/04/2024', '07/06/2025', '15/01/2025', '12/10/2021', '28/04/2023', '28/09/2024', '04/06/2021', '06/11/2020', '18/05/2023', '04/05/2024', '09/10/2024', '25/11/2022', '27/06/2021', '13/09/2022', '05/02/2022', '26/08/2021', '31/01/2023', '15/01/2021', '26/11/2022', '08/02/2022', '03/06/2025', '12/11/2024', '21/05/2021', '28/10/2022', '12/12/2022', '27/04/2025', '02/04/2025', '21/09/2023', '23/02/2024', '04/05/2023', '13/12/2021', '11/10/2022', '09/01/2023', '27/08/2020', '06/04/2024', '04/04/2024', '20/09/2023', '01/09/2022', '25/03/2025', '17/12/2022', '27/04/2024', '07/07/2023', '15/08/2022', '24/09/2021', '16/07/2021', '23/08/2024', '20/11/2023', '09/01/2021', '03/06/2024', '02/08/2020', '13/10/2022', '29/06/2021', '15/07/2022', '28/06/2024', '13/12/2023', '21/05/2022', '29/04/2025', '25/03/2023', '19/06/2023', '26/12/2023', '10/08/2020', '03/09/2021', '15/07/2024', '19/08/2024', '31/05/2023', '02/04/2024', '08/12/2021', '30/01/2024', '06/12/2024', '11/04/2021', '23/08/2023']
----------------------------------------------------------------------------------------------------
➡️ Nature mutation:
Unique values count: 6
Null count: 0 (0.00%)
Sample values: ['Adjudication', 'Vente', 'Echange', 'Expropriation', "Vente en l'état futur d'achèvement", 'Vente terrain à bâtir']
----------------------------------------------------------------------------------------------------
➡️ Valeur fonciere:
Unique values count: 466667
Null count: 194390 (0.97%)
Sample values: ['177300,00', '55332,00', '789860,00', '191,50', '245355,00', '33915092,00', '167600,10', '411160,30', '655720,00', '127345,84', '399980,00', '1005232,00', '138767,00', '222052,80', '571650,00', '193924,00', '254820,00', '14842,80', '101323,20', '484330,00', '227165,00', '6594,48', '495812,00', '38917,99', '211028,47', '7940,80', '84933,00', '244675,00', '60910,00', '696696,00', '490364,00', '1026360,00', '451410,00', '321753,00', '22523,00', '293482,80', '5895,75', '125099,09', '172975,00', '977125,00', '714,24', '24708,40', '248233,00', '8438,63', '365986,00', '559640,00', '176648,00', '159965,00', '1416,15', '174618,00', '352365,00', '327184,00', '16690,00', '48450,02', '308333,34', '1324500,00', '49474,00', '2267,60', '74888,03', '127558,00', '442385,00', '688,86', '114266,00', '161942,31', '879646,70', '36257,58', '2986,00', '361337,50', '607520,00', '18309,79', '149860,00', '11609,00', '2531,00', '1319845,90', '124362,00', '222359,42', '234531,78', '140,00', '660550,00', '1513562,40', '283331,00', '138725,00', '1052,00', '175110,00', '200871,00', '844771,00', '1926700,00', '413830,00', '742140,00', '35904,16', '2017,50', '138378,00', '533959,56', '76501,00', '126481,10', '1707202,80', '1538500,00', '156805,00', '11784,14', '1936,00', '340460,00', '412260,00', '78295,00', '172790,00', '52440000,00', '422640,00', '229401,00', '42852,00', '531503,00', '694,00', '652080,00', '190855,00', '172972,80', '925231,00', '467262,00', '78705,00', '24943,48', '11287,96', '147854,00', '640430,00']
----------------------------------------------------------------------------------------------------
➡️ No voie:
Unique values count: 9126
Null count: 7474511 (37.18%)
Sample values: ['1593', '6491', '9325', '1525', '1633', '2142', '9257', '6309', '3822', '5999', '7504', '303', '3131', '3899', '9650', '1059', '4229', '3003', '8000', '7039', '5617', '4846', '7442', '5370', '4634', '6271', '5666', '2046', '6546', '567', '6078', '2555', '9834', '1450', '6830', '1579', '8207', '931', '2388', '276', '6549', '9057', '7234', '5629', '5793', '6131', '1812', '3818', '1788', '5212', '8890', '7473', '3636', '5058', '7416', '2233', '3254', '9229', '6388', '5308', '1270', '7581', '2641', '568', '9219', '2217', '2969', '8335', '4411', '4571', '3521', '9140', '5490', '888', '9960', '2666', '1071', '8163', '2315', '840', '9657', '2615', '6061', '2499', '7908', '6740', '3405', '2417', '7831', '5008', '4309', '2098', '5640', '2150', '9600', '9236', '3560', '2403', '2782', '5107', '6895', '9788', '7580', '3082', '4378', '1675', '1318', '5924', '9507', '126', '9975', '9389', '4218', '6689', '628', '305', '3631', '4681', '2770', '3430']
----------------------------------------------------------------------------------------------------
➡️ B/T/Q:
Unique values count: 40
Null count: 19197659 (95.50%)
Sample values: ['Y', 'b', 'E', 'K', '1', '3', 'F', 'V', 'N', 'T', 'G', 'B', 'Z', '2', 'H', '8', 'W', 'P', 'D', 'S', 'M', '9', '*', 'Q', '7', 'U', '-', '5', '4', 'R', 'O', 'J', '0', 'C', 'I', 'L', 'A', '.', 'X', '6']
----------------------------------------------------------------------------------------------------
➡️ Type de voie:
Unique values count: 152
Null count: 7942059 (39.51%)
Sample values: ['ESPA', 'HLE', 'PAS', 'QUA', 'GR', 'PAE', 'HLM', 'MAIL', 'COTE', 'VALL', 'COL', 'ALL', 'VTE', 'QUAI', 'PRT', 'CR', 'PLA', 'BORD', 'VIA', 'CHL', 'JTE', 'PLAG', 'PRV', 'PKG', 'CORO', 'TRA', 'CIVE', 'RULT', 'FOS', 'PCH', 'BRTL', 'AUT', 'DEVI', 'CAE', 'ZONE', 'ZUP', 'MAIS', 'CALL', 'VAL', 'DIG', 'TRAB', 'PLE', 'REM', 'PIST', 'CAN', 'ECL', 'ANGL', 'LOT', 'ZAC', 'D', 'VLA', 'CHEM', 'VOIE', 'BD', 'TSSE', 'ZAD', 'RIVE', 'ACH', 'VOUT', 'PTTE', 'VEN', 'RAC', 'PARC', 'CITE', 'LEVE', 'CRX', 'BSN', 'PLAN', 'CLOS', 'VCHE', 'PL', 'GAL', 'CC', 'HLG', 'FG', 'CHS', 'DRA', 'CHV', 'BRG', 'GPL', 'CRS', 'RLE', 'GARE', 'NTE', 'PTA', 'PASS', 'VIL', 'ZI', 'COIN', 'ART', 'DOM', 'N', 'MAR', 'SEN', 'CD', 'RTE', 'VC', 'COR', 'CLR', 'AGL', 'PTE', 'IMP', 'LICE', 'HAM', 'ILOT', 'SQ', 'CAMI', 'PONT', 'MRN', 'RTD', 'ESP', 'DSC', 'CAR', 'HAB', 'VOY', 'BRE', 'PORT', 'CPG', 'AV', 'STDE']
----------------------------------------------------------------------------------------------------
➡️ Code voie:
Unique values count: 20064
Null count: 150482 (0.75%)
Sample values: ['B680', '6491', 'H482', '9325', 'P363', 'G573', '8814', '1059', 'B146', 'G657', 'B130', 'C991', '5617', 'F928', 'F319', 'I462', '4634', 'F110', 'D515', '6546', 'F666', 'C982', '8621', '1579', 'Q578', '8207', 'C447', '8884', 'I753', 'I261', '9057', '5629', '1812', '8890', '5212', 'C707', 'B781', 'H801', '0322', '9229', 'I733', 'J379', 'A393', 'C387', 'H957', 'F062', '0289', 'C058', '2969', 'A152', '9140', '0998', 'C600', 'E032', 'D979', 'B083', 'E075', '4309', '2098', 'E652', 'B678', 'V163', '5107', '7580', '3082', 'D030', '9507', '9389', 'D558', '3631', 'E981', 'K422', 'H865', '5892', 'B506', 'I649', 'D918', '4158', 'X005', '7202', 'A621', '6907', '4479', '2333', '8296', 'X030', '6139', 'B474', 'D427', 'H123', '2162', '8743', 'E682', 'C195', 'E584', 'F311', 'G351', 'D105', 'D769', '3272', '6389', 'E650', '9437', 'E670', 'K468', '6698', 'B633', '2605', '2477', 'A747', '9544', '2342', 'H613', '9848', 'J124', '3946', 'D106', '0412', '6185', '4968']
----------------------------------------------------------------------------------------------------
➡️ Voie:
Unique values count: 1132199
Null count: 151263 (0.75%)
Sample values: ['MAGISTRAT SUD', 'DES AUTRES PLANETES', 'SOUS SAUNIAL', 'FERMI', 'DU CITIS', 'CHEZ KAKI', 'CHAMPS MARTIN MEUNIER', 'ETANG DE LA PRAZ', 'BOUIGUO DE MEDAN', 'DE TAURENS', 'LA CELLIERE', 'FEYPOT', 'KERTOUDIC', 'LE DEVINET', 'DU FAYET', 'LE COUSINIE', 'BOSSELEINE', 'LA HAIE A TROCHARD', 'GEORGES CHARRIER', 'BAS DE POMME D ARC', 'LES COSSES DU MAGNOU', 'MARCEL LAUTARD', 'DE PIED BLANC', 'LES CHAMPS ANSELME EST', 'DES ROSSANDES', 'LA SERSIOGRAND', 'GROS ROCHER', 'CLOS DU BOIS ROSSIGNOL', 'LA CHEVESSERIE', 'DE COURRIN', 'JAUREZE', 'LE PRE DU BREUX', 'LA BERTONNIE', 'LEVITE', 'CHODORELLE', 'GRANDS ARRAYIES', 'ABBE ARTARIT', 'LA LANDE DE LA GRANGE', 'DE FEBVRY', 'LE COTEAU DE LIQUET', 'LE GRAND ROQUEMARD', 'KERVAN GOAREM AR STANC', 'DES BOSCHETTES', 'CHEZ DAMOUR', 'DERRIERE LA TUVIERE', 'DE LA NAUZETTE', 'LE CHEMIN DE L ABBAYE AUX', 'DANIEL SAGE', 'AU VEZIS', 'L ECLATE', 'KERBLEUNIOU', 'LA DOUBRIE', 'HOUDENT', 'DE GATEBOURG', 'DES NOISETIERS (MARIGNE)', 'CAPIGRIGIO', 'LA BARATRIE', 'LA TAPINIERE', 'ROUTE DE LA SERRE', 'DES 3 FRERES', 'PAUL MARAIS', 'SOMBEZAU', 'FEMAJOLA', 'CASTIGUES-SUD', 'RULANOU', 'FRANGOUILLE', 'LES SOUPEES', 'A ENMANSOT', 'SOUS LA CORVEE', 'VALESCHIERAS EST', 'PUYLAGORGE', 'LEON HUTIN', 'JEAN MARIE JEGO', 'DOMINIQUE LAGRU', 'LES HARDINES DE BELZAISE', 'CHAMP SABATAY', 'DU PUITS DE LA FIGUIERE', 'LE PUISEUX', 'VERKEERDE BECQUE ET KLAP H', 'JOUR DE FETE', 'LE THUEST', 'LA CROTTE', 'EDMOND LABATUT', 'CONSOLANT-SUD', 'ESTRADE', 'PASTEUR DE VALANJOU', 'CAMP A REDON', 'FRANCIS LOPEZ', 'GDE PIECE CARREFOUR AMOURE', 'BOIS DES CERISIOUX', 'CAP DE NAOU', 'LE FOND DE PAIX', 'PIECE DU PRE BOTEREAU', 'LA HAYE CATIN', 'CARTIVET', 'CHEZ LES BARROCHINS', 'AU PUY DE LA FON', 'AU BOIRAT', 'PRAIRIE DE BEAULIEU', 'L HERARDIERE', 'PRE DU VAUX', 'AR VELANEC RUBRAS', 'VOTEN VILLAREC', 'EN VECHERE', 'DE L ECOTTAIS', 'LANDAOUDEC', 'LE PUY DE BEAU', 'QUELME', 'LA DUPRAIRIE', 'JULIOCOURT', 'BEAUVAIS D EN BAS', 'LAZEUYS', 'LA GILLOUARDIERE', 'LE MASLEMONGE', 'ROIDE FONTAINE', 'LA PIOT', 'LE PRE DE SEVREAU', 'VERGER DU PRE', 'LE HALLIOU', 'DES JOYEUSES VACANCES']
----------------------------------------------------------------------------------------------------
➡️ Code postal:
Unique values count: 5871
Null count: 151600 (0.75%)
Sample values: ['91440', '37110', '74410', '59400', '69560', '19130', '45370', '60160', '63710', '51360', '8000', '30480', '64800', '11270', '70440', '22450', '12720', '13850', '1450', '6830', '97225', '11140', '62158', '55270', '79460', '13750', '14860', '64520', '26570', '40990', '66670', '12630', '35200', '58440', '92000', '66680', '31700', '59180', '1270', '54450', '19300', '15100', '33350', '9140', '13830', '89430', '87140', '14850', '94430', '19290', '42430', '78250', '18500', '17640', '88100', '40260', '83420', '62132', '19330', '69170', '25870', '6740', '58230', '12210', '40560', '20244', '76910', '2150', '9600', '30760', '77660', '94290', '85250', '73000', '44600', '7580', '51140', '43260', '73800', '95570', '69910', '43340', '82340', '74330', '59157', '3430', '83600', '42360', '97470', '34920', '84130', '82390', '3290', '55230', '75005', '83143', '62100', '4370', '43290', '7200', '13610', '38530', '44310', '56400', '30840', '95520', '62460', '13111', '31370', '25530', '33430', '42740', '61800', '51460', '58500', '58240', '37400', '59154', '2450', '62131']
----------------------------------------------------------------------------------------------------
➡️ Commune:
Unique values count: 31569
Null count: 0 (0.00%)
Sample values: ['OUFFIERES', 'TAILLET', 'ICHY', 'EPECAMPS', 'LEIGNE-LES-BOIS', 'ANDON', 'LOMPNAS', 'BRAILLANS', 'AIGUEBELETTE-LE-LAC', 'LE VIEUX BOURG', 'PLANTY', 'MONLONG', 'PONTEILS-ET-BRESIS', 'SAINT-JAL', 'VALENCAY', 'CHAPONNAY', 'VARENNES-SOUS-DUN', 'CARSAN', 'SAINT-MARTIN-DU-LAC', 'CLERY-GRAND', 'VALLEROY-LE-SEC', 'ARIGNAC', 'NEVY-SUR-SEILLE', 'BEZANCOURT', 'AUMENANCOURT', 'GONDRECOURT-AIX', 'SAINT FLOUR', 'VINDRAC-ALAYRAC', 'HERMELINGHEN', 'BEAURAINS LES NOYON', 'CEAUX', 'BEAUTOT', 'NEUVELLE-LES-VOISEY', 'PEISEY-NANCROIX', 'BASSE-SUR-LE-RUPT', 'RIBECOURT DRESLINCOURT', 'SAINTE-ENGRACE', 'COURCELLES LES GISORS', 'ECLOSE-BADINIERES', 'SAINT-GERMAIN-DE-LIVET', 'METHAMIS', 'CABANNES', 'MARSANNAY-LE-BOIS', 'ESPEDAILLAC', 'BESSE SUR BRAYE', 'CARCANIERES', 'GALEY', 'BOUFFRY', 'ECHEVANNES', 'CESSIERES SUZY', 'SAINT-MARTIN-DU-TARTRE', 'VENOY', 'LICHERES-PRES-AIGREMONT', 'TROGUERY', 'VERGHEAS', 'PERRAY-EN-YVELINES (LE)', 'ST ANDRE DE L EURE', 'MOUCHY LE CHATEL', 'BEAUREVOIR', 'CUSSAC-SUR-LOIRE', 'CHATEAUNEUF-VAL-DE-BARGIS', 'FRONTENAC', 'RIGNOVELLE', 'VILLEFRANCHE-DU-PERIGORD', 'MAYAC', 'MESNIL-SAINT-DENIS (LE)', 'SEMILLY', 'VENTENAC', 'LETELON', 'BONNET', 'AVON LES ROCHES', 'MENIL ANNELLES', 'TUGERAS-SAINT-MAURICE', 'VARENNE-SAINT-GERMAIN', 'LA CHAPELLE HUON', 'BEAUCE LA ROMAINE', 'DIZIMIEU', 'VERT-TOULON', 'SAINT-MARTIN-LA-GARENNE', "GEUS D'OLORON", 'PERS-EN-GATINAIS', 'AVOCOURT', 'NARCY', 'CHEVREVILLE', 'ARPAVON', 'SERRE-NERPOL', 'RUPT', 'DERBAMONT', 'COLLEGIEN', 'OSTREVILLE', 'BIOULE', 'NOGNA', 'LE POISLAY', 'LES PAROCHES', 'ERVILLE-SUR-MER', 'SAINT-LEGER', 'VERS-SOUS-SELLIERES', 'PLESSIS-SAINT-BENOIST', 'MONTEAUX', 'SEPTVAUX', 'NANCY-SUR-CLUSES', 'LE CHATENET EN DOGNON', 'BONA', 'GRAND RIVIERE', 'TORCY-LE-GRAND', 'JONCHERE (LA)', 'CHAMPNETERY', 'FRANSECHES', 'HEUDREVILLE SUR EURE', 'VALGORGE', 'VIONS', 'LUZARCHES', 'SIX-FOURS-LES-PLAGES', 'MARVILLE MOUTIERS BRULE', 'ROUECOURT', 'BRIGNEMONT', 'CORPS', 'VILLANOVA', 'SENEUJOLS', 'VALLEROY']
----------------------------------------------------------------------------------------------------
➡️ Code departement:
Unique values count: 97
Null count: 0 (0.00%)
Sample values: ['34', '70', '02', '58', '14', '33', '41', '10', '31', '64', '84', '07', '55', '61', '2A', '79', '27', '51', '93', '29', '65', '69', '75', '52', '94', '01', '36', '48', '24', '26', '16', '08', '22', '11', '90', '13', '87', '60', '73', '83', '32', '49', '19', '56', '81', '45', '40', '66', '28', '72', '74', '95', '44', '37', '17', '972', '46', '43', '89', '59', '85', '03', '2B', '78', '86', '09', '21', '23', '76', '973', '62', '77', '971', '91', '92', '06', '63', '88', '53', '15', '25', '80', '54', '35', '82', '47', '71', '39', '12', '974', '05', '30', '50', '42', '18', '38', '04']
----------------------------------------------------------------------------------------------------
➡️ Code commune:
Unique values count: 908
Null count: 0 (0.00%)
Sample values: ['600', '577', '622', '112', '483', '373', '1', '301', '70', '645', '787', '635', '303', '736', '871', '164', '377', '408', '856', '344', '58', '14', '691', '148', '175', '474', '683', '494', '797', '726', '216', '244', '382', '593', '466', '55', '274', '547', '567', '410', '701', '821', '150', '199', '51', '499', '613', '779', '29', '6', '376', '276', '69', '403', '740', '798', '285', '677', '332', '298', '737', '760', '497', '94', '258', '26', '734', '846', '590', '449', '22', '731', '644', '295', '198', '318', '666', '520', '425', '414', '543', '479', '487', '490', '245', '90', '11', '568', '388', '898', '209', '409', '806', '309', '225', '909', '60', '269', '73', '275', '184', '19', '689', '862', '820', '588', '502', '888', '747', '262', '508', '385', '702', '346', '621', '323', '283', '480', '655', '554']
----------------------------------------------------------------------------------------------------
➡️ Prefixe de section:
Unique values count: 759
Null count: 19147817 (95.25%)
Sample values: ['577', '600', '622', '112', '483', '373', '1', '301', '70', '645', '635', '303', '871', '164', '377', '408', '856', '344', '58', '14', '691', '148', '175', '494', '216', '244', '382', '593', '466', '55', '274', '547', '567', '410', '701', '821', '150', '199', '51', '499', '29', '376', '6', '276', '69', '403', '285', '332', '298', '497', '94', '258', '26', '846', '449', '22', '414', '295', '198', '318', '644', '479', '520', '543', '245', '568', '90', '11', '388', '898', '409', '209', '806', '309', '225', '909', '60', '269', '73', '275', '184', '19', '820', '588', '502', '888', '508', '262', '385', '702', '621', '346', '323', '283', '480', '655', '192', '208', '840', '311', '104', '380', '484', '43', '618', '132', '331', '322', '59', '653', '248', '688', '564', '340', '473', '730', '78', '98', '906', '530']
----------------------------------------------------------------------------------------------------
➡️ Section:
Unique values count: 588
Null count: 725 (0.00%)
Sample values: ['OC', 'MH', 'VN', 'MJ', 'AD', 'RA', 'BR', 'ZR', 'SK', 'YK', 'LB', 'GF', 'WY', 'MN', 'SR', 'AK', 'RD', 'ES', 'YM', 'VX', 'IU', 'LV', 'NS', 'TR', 'TW', 'XM', 'HI', 'RM', 'WK', 'XB', 'XW', 'YC', 'FU', 'X', 'CS', 'TV', 'GN', 'SS', 'LP', 'YU', 'E', 'BS', 'NY', 'IG', 'GP', 'OH', 'ZZ', 'AH', 'BO', 'ZF', 'VW', 'RH', 'TH', 'AE', 'NB', 'YS', 'PZ', 'OP', 'YI', 'FL', 'HA', 'VB', 'DK', 'YJ', 'RT', 'BN', 'XA', 'PB', 'NR', 'YB', 'MT', 'MD', 'XO', 'AX', 'HV', 'ID', 'ST', 'FX', 'KK', 'WA', 'XK', 'HE', 'AC', 'YD', 'GB', 'OR', 'WV', 'BJ', 'T', 'DO', 'CD', 'DS', 'MM', 'BY', 'LI', 'TD', 'IC', 'BQ', 'LM', 'FM', 'JF', 'EM', 'OB', 'EB', 'RR', 'TT', 'MP', 'DM', 'FR', 'WB', 'YF', 'AZ', 'EV', 'CN', 'PH', 'TL', 'DW', 'TO', 'VR', 'NT']
----------------------------------------------------------------------------------------------------
➡️ No plan:
Unique values count: 8239
Null count: 0 (0.00%)
Sample values: ['1593', '6491', '9325', '1525', '1633', '2142', '6309', '3822', '5999', '7504', '303', '3131', '3899', '1059', '4229', '3003', '8000', '7039', '5617', '4846', '7442', '5370', '4634', '6271', '5666', '2046', '6546', '567', '6078', '2555', '9834', '1450', '6830', '1579', '3837', '931', '2388', '276', '6549', '7234', '5629', '6131', '5793', '1812', '3818', '1788', '5212', '7473', '3636', '5058', '2233', '3254', '9229', '6388', '5308', '1270', '7581', '2641', '568', '9219', '2217', '2969', '4411', '4571', '3521', '8395', '5490', '888', '2666', '1071', '8163', '2315', '4861', '840', '2615', '6061', '2499', '7908', '6740', '3405', '2417', '4309', '5008', '2098', '2150', '5640', '7950', '3560', '2403', '2782', '5107', '6895', '9788', '7580', '3082', '4378', '1318', '1675', '5924', '126', '4218', '6689', '628', '4672', '305', '3631', '4681', '2770', '3430', '5892', '369', '4868', '3290', '1674', '7644', '2232', '4158', '6268', '4841', '652']
----------------------------------------------------------------------------------------------------
➡️ No Volume:
Unique values count: 2068
Null count: 20057358 (99.77%)

### **DATASET TABLE V1 (Original vs Standard Names)**

| #  | Original Column Name           | Standardized            | Description                                  |
| -- | ------------------------------ | ----------------------- | -------------------------------------------- |
| 0  | **No disposition**             | `transaction_id`        | Unique identifier of the transaction         |
| 1  | **Date mutation**              | `transaction_date`      | Date when the property was sold              |
| 2  | **Nature mutation**            | `transaction_type`      | Nature of transaction (sale, exchange, etc.) |
| 3  | **Valeur fonciere**            | `property_value`        | Transaction price in euros                   |
| 4  | **No voie**                    | `street_number`         | Street number of the property                |
| 5  | **B/T/Q**                      | `btq_code`              | Building / Type / Quarter code               |
| 6  | **Type de voie**               | `street_type`           | Type of street (Rue, Avenue, etc.)           |
| 7  | **Code voie**                  | `street_id`             | Street identifier code                       |
| 8  | **Voie**                       | `street_name`           | Full street name                             |
| 9  | **Code postal**                | `postal_code`           | Postal code (categorical, not numeric)       |
| 10 | **Commune**                    | `com_name`              | Commune name                                 |
| 11 | **Code departement**           | `dep_code`              | Department code: DD                          |
| 12 | **Code commune**               | `com_code`              | Commune code: CCC                            |
| 13 | **Prefixe de section**         | `section_prefix`        | Section prefix (cadastral division)          |
| 14 | **Section**                    | `section`               | Cadastral section identifier                 |
| 15 | **No plan**                    | `plot_number`           | Parcel/plot number                           |
| 16 | **No Volume**                  | `volume_number`         | Volume number (rarely used cadastral info)   |
| 17 | **1er lot**                    | `lot_1`                 | Identifier of the first lot                  |
| 18 | **Surface Carrez du 1er lot**  | `lot_1_surface`         | Carrez surface of the first lot (m²)         |
| 19 | **2eme lot**                   | `lot_2`                 | Identifier of the second lot                 |
| 20 | **Surface Carrez du 2eme lot** | `lot_2_surface`         | Carrez surface of the second lot (m²)        |
| 21 | **3eme lot**                   | `lot_3`                 | Identifier of the third lot                  |
| 22 | **Surface Carrez du 3eme lot** | `lot_3_surface`         | Carrez surface of the third lot (m²)         |
| 23 | **4eme lot**                   | `lot_4`                 | Identifier of the fourth lot                 |
| 24 | **Surface Carrez du 4eme lot** | `lot_4_surface`         | Carrez surface of the fourth lot (m²)        |
| 25 | **5eme lot**                   | `lot_5`                 | Identifier of the fifth lot                  |
| 26 | **Surface Carrez du 5eme lot** | `lot_5_surface`         | Carrez surface of the fifth lot (m²)         |
| 27 | **Nombre de lots**             | `lots_count`            | Number of lots in the transaction            |
| 28 | **Code type local**            | `property_type_code`    | Code for property type                       |
| 29 | **Type local**                 | `property_type`         | Property type (Apartment, House, etc.)       |
| 30 | **Surface reelle bati**        | `building_real_surface` | Built area in square meters                  |
| 31 | **Nombre pieces principales**  | `main_rooms_count`      | Number of main rooms                         |
| 32 | **Nature culture**             | `land_nature`           | Type of land usage                           |
| 33 | **Nature culture speciale**    | `land_nature_special`   | Specific land usage classification           |
| 34 | **Surface terrain**            | `land_surface`          | Land area in square meters                   |

### **RENAME COLUMNS**

In [ ]:
from pathlib import Path
import pandas as pd

INPUT_FILE = Path("../data/processed/CONCAT_ValeursFoncieres.csv")
OUTPUT_FILE = Path("../data/processed/STANDARD_ValeursFoncieres.csv")

CHUNK_SIZE = 500_000

# ---------------------------------------------
# Define the renaming dictionary
# ---------------------------------------------
rename_columns = {
    "No disposition": "transaction_id",
    "Date mutation": "transaction_date",
    "Nature mutation": "transaction_type",
    "Valeur fonciere": "property_value",
    "No voie": "street_number",
    "B/T/Q": "btq_code",
    "Type de voie": "street_type",
    "Code voie": "street_id",
    "Voie": "street_name",
    "Code postal": "postal_code",
    "Commune": "com_name",
    "Code departement": "dep_code",
    "Code commune": "com_code",
    "Prefixe de section": "section_prefix",
    "Section": "section",
    "No plan": "plot_number",
    "No Volume": "volume_number",

    # Lot identifier and surface
    "1er lot": "lot_1",
    "Surface Carrez du 1er lot": "lot_1_surface",
    "2eme lot": "lot_2",
    "Surface Carrez du 2eme lot": "lot_2_surface",
    "3eme lot": "lot_3",
    "Surface Carrez du 3eme lot": "lot_3_surface",
    "4eme lot": "lot_4",
    "Surface Carrez du 4eme lot": "lot_4_surface",
    "5eme lot": "lot_5",
    "Surface Carrez du 5eme lot": "lot_5_surface",

    "Nombre de lots": "lots_count",

    "Code type local": "property_type_code",
    "Type local": "property_type",
    "Surface reelle bati": "building_real_surface",
    "Nombre pieces principales": "main_rooms_count",
    "Nature culture": "land_nature",
    "Nature culture speciale": "land_nature_special",
    "Surface terrain": "land_surface",
}

def rename_columns_chunked(
    input_file: Path,
    output_file: Path,
    rename_dict: dict,
    chunk_size: int = 50_000
) -> None:
    output_file.parent.mkdir(parents=True, exist_ok=True)

    first_write = True
    total_rows = 0

    for chunk_idx, chunk in enumerate(
        pd.read_csv(input_file, chunksize=chunk_size, dtype=str),
        start=1
    ):
        chunk = chunk.rename(columns=rename_dict)

        chunk.to_csv(
            output_file,
            mode="w" if first_write else "a",
            index=False,
            header=first_write,
            encoding="utf-8"
        )

        first_write = False
        total_rows += len(chunk)

        print(f"Chunk {chunk_idx} written -> {len(chunk):,} rows | total: {total_rows:,}")

    print("\n✅ Done! Standardized columns")
    print(f"Saved file: {output_file}")
    print(f"Shape: {total_rows:,} rows and {len(rename_dict)} columns")

rename_columns_chunked(INPUT_FILE, OUTPUT_FILE, rename_columns, CHUNK_SIZE)

Chunk 1 written -> 500,000 rows | total: 500,000
Chunk 2 written -> 500,000 rows | total: 1,000,000
Chunk 3 written -> 500,000 rows | total: 1,500,000
Chunk 4 written -> 500,000 rows | total: 2,000,000
Chunk 5 written -> 500,000 rows | total: 2,500,000
Chunk 6 written -> 500,000 rows | total: 3,000,000
Chunk 7 written -> 500,000 rows | total: 3,500,000
Chunk 8 written -> 500,000 rows | total: 4,000,000
Chunk 9 written -> 500,000 rows | total: 4,500,000
Chunk 10 written -> 500,000 rows | total: 5,000,000
Chunk 11 written -> 500,000 rows | total: 5,500,000
Chunk 12 written -> 500,000 rows | total: 6,000,000
Chunk 13 written -> 500,000 rows | total: 6,500,000
Chunk 14 written -> 500,000 rows | total: 7,000,000
Chunk 15 written -> 500,000 rows | total: 7,500,000
Chunk 16 written -> 500,000 rows | total: 8,000,000
Chunk 17 written -> 500,000 rows | total: 8,500,000
Chunk 18 written -> 500,000 rows | total: 9,000,000
Chunk 19 written -> 500,000 rows | total: 9,500,000
Chunk 20 written -> 500,000 rows | total: 10,000,000
Chunk 21 written -> 500,000 rows | total: 10,500,000
Chunk 22 written -> 500,000 rows | total: 11,000,000
Chunk 23 written -> 500,000 rows | total: 11,500,000
Chunk 24 written -> 500,000 rows | total: 12,000,000
Chunk 25 written -> 500,000 rows | total: 12,500,000
Chunk 26 written -> 500,000 rows | total: 13,000,000
Chunk 27 written -> 500,000 rows | total: 13,500,000
Chunk 28 written -> 500,000 rows | total: 14,000,000
Chunk 29 written -> 500,000 rows | total: 14,500,000
Chunk 30 written -> 500,000 rows | total: 15,000,000
Chunk 31 written -> 500,000 rows | total: 15,500,000
Chunk 32 written -> 500,000 rows | total: 16,000,000
Chunk 33 written -> 500,000 rows | total: 16,500,000
Chunk 34 written -> 500,000 rows | total: 17,000,000
Chunk 35 written -> 500,000 rows | total: 17,500,000
Chunk 36 written -> 500,000 rows | total: 18,000,000
Chunk 37 written -> 500,000 rows | total: 18,500,000
Chunk 38 written -> 500,000 rows | total: 19,000,000
Chunk 39 written -> 500,000 rows | total: 19,500,000
Chunk 40 written -> 500,000 rows | total: 20,000,000
Chunk 41 written -> 102,739 rows | total: 20,102,739

✅ Done! Standardized columns
Saved file: ..\data\processed\STANDARD_ValeursFoncieres.csv
Shape: 20,102,739 rows and 35 columns

<hr>

## 2️⃣ INVALID VALUES


<style>
h1 {
    text-align: center;
    color: black;
    font-weight: bold;
}
</style>

<style>
h2 {
    text-align: left;
    color: black;
    font-weight: bold;
}
</style>

<style>
h3 {
    text-align: left;
    color: black;
    font-weight: bold;
}
</style>

<style>
h4 {
    text-align: left;
    color: black;
    font-weight: bold;
}
</style>
<hr>

→ WHY? Ensure logical consistency of values in each column

### **SHAPE & HEAD**

In [7]:
import pandas as pd

FILE = "../data/processed/STANDARD_ValeursFoncieres.csv"
CHUNK_SIZE = 500_000

total_rows = 0
columns = None

for chunk in pd.read_csv(FILE, chunksize=CHUNK_SIZE, dtype=str):
    total_rows += len(chunk)
    if columns is None:
        columns = chunk.columns

print("Shape:", total_rows, "rows and", len(columns), "columns")

df_head = pd.read_csv(FILE, nrows=5, dtype=str)
display(df_head)

Shape: 20102739 rows and 35 columns

,transaction_id,transaction_date,transaction_type,property_value,street_number,btq_code,street_type,street_id,street_name,postal_code,com_name,dep_code,com_code,section_prefix,section,plot_number,volume_number,lot_1,lot_1_surface,lot_2,lot_2_surface,lot_3,lot_3_surface,lot_4,lot_4_surface,lot_5,lot_5_surface,lots_count,property_type_code,property_type,building_real_surface,main_rooms_count,land_nature,land_nature_special,land_surface
0,000001,01/07/2020,Vente,"31234,16",NaN,NaN,NaN,B064,SAINT JULIEN,1560,SAINT-JULIEN-SUR-REYSSOUZE,01,367,NaN,A,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,AB,NaN,1192
1,000001,01/07/2020,Vente,"278000,00",NaN,NaN,NaN,B188,A LA PEROUSE,1250,CORVEISSIAT,01,125,NaN,C,509,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,BS,NaN,10092
2,000001,01/07/2020,Vente,"278000,00",NaN,NaN,NaN,B188,A LA PEROUSE,1250,CORVEISSIAT,01,125,NaN,C,510,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,L,NaN,4570
3,000001,01/07/2020,Vente,"278000,00",NaN,NaN,NaN,B079,AUX COMMUNS,1250,CORVEISSIAT,01,125,NaN,ZL,96,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,BS,NaN,5750
4,000001,01/07/2020,Vente,"278000,00",NaN,NaN,NaN,B033,EN COMBARNAUD,1250,SIMANDRE-SUR-SURAN,01,408,NaN,A,14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,BT,NaN,648170

### **INFO**

In [8]:
import pandas as pd

FILE = "../data/processed/STANDARD_ValeursFoncieres.csv"
CHUNK_SIZE = 500_000

total_rows = 0
columns = None
non_null_counts = None
dtypes = None

for chunk in pd.read_csv(FILE, chunksize=CHUNK_SIZE, dtype=str):
    if columns is None:
        columns = chunk.columns.tolist()
        non_null_counts = {col: 0 for col in columns}
        dtypes = chunk.dtypes.astype(str).to_dict()

    total_rows += len(chunk)

    for col in columns:
        non_null_counts[col] += chunk[col].notna().sum()

# Build info-style summary
info_df = pd.DataFrame({
    "column": columns,
    "non_null_count": [non_null_counts[col] for col in columns],
    "null_count": [total_rows - non_null_counts[col] for col in columns],
    "dtype": [dtypes[col] for col in columns]
})

print(f"RangeIndex: {total_rows} entries, 0 to {total_rows - 1}")
print(f"Data columns (total {len(columns)} columns):")
display(info_df)
print(f"dtypes: {info_df['dtype'].value_counts().to_dict()}")
print(f"memory usage: not computed (chunked mode)")

RangeIndex: 20102739 entries, 0 to 20102738
Data columns (total 35 columns):

                   column  non_null_count  null_count   dtype
0          transaction_id        20102739           0  object
1        transaction_date        20102739           0  object
2        transaction_type        20102739           0  object
3          property_value        19908349      194390  object
4           street_number        12628228     7474511  object
5                btq_code          905080    19197659  object
6             street_type        12160680     7942059  object
7               street_id        19952257      150482  object
8             street_name        19951476      151263  object
9             postal_code        19951139      151600  object
10               com_name        20102739           0  object
11               dep_code        20102739           0  object
12               com_code        20102739           0  object
13         section_prefix          954922    19147817  object
14                section        20102014         725  object
15            plot_number        20102739           0  object
16          volume_number           45381    20057358  object
17                  lot_1         6304273    13798466  object
18          lot_1_surface         1772926    18329813  object
19                  lot_2         1848289    18254450  object
20          lot_2_surface          570300    19532439  object
21                  lot_3          331965    19770774  object
22          lot_3_surface           64116    20038623  object
23                  lot_4          108005    19994734  object
24          lot_4_surface           15935    20086804  object
25                  lot_5           48066    20054673  object
26          lot_5_surface            5697    20097042  object
27             lots_count        20102739           0  object
28     property_type_code        11890422     8212317  object
29          property_type        11890422     8212317  object
30  building_real_surface        11877616     8225123  object
31       main_rooms_count        11877616     8225123  object
32            land_nature        13706037     6396702  object
33    land_nature_special          863125    19239614  object
34           land_surface        13706037     6396702  object

dtypes: {'object': 35}
memory usage: not computed (chunked mode)

### **UNIQUE VALUES & NULLS**

In [9]:
from collections import defaultdict
import pandas as pd

FILE = "../data/processed/STANDARD_ValeursFoncieres.csv"

unique_values = defaultdict(set)
null_counts = defaultdict(int)
total_rows = 0

for chunk in pd.read_csv(
    FILE,
    chunksize=500_000,
    dtype=str,          # ✅ avoids mixed types warning
    low_memory=False
):
    total_rows += len(chunk)

    for col in chunk.columns:
        # ✅ Count nulls (DO NOT drop them)
        null_counts[col] += chunk[col].isna().sum()

        # ✅ Collect only non-null values (nulls are still preserved in dataset)
        unique_values[col].update(
            chunk.loc[chunk[col].notna(), col].unique()
        )

# --------------------------------------------------
# Display results
# --------------------------------------------------
print(f"\nTotal rows processed: {total_rows:,}")
print(100 * "-")

for col in unique_values:
    values = list(unique_values[col])
    null_pct = (null_counts[col] / total_rows) * 100

    print(f"➡️ {col}:")
    print(f"Unique values count: {len(values)}")
    print(f"Null count: {null_counts[col]} ({null_pct:.2f}%)")
    print(f"Sample values: {values[:120]}")
    print(100 * "-")

Total rows processed: 20,102,739
----------------------------------------------------------------------------------------------------
➡️ transaction_id:
Unique values count: 1204
Null count: 0 (0.00%)
Sample values: ['000576', '000189', '000145', '000546', '000951', '001152', '001186', '000358', '001194', '000797', '000915', '000261', '000925', '001052', '000988', '000115', '001043', '000855', '000422', '000830', '000232', '000411', '001132', '001148', '000440', '001011', '000494', '000462', '000475', '001021', '001154', '000183', '000312', '001017', '001110', '000852', '000511', '000645', '000918', '000629', '000398', '000361', '001074', '000420', '000141', '000164', '000085', '000697', '000126', '000308', '000672', '001055', '000755', '000283', '000470', '000586', '000043', '000432', '001108', '000122', '000153', '000493', '001121', '000055', '000031', '000223', '000143', '000229', '000694', '000707', '000714', '001030', '000776', '000949', '000712', '000483', '000167', '000341', '000022', '000074', '000722', '000831', '001236', '000521', '000954', '001173', '000051', '000534', '000372', '000200', '000386', '000434', '000381', '000219', '000150', '000015', '000111', '000635', '000574', '000763', '000953', '000723', '000458', '001116', '000468', '000587', '000675', '001081', '001036', '000291', '001050', '000007', '000340', '000897', '001029', '000274', '000426', '001157', '000235', '000818']
----------------------------------------------------------------------------------------------------
➡️ transaction_date:
Unique values count: 1806
Null count: 0 (0.00%)
Sample values: ['05/11/2024', '10/12/2022', '16/08/2021', '14/09/2021', '21/12/2021', '17/04/2021', '11/12/2023', '28/08/2022', '18/11/2020', '10/07/2020', '01/03/2025', '29/10/2020', '07/08/2023', '04/03/2025', '14/01/2021', '10/10/2020', '24/05/2025', '22/12/2020', '08/09/2021', '09/12/2020', '19/11/2020', '05/04/2022', '18/08/2024', '27/11/2024', '20/01/2025', '25/12/2024', '27/05/2024', '02/09/2021', '03/08/2024', '05/10/2020', '16/06/2021', '22/02/2022', '11/08/2022', '22/07/2020', '25/05/2021', '09/12/2022', '09/03/2021', '05/06/2021', '04/02/2021', '03/01/2021', '26/12/2021', '10/04/2022', '01/05/2024', '22/08/2021', '31/10/2022', '28/05/2022', '26/12/2020', '07/02/2024', '20/08/2024', '01/04/2024', '07/06/2025', '15/01/2025', '12/10/2021', '28/04/2023', '28/09/2024', '04/06/2021', '06/11/2020', '18/05/2023', '04/05/2024', '09/10/2024', '25/11/2022', '27/06/2021', '13/09/2022', '05/02/2022', '26/08/2021', '31/01/2023', '15/01/2021', '26/11/2022', '08/02/2022', '03/06/2025', '12/11/2024', '21/05/2021', '28/10/2022', '12/12/2022', '27/04/2025', '02/04/2025', '21/09/2023', '23/02/2024', '04/05/2023', '13/12/2021', '11/10/2022', '09/01/2023', '27/08/2020', '06/04/2024', '04/04/2024', '20/09/2023', '01/09/2022', '25/03/2025', '17/12/2022', '27/04/2024', '07/07/2023', '15/08/2022', '24/09/2021', '16/07/2021', '23/08/2024', '20/11/2023', '09/01/2021', '03/06/2024', '02/08/2020', '13/10/2022', '29/06/2021', '15/07/2022', '28/06/2024', '13/12/2023', '21/05/2022', '29/04/2025', '25/03/2023', '19/06/2023', '26/12/2023', '10/08/2020', '03/09/2021', '15/07/2024', '19/08/2024', '31/05/2023', '02/04/2024', '08/12/2021', '30/01/2024', '06/12/2024', '11/04/2021', '23/08/2023']
----------------------------------------------------------------------------------------------------
➡️ transaction_type:
Unique values count: 6
Null count: 0 (0.00%)
Sample values: ['Adjudication', 'Vente', 'Echange', 'Expropriation', "Vente en l'état futur d'achèvement", 'Vente terrain à bâtir']
----------------------------------------------------------------------------------------------------
➡️ property_value:
Unique values count: 466667
Null count: 194390 (0.97%)
Sample values: ['177300,00', '55332,00', '789860,00', '191,50', '245355,00', '33915092,00', '167600,10', '411160,30', '655720,00', '127345,84', '399980,00', '1005232,00', '138767,00', '222052,80', '571650,00', '193924,00', '254820,00', '14842,80', '101323,20', '484330,00', '227165,00', '6594,48', '495812,00', '38917,99', '211028,47', '7940,80', '84933,00', '244675,00', '60910,00', '696696,00', '490364,00', '1026360,00', '451410,00', '321753,00', '22523,00', '293482,80', '5895,75', '125099,09', '172975,00', '977125,00', '714,24', '24708,40', '248233,00', '8438,63', '365986,00', '559640,00', '176648,00', '159965,00', '1416,15', '174618,00', '352365,00', '327184,00', '16690,00', '48450,02', '308333,34', '1324500,00', '49474,00', '2267,60', '74888,03', '127558,00', '442385,00', '688,86', '114266,00', '161942,31', '879646,70', '36257,58', '2986,00', '361337,50', '607520,00', '18309,79', '149860,00', '11609,00', '2531,00', '1319845,90', '124362,00', '222359,42', '234531,78', '140,00', '660550,00', '1513562,40', '283331,00', '138725,00', '1052,00', '175110,00', '200871,00', '844771,00', '1926700,00', '413830,00', '742140,00', '35904,16', '2017,50', '138378,00', '533959,56', '76501,00', '126481,10', '1707202,80', '1538500,00', '156805,00', '11784,14', '1936,00', '340460,00', '412260,00', '78295,00', '172790,00', '52440000,00', '422640,00', '229401,00', '42852,00', '531503,00', '694,00', '652080,00', '190855,00', '172972,80', '925231,00', '467262,00', '78705,00', '24943,48', '11287,96', '147854,00', '640430,00']
----------------------------------------------------------------------------------------------------
➡️ street_number:
Unique values count: 9126
Null count: 7474511 (37.18%)
Sample values: ['1593', '6491', '9325', '1525', '1633', '2142', '9257', '6309', '3822', '5999', '7504', '303', '3131', '3899', '9650', '1059', '4229', '3003', '8000', '7039', '5617', '4846', '7442', '5370', '4634', '6271', '5666', '2046', '6546', '567', '6078', '2555', '9834', '1450', '6830', '1579', '8207', '931', '2388', '276', '6549', '9057', '7234', '5629', '5793', '6131', '1812', '3818', '1788', '5212', '8890', '7473', '3636', '5058', '7416', '2233', '3254', '9229', '6388', '5308', '1270', '7581', '2641', '568', '9219', '2217', '2969', '8335', '4411', '4571', '3521', '9140', '5490', '888', '9960', '2666', '1071', '8163', '2315', '840', '9657', '2615', '6061', '2499', '7908', '6740', '3405', '2417', '7831', '5008', '4309', '2098', '5640', '2150', '9600', '9236', '3560', '2403', '2782', '5107', '6895', '9788', '7580', '3082', '4378', '1675', '1318', '5924', '9507', '126', '9975', '9389', '4218', '6689', '628', '305', '3631', '4681', '2770', '3430']
----------------------------------------------------------------------------------------------------
➡️ btq_code:
Unique values count: 40
Null count: 19197659 (95.50%)
Sample values: ['Y', 'b', 'E', 'K', '1', '3', 'F', 'V', 'N', 'T', 'G', 'B', 'Z', '2', 'H', '8', 'W', 'P', 'D', 'S', 'M', '9', '*', 'Q', '7', 'U', '-', '5', '4', 'R', 'O', 'J', '0', 'C', 'I', 'L', 'A', '.', 'X', '6']
----------------------------------------------------------------------------------------------------
➡️ street_type:
Unique values count: 152
Null count: 7942059 (39.51%)
Sample values: ['ESPA', 'HLE', 'PAS', 'QUA', 'GR', 'PAE', 'HLM', 'MAIL', 'COTE', 'VALL', 'COL', 'ALL', 'VTE', 'QUAI', 'PRT', 'CR', 'PLA', 'BORD', 'VIA', 'CHL', 'JTE', 'PLAG', 'PRV', 'PKG', 'CORO', 'TRA', 'CIVE', 'RULT', 'FOS', 'PCH', 'BRTL', 'AUT', 'DEVI', 'CAE', 'ZONE', 'ZUP', 'MAIS', 'CALL', 'VAL', 'DIG', 'TRAB', 'PLE', 'REM', 'PIST', 'CAN', 'ECL', 'ANGL', 'LOT', 'ZAC', 'D', 'VLA', 'CHEM', 'VOIE', 'BD', 'TSSE', 'ZAD', 'RIVE', 'ACH', 'VOUT', 'PTTE', 'VEN', 'RAC', 'PARC', 'CITE', 'LEVE', 'CRX', 'BSN', 'PLAN', 'CLOS', 'VCHE', 'PL', 'GAL', 'CC', 'HLG', 'FG', 'CHS', 'DRA', 'CHV', 'BRG', 'GPL', 'CRS', 'RLE', 'GARE', 'NTE', 'PTA', 'PASS', 'VIL', 'ZI', 'COIN', 'ART', 'DOM', 'N', 'MAR', 'SEN', 'CD', 'RTE', 'VC', 'COR', 'CLR', 'AGL', 'PTE', 'IMP', 'LICE', 'HAM', 'ILOT', 'SQ', 'CAMI', 'PONT', 'MRN', 'RTD', 'ESP', 'DSC', 'CAR', 'HAB', 'VOY', 'BRE', 'PORT', 'CPG', 'AV', 'STDE']
----------------------------------------------------------------------------------------------------
➡️ street_id:
Unique values count: 20064
Null count: 150482 (0.75%)
Sample values: ['B680', '6491', 'H482', '9325', 'P363', 'G573', '8814', '1059', 'B146', 'G657', 'B130', 'C991', '5617', 'F928', 'F319', 'I462', '4634', 'F110', 'D515', '6546', 'F666', 'C982', '8621', '1579', 'Q578', '8207', 'C447', '8884', 'I753', 'I261', '9057', '5629', '1812', '8890', '5212', 'C707', 'B781', 'H801', '0322', '9229', 'I733', 'J379', 'A393', 'C387', 'H957', 'F062', '0289', 'C058', '2969', 'A152', '9140', '0998', 'C600', 'E032', 'D979', 'B083', 'E075', '4309', '2098', 'E652', 'B678', 'V163', '5107', '7580', '3082', 'D030', '9507', '9389', 'D558', '3631', 'E981', 'K422', 'H865', '5892', 'B506', 'I649', 'D918', '4158', 'X005', '7202', 'A621', '6907', '4479', '2333', '8296', 'X030', '6139', 'B474', 'D427', 'H123', '2162', '8743', 'E682', 'C195', 'E584', 'F311', 'G351', 'D105', 'D769', '3272', '6389', 'E650', '9437', 'E670', 'K468', '6698', 'B633', '2605', '2477', 'A747', '9544', '2342', 'H613', '9848', 'J124', '3946', 'D106', '0412', '6185', '4968']
----------------------------------------------------------------------------------------------------
➡️ street_name:
Unique values count: 1132199
Null count: 151263 (0.75%)
Sample values: ['MAGISTRAT SUD', 'DES AUTRES PLANETES', 'SOUS SAUNIAL', 'FERMI', 'DU CITIS', 'CHEZ KAKI', 'CHAMPS MARTIN MEUNIER', 'ETANG DE LA PRAZ', 'BOUIGUO DE MEDAN', 'DE TAURENS', 'LA CELLIERE', 'FEYPOT', 'KERTOUDIC', 'LE DEVINET', 'DU FAYET', 'LE COUSINIE', 'BOSSELEINE', 'LA HAIE A TROCHARD', 'GEORGES CHARRIER', 'BAS DE POMME D ARC', 'LES COSSES DU MAGNOU', 'MARCEL LAUTARD', 'DE PIED BLANC', 'LES CHAMPS ANSELME EST', 'DES ROSSANDES', 'LA SERSIOGRAND', 'GROS ROCHER', 'CLOS DU BOIS ROSSIGNOL', 'LA CHEVESSERIE', 'DE COURRIN', 'JAUREZE', 'LE PRE DU BREUX', 'LA BERTONNIE', 'LEVITE', 'CHODORELLE', 'GRANDS ARRAYIES', 'ABBE ARTARIT', 'LA LANDE DE LA GRANGE', 'DE FEBVRY', 'LE COTEAU DE LIQUET', 'LE GRAND ROQUEMARD', 'KERVAN GOAREM AR STANC', 'DES BOSCHETTES', 'CHEZ DAMOUR', 'DERRIERE LA TUVIERE', 'DE LA NAUZETTE', 'LE CHEMIN DE L ABBAYE AUX', 'DANIEL SAGE', 'AU VEZIS', 'L ECLATE', 'KERBLEUNIOU', 'LA DOUBRIE', 'HOUDENT', 'DE GATEBOURG', 'DES NOISETIERS (MARIGNE)', 'CAPIGRIGIO', 'LA BARATRIE', 'LA TAPINIERE', 'ROUTE DE LA SERRE', 'DES 3 FRERES', 'PAUL MARAIS', 'SOMBEZAU', 'FEMAJOLA', 'CASTIGUES-SUD', 'RULANOU', 'FRANGOUILLE', 'LES SOUPEES', 'A ENMANSOT', 'SOUS LA CORVEE', 'VALESCHIERAS EST', 'PUYLAGORGE', 'LEON HUTIN', 'JEAN MARIE JEGO', 'DOMINIQUE LAGRU', 'LES HARDINES DE BELZAISE', 'CHAMP SABATAY', 'DU PUITS DE LA FIGUIERE', 'LE PUISEUX', 'VERKEERDE BECQUE ET KLAP H', 'JOUR DE FETE', 'LE THUEST', 'LA CROTTE', 'EDMOND LABATUT', 'CONSOLANT-SUD', 'ESTRADE', 'PASTEUR DE VALANJOU', 'CAMP A REDON', 'FRANCIS LOPEZ', 'GDE PIECE CARREFOUR AMOURE', 'BOIS DES CERISIOUX', 'CAP DE NAOU', 'LE FOND DE PAIX', 'PIECE DU PRE BOTEREAU', 'LA HAYE CATIN', 'CARTIVET', 'CHEZ LES BARROCHINS', 'AU PUY DE LA FON', 'AU BOIRAT', 'PRAIRIE DE BEAULIEU', 'L HERARDIERE', 'PRE DU VAUX', 'AR VELANEC RUBRAS', 'VOTEN VILLAREC', 'EN VECHERE', 'DE L ECOTTAIS', 'LANDAOUDEC', 'LE PUY DE BEAU', 'QUELME', 'LA DUPRAIRIE', 'JULIOCOURT', 'BEAUVAIS D EN BAS', 'LAZEUYS', 'LA GILLOUARDIERE', 'LE MASLEMONGE', 'ROIDE FONTAINE', 'LA PIOT', 'LE PRE DE SEVREAU', 'VERGER DU PRE', 'LE HALLIOU', 'DES JOYEUSES VACANCES']
----------------------------------------------------------------------------------------------------
➡️ postal_code:
Unique values count: 5871
Null count: 151600 (0.75%)
Sample values: ['91440', '37110', '74410', '59400', '69560', '19130', '45370', '60160', '63710', '51360', '8000', '30480', '64800', '11270', '70440', '22450', '12720', '13850', '1450', '6830', '97225', '11140', '62158', '55270', '79460', '13750', '14860', '64520', '26570', '40990', '66670', '12630', '35200', '58440', '92000', '66680', '31700', '59180', '1270', '54450', '19300', '15100', '33350', '9140', '13830', '89430', '87140', '14850', '94430', '19290', '42430', '78250', '18500', '17640', '88100', '40260', '83420', '62132', '19330', '69170', '25870', '6740', '58230', '12210', '40560', '20244', '76910', '2150', '9600', '30760', '77660', '94290', '85250', '73000', '44600', '7580', '51140', '43260', '73800', '95570', '69910', '43340', '82340', '74330', '59157', '3430', '83600', '42360', '97470', '34920', '84130', '82390', '3290', '55230', '75005', '83143', '62100', '4370', '43290', '7200', '13610', '38530', '44310', '56400', '30840', '95520', '62460', '13111', '31370', '25530', '33430', '42740', '61800', '51460', '58500', '58240', '37400', '59154', '2450', '62131']
----------------------------------------------------------------------------------------------------
➡️ com_name:
Unique values count: 31569
Null count: 0 (0.00%)
Sample values: ['OUFFIERES', 'TAILLET', 'ICHY', 'EPECAMPS', 'LEIGNE-LES-BOIS', 'ANDON', 'LOMPNAS', 'BRAILLANS', 'AIGUEBELETTE-LE-LAC', 'LE VIEUX BOURG', 'PLANTY', 'MONLONG', 'PONTEILS-ET-BRESIS', 'SAINT-JAL', 'VALENCAY', 'CHAPONNAY', 'VARENNES-SOUS-DUN', 'CARSAN', 'SAINT-MARTIN-DU-LAC', 'CLERY-GRAND', 'VALLEROY-LE-SEC', 'ARIGNAC', 'NEVY-SUR-SEILLE', 'BEZANCOURT', 'AUMENANCOURT', 'GONDRECOURT-AIX', 'SAINT FLOUR', 'VINDRAC-ALAYRAC', 'HERMELINGHEN', 'BEAURAINS LES NOYON', 'CEAUX', 'BEAUTOT', 'NEUVELLE-LES-VOISEY', 'PEISEY-NANCROIX', 'BASSE-SUR-LE-RUPT', 'RIBECOURT DRESLINCOURT', 'SAINTE-ENGRACE', 'COURCELLES LES GISORS', 'ECLOSE-BADINIERES', 'SAINT-GERMAIN-DE-LIVET', 'METHAMIS', 'CABANNES', 'MARSANNAY-LE-BOIS', 'ESPEDAILLAC', 'BESSE SUR BRAYE', 'CARCANIERES', 'GALEY', 'BOUFFRY', 'ECHEVANNES', 'CESSIERES SUZY', 'SAINT-MARTIN-DU-TARTRE', 'VENOY', 'LICHERES-PRES-AIGREMONT', 'TROGUERY', 'VERGHEAS', 'PERRAY-EN-YVELINES (LE)', 'ST ANDRE DE L EURE', 'MOUCHY LE CHATEL', 'BEAUREVOIR', 'CUSSAC-SUR-LOIRE', 'CHATEAUNEUF-VAL-DE-BARGIS', 'FRONTENAC', 'RIGNOVELLE', 'VILLEFRANCHE-DU-PERIGORD', 'MAYAC', 'MESNIL-SAINT-DENIS (LE)', 'SEMILLY', 'VENTENAC', 'LETELON', 'BONNET', 'AVON LES ROCHES', 'MENIL ANNELLES', 'TUGERAS-SAINT-MAURICE', 'VARENNE-SAINT-GERMAIN', 'LA CHAPELLE HUON', 'BEAUCE LA ROMAINE', 'DIZIMIEU', 'VERT-TOULON', 'SAINT-MARTIN-LA-GARENNE', "GEUS D'OLORON", 'PERS-EN-GATINAIS', 'AVOCOURT', 'NARCY', 'CHEVREVILLE', 'ARPAVON', 'SERRE-NERPOL', 'RUPT', 'DERBAMONT', 'COLLEGIEN', 'OSTREVILLE', 'BIOULE', 'NOGNA', 'LE POISLAY', 'LES PAROCHES', 'ERVILLE-SUR-MER', 'SAINT-LEGER', 'VERS-SOUS-SELLIERES', 'PLESSIS-SAINT-BENOIST', 'MONTEAUX', 'SEPTVAUX', 'NANCY-SUR-CLUSES', 'LE CHATENET EN DOGNON', 'BONA', 'GRAND RIVIERE', 'TORCY-LE-GRAND', 'JONCHERE (LA)', 'CHAMPNETERY', 'FRANSECHES', 'HEUDREVILLE SUR EURE', 'VALGORGE', 'VIONS', 'LUZARCHES', 'SIX-FOURS-LES-PLAGES', 'MARVILLE MOUTIERS BRULE', 'ROUECOURT', 'BRIGNEMONT', 'CORPS', 'VILLANOVA', 'SENEUJOLS', 'VALLEROY']
----------------------------------------------------------------------------------------------------
➡️ dep_code:
Unique values count: 97
Null count: 0 (0.00%)
Sample values: ['34', '70', '02', '58', '14', '33', '41', '10', '31', '64', '84', '07', '55', '61', '2A', '79', '27', '51', '93', '29', '65', '69', '75', '52', '94', '01', '36', '48', '24', '26', '16', '08', '22', '11', '90', '13', '87', '60', '73', '83', '32', '49', '19', '56', '81', '45', '40', '66', '28', '72', '74', '95', '44', '37', '17', '972', '46', '43', '89', '59', '85', '03', '2B', '78', '86', '09', '21', '23', '76', '973', '62', '77', '971', '91', '92', '06', '63', '88', '53', '15', '25', '80', '54', '35', '82', '47', '71', '39', '12', '974', '05', '30', '50', '42', '18', '38', '04']
----------------------------------------------------------------------------------------------------
➡️ com_code:
Unique values count: 908
Null count: 0 (0.00%)
Sample values: ['600', '577', '622', '112', '483', '373', '1', '301', '70', '645', '787', '635', '303', '736', '871', '164', '377', '408', '856', '344', '58', '14', '691', '148', '175', '474', '683', '494', '797', '726', '216', '244', '382', '593', '466', '55', '274', '547', '567', '410', '701', '821', '150', '199', '51', '499', '613', '779', '29', '6', '376', '276', '69', '403', '740', '798', '285', '677', '332', '298', '737', '760', '497', '94', '258', '26', '734', '846', '590', '449', '22', '731', '644', '295', '198', '318', '666', '520', '425', '414', '543', '479', '487', '490', '245', '90', '11', '568', '388', '898', '209', '409', '806', '309', '225', '909', '60', '269', '73', '275', '184', '19', '689', '862', '820', '588', '502', '888', '747', '262', '508', '385', '702', '346', '621', '323', '283', '480', '655', '554']
----------------------------------------------------------------------------------------------------
➡️ section_prefix:
Unique values count: 759
Null count: 19147817 (95.25%)
Sample values: ['577', '600', '622', '112', '483', '373', '1', '301', '70', '645', '635', '303', '871', '164', '377', '408', '856', '344', '58', '14', '691', '148', '175', '494', '216', '244', '382', '593', '466', '55', '274', '547', '567', '410', '701', '821', '150', '199', '51', '499', '29', '376', '6', '276', '69', '403', '285', '332', '298', '497', '94', '258', '26', '846', '449', '22', '414', '295', '198', '318', '644', '479', '520', '543', '245', '568', '90', '11', '388', '898', '409', '209', '806', '309', '225', '909', '60', '269', '73', '275', '184', '19', '820', '588', '502', '888', '508', '262', '385', '702', '621', '346', '323', '283', '480', '655', '192', '208', '840', '311', '104', '380', '484', '43', '618', '132', '331', '322', '59', '653', '248', '688', '564', '340', '473', '730', '78', '98', '906', '530']
----------------------------------------------------------------------------------------------------
➡️ section:
Unique values count: 588
Null count: 725 (0.00%)
Sample values: ['OC', 'MH', 'VN', 'MJ', 'AD', 'RA', 'BR', 'ZR', 'SK', 'YK', 'LB', 'GF', 'WY', 'MN', 'SR', 'AK', 'RD', 'ES', 'YM', 'VX', 'IU', 'LV', 'NS', 'TR', 'TW', 'XM', 'HI', 'RM', 'WK', 'XB', 'XW', 'YC', 'FU', 'X', 'CS', 'TV', 'GN', 'SS', 'LP', 'YU', 'E', 'BS', 'NY', 'IG', 'GP', 'OH', 'ZZ', 'AH', 'BO', 'ZF', 'VW', 'RH', 'TH', 'AE', 'NB', 'YS', 'PZ', 'OP', 'YI', 'FL', 'HA', 'VB', 'DK', 'YJ', 'RT', 'BN', 'XA', 'PB', 'NR', 'YB', 'MT', 'MD', 'XO', 'AX', 'HV', 'ID', 'ST', 'FX', 'KK', 'WA', 'XK', 'HE', 'AC', 'YD', 'GB', 'OR', 'WV', 'BJ', 'T', 'DO', 'CD', 'DS', 'MM', 'BY', 'LI', 'TD', 'IC', 'BQ', 'LM', 'FM', 'JF', 'EM', 'OB', 'EB', 'RR', 'TT', 'MP', 'DM', 'FR', 'WB', 'YF', 'AZ', 'EV', 'CN', 'PH', 'TL', 'DW', 'TO', 'VR', 'NT']
----------------------------------------------------------------------------------------------------
➡️ plot_number:
Unique values count: 8239
Null count: 0 (0.00%)
Sample values: ['1593', '6491', '9325', '1525', '1633', '2142', '6309', '3822', '5999', '7504', '303', '3131', '3899', '1059', '4229', '3003', '8000', '7039', '5617', '4846', '7442', '5370', '4634', '6271', '5666', '2046', '6546', '567', '6078', '2555', '9834', '1450', '6830', '1579', '3837', '931', '2388', '276', '6549', '7234', '5629', '6131', '5793', '1812', '3818', '1788', '5212', '7473', '3636', '5058', '2233', '3254', '9229', '6388', '5308', '1270', '7581', '2641', '568', '9219', '2217', '2969', '4411', '4571', '3521', '8395', '5490', '888', '2666', '1071', '8163', '2315', '4861', '840', '2615', '6061', '2499', '7908', '6740', '3405', '2417', '4309', '5008', '2098', '2150', '5640', '7950', '3560', '2403', '2782', '5107', '6895', '9788', '7580', '3082', '4378', '1318', '1675', '5924', '126', '4218', '6689', '628', '4672', '305', '3631', '4681', '2770', '3430', '5892', '369', '4868', '3290', '1674', '7644', '2232', '4158', '6268', '4841', '652']
----------------------------------------------------------------------------------------------------
➡️ volume_number:
Unique values count: 2068
Null count: 20057358 (99.77%)

### **Deal with INVALID VALUES**

In [10]:
from pathlib import Path
import pandas as pd

INPUT_FILE = Path("../data/processed/STANDARD_ValeursFoncieres.csv")
OUTPUT_FILE = Path("../data/processed/INVALIDS_ValeursFoncieres.csv")

CHUNK_SIZE = 500_000

date_cols = [
    "transaction_date",
]

numeric_float_cols = [
    "property_value",
    "building_real_surface",
    "land_surface",
    "lot_1_surface",
    "lot_2_surface",
    "lot_3_surface",
    "lot_4_surface",
    "lot_5_surface",
]

numeric_int_cols = [
    "lots_count",
    "main_rooms_count",
]

categorical_cols = [
    "transaction_id",
    "transaction_type",
    "street_number",
    "btq_code",
    "street_type",
    "street_id",
    "street_name",
    "postal_code",
    "com_name",
    "dep_code",
    "com_code",
    "section_prefix",
    "section",
    "plot_number",
    "volume_number",
    "property_type_code",
    "property_type",
    "land_nature",
    "land_nature_special",
    "lot_1",
    "lot_2",
    "lot_3",
    "lot_4",
    "lot_5",
]

# STANDARDIZE FAKE NULLS to NaN
missing_markers = {
    "MISSING", "", " ", "NA", "N/A", "None", "null", "NULL", "nan", "NaN"
}


def standardize_nulls(chunk: pd.DataFrame) -> pd.DataFrame:
    for col in chunk.columns:
        if chunk[col].dtype == "object" or str(chunk[col].dtype) == "string":
            chunk[col] = chunk[col].astype("string").str.strip()
            chunk[col] = chunk[col].replace(missing_markers, pd.NA)
    return chunk


def clean_date_columns(chunk: pd.DataFrame, cols: list[str]) -> pd.DataFrame:
    for col in cols:
        if col in chunk.columns:
            chunk[col] = pd.to_datetime(
                chunk[col],
                format="%d/%m/%Y",
                errors="coerce"
            )
    return chunk


def clean_float_columns(chunk: pd.DataFrame, cols: list[str]) -> pd.DataFrame:
    for col in cols:
        if col in chunk.columns:
            chunk[col] = (
                chunk[col]
                .astype("string")
                .str.replace(",", ".", regex=False)
                .str.strip()
            )
            chunk[col] = pd.to_numeric(chunk[col], errors="coerce")
    return chunk


def clean_int_columns(chunk: pd.DataFrame, cols: list[str]) -> pd.DataFrame:
    for col in cols:
        if col in chunk.columns:
            chunk[col] = (
                chunk[col]
                .astype("string")
                .str.strip()
            )
            chunk[col] = pd.to_numeric(chunk[col], errors="coerce").astype("Int64")
    return chunk


def clean_categorical_columns(chunk: pd.DataFrame, cols: list[str]) -> pd.DataFrame:
    for col in cols:
        if col in chunk.columns:
            chunk[col] = chunk[col].astype("string").str.strip()
    return chunk


def apply_custom_invalid_rules(chunk: pd.DataFrame) -> pd.DataFrame:
    # transaction_type: translate and standardize
    if "transaction_type" in chunk.columns:
        chunk["transaction_type"] = chunk["transaction_type"].replace({
            "Vente": "Sale",
            "Vente en l'état futur d'achèvement": "Sale in future state of completion",
            "Vente terrain à bâtir": "Sale of unbuilt land",
            "Echange": "Exchange",
            "Adjudication": "Auction",
            "Expropriation": "Expropriation",
        })

    # property_type: translate actual DVF categories seen in your data
    if "property_type" in chunk.columns:
        chunk["property_type"] = chunk["property_type"].replace({
            "Maison": "House",
            "Appartement": "Apartment",
            "Dépendance": "Outbuilding",
            "Local industriel. commercial ou assimilé": "Industrial or commercial premises",
        })

    # btq_code: clean invalid symbols and standardize lowercase b
    if "btq_code" in chunk.columns:
        chunk["btq_code"] = chunk["btq_code"].replace(["-", ".", "*"], pd.NA)
        chunk["btq_code"] = chunk["btq_code"].replace({"b": "B"})

    # building_real_surface and main_rooms_count:
    # use 0 when missing at this invalid-handling stage
    if "building_real_surface" in chunk.columns:
        chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0.0)

    if "main_rooms_count" in chunk.columns:
        chunk["main_rooms_count"] = chunk["main_rooms_count"].fillna(0).astype("Int64")

    # create surface_type
    if {"building_real_surface", "land_surface"}.issubset(chunk.columns):
        b = chunk["building_real_surface"].fillna(0)
        l = chunk["land_surface"].fillna(0)

        chunk["surface_type"] = pd.NA
        chunk.loc[(b > 0) & (l == 0), "surface_type"] = "building"
        chunk.loc[(b == 0) & (l > 0), "surface_type"] = "land"
        chunk.loc[(b > 0) & (l > 0), "surface_type"] = "combined"

    return chunk


def clean_chunk(chunk: pd.DataFrame) -> pd.DataFrame:
    chunk = standardize_nulls(chunk)
    chunk = clean_date_columns(chunk, date_cols)
    chunk = clean_float_columns(chunk, numeric_float_cols)
    chunk = clean_int_columns(chunk, numeric_int_cols)
    chunk = clean_categorical_columns(chunk, categorical_cols)
    chunk = apply_custom_invalid_rules(chunk)
    return chunk


def clean_file_chunked(input_file: Path, output_file: Path, chunk_size: int = 50_000) -> None:
    output_file.parent.mkdir(parents=True, exist_ok=True)

    first_write = True
    total_rows = 0

    for chunk_idx, chunk in enumerate(
        pd.read_csv(input_file, chunksize=chunk_size, dtype=str, low_memory=False),
        start=1
    ):
        chunk = clean_chunk(chunk)

        chunk.to_csv(
            output_file,
            mode="w" if first_write else "a",
            index=False,
            header=first_write,
            encoding="utf-8"
        )

        first_write = False
        total_rows += len(chunk)

        print(f"Chunk {chunk_idx} written -> {len(chunk):,} rows | total: {total_rows:,}")

    print("\n✅ Done! Handled invalid values")
    print(f"Saved file: {output_file}")
    print(f"Total rows written: {total_rows:,}")


clean_file_chunked(INPUT_FILE, OUTPUT_FILE, CHUNK_SIZE)

Chunk 1 written -> 500,000 rows | total: 500,000
Chunk 2 written -> 500,000 rows | total: 1,000,000
Chunk 3 written -> 500,000 rows | total: 1,500,000
Chunk 4 written -> 500,000 rows | total: 2,000,000
Chunk 5 written -> 500,000 rows | total: 2,500,000
Chunk 6 written -> 500,000 rows | total: 3,000,000
Chunk 7 written -> 500,000 rows | total: 3,500,000
Chunk 8 written -> 500,000 rows | total: 4,000,000
Chunk 9 written -> 500,000 rows | total: 4,500,000
Chunk 10 written -> 500,000 rows | total: 5,000,000
Chunk 11 written -> 500,000 rows | total: 5,500,000
Chunk 12 written -> 500,000 rows | total: 6,000,000
Chunk 13 written -> 500,000 rows | total: 6,500,000
Chunk 14 written -> 500,000 rows | total: 7,000,000
Chunk 15 written -> 500,000 rows | total: 7,500,000
Chunk 16 written -> 500,000 rows | total: 8,000,000
Chunk 17 written -> 500,000 rows | total: 8,500,000
Chunk 18 written -> 500,000 rows | total: 9,000,000
Chunk 19 written -> 500,000 rows | total: 9,500,000
Chunk 20 written -> 500,000 rows | total: 10,000,000
Chunk 21 written -> 500,000 rows | total: 10,500,000
Chunk 22 written -> 500,000 rows | total: 11,000,000
Chunk 23 written -> 500,000 rows | total: 11,500,000
Chunk 24 written -> 500,000 rows | total: 12,000,000
Chunk 25 written -> 500,000 rows | total: 12,500,000
Chunk 26 written -> 500,000 rows | total: 13,000,000
Chunk 27 written -> 500,000 rows | total: 13,500,000
Chunk 28 written -> 500,000 rows | total: 14,000,000
Chunk 29 written -> 500,000 rows | total: 14,500,000
Chunk 30 written -> 500,000 rows | total: 15,000,000
Chunk 31 written -> 500,000 rows | total: 15,500,000
Chunk 32 written -> 500,000 rows | total: 16,000,000
Chunk 33 written -> 500,000 rows | total: 16,500,000
Chunk 34 written -> 500,000 rows | total: 17,000,000
Chunk 35 written -> 500,000 rows | total: 17,500,000
Chunk 36 written -> 500,000 rows | total: 18,000,000
Chunk 37 written -> 500,000 rows | total: 18,500,000
Chunk 38 written -> 500,000 rows | total: 19,000,000
Chunk 39 written -> 500,000 rows | total: 19,500,000
Chunk 40 written -> 500,000 rows | total: 20,000,000
Chunk 41 written -> 102,739 rows | total: 20,102,739

✅ Done! Handled invalid values
Saved file: ..\data\processed\INVALIDS_ValeursFoncieres.csv
Total rows written: 20,102,739

### **DATASET TABLE V2**

| #  | Original Column Name           | Standardized            | Description                                       | Data Type | Type                 |
| -- | ------------------------------ | ----------------------- | ------------------------------------------------- | --------- | -------------------- |
| 0  | **No disposition**             | `transaction_id`        | Unique identifier of the transaction              | string    | Categorical          |
| 1  | **Date mutation**              | `transaction_date`      | Date when the property was sold                   | string    | Temporal             |
| 2  | **Nature mutation**            | `transaction_type`      | Nature of transaction (sale, exchange, etc.)      | string    | Categorical          |
| 3  | **Valeur fonciere**            | `property_value`        | Transaction price in euros                        | float     | Numeric (**TARGET**) |
| 4  | **No voie**                    | `street_number`         | Street number of the property                     | string    | Categorical          |
| 5  | **B/T/Q**                      | `btq_code`              | Building / Type / Quarter code                    | string    | Categorical          |
| 6  | **Type de voie**               | `street_type`           | Type of street (Rue, Avenue, etc.)                | string    | Categorical          |
| 7  | **Code voie**                  | `street_id`             | Street identifier code                            | string    | Categorical          |
| 8  | **Voie**                       | `street_name`           | Full street name                                  | string    | Categorical          |
| 9  | **Code postal**                | `postal_code`           | Postal code                                       | string    | Categorical          |
| 10 | **Commune**                    | `com_name`              | Commune name                                      | string    | Categorical          |
| 11 | **Code departement**           | `dep_code`              | Department code                                   | string    | Categorical          |
| 12 | **Code commune**               | `com_code`              | Commune code                                      | string    | Categorical          |
| 13 | **Prefixe de section**         | `section_prefix`        | Section prefix used in cadastral identification   | string    | Categorical          |
| 14 | **Section**                    | `section`               | Cadastral section identifier                      | string    | Categorical          |
| 15 | **No plan**                    | `plot_number`           | Parcel / plot number                              | string    | Categorical          |
| 16 | **No Volume**                  | `volume_number`         | Volume number for special cadastral cases         | string    | Categorical          |
| 17 | **1er lot**                    | `lot_1`                 | Identifier of the first lot                       | string    | Categorical          |
| 18 | **Surface Carrez du 1er lot**  | `lot_1_carrez_surface`  | Carrez surface of the first lot in square meters  | float     | Numeric              |
| 19 | **2eme lot**                   | `lot_2`                 | Identifier of the second lot                      | string    | Categorical          |
| 20 | **Surface Carrez du 2eme lot** | `lot_2_carrez_surface`  | Carrez surface of the second lot in square meters | float     | Numeric              |
| 21 | **3eme lot**                   | `lot_3`                 | Identifier of the third lot                       | string    | Categorical          |
| 22 | **Surface Carrez du 3eme lot** | `lot_3_carrez_surface`  | Carrez surface of the third lot in square meters  | float     | Numeric              |
| 23 | **4eme lot**                   | `lot_4`                 | Identifier of the fourth lot                      | string    | Categorical          |
| 24 | **Surface Carrez du 4eme lot** | `lot_4_carrez_surface`  | Carrez surface of the fourth lot in square meters | float     | Numeric              |
| 25 | **5eme lot**                   | `lot_5`                 | Identifier of the fifth lot                       | string    | Categorical          |
| 26 | **Surface Carrez du 5eme lot** | `lot_5_carrez_surface`  | Carrez surface of the fifth lot in square meters  | float     | Numeric              |
| 27 | **Nombre de lots**             | `lots_count`            | Number of lots in the transaction                 | integer   | Numeric              |
| 28 | **Code type local**            | `property_type_code`    | Code for property type                            | string    | Categorical          |
| 29 | **Type local**                 | `property_type`         | Property type (Apartment, House, etc.)            | string    | Categorical          |
| 30 | **Surface reelle bati**        | `building_real_surface` | Built area in square meters                       | float     | Numeric              |
| 31 | **Nombre pieces principales**  | `main_rooms_count`      | Number of main rooms                              | integer   | Numeric              |
| 32 | **Nature culture**             | `land_nature`           | General type of land usage                        | string    | Categorical          |
| 33 | **Nature culture speciale**    | `land_nature_special`   | Specific type of land usage                       | string    | Categorical          |
| 34 | **Surface terrain**            | `land_surface`          | Land area in square meters                        | float     | Numeric              |
| 35 | *(derived)*                    | `surface_type`          | Type of surface: building / land / combined       | string    | Derived Categorical  |

---
###  **CREATE `df_com_dep`**

from `df_com` :
- ✔ COMTYPE → commune type
- ✔ COM → commune INSEE code
- ✔ NCCENR → official commune names in MAJ & "-" & ACCENT
- ✔ DEP → department code

from `df_dep` :
 - ✔ DEP → department code
 - ✔ NCCENR → official department names NAMES

combine: add dep_name using DEP

rename columns

save csv

#### **CREATE `df_com`**
- create df_com with select columns from v_communes_2026.csv
	- COM
	- TYPECOM
	- NCCENR (uppercase + encoding & decoding)
	- DEP
- rename df_com columns
	- insee_code = COM
	- com_type = TYPECOM 
	- com_name = NCCENR
	- dep_code = DEP

In [ ]:
# load raw communes dataset
try:
    df_com = pd.read_csv("../data/raw/v_commune_2026.csv", sep=",", encoding="utf-8")
except UnicodeDecodeError:
    df_com = pd.read_csv("../data/raw/v_commune_2026.csv", sep=",", encoding="latin-1")

# rename df_com columns
df_com.rename(columns={
    "COM": "insee_code",
    "TYPECOM": "com_type",
    "NCCENR": "com_name",
    "DEP": "dep_code"
}, inplace=True)

# uppercase + encoding & decoding of com_name
df_com["com_name"] = (
    df_com["com_name"]
    .astype(str)
    .str.upper()
)

# drop other columns except insee_code, com_type, com_name, dep_code
df_com = df_com[["insee_code", "com_type", "com_name", "dep_code"]]

# display df_com
print("Communes Dataset Shape:", df_com.shape[0], "rows and", df_com.shape[1], "columns")
display(df_com.head())
print(100 * "-")
# display unique values of com_name
print("Unique Values of `com_name`:")
display(df_com["com_name"].unique())

# save df_com in a new CSV file
df_com.to_csv("../data/processed/COM_2026.csv", index=False)

#### **CREATE `df_dep`**

In [ ]:
# load raw departement dataset
try:
    df_dep = pd.read_csv("../data/raw/v_departement_2026.csv", sep=",", encoding="utf-8")
except UnicodeDecodeError:
    df_dep = pd.read_csv("../data/raw/v_departement_2026.csv", sep=",", encoding="latin-1")

# rename df_dep columns
df_dep.rename(columns={
    "DEP": "dep_code",
    "NCCENR": "dep_name"
}, inplace=True)

# uppercase + encoding & decoding of dep_name
df_dep["dep_name"] = (
    df_dep["dep_name"]
    .astype(str)
    .str.upper()
)

# drop other columns except dep_code, dep_name
df_dep = df_dep[["dep_code", "dep_name"]]

# display df_dep
print("Departements Dataset Shape:", df_dep.shape[0], "rows and", df_dep.shape[1], "columns")
display(df_dep.head())
print(100 * "-")
# display unique values of dep_name
print("Unique Values of `dep_name`:")
display(df_dep["dep_name"].unique())

# save df_dep in a new CSV file
df_dep.to_csv("../data/processed/DEP_2026.csv", index=False)

#### **USE `com_name` column to COMBINE and create `COM_DEP_2026.CSV`**

In [ ]:
# create df_com_dep by merging df_com and df_dep on dep_code
df_com_dep = pd.merge(df_com, df_dep, on="dep_code", how="left")
# display df_com_dep
print("Combined Communes & Departements Dataset Shape:", df_com_dep.shape[0], "rows and", df_com_dep.shape[1], "columns")
display(df_com_dep.head())
print(100 * "-")
# display unique values of com_name and dep_name in df_com_dep
print("Unique Values of `com_name` in df_com_dep:")
display(df_com_dep["com_name"].unique())
print("Unique Values of `dep_name` in df_com_dep:")
display(df_com_dep["dep_name"].unique())
# save df_com_dep in a new CSV file
df_com_dep.to_csv("../data/processed/COM_DEP_2026.csv", index=False)

<hr>

## 3️⃣ DATA TYPES


<style>
h1 {
    text-align: center;
    color: black;
    font-weight: bold;
}
</style>

<style>
h2 {
    text-align: left;
    color: black;
    font-weight: bold;
}
</style>

<style>
h3 {
    text-align: left;
    color: black;
    font-weight: bold;
}
</style>

<style>
h4 {
    text-align: left;
    color: black;
    font-weight: bold;
}
</style>
<hr>

→  WHY? Enable correct calculations and analysis.

### **SHAPE & HEAD**

In [11]:
import pandas as pd

FILE = "../data/processed/INVALIDS_ValeursFoncieres.csv"
CHUNK_SIZE = 500_000

total_rows = 0
columns = None

for chunk in pd.read_csv(FILE, chunksize=CHUNK_SIZE, dtype=str):
    total_rows += len(chunk)
    if columns is None:
        columns = chunk.columns

print("Shape:", total_rows, "rows and", len(columns), "columns")

df_head = pd.read_csv(FILE, nrows=5, dtype=str)
display(df_head)

Shape: 20102739 rows and 36 columns

,transaction_id,transaction_date,transaction_type,property_value,street_number,btq_code,street_type,street_id,street_name,postal_code,com_name,dep_code,com_code,section_prefix,section,plot_number,volume_number,lot_1,lot_1_surface,lot_2,lot_2_surface,lot_3,lot_3_surface,lot_4,lot_4_surface,lot_5,lot_5_surface,lots_count,property_type_code,property_type,building_real_surface,main_rooms_count,land_nature,land_nature_special,land_surface,surface_type
0,000001,2020-07-01,Sale,31234.16,NaN,NaN,NaN,B064,SAINT JULIEN,1560,SAINT-JULIEN-SUR-REYSSOUZE,01,367,NaN,A,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,0,0,AB,NaN,1192,land
1,000001,2020-07-01,Sale,278000.0,NaN,NaN,NaN,B188,A LA PEROUSE,1250,CORVEISSIAT,01,125,NaN,C,509,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,0,0,BS,NaN,10092,land
2,000001,2020-07-01,Sale,278000.0,NaN,NaN,NaN,B188,A LA PEROUSE,1250,CORVEISSIAT,01,125,NaN,C,510,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,0,0,L,NaN,4570,land
3,000001,2020-07-01,Sale,278000.0,NaN,NaN,NaN,B079,AUX COMMUNS,1250,CORVEISSIAT,01,125,NaN,ZL,96,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,0,0,BS,NaN,5750,land
4,000001,2020-07-01,Sale,278000.0,NaN,NaN,NaN,B033,EN COMBARNAUD,1250,SIMANDRE-SUR-SURAN,01,408,NaN,A,14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,0,0,BT,NaN,648170,land

### **UNIQUE VALUES & NULLS**

In [12]:
from collections import defaultdict
import pandas as pd

FILE = "../data/processed/INVALIDS_ValeursFoncieres.csv"

unique_values = defaultdict(set)
null_counts = defaultdict(int)
total_rows = 0

for chunk in pd.read_csv(
    FILE,
    chunksize=500_000,
    dtype=str,          # ✅ avoids mixed types warning
    low_memory=False
):
    total_rows += len(chunk)

    for col in chunk.columns:
        # ✅ Count nulls (DO NOT drop them)
        null_counts[col] += chunk[col].isna().sum()

        # ✅ Collect only non-null values (nulls are still preserved in dataset)
        unique_values[col].update(
            chunk.loc[chunk[col].notna(), col].unique()
        )

# --------------------------------------------------
# Display results
# --------------------------------------------------
print(f"\nTotal rows processed: {total_rows:,}")
print(100 * "-")

for col in unique_values:
    values = list(unique_values[col])
    null_pct = (null_counts[col] / total_rows) * 100

    print(f"➡️ {col}:")
    print(f"Unique values count: {len(values)}")
    print(f"Null count: {null_counts[col]} ({null_pct:.2f}%)")
    print(f"Sample values: {values[:120]}")
    print(100 * "-")

Total rows processed: 20,102,739
----------------------------------------------------------------------------------------------------
➡️ transaction_id:
Unique values count: 1204
Null count: 0 (0.00%)
Sample values: ['000576', '000189', '000145', '000546', '000951', '001152', '001186', '000358', '001194', '000797', '000915', '000261', '000925', '001052', '000988', '000115', '001043', '000855', '000422', '000830', '000232', '000411', '001132', '001148', '000440', '001011', '000494', '000462', '000475', '001021', '001154', '000183', '000312', '001017', '001110', '000852', '000511', '000645', '000918', '000629', '000398', '000361', '001074', '000420', '000141', '000164', '000085', '000697', '000126', '000308', '000672', '001055', '000755', '000283', '000470', '000586', '000043', '000432', '001108', '000122', '000153', '000493', '001121', '000055', '000031', '000223', '000143', '000229', '000694', '000707', '000714', '001030', '000776', '000949', '000712', '000483', '000167', '000341', '000022', '000074', '000722', '000831', '001236', '000521', '000954', '001173', '000051', '000534', '000372', '000200', '000386', '000434', '000381', '000219', '000150', '000015', '000111', '000635', '000574', '000763', '000953', '000723', '000458', '001116', '000468', '000587', '000675', '001081', '001036', '000291', '001050', '000007', '000340', '000897', '001029', '000274', '000426', '001157', '000235', '000818']
----------------------------------------------------------------------------------------------------
➡️ transaction_date:
Unique values count: 1806
Null count: 0 (0.00%)
Sample values: ['2023-10-08', '2024-05-20', '2021-08-25', '2023-04-01', '2021-05-24', '2021-08-15', '2024-07-30', '2025-04-04', '2022-07-23', '2021-03-12', '2022-03-31', '2021-04-08', '2021-11-30', '2025-06-28', '2024-11-26', '2024-07-25', '2021-03-17', '2025-03-25', '2022-04-15', '2022-04-26', '2023-12-05', '2023-12-13', '2023-12-28', '2021-05-15', '2022-10-28', '2021-07-14', '2024-07-14', '2022-06-11', '2025-05-19', '2021-09-30', '2024-07-07', '2020-10-31', '2021-04-03', '2021-07-27', '2022-06-03', '2023-06-05', '2020-11-29', '2021-01-17', '2022-10-26', '2024-10-29', '2024-02-25', '2022-01-24', '2021-03-21', '2021-06-01', '2022-01-21', '2024-06-21', '2024-02-03', '2025-06-02', '2021-03-16', '2025-05-31', '2025-04-25', '2022-11-29', '2024-02-20', '2022-11-05', '2021-10-13', '2025-01-31', '2024-03-28', '2021-08-29', '2024-11-12', '2020-07-03', '2023-12-03', '2022-03-18', '2021-11-22', '2020-11-09', '2024-05-15', '2024-08-12', '2024-08-09', '2020-07-30', '2021-04-21', '2024-04-13', '2021-05-30', '2025-01-29', '2024-12-25', '2025-03-30', '2022-02-07', '2020-09-08', '2023-05-13', '2021-01-21', '2020-12-15', '2020-11-03', '2020-08-03', '2023-02-15', '2024-03-16', '2024-03-14', '2021-10-17', '2024-08-02', '2020-08-31', '2022-09-01', '2024-10-05', '2022-03-22', '2021-03-05', '2021-10-04', '2024-01-29', '2024-10-07', '2024-01-30', '2021-06-21', '2023-07-18', '2025-06-19', '2020-12-29', '2023-10-20', '2024-02-11', '2024-04-11', '2024-07-28', '2022-09-26', '2022-07-26', '2022-12-06', '2024-07-04', '2023-05-01', '2022-09-09', '2022-02-19', '2021-11-27', '2021-04-16', '2025-06-20', '2025-01-07', '2023-07-07', '2021-05-02', '2024-09-06', '2024-04-17', '2021-11-14', '2023-11-03']
----------------------------------------------------------------------------------------------------
➡️ transaction_type:
Unique values count: 6
Null count: 0 (0.00%)
Sample values: ['Sale in future state of completion', 'Sale of unbuilt land', 'Expropriation', 'Auction', 'Sale', 'Exchange']
----------------------------------------------------------------------------------------------------
➡️ property_value:
Unique values count: 466667
Null count: 194390 (0.97%)
Sample values: ['75572.47', '424131.0', '363151.0', '629335.0', '92915.0', '673340.0', '236008.0', '1768.0', '79707.0', '646146.0', '5423.7', '223070.0', '201536.0', '4281.42', '2311.75', '3205.5', '376944.0', '666.0', '78641.0', '212539.0', '12668.8', '122941.0', '175530.0', '94209.0', '131605.69', '16568.96', '213505.0', '290850.0', '88087.02', '23138.4', '831000.0', '1809825.0', '278280.0', '11835.68', '7575.2', '11864.4', '168997.0', '628100.0', '781.5', '972550.0', '244831.0', '117800.0', '111130.0', '135430.0', '43976.0', '2984.45', '144047.42', '137775.0', '93.33', '845775.0', '57542.27', '64301.0', '771159.0', '535432.0', '746300.0', '1878500.0', '135037.25', '181180.0', '13072.5', '68150.0', '214918.42', '26565.0', '543475.0', '9751.0', '60957.0', '47622.6', '392162.0', '34169.85', '33765.0', '485320.0', '1156332.0', '326205.0', '58129.45', '697.35', '30340.0', '76225.0', '1373700.0', '61192.0', '25334.4', '514942.0', '94980.0', '50815.0', '351208.0', '104718.0', '135828.11', '432505.0', '265786.0', '36468.75', '1643250.0', '809900.0', '96101.35', '47037.0', '25471.0', '237798.0', '481030.0', '1106780.0', '98410.0', '106195.0', '30005.0', '37083.6', '245028.0', '98782.0', '33772.5', '125627.52', '377160.0', '3876019.0', '27681.0', '98216.8', '220561.0', '45141.72', '8383.95', '1148.39', '21404.0', '483230.0', '552640.0', '734235.0', '6599723.5', '327124.0', '599240.0', '2675900.0']
----------------------------------------------------------------------------------------------------
➡️ street_number:
Unique values count: 9126
Null count: 7474511 (37.18%)
Sample values: ['1593', '6491', '9325', '1525', '1633', '2142', '9257', '6309', '3822', '5999', '7504', '303', '3131', '3899', '9650', '1059', '4229', '3003', '8000', '7039', '5617', '4846', '7442', '5370', '4634', '6271', '5666', '2046', '6546', '567', '6078', '2555', '9834', '1450', '6830', '1579', '8207', '931', '2388', '276', '6549', '9057', '7234', '5629', '5793', '6131', '1812', '3818', '1788', '5212', '8890', '7473', '3636', '5058', '7416', '2233', '3254', '9229', '6388', '5308', '1270', '7581', '2641', '568', '9219', '2217', '2969', '8335', '4411', '4571', '3521', '9140', '5490', '888', '9960', '2666', '1071', '8163', '2315', '840', '9657', '2615', '6061', '2499', '7908', '6740', '3405', '2417', '7831', '5008', '4309', '2098', '5640', '2150', '9600', '9236', '3560', '2403', '2782', '5107', '6895', '9788', '7580', '3082', '4378', '1675', '1318', '5924', '9507', '126', '9975', '9389', '4218', '6689', '628', '305', '3631', '4681', '2770', '3430']
----------------------------------------------------------------------------------------------------
➡️ btq_code:
Unique values count: 36
Null count: 19197741 (95.50%)
Sample values: ['Y', 'E', 'K', '1', '3', 'F', 'V', 'N', 'T', 'G', 'B', 'Z', '2', 'H', '8', 'W', 'P', 'D', 'S', 'M', '9', 'Q', '7', 'U', '5', '4', 'R', 'O', 'J', '0', 'C', 'I', 'L', 'A', 'X', '6']
----------------------------------------------------------------------------------------------------
➡️ street_type:
Unique values count: 152
Null count: 7942059 (39.51%)
Sample values: ['ESPA', 'HLE', 'PAS', 'QUA', 'GR', 'PAE', 'HLM', 'MAIL', 'COTE', 'VALL', 'COL', 'ALL', 'VTE', 'QUAI', 'PRT', 'CR', 'PLA', 'BORD', 'VIA', 'CHL', 'JTE', 'PLAG', 'PRV', 'PKG', 'CORO', 'TRA', 'CIVE', 'RULT', 'FOS', 'PCH', 'BRTL', 'AUT', 'DEVI', 'CAE', 'ZONE', 'ZUP', 'MAIS', 'CALL', 'VAL', 'DIG', 'TRAB', 'PLE', 'REM', 'PIST', 'CAN', 'ECL', 'ANGL', 'LOT', 'ZAC', 'D', 'VLA', 'CHEM', 'VOIE', 'BD', 'TSSE', 'ZAD', 'RIVE', 'ACH', 'VOUT', 'PTTE', 'VEN', 'RAC', 'PARC', 'CITE', 'LEVE', 'CRX', 'BSN', 'PLAN', 'CLOS', 'VCHE', 'PL', 'GAL', 'CC', 'HLG', 'FG', 'CHS', 'DRA', 'CHV', 'BRG', 'GPL', 'CRS', 'RLE', 'GARE', 'NTE', 'PTA', 'PASS', 'VIL', 'ZI', 'COIN', 'ART', 'DOM', 'N', 'MAR', 'SEN', 'CD', 'RTE', 'VC', 'COR', 'CLR', 'AGL', 'PTE', 'IMP', 'LICE', 'HAM', 'ILOT', 'SQ', 'CAMI', 'PONT', 'MRN', 'RTD', 'ESP', 'DSC', 'CAR', 'HAB', 'VOY', 'BRE', 'PORT', 'CPG', 'AV', 'STDE']
----------------------------------------------------------------------------------------------------
➡️ street_id:
Unique values count: 20064
Null count: 150482 (0.75%)
Sample values: ['B680', '6491', 'H482', '9325', 'P363', 'G573', '8814', '1059', 'B146', 'G657', 'B130', 'C991', '5617', 'F928', 'F319', 'I462', '4634', 'F110', 'D515', '6546', 'F666', 'C982', '8621', '1579', 'Q578', '8207', 'C447', '8884', 'I753', 'I261', '9057', '5629', '1812', '8890', '5212', 'C707', 'B781', 'H801', '0322', '9229', 'I733', 'J379', 'A393', 'C387', 'H957', 'F062', '0289', 'C058', '2969', 'A152', '9140', '0998', 'C600', 'E032', 'D979', 'B083', 'E075', '4309', '2098', 'E652', 'B678', 'V163', '5107', '7580', '3082', 'D030', '9507', '9389', 'D558', '3631', 'E981', 'K422', 'H865', '5892', 'B506', 'I649', 'D918', '4158', 'X005', '7202', 'A621', '6907', '4479', '2333', '8296', 'X030', '6139', 'B474', 'D427', 'H123', '2162', '8743', 'E682', 'C195', 'E584', 'F311', 'G351', 'D105', 'D769', '3272', '6389', 'E650', '9437', 'E670', 'K468', '6698', 'B633', '2605', '2477', 'A747', '9544', '2342', 'H613', '9848', 'J124', '3946', 'D106', '0412', '6185', '4968']
----------------------------------------------------------------------------------------------------
➡️ street_name:
Unique values count: 1132199
Null count: 151263 (0.75%)
Sample values: ['MAGISTRAT SUD', 'DES AUTRES PLANETES', 'SOUS SAUNIAL', 'FERMI', 'DU CITIS', 'CHEZ KAKI', 'CHAMPS MARTIN MEUNIER', 'ETANG DE LA PRAZ', 'BOUIGUO DE MEDAN', 'DE TAURENS', 'LA CELLIERE', 'FEYPOT', 'KERTOUDIC', 'LE DEVINET', 'DU FAYET', 'LE COUSINIE', 'BOSSELEINE', 'LA HAIE A TROCHARD', 'GEORGES CHARRIER', 'BAS DE POMME D ARC', 'LES COSSES DU MAGNOU', 'MARCEL LAUTARD', 'DE PIED BLANC', 'LES CHAMPS ANSELME EST', 'DES ROSSANDES', 'LA SERSIOGRAND', 'GROS ROCHER', 'CLOS DU BOIS ROSSIGNOL', 'LA CHEVESSERIE', 'DE COURRIN', 'JAUREZE', 'LE PRE DU BREUX', 'LA BERTONNIE', 'LEVITE', 'CHODORELLE', 'GRANDS ARRAYIES', 'ABBE ARTARIT', 'LA LANDE DE LA GRANGE', 'DE FEBVRY', 'LE COTEAU DE LIQUET', 'LE GRAND ROQUEMARD', 'KERVAN GOAREM AR STANC', 'DES BOSCHETTES', 'CHEZ DAMOUR', 'DERRIERE LA TUVIERE', 'DE LA NAUZETTE', 'LE CHEMIN DE L ABBAYE AUX', 'DANIEL SAGE', 'AU VEZIS', 'L ECLATE', 'KERBLEUNIOU', 'LA DOUBRIE', 'HOUDENT', 'DE GATEBOURG', 'DES NOISETIERS (MARIGNE)', 'CAPIGRIGIO', 'LA BARATRIE', 'LA TAPINIERE', 'ROUTE DE LA SERRE', 'DES 3 FRERES', 'PAUL MARAIS', 'SOMBEZAU', 'FEMAJOLA', 'CASTIGUES-SUD', 'RULANOU', 'FRANGOUILLE', 'LES SOUPEES', 'A ENMANSOT', 'SOUS LA CORVEE', 'VALESCHIERAS EST', 'PUYLAGORGE', 'LEON HUTIN', 'JEAN MARIE JEGO', 'DOMINIQUE LAGRU', 'LES HARDINES DE BELZAISE', 'CHAMP SABATAY', 'DU PUITS DE LA FIGUIERE', 'LE PUISEUX', 'VERKEERDE BECQUE ET KLAP H', 'JOUR DE FETE', 'LE THUEST', 'LA CROTTE', 'EDMOND LABATUT', 'CONSOLANT-SUD', 'ESTRADE', 'PASTEUR DE VALANJOU', 'CAMP A REDON', 'FRANCIS LOPEZ', 'GDE PIECE CARREFOUR AMOURE', 'BOIS DES CERISIOUX', 'CAP DE NAOU', 'LE FOND DE PAIX', 'PIECE DU PRE BOTEREAU', 'LA HAYE CATIN', 'CARTIVET', 'CHEZ LES BARROCHINS', 'AU PUY DE LA FON', 'AU BOIRAT', 'PRAIRIE DE BEAULIEU', 'L HERARDIERE', 'PRE DU VAUX', 'AR VELANEC RUBRAS', 'VOTEN VILLAREC', 'EN VECHERE', 'DE L ECOTTAIS', 'LANDAOUDEC', 'LE PUY DE BEAU', 'QUELME', 'LA DUPRAIRIE', 'JULIOCOURT', 'BEAUVAIS D EN BAS', 'LAZEUYS', 'LA GILLOUARDIERE', 'LE MASLEMONGE', 'ROIDE FONTAINE', 'LA PIOT', 'LE PRE DE SEVREAU', 'VERGER DU PRE', 'LE HALLIOU', 'DES JOYEUSES VACANCES']
----------------------------------------------------------------------------------------------------
➡️ postal_code:
Unique values count: 5871
Null count: 151600 (0.75%)
Sample values: ['91440', '37110', '74410', '59400', '69560', '19130', '45370', '60160', '63710', '51360', '8000', '30480', '64800', '11270', '70440', '22450', '12720', '13850', '1450', '6830', '97225', '11140', '62158', '55270', '79460', '13750', '14860', '64520', '26570', '40990', '66670', '12630', '35200', '58440', '92000', '66680', '31700', '59180', '1270', '54450', '19300', '15100', '33350', '9140', '13830', '89430', '87140', '14850', '94430', '19290', '42430', '78250', '18500', '17640', '88100', '40260', '83420', '62132', '19330', '69170', '25870', '6740', '58230', '12210', '40560', '20244', '76910', '2150', '9600', '30760', '77660', '94290', '85250', '73000', '44600', '7580', '51140', '43260', '73800', '95570', '69910', '43340', '82340', '74330', '59157', '3430', '83600', '42360', '97470', '34920', '84130', '82390', '3290', '55230', '75005', '83143', '62100', '4370', '43290', '7200', '13610', '38530', '44310', '56400', '30840', '95520', '62460', '13111', '31370', '25530', '33430', '42740', '61800', '51460', '58500', '58240', '37400', '59154', '2450', '62131']
----------------------------------------------------------------------------------------------------
➡️ com_name:
Unique values count: 31569
Null count: 0 (0.00%)
Sample values: ['OUFFIERES', 'TAILLET', 'ICHY', 'EPECAMPS', 'LEIGNE-LES-BOIS', 'ANDON', 'LOMPNAS', 'BRAILLANS', 'AIGUEBELETTE-LE-LAC', 'LE VIEUX BOURG', 'PLANTY', 'MONLONG', 'PONTEILS-ET-BRESIS', 'SAINT-JAL', 'VALENCAY', 'CHAPONNAY', 'VARENNES-SOUS-DUN', 'CARSAN', 'SAINT-MARTIN-DU-LAC', 'CLERY-GRAND', 'VALLEROY-LE-SEC', 'ARIGNAC', 'NEVY-SUR-SEILLE', 'BEZANCOURT', 'AUMENANCOURT', 'GONDRECOURT-AIX', 'SAINT FLOUR', 'VINDRAC-ALAYRAC', 'HERMELINGHEN', 'BEAURAINS LES NOYON', 'CEAUX', 'BEAUTOT', 'NEUVELLE-LES-VOISEY', 'PEISEY-NANCROIX', 'BASSE-SUR-LE-RUPT', 'RIBECOURT DRESLINCOURT', 'SAINTE-ENGRACE', 'COURCELLES LES GISORS', 'ECLOSE-BADINIERES', 'SAINT-GERMAIN-DE-LIVET', 'METHAMIS', 'CABANNES', 'MARSANNAY-LE-BOIS', 'ESPEDAILLAC', 'BESSE SUR BRAYE', 'CARCANIERES', 'GALEY', 'BOUFFRY', 'ECHEVANNES', 'CESSIERES SUZY', 'SAINT-MARTIN-DU-TARTRE', 'VENOY', 'LICHERES-PRES-AIGREMONT', 'TROGUERY', 'VERGHEAS', 'PERRAY-EN-YVELINES (LE)', 'ST ANDRE DE L EURE', 'MOUCHY LE CHATEL', 'BEAUREVOIR', 'CUSSAC-SUR-LOIRE', 'CHATEAUNEUF-VAL-DE-BARGIS', 'FRONTENAC', 'RIGNOVELLE', 'VILLEFRANCHE-DU-PERIGORD', 'MAYAC', 'MESNIL-SAINT-DENIS (LE)', 'SEMILLY', 'VENTENAC', 'LETELON', 'BONNET', 'AVON LES ROCHES', 'MENIL ANNELLES', 'TUGERAS-SAINT-MAURICE', 'VARENNE-SAINT-GERMAIN', 'LA CHAPELLE HUON', 'BEAUCE LA ROMAINE', 'DIZIMIEU', 'VERT-TOULON', 'SAINT-MARTIN-LA-GARENNE', "GEUS D'OLORON", 'PERS-EN-GATINAIS', 'AVOCOURT', 'NARCY', 'CHEVREVILLE', 'ARPAVON', 'SERRE-NERPOL', 'RUPT', 'DERBAMONT', 'COLLEGIEN', 'OSTREVILLE', 'BIOULE', 'NOGNA', 'LE POISLAY', 'LES PAROCHES', 'ERVILLE-SUR-MER', 'SAINT-LEGER', 'VERS-SOUS-SELLIERES', 'PLESSIS-SAINT-BENOIST', 'MONTEAUX', 'SEPTVAUX', 'NANCY-SUR-CLUSES', 'LE CHATENET EN DOGNON', 'BONA', 'GRAND RIVIERE', 'TORCY-LE-GRAND', 'JONCHERE (LA)', 'CHAMPNETERY', 'FRANSECHES', 'HEUDREVILLE SUR EURE', 'VALGORGE', 'VIONS', 'LUZARCHES', 'SIX-FOURS-LES-PLAGES', 'MARVILLE MOUTIERS BRULE', 'ROUECOURT', 'BRIGNEMONT', 'CORPS', 'VILLANOVA', 'SENEUJOLS', 'VALLEROY']
----------------------------------------------------------------------------------------------------
➡️ dep_code:
Unique values count: 97
Null count: 0 (0.00%)
Sample values: ['34', '70', '02', '58', '14', '33', '41', '10', '31', '64', '84', '07', '55', '61', '2A', '79', '27', '51', '93', '29', '65', '69', '75', '52', '94', '01', '36', '48', '24', '26', '16', '08', '22', '11', '90', '13', '87', '60', '73', '83', '32', '49', '19', '56', '81', '45', '40', '66', '28', '72', '74', '95', '44', '37', '17', '972', '46', '43', '89', '59', '85', '03', '2B', '78', '86', '09', '21', '23', '76', '973', '62', '77', '971', '91', '92', '06', '63', '88', '53', '15', '25', '80', '54', '35', '82', '47', '71', '39', '12', '974', '05', '30', '50', '42', '18', '38', '04']
----------------------------------------------------------------------------------------------------
➡️ com_code:
Unique values count: 908
Null count: 0 (0.00%)
Sample values: ['600', '577', '622', '112', '483', '373', '1', '301', '70', '645', '787', '635', '303', '736', '871', '164', '377', '408', '856', '344', '58', '14', '691', '148', '175', '474', '683', '494', '797', '726', '216', '244', '382', '593', '466', '55', '274', '547', '567', '410', '701', '821', '150', '199', '51', '499', '613', '779', '29', '6', '376', '276', '69', '403', '740', '798', '285', '677', '332', '298', '737', '760', '497', '94', '258', '26', '734', '846', '590', '449', '22', '731', '644', '295', '198', '318', '666', '520', '425', '414', '543', '479', '487', '490', '245', '90', '11', '568', '388', '898', '209', '409', '806', '309', '225', '909', '60', '269', '73', '275', '184', '19', '689', '862', '820', '588', '502', '888', '747', '262', '508', '385', '702', '346', '621', '323', '283', '480', '655', '554']
----------------------------------------------------------------------------------------------------
➡️ section_prefix:
Unique values count: 759
Null count: 19147817 (95.25%)
Sample values: ['577', '600', '622', '112', '483', '373', '1', '301', '70', '645', '635', '303', '871', '164', '377', '408', '856', '344', '58', '14', '691', '148', '175', '494', '216', '244', '382', '593', '466', '55', '274', '547', '567', '410', '701', '821', '150', '199', '51', '499', '29', '376', '6', '276', '69', '403', '285', '332', '298', '497', '94', '258', '26', '846', '449', '22', '414', '295', '198', '318', '644', '479', '520', '543', '245', '568', '90', '11', '388', '898', '409', '209', '806', '309', '225', '909', '60', '269', '73', '275', '184', '19', '820', '588', '502', '888', '508', '262', '385', '702', '621', '346', '323', '283', '480', '655', '192', '208', '840', '311', '104', '380', '484', '43', '618', '132', '331', '322', '59', '653', '248', '688', '564', '340', '473', '730', '78', '98', '906', '530']
----------------------------------------------------------------------------------------------------
➡️ section:
Unique values count: 588
Null count: 725 (0.00%)
Sample values: ['OC', 'MH', 'VN', 'MJ', 'AD', 'RA', 'BR', 'ZR', 'SK', 'YK', 'LB', 'GF', 'WY', 'MN', 'SR', 'AK', 'RD', 'ES', 'YM', 'VX', 'IU', 'LV', 'NS', 'TR', 'TW', 'XM', 'HI', 'RM', 'WK', 'XB', 'XW', 'YC', 'FU', 'X', 'CS', 'TV', 'GN', 'SS', 'LP', 'YU', 'E', 'BS', 'NY', 'IG', 'GP', 'OH', 'ZZ', 'AH', 'BO', 'ZF', 'VW', 'RH', 'TH', 'AE', 'NB', 'YS', 'PZ', 'OP', 'YI', 'FL', 'HA', 'VB', 'DK', 'YJ', 'RT', 'BN', 'XA', 'PB', 'NR', 'YB', 'MT', 'MD', 'XO', 'AX', 'HV', 'ID', 'ST', 'FX', 'KK', 'WA', 'XK', 'HE', 'AC', 'YD', 'GB', 'OR', 'WV', 'BJ', 'T', 'DO', 'CD', 'DS', 'MM', 'BY', 'LI', 'TD', 'IC', 'BQ', 'LM', 'FM', 'JF', 'EM', 'OB', 'EB', 'RR', 'TT', 'MP', 'DM', 'FR', 'WB', 'YF', 'AZ', 'EV', 'CN', 'PH', 'TL', 'DW', 'TO', 'VR', 'NT']
----------------------------------------------------------------------------------------------------
➡️ plot_number:
Unique values count: 8239
Null count: 0 (0.00%)
Sample values: ['1593', '6491', '9325', '1525', '1633', '2142', '6309', '3822', '5999', '7504', '303', '3131', '3899', '1059', '4229', '3003', '8000', '7039', '5617', '4846', '7442', '5370', '4634', '6271', '5666', '2046', '6546', '567', '6078', '2555', '9834', '1450', '6830', '1579', '3837', '931', '2388', '276', '6549', '7234', '5629', '6131', '5793', '1812', '3818', '1788', '5212', '7473', '3636', '5058', '2233', '3254', '9229', '6388', '5308', '1270', '7581', '2641', '568', '9219', '2217', '2969', '4411', '4571', '3521', '8395', '5490', '888', '2666', '1071', '8163', '2315', '4861', '840', '2615', '6061', '2499', '7908', '6740', '3405', '2417', '4309', '5008', '2098', '2150', '5640', '7950', '3560', '2403', '2782', '5107', '6895', '9788', '7580', '3082', '4378', '1318', '1675', '5924', '126', '4218', '6689', '628', '4672', '305', '3631', '4681', '2770', '3430', '5892', '369', '4868', '3290', '1674', '7644', '2232', '4158', '6268', '4841', '652']
----------------------------------------------------------------------------------------------------
➡️ volume_number:
Unique values count: 2068
Null count: 20057358 (99.77%)

### **dtype MAPPING**

In [ ]:

dtype_map = {
    # categorical / identifiers
    "transaction_id": "string",
    "transaction_date": "string",  # convert to datetime after loading
    "transaction_type": "string",
    "street_number": "string",
    "btq_code": "string",
    "street_type": "string",
    "street_id": "string",
    "street_name": "string",
    "postal_code": "string",
    "com_name": "string",
    "dep_code": "string",
    "com_code": "string",
    "section_prefix": "string",
    "section": "string",
    "plot_number": "string",
    "volume_number": "string",
    "property_type_code": "string",  # keep as string (categorical)
    "property_type": "string",
    "land_nature": "string",
    "land_nature_special": "string",
    "surface_type": "string",

    # lot identifiers
    "lot_1": "string",
    "lot_2": "string",
    "lot_3": "string",
    "lot_4": "string",
    "lot_5": "string",

    # numeric (use nullable Float64 for consistency)
    "property_value": "Float64",
    "building_real_surface": "Float64",
    "land_surface": "Float64",
    "lot_1_surface": "Float64",
    "lot_2_surface": "Float64",
    "lot_3_surface": "Float64",
    "lot_4_surface": "Float64",
    "lot_5_surface": "Float64",

    # integer (nullable)
    "lots_count": "Int64",
    "main_rooms_count": "Int64",
}

### **CONVERT DATA TYPES**

In [13]:
from pathlib import Path
import pandas as pd

INPUT_FILE = Path("../data/processed/INVALIDS_ValeursFoncieres.csv")
OUTPUT_FILE = Path("../data/processed/TYPES_ValeursFoncieres.csv")

CHUNK_SIZE = 500_000

# Columns by target type
string_cols = [
    "transaction_id",
    "transaction_type",
    "street_number",
    "btq_code",
    "street_type",
    "street_id",
    "street_name",
    "postal_code",
    "com_name",
    "dep_code",
    "com_code",
    "section_prefix",
    "section",
    "plot_number",
    "volume_number",
    "property_type_code",
    "property_type",
    "land_nature",
    "land_nature_special",
    "surface_type",
    "lot_1",
    "lot_2",
    "lot_3",
    "lot_4",
    "lot_5"
]

date_cols = [
    "transaction_date",
]

float_cols = [
    "property_value",
    "building_real_surface",
    "land_surface",
    "lot_1_surface",
    "lot_2_surface",
    "lot_3_surface",
    "lot_4_surface",
    "lot_5_surface"
]

int_cols = [
    "lots_count",
    "main_rooms_count",
]


def convert_chunk_types(chunk: pd.DataFrame) -> pd.DataFrame:
    # String / categorical columns
    for col in string_cols:
        if col in chunk.columns:
            chunk[col] = chunk[col].astype("string").str.strip()

    # Date columns
    for col in date_cols:
        if col in chunk.columns:
            chunk[col] = pd.to_datetime(
                chunk[col],
                errors="coerce"
            )

    # Float columns
    for col in float_cols:
        if col in chunk.columns:
            if chunk[col].dtype == "object" or str(chunk[col].dtype) == "string":
                chunk[col] = (
                    chunk[col]
                    .astype("string")
                    .str.replace(",", ".", regex=False)
                    .str.strip()
                )
            chunk[col] = pd.to_numeric(chunk[col], errors="coerce").astype("float64")

    # Integer columns
    for col in int_cols:
        if col in chunk.columns:
            if chunk[col].dtype == "object" or str(chunk[col].dtype) == "string":
                chunk[col] = chunk[col].astype("string").str.strip()
            chunk[col] = pd.to_numeric(chunk[col], errors="coerce").astype("Int64")

    return chunk


def convert_file_types_chunked(
    input_file: Path,
    output_file: Path,
    chunk_size: int = 50_000
) -> None:
    output_file.parent.mkdir(parents=True, exist_ok=True)

    first_write = True
    total_rows = 0

    for chunk_idx, chunk in enumerate(
        pd.read_csv(input_file, chunksize=chunk_size, dtype=str),
        start=1
    ):
        chunk = convert_chunk_types(chunk)

        chunk.to_csv(
            output_file,
            mode="w" if first_write else "a",
            index=False,
            header=first_write,
            encoding="utf-8"
        )

        first_write = False
        total_rows += len(chunk)

        print(f"Chunk {chunk_idx} written -> {len(chunk):,} rows | total: {total_rows:,}")

    print("\n✅ Done! Converted column data types")
    print(f"Saved file: {output_file}")
    print(f"Total rows written: {total_rows:,}")


convert_file_types_chunked(INPUT_FILE, OUTPUT_FILE, CHUNK_SIZE)

Chunk 1 written -> 500,000 rows | total: 500,000
Chunk 2 written -> 500,000 rows | total: 1,000,000
Chunk 3 written -> 500,000 rows | total: 1,500,000
Chunk 4 written -> 500,000 rows | total: 2,000,000
Chunk 5 written -> 500,000 rows | total: 2,500,000
Chunk 6 written -> 500,000 rows | total: 3,000,000
Chunk 7 written -> 500,000 rows | total: 3,500,000
Chunk 8 written -> 500,000 rows | total: 4,000,000
Chunk 9 written -> 500,000 rows | total: 4,500,000
Chunk 10 written -> 500,000 rows | total: 5,000,000
Chunk 11 written -> 500,000 rows | total: 5,500,000
Chunk 12 written -> 500,000 rows | total: 6,000,000
Chunk 13 written -> 500,000 rows | total: 6,500,000
Chunk 14 written -> 500,000 rows | total: 7,000,000
Chunk 15 written -> 500,000 rows | total: 7,500,000
Chunk 16 written -> 500,000 rows | total: 8,000,000
Chunk 17 written -> 500,000 rows | total: 8,500,000
Chunk 18 written -> 500,000 rows | total: 9,000,000
Chunk 19 written -> 500,000 rows | total: 9,500,000
Chunk 20 written -> 500,000 rows | total: 10,000,000
Chunk 21 written -> 500,000 rows | total: 10,500,000
Chunk 22 written -> 500,000 rows | total: 11,000,000
Chunk 23 written -> 500,000 rows | total: 11,500,000
Chunk 24 written -> 500,000 rows | total: 12,000,000
Chunk 25 written -> 500,000 rows | total: 12,500,000
Chunk 26 written -> 500,000 rows | total: 13,000,000
Chunk 27 written -> 500,000 rows | total: 13,500,000
Chunk 28 written -> 500,000 rows | total: 14,000,000
Chunk 29 written -> 500,000 rows | total: 14,500,000
Chunk 30 written -> 500,000 rows | total: 15,000,000
Chunk 31 written -> 500,000 rows | total: 15,500,000
Chunk 32 written -> 500,000 rows | total: 16,000,000
Chunk 33 written -> 500,000 rows | total: 16,500,000
Chunk 34 written -> 500,000 rows | total: 17,000,000
Chunk 35 written -> 500,000 rows | total: 17,500,000
Chunk 36 written -> 500,000 rows | total: 18,000,000
Chunk 37 written -> 500,000 rows | total: 18,500,000
Chunk 38 written -> 500,000 rows | total: 19,000,000
Chunk 39 written -> 500,000 rows | total: 19,500,000
Chunk 40 written -> 500,000 rows | total: 20,000,000
Chunk 41 written -> 102,739 rows | total: 20,102,739

✅ Done! Converted column data types
Saved file: ..\data\processed\TYPES_ValeursFoncieres.csv
Total rows written: 20,102,739

### **DATASET TABLE V3 (Features & Target + Categorical vs Numeric)**

| #  | Original Column Name           | Standardized            | Description                                       | Data Type      | Type                          |
| -- | ------------------------------ | ----------------------- | ------------------------------------------------- | -------------- | ----------------------------- |
| 0  | **No disposition**             | `transaction_id`        | Unique identifier of the transaction              | string         | Categorical / identifier      |
| 1  | **Date mutation**              | `transaction_date`      | Date when the property was sold                   | datetime64[ns] | Temporal                      |
| 2  | **Nature mutation**            | `transaction_type`      | Nature of transaction (sale, exchange, etc.)      | string         | Categorical                   |
| 3  | **Valeur fonciere**            | `property_value`        | Transaction price in euros                        | Float64        | Numeric (**TARGET**)          |
| 4  | **No voie**                    | `street_number`         | Street number of the property                     | string         | Categorical / identifier      |
| 5  | **B/T/Q**                      | `btq_code`              | Building / Type / Quarter code                    | string         | Categorical                   |
| 6  | **Type de voie**               | `street_type`           | Type of street (Rue, Avenue, etc.)                | string         | Categorical                   |
| 7  | **Code voie**                  | `street_id`             | Street identifier code                            | string         | Categorical / identifier      |
| 8  | **Voie**                       | `street_name`           | Full street name                                  | string         | Categorical                   |
| 9  | **Code postal**                | `postal_code`           | Postal code                                       | string         | Categorical / geographic code |
| 10 | **Commune**                    | `com_name`              | Commune name                                      | string         | Categorical                   |
| 11 | **Code departement**           | `dep_code`              | Department code                                   | string         | Categorical / geographic code |
| 12 | **Code commune**               | `com_code`              | Commune code                                      | string         | Categorical / geographic code |
| 13 | **Prefixe de section**         | `section_prefix`        | Section prefix used in cadastral identification   | string         | Categorical / cadastral code  |
| 14 | **Section**                    | `section`               | Cadastral section identifier                      | string         | Categorical / cadastral code  |
| 15 | **No plan**                    | `plot_number`           | Parcel / plot number                              | string         | Categorical / identifier      |
| 16 | **No Volume**                  | `volume_number`         | Volume number for special cadastral cases         | string         | Categorical / identifier      |
| 17 | **1er lot**                    | `lot_1`                 | Identifier of the first lot                       | string         | Categorical / identifier      |
| 18 | **Surface Carrez du 1er lot**  | `lot_1_surface`         | Carrez surface of the first lot in square meters  | Float64        | Numeric                       |
| 19 | **2eme lot**                   | `lot_2`                 | Identifier of the second lot                      | string         | Categorical / identifier      |
| 20 | **Surface Carrez du 2eme lot** | `lot_2_surface`         | Carrez surface of the second lot in square meters | Float64        | Numeric                       |
| 21 | **3eme lot**                   | `lot_3`                 | Identifier of the third lot                       | string         | Categorical / identifier      |
| 22 | **Surface Carrez du 3eme lot** | `lot_3_surface`         | Carrez surface of the third lot in square meters  | Float64        | Numeric                       |
| 23 | **4eme lot**                   | `lot_4`                 | Identifier of the fourth lot                      | string         | Categorical / identifier      |
| 24 | **Surface Carrez du 4eme lot** | `lot_4_surface`         | Carrez surface of the fourth lot in square meters | Float64        | Numeric                       |
| 25 | **5eme lot**                   | `lot_5`                 | Identifier of the fifth lot                       | string         | Categorical / identifier      |
| 26 | **Surface Carrez du 5eme lot** | `lot_5_surface`         | Carrez surface of the fifth lot in square meters  | Float64        | Numeric                       |
| 27 | **Nombre de lots**             | `lots_count`            | Number of lots in the transaction                 | Int64          | Numeric count                 |
| 28 | **Code type local**            | `property_type_code`    | Code for property type                            | string         | Categorical code              |
| 29 | **Type local**                 | `property_type`         | Property type (Apartment, House, etc.)            | string         | Categorical                   |
| 30 | **Surface reelle bati**        | `building_real_surface` | Built area in square meters                       | Float64        | Numeric                       |
| 31 | **Nombre pieces principales**  | `main_rooms_count`      | Number of main rooms                              | Int64          | Numeric count                 |
| 32 | **Nature culture**             | `land_nature`           | General type of land usage                        | string         | Categorical                   |
| 33 | **Nature culture speciale**    | `land_nature_special`   | Specific type of land usage                       | string         | Categorical                   |
| 34 | **Surface terrain**            | `land_surface`          | Land area in square meters                        | Float64        | Numeric                       |
| 35 | *(derived)*                    | `surface_type`          | Type of surface: building / land / combined       | string         | Derived categorical           |

<hr>

## 4️⃣ NULL VALUES


<style>
h1 {
    text-align: center;
    color: black;
    font-weight: bold;
}
</style>

<style>
h2 {
    text-align: left;
    color: black;
    font-weight: bold;
}
</style>

<style>
h3 {
    text-align: left;
    color: black;
    font-weight: bold;
}
</style>

<style>
h4 {
    text-align: left;
    color: black;
    font-weight: bold;
}
</style>
<hr>

→ WHY? Missing data can bias results.

### **INFO - NULLS COUNT (BEFORE)**

In [15]:
import pandas as pd

FILE = "../data/processed/TYPES_ValeursFoncieres.csv"
CHUNK_SIZE = 500_000
dtype_map = {
    # categorical / identifiers
    "transaction_id": "string",
    "transaction_date": "string",  # convert to datetime after loading
    "transaction_type": "string",
    "street_number": "string",
    "btq_code": "string",
    "street_type": "string",
    "street_id": "string",
    "street_name": "string",
    "postal_code": "string",
    "com_name": "string",
    "dep_code": "string",
    "com_code": "string",
    "section_prefix": "string",
    "section": "string",
    "plot_number": "string",
    "volume_number": "string",
    "property_type_code": "string",  # keep as string (categorical)
    "property_type": "string",
    "land_nature": "string",
    "land_nature_special": "string",
    "surface_type": "string",

    # categorical lot identifiers
    "lot_1": "string",
    "lot_2": "string",
    "lot_3": "string",
    "lot_4": "string",
    "lot_5": "string",

    # numeric float (use nullable Float64 for consistency)
    "property_value": "Float64",
    "building_real_surface": "Float64",
    "land_surface": "Float64",
    "lot_1_surface": "Float64",
    "lot_2_surface": "Float64",
    "lot_3_surface": "Float64",
    "lot_4_surface": "Float64",
    "lot_5_surface": "Float64",

    # numeric integer (nullable)
    "lots_count": "Int64",
    "main_rooms_count": "Int64",
}


total_rows = 0
columns = None
non_null_counts = None
dtypes = None

for chunk in pd.read_csv(
    FILE,
    chunksize=CHUNK_SIZE,
    dtype=dtype_map,
    #parse_dates=["transaction_date"],
    #dayfirst=True,        # IMPORTANT! date format: dd/mm/yyyy
    low_memory=False      # removes DtypeWarning
):
    if columns is None:
        columns = chunk.columns.tolist()
        non_null_counts = {col: 0 for col in columns}
        dtypes = chunk.dtypes.astype(str).to_dict()

    total_rows += len(chunk)

    for col in columns:
        non_null_counts[col] += chunk[col].notna().sum()

info_df = pd.DataFrame({
    "column": columns,
    "non_null_count": [non_null_counts[col] for col in columns],
    "null_count": [total_rows - non_null_counts[col] for col in columns],
    "dtype": [dtypes[col] for col in columns]
})

print(f"RangeIndex: {total_rows} entries, 0 to {total_rows - 1}")
print(f"Data columns (total {len(columns)} columns):")
display(info_df)
print(f"dtypes: {info_df['dtype'].value_counts().to_dict()}")
print("memory usage: not computed (chunked mode)")

RangeIndex: 20102739 entries, 0 to 20102738
Data columns (total 36 columns):

                   column  non_null_count  null_count    dtype
0          transaction_id        20102739           0   string
1        transaction_date        20102739           0   string
2        transaction_type        20102739           0   string
3          property_value        19908349      194390  Float64
4           street_number        12628228     7474511   string
5                btq_code          904998    19197741   string
6             street_type        12160680     7942059   string
7               street_id        19952257      150482   string
8             street_name        19951476      151263   string
9             postal_code        19951139      151600   string
10               com_name        20102739           0   string
11               dep_code        20102739           0   string
12               com_code        20102739           0   string
13         section_prefix          954922    19147817   string
14                section        20102014         725   string
15            plot_number        20102739           0   string
16          volume_number           45381    20057358   string
17                  lot_1         6304273    13798466   string
18          lot_1_surface         1772926    18329813  Float64
19                  lot_2         1848289    18254450   string
20          lot_2_surface          570300    19532439  Float64
21                  lot_3          331965    19770774   string
22          lot_3_surface           64116    20038623  Float64
23                  lot_4          108005    19994734   string
24          lot_4_surface           15935    20086804  Float64
25                  lot_5           48066    20054673   string
26          lot_5_surface            5697    20097042  Float64
27             lots_count        20102739           0    Int64
28     property_type_code        11890422     8212317   string
29          property_type        11890422     8212317   string
30  building_real_surface        20102739           0  Float64
31       main_rooms_count        20102739           0    Int64
32            land_nature        13706037     6396702   string
33    land_nature_special          863125    19239614   string
34           land_surface        13706037     6396702  Float64
35           surface_type        16360511     3742228   string

dtypes: {'string': 26, 'Float64': 8, 'Int64': 2}
memory usage: not computed (chunked mode)

### **DEAL with NULLS FINAL**

In [19]:
from pathlib import Path
import pandas as pd

INPUT_FILE = Path("../data/processed/TYPES_ValeursFoncieres.csv")
OUTPUT_FILE = Path("../data/processed/NULLS_ValeursFoncieres.csv")

CHUNK_SIZE = 500_000

dtype_map = {
    # categorical / identifiers
    "transaction_id": "string",
    "transaction_date": "string",
    "transaction_type": "string",
    "street_number": "string",
    "btq_code": "string",
    "street_type": "string",
    "street_id": "string",
    "street_name": "string",
    "postal_code": "string",
    "com_name": "string",
    "dep_code": "string",
    "com_code": "string",
    "section_prefix": "string",
    "section": "string",
    "plot_number": "string",
    "volume_number": "string",
    "property_type_code": "string",
    "property_type": "string",
    "land_nature": "string",
    "land_nature_special": "string",
    "surface_type": "string",

    # categorical lot identifiers
    "lot_1": "string",
    "lot_2": "string",
    "lot_3": "string",
    "lot_4": "string",
    "lot_5": "string",

    # numeric float
    "property_value": "Float64",
    "building_real_surface": "Float64",
    "land_surface": "Float64",
    "lot_1_surface": "Float64",
    "lot_2_surface": "Float64",
    "lot_3_surface": "Float64",
    "lot_4_surface": "Float64",
    "lot_5_surface": "Float64",

    # numeric integer
    "lots_count": "Int64",
    "main_rooms_count": "Int64",
}


def handle_nulls(chunk: pd.DataFrame) -> pd.DataFrame:

    # --------------------------------------------------------------------------------
    # Column: property_value (TARGET)
    # --------------------------------------------------------------------------------
    # target cannot be imputed safely
    chunk = chunk.dropna(subset=["property_value"]).copy()

    # --------------------------------------------------------------------------------
    # Column: building_real_surface
    # --------------------------------------------------------------------------------
    chunk["building_real_surface"] = chunk["building_real_surface"].fillna(0.0)

    # --------------------------------------------------------------------------------
    # Columns: lot_1_surface, lot_2_surface, lot_3_surface, lot_4_surface, lot_5_surface
    # --------------------------------------------------------------------------------
    chunk["lot_1_surface"] = chunk["lot_1_surface"].fillna(0.0)
    chunk["lot_2_surface"] = chunk["lot_2_surface"].fillna(0.0)
    chunk["lot_3_surface"] = chunk["lot_3_surface"].fillna(0.0)
    chunk["lot_4_surface"] = chunk["lot_4_surface"].fillna(0.0)
    chunk["lot_5_surface"] = chunk["lot_5_surface"].fillna(0.0)

    # --------------------------------------------------------------------------------
    # Column: main_rooms_count
    # --------------------------------------------------------------------------------
    # if main_rooms_count is missing and building_real_surface exists, fill with 0
    mask = (
        chunk["main_rooms_count"].isna() &
        (chunk["building_real_surface"] >= 0)
    )
    chunk.loc[mask, "main_rooms_count"] = 0

    # --------------------------------------------------------------------------------
    # Column: land_surface
    # --------------------------------------------------------------------------------
    # if land_surface is missing and building_real_surface exists, fill with 0
    mask = (
        chunk["land_surface"].isna() &
        (chunk["building_real_surface"] > 0)
    )
    chunk.loc[mask, "land_surface"] = 0.0

    # --------------------------------------------------------------------------------
    # Column: land_surface
    # --------------------------------------------------------------------------------
    chunk["land_surface"] = chunk["land_surface"].fillna(0.0)

    # --------------------------------------------------------------------------------
    # Column: lots_count
    # --------------------------------------------------------------------------------
    chunk["lots_count"] = chunk["lots_count"].fillna(0)

    # --------------------------------------------------------------------------------
    # Column: main_rooms_count
    # --------------------------------------------------------------------------------
    chunk["main_rooms_count"] = chunk["main_rooms_count"].fillna(0)

    # --------------------------------------------------------------------------------
    # Column: transaction_id
    # --------------------------------------------------------------------------------
    chunk["transaction_id"] = chunk["transaction_id"].fillna("Unknown")

    # --------------------------------------------------------------------------------
    # Column: transaction_date
    # --------------------------------------------------------------------------------
    chunk["transaction_date"] = chunk["transaction_date"].fillna("Unknown")

    # --------------------------------------------------------------------------------
    # Column: transaction_type
    # --------------------------------------------------------------------------------
    chunk["transaction_type"] = chunk["transaction_type"].fillna("Unknown")

    # --------------------------------------------------------------------------------
    # Column: street_number
    # --------------------------------------------------------------------------------
    chunk["street_number"] = chunk["street_number"].fillna("Unknown")

    # --------------------------------------------------------------------------------
    # Column: btq_code
    # --------------------------------------------------------------------------------
    chunk["btq_code"] = chunk["btq_code"].fillna("Unknown")

    # --------------------------------------------------------------------------------
    # Column: street_type
    # --------------------------------------------------------------------------------
    chunk["street_type"] = chunk["street_type"].fillna("Unknown")

    # --------------------------------------------------------------------------------
    # Column: street_id
    # --------------------------------------------------------------------------------
    chunk["street_id"] = chunk["street_id"].fillna("Unknown")

    # --------------------------------------------------------------------------------
    # Column: street_name
    # --------------------------------------------------------------------------------
    chunk["street_name"] = chunk["street_name"].fillna("Unknown")

    # --------------------------------------------------------------------------------
    # Column: postal_code
    # --------------------------------------------------------------------------------
    chunk["postal_code"] = chunk["postal_code"].fillna("Unknown")

    # --------------------------------------------------------------------------------
    # Column: com_name
    # --------------------------------------------------------------------------------
    chunk["com_name"] = chunk["com_name"].fillna("Unknown")

    # --------------------------------------------------------------------------------
    # Column: dep_code
    # --------------------------------------------------------------------------------
    chunk["dep_code"] = chunk["dep_code"].fillna("Unknown")

    # --------------------------------------------------------------------------------
    # Column: com_code
    # --------------------------------------------------------------------------------
    chunk["com_code"] = chunk["com_code"].fillna("Unknown")

    # --------------------------------------------------------------------------------
    # Column: section_prefix
    # --------------------------------------------------------------------------------
    chunk["section_prefix"] = chunk["section_prefix"].fillna("Unknown")

    # --------------------------------------------------------------------------------
    # Column: section
    # --------------------------------------------------------------------------------
    chunk["section"] = chunk["section"].fillna("Unknown")

    # --------------------------------------------------------------------------------
    # Column: plot_number
    # --------------------------------------------------------------------------------
    chunk["plot_number"] = chunk["plot_number"].fillna("Unknown")

    # --------------------------------------------------------------------------------
    # Column: volume_number
    # --------------------------------------------------------------------------------
    chunk["volume_number"] = chunk["volume_number"].fillna("Unknown")

    # --------------------------------------------------------------------------------
    # Columns: lot_1, lot_2, lot_3, lot_4, lot_5
    # --------------------------------------------------------------------------------
    chunk["lot_1"] = chunk["lot_1"].fillna("Unknown")
    chunk["lot_2"] = chunk["lot_2"].fillna("Unknown")
    chunk["lot_3"] = chunk["lot_3"].fillna("Unknown")
    chunk["lot_4"] = chunk["lot_4"].fillna("Unknown")
    chunk["lot_5"] = chunk["lot_5"].fillna("Unknown")

    # --------------------------------------------------------------------------------
    # Column: property_type_code
    # --------------------------------------------------------------------------------
    chunk["property_type_code"] = chunk["property_type_code"].fillna("Unknown")

    # --------------------------------------------------------------------------------
    # Column: property_type
    # --------------------------------------------------------------------------------
    chunk["property_type"] = chunk["property_type"].fillna("Unknown")

    # --------------------------------------------------------------------------------
    # Column: land_nature
    # --------------------------------------------------------------------------------
    chunk["land_nature"] = chunk["land_nature"].fillna("Unknown")

    # --------------------------------------------------------------------------------
    # Column: land_nature_special
    # --------------------------------------------------------------------------------
    chunk["land_nature_special"] = chunk["land_nature_special"].fillna("Unknown")

    # --------------------------------------------------------------------------------
    # Column: surface_type
    # --------------------------------------------------------------------------------
    chunk["surface_type"] = chunk["surface_type"].fillna("Unknown")

    # --------------------------------------------------------------------------------
    # Restore numeric dtypes
    # --------------------------------------------------------------------------------
    chunk["property_value"] = pd.to_numeric(chunk["property_value"], errors="coerce")
    chunk["building_real_surface"] = pd.to_numeric(chunk["building_real_surface"], errors="coerce")
    chunk["land_surface"] = pd.to_numeric(chunk["land_surface"], errors="coerce")
    chunk["lot_1_surface"] = pd.to_numeric(chunk["lot_1_surface"], errors="coerce")
    chunk["lot_2_surface"] = pd.to_numeric(chunk["lot_2_surface"], errors="coerce")
    chunk["lot_3_surface"] = pd.to_numeric(chunk["lot_3_surface"], errors="coerce")
    chunk["lot_4_surface"] = pd.to_numeric(chunk["lot_4_surface"], errors="coerce")
    chunk["lot_5_surface"] = pd.to_numeric(chunk["lot_5_surface"], errors="coerce")

    chunk["lots_count"] = pd.to_numeric(chunk["lots_count"], errors="coerce").astype("Int64")
    chunk["main_rooms_count"] = pd.to_numeric(chunk["main_rooms_count"], errors="coerce").astype("Int64")

    return chunk


def process_nulls_chunked(input_file: Path, output_file: Path, chunk_size: int = 500_000) -> None:
    output_file.parent.mkdir(parents=True, exist_ok=True)

    first_write = True
    total_rows_read = 0
    total_rows_written = 0
    total_rows_dropped = 0

    for i, chunk in enumerate(
        pd.read_csv(
            input_file,
            chunksize=chunk_size,
            dtype=dtype_map,
            low_memory=False
        ),
        start=1
    ):
        rows_before = len(chunk)
        total_rows_read += rows_before

        chunk = handle_nulls(chunk)

        rows_after = len(chunk)
        total_rows_written += rows_after
        total_rows_dropped += rows_before - rows_after

        chunk.to_csv(
            output_file,
            mode="w" if first_write else "a",
            index=False,
            header=first_write,
            encoding="utf-8"
        )

        first_write = False

        print(
            f"Chunk {i} processed -> "
            f"read: {rows_before:,} | kept: {rows_after:,} | "
            f"dropped: {rows_before - rows_after:,} | total kept: {total_rows_written:,}"
        )

    print("\n✅ Done! Null values handled")
    print(f"Saved file: {output_file}")
    print(f"Total rows read: {total_rows_read:,}")
    print(f"Total rows dropped: {total_rows_dropped:,}")
    print(f"Total rows written: {total_rows_written:,}")


process_nulls_chunked(INPUT_FILE, OUTPUT_FILE, CHUNK_SIZE)

Chunk 1 processed -> read: 500,000 | kept: 496,656 | dropped: 3,344 | total kept: 496,656
Chunk 2 processed -> read: 500,000 | kept: 496,789 | dropped: 3,211 | total kept: 993,445
Chunk 3 processed -> read: 500,000 | kept: 485,317 | dropped: 14,683 | total kept: 1,478,762
Chunk 4 processed -> read: 500,000 | kept: 487,634 | dropped: 12,366 | total kept: 1,966,396
Chunk 5 processed -> read: 500,000 | kept: 497,421 | dropped: 2,579 | total kept: 2,463,817
Chunk 6 processed -> read: 500,000 | kept: 497,411 | dropped: 2,589 | total kept: 2,961,228
Chunk 7 processed -> read: 500,000 | kept: 484,285 | dropped: 15,715 | total kept: 3,445,513
Chunk 8 processed -> read: 500,000 | kept: 498,051 | dropped: 1,949 | total kept: 3,943,564
Chunk 9 processed -> read: 500,000 | kept: 496,009 | dropped: 3,991 | total kept: 4,439,573
Chunk 10 processed -> read: 500,000 | kept: 496,176 | dropped: 3,824 | total kept: 4,935,749
Chunk 11 processed -> read: 500,000 | kept: 495,767 | dropped: 4,233 | total kept: 5,431,516
Chunk 12 processed -> read: 500,000 | kept: 497,158 | dropped: 2,842 | total kept: 5,928,674
Chunk 13 processed -> read: 500,000 | kept: 496,778 | dropped: 3,222 | total kept: 6,425,452
Chunk 14 processed -> read: 500,000 | kept: 496,471 | dropped: 3,529 | total kept: 6,921,923
Chunk 15 processed -> read: 500,000 | kept: 498,024 | dropped: 1,976 | total kept: 7,419,947
Chunk 16 processed -> read: 500,000 | kept: 496,252 | dropped: 3,748 | total kept: 7,916,199
Chunk 17 processed -> read: 500,000 | kept: 497,773 | dropped: 2,227 | total kept: 8,413,972
Chunk 18 processed -> read: 500,000 | kept: 495,422 | dropped: 4,578 | total kept: 8,909,394
Chunk 19 processed -> read: 500,000 | kept: 494,107 | dropped: 5,893 | total kept: 9,403,501
Chunk 20 processed -> read: 500,000 | kept: 496,947 | dropped: 3,053 | total kept: 9,900,448
Chunk 21 processed -> read: 500,000 | kept: 496,089 | dropped: 3,911 | total kept: 10,396,537
Chunk 22 processed -> read: 500,000 | kept: 497,408 | dropped: 2,592 | total kept: 10,893,945
Chunk 23 processed -> read: 500,000 | kept: 496,785 | dropped: 3,215 | total kept: 11,390,730
Chunk 24 processed -> read: 500,000 | kept: 497,084 | dropped: 2,916 | total kept: 11,887,814
Chunk 25 processed -> read: 500,000 | kept: 495,564 | dropped: 4,436 | total kept: 12,383,378
Chunk 26 processed -> read: 500,000 | kept: 495,973 | dropped: 4,027 | total kept: 12,879,351
Chunk 27 processed -> read: 500,000 | kept: 494,048 | dropped: 5,952 | total kept: 13,373,399
Chunk 28 processed -> read: 500,000 | kept: 496,504 | dropped: 3,496 | total kept: 13,869,903
Chunk 29 processed -> read: 500,000 | kept: 496,292 | dropped: 3,708 | total kept: 14,366,195
Chunk 30 processed -> read: 500,000 | kept: 496,547 | dropped: 3,453 | total kept: 14,862,742
Chunk 31 processed -> read: 500,000 | kept: 489,882 | dropped: 10,118 | total kept: 15,352,624
Chunk 32 processed -> read: 500,000 | kept: 496,730 | dropped: 3,270 | total kept: 15,849,354
Chunk 33 processed -> read: 500,000 | kept: 494,292 | dropped: 5,708 | total kept: 16,343,646
Chunk 34 processed -> read: 500,000 | kept: 494,619 | dropped: 5,381 | total kept: 16,838,265
Chunk 35 processed -> read: 500,000 | kept: 489,868 | dropped: 10,132 | total kept: 17,328,133
Chunk 36 processed -> read: 500,000 | kept: 495,687 | dropped: 4,313 | total kept: 17,823,820
Chunk 37 processed -> read: 500,000 | kept: 496,706 | dropped: 3,294 | total kept: 18,320,526
Chunk 38 processed -> read: 500,000 | kept: 497,211 | dropped: 2,789 | total kept: 18,817,737
Chunk 39 processed -> read: 500,000 | kept: 495,678 | dropped: 4,322 | total kept: 19,313,415
Chunk 40 processed -> read: 500,000 | kept: 493,639 | dropped: 6,361 | total kept: 19,807,054
Chunk 41 processed -> read: 102,739 | kept: 101,295 | dropped: 1,444 | total kept: 19,908,349

✅ Done! Null values handled
Saved file: ..\data\processed\NULLS_ValeursFoncieres.csv
Total rows read: 20,102,739
Total rows dropped: 194,390
Total rows written: 19,908,349

### **INFO - NULLS COUNT (AFTER)**

In [20]:
import pandas as pd

print("Re-checking data types and null counts after null handling...")

FILE = "../data/processed/NULLS_ValeursFoncieres.csv"
CHUNK_SIZE = 500_000

dtype_map = {
    # categorical / identifiers
    "transaction_id": "string",
    "transaction_date": "string",  # convert to datetime after loading
    "transaction_type": "string",
    "street_number": "string",
    "btq_code": "string",
    "street_type": "string",
    "street_id": "string",
    "street_name": "string",
    "postal_code": "string",
    "com_name": "string",
    "dep_code": "string",
    "com_code": "string",
    "section_prefix": "string",
    "section": "string",
    "plot_number": "string",
    "volume_number": "string",
    "property_type_code": "string",  # keep as string (categorical)
    "property_type": "string",
    "land_nature": "string",
    "land_nature_special": "string",
    "surface_type": "string",

    # lot identifiers
    "lot_1": "string",
    "lot_2": "string",
    "lot_3": "string",
    "lot_4": "string",
    "lot_5": "string",

    # numeric (use nullable Float64 for consistency)
    "property_value": "Float64",
    "building_real_surface": "Float64",
    "land_surface": "Float64",
    "lot_1_surface": "Float64",
    "lot_2_surface": "Float64",
    "lot_3_surface": "Float64",
    "lot_4_surface": "Float64",
    "lot_5_surface": "Float64",

    # integer (nullable)
    "lots_count": "Int64",
    "main_rooms_count": "Int64",
}


total_rows = 0
columns = None
non_null_counts = None
dtypes = None

for chunk in pd.read_csv(
    FILE,
    chunksize=CHUNK_SIZE,
    dtype=dtype_map,
    #parse_dates=["transaction_date"],
    #dayfirst=True,        # IMPORTANT! date format: dd/mm/yyyy
    low_memory=False      # removes DtypeWarning
):
    if columns is None:
        columns = chunk.columns.tolist()
        non_null_counts = {col: 0 for col in columns}
        dtypes = chunk.dtypes.astype(str).to_dict()

    total_rows += len(chunk)

    for col in columns:
        non_null_counts[col] += chunk[col].notna().sum()

info_df = pd.DataFrame({
    "column": columns,
    "non_null_count": [non_null_counts[col] for col in columns],
    "null_count": [total_rows - non_null_counts[col] for col in columns],
    "dtype": [dtypes[col] for col in columns]
})

print(f"RangeIndex: {total_rows} entries, 0 to {total_rows - 1}")
print(f"Data columns (total {len(columns)} columns):")
display(info_df)
print(f"dtypes: {info_df['dtype'].value_counts().to_dict()}")
print("memory usage: not computed (chunked mode)")

Re-checking data types and null counts after null handling...
RangeIndex: 19908349 entries, 0 to 19908348
Data columns (total 36 columns):

                   column  non_null_count  null_count    dtype
0          transaction_id        19908349           0   string
1        transaction_date        19908349           0   string
2        transaction_type        19908349           0   string
3          property_value        19908349           0  Float64
4           street_number        19908349           0   string
5                btq_code        19908349           0   string
6             street_type        19908349           0   string
7               street_id        19908349           0   string
8             street_name        19908349           0   string
9             postal_code        19908349           0   string
10               com_name        19908349           0   string
11               dep_code        19908349           0   string
12               com_code        19908349           0   string
13         section_prefix        19908349           0   string
14                section        19908349           0   string
15            plot_number        19908349           0   string
16          volume_number        19908349           0   string
17                  lot_1        19908349           0   string
18          lot_1_surface        19908349           0  Float64
19                  lot_2        19908349           0   string
20          lot_2_surface        19908349           0  Float64
21                  lot_3        19908349           0   string
22          lot_3_surface        19908349           0  Float64
23                  lot_4        19908349           0   string
24          lot_4_surface        19908349           0  Float64
25                  lot_5        19908349           0   string
26          lot_5_surface        19908349           0  Float64
27             lots_count        19908349           0    Int64
28     property_type_code        19908349           0   string
29          property_type        19908349           0   string
30  building_real_surface        19908349           0  Float64
31       main_rooms_count        19908349           0    Int64
32            land_nature        19908349           0   string
33    land_nature_special        19908349           0   string
34           land_surface        19908349           0  Float64
35           surface_type        19908349           0   string

dtypes: {'string': 26, 'Float64': 8, 'Int64': 2}
memory usage: not computed (chunked mode)

<hr>

## 5️⃣ DUPLICATES


<style>
h1 {
    text-align: center;
    color: black;
    font-weight: bold;
}
</style>

<style>
h2 {
    text-align: left;
    color: black;
    font-weight: bold;
}
</style>

<style>
h3 {
    text-align: left;
    color: black;
    font-weight: bold;
}
</style>

<style>
h4 {
    text-align: left;
    color: black;
    font-weight: bold;
}
</style>
<hr>

### **SHAPE & HEAD - BEFORE Dealing with Duplicates**

In [21]:
import pandas as pd

FILE = "../data/processed/NULLS_ValeursFoncieres.csv"
CHUNK_SIZE = 500_000

dtype_map = {
    # categorical / identifiers
    "transaction_id": "string",
    "transaction_date": "string",  # convert to datetime after loading
    "transaction_type": "string",
    "street_number": "string",
    "btq_code": "string",
    "street_type": "string",
    "street_id": "string",
    "street_name": "string",
    "postal_code": "string",
    "com_name": "string",
    "dep_code": "string",
    "com_code": "string",
    "section_prefix": "string",
    "section": "string",
    "plot_number": "string",
    "volume_number": "string",
    "property_type_code": "string",  # keep as string (categorical)
    "property_type": "string",
    "land_nature": "string",
    "land_nature_special": "string",
    "surface_type": "string",

    # lot identifiers
    "lot_1": "string",
    "lot_2": "string",
    "lot_3": "string",
    "lot_4": "string",
    "lot_5": "string",

    # numeric (use nullable Float64 for consistency)
    "property_value": "Float64",
    "building_real_surface": "Float64",
    "land_surface": "Float64",
    "lot_1_surface": "Float64",
    "lot_2_surface": "Float64",
    "lot_3_surface": "Float64",
    "lot_4_surface": "Float64",
    "lot_5_surface": "Float64",

    # integer (nullable)
    "lots_count": "Int64",
    "main_rooms_count": "Int64",
}

# ---------------------------
# Get full dataset shape
# ---------------------------
total_rows = 0
columns = None

for chunk in pd.read_csv(
    FILE,
    chunksize=CHUNK_SIZE,
    dtype=dtype_map,
    low_memory=False
):
    total_rows += len(chunk)
    if columns is None:
        columns = chunk.columns

print("Shape:", total_rows, "rows and", len(columns), "columns")

# ---------------------------
# Display head with correct dtypes
# ---------------------------
df_head = pd.read_csv(
    FILE,
    nrows=5,
    dtype=dtype_map,
    low_memory=False
)

display(df_head)

Shape: 19908349 rows and 36 columns

,transaction_id,transaction_date,transaction_type,property_value,street_number,btq_code,street_type,street_id,street_name,postal_code,com_name,dep_code,com_code,section_prefix,section,plot_number,volume_number,lot_1,lot_1_surface,lot_2,lot_2_surface,lot_3,lot_3_surface,lot_4,lot_4_surface,lot_5,lot_5_surface,lots_count,property_type_code,property_type,building_real_surface,main_rooms_count,land_nature,land_nature_special,land_surface,surface_type
0,000001,2020-07-01,Sale,31234.16,Unknown,Unknown,Unknown,B064,SAINT JULIEN,1560,SAINT-JULIEN-SUR-REYSSOUZE,01,367,Unknown,A,8,Unknown,Unknown,0.0,Unknown,0.0,Unknown,0.0,Unknown,0.0,Unknown,0.0,0,Unknown,Unknown,0.0,0,AB,Unknown,1192.0,land
1,000001,2020-07-01,Sale,278000.0,Unknown,Unknown,Unknown,B188,A LA PEROUSE,1250,CORVEISSIAT,01,125,Unknown,C,509,Unknown,Unknown,0.0,Unknown,0.0,Unknown,0.0,Unknown,0.0,Unknown,0.0,0,Unknown,Unknown,0.0,0,BS,Unknown,10092.0,land
2,000001,2020-07-01,Sale,278000.0,Unknown,Unknown,Unknown,B188,A LA PEROUSE,1250,CORVEISSIAT,01,125,Unknown,C,510,Unknown,Unknown,0.0,Unknown,0.0,Unknown,0.0,Unknown,0.0,Unknown,0.0,0,Unknown,Unknown,0.0,0,L,Unknown,4570.0,land
3,000001,2020-07-01,Sale,278000.0,Unknown,Unknown,Unknown,B079,AUX COMMUNS,1250,CORVEISSIAT,01,125,Unknown,ZL,96,Unknown,Unknown,0.0,Unknown,0.0,Unknown,0.0,Unknown,0.0,Unknown,0.0,0,Unknown,Unknown,0.0,0,BS,Unknown,5750.0,land
4,000001,2020-07-01,Sale,278000.0,Unknown,Unknown,Unknown,B033,EN COMBARNAUD,1250,SIMANDRE-SUR-SURAN,01,408,Unknown,A,14,Unknown,Unknown,0.0,Unknown,0.0,Unknown,0.0,Unknown,0.0,Unknown,0.0,0,Unknown,Unknown,0.0,0,BT,Unknown,648170.0,land

### **DUPLICATES STATS (percentage and count of duplicates)**

In [ ]:
import pandas as pd
from pathlib import Path
import hashlib

INPUT_FILE = Path("../data/processed/NULLS_ValeursFoncieres.csv")

chunk_size = 1_000_000

dtype_map = {
    "transaction_id": "string",
    "transaction_date": "string",
    "transaction_type": "string",
    "street_number": "string",
    "btq_code": "string",
    "street_type": "string",
    "street_id": "string",
    "street_name": "string",
    "postal_code": "string",
    "com_name": "string",
    "dep_code": "string",
    "com_code": "string",
    "section_prefix": "string",
    "section": "string",
    "plot_number": "string",
    "volume_number": "string",
    "property_type_code": "string",
    "property_type": "string",
    "land_nature": "string",
    "land_nature_special": "string",
    "surface_type": "string",

    "lot_1": "string",
    "lot_2": "string",
    "lot_3": "string",
    "lot_4": "string",
    "lot_5": "string",

    "property_value": "Float64",
    "building_real_surface": "Float64",
    "land_surface": "Float64",
    "lot_1_surface": "Float64",
    "lot_2_surface": "Float64",
    "lot_3_surface": "Float64",
    "lot_4_surface": "Float64",
    "lot_5_surface": "Float64",

    "lots_count": "Int64",
    "main_rooms_count": "Int64",
}

total_rows = 0
total_duplicates = 0
seen_hashes = set()


def hash_row(row):
    # No cleaning needed, just stringify
    row_string = "|".join(map(str, row))
    return hashlib.md5(row_string.encode("utf-8")).hexdigest()


for chunk in pd.read_csv(
    INPUT_FILE,
    chunksize=chunk_size,
    dtype=dtype_map,
    low_memory=False
):
    total_rows += len(chunk)

    for row in chunk.itertuples(index=False, name=None):
        h = hash_row(row)

        if h in seen_hashes:
            total_duplicates += 1
        else:
            seen_hashes.add(h)


unique_rows = total_rows - total_duplicates
duplicate_percentage = (total_duplicates / total_rows) * 100

print(f"Total rows (including duplicates): {total_rows:,}")
print(f"Duplicate rows (excluding first occurrences): {total_duplicates:,}")
print(f"Duplicate percentage: {duplicate_percentage:.2f}%")
print(f"Total rows without duplicates (including first occurrences): {unique_rows:,}")

Total rows (including duplicates): 19,908,349
Duplicate rows (excluding first occurrences): 1,388,539
Duplicate percentage: 6.97%
Total rows without duplicates (including first occurrences): 18,519,810

### **DUPLICATES ROWS & NULLS**

In [23]:
from pathlib import Path
import pandas as pd
import hashlib

FILE = Path("../data/processed/NULLS_ValeursFoncieres.csv")
CHUNK_SIZE = 500_000


dtype_map = {
    # categorical / identifiers
    "transaction_id": "string",
    "transaction_date": "string",  # convert to datetime after loading
    "transaction_type": "string",
    "street_number": "string",
    "btq_code": "string",
    "street_type": "string",
    "street_id": "string",
    "street_name": "string",
    "postal_code": "string",
    "com_name": "string",
    "dep_code": "string",
    "com_code": "string",
    "section_prefix": "string",
    "section": "string",
    "plot_number": "string",
    "volume_number": "string",
    "property_type_code": "string",  # keep as string (categorical)
    "property_type": "string",
    "land_nature": "string",
    "land_nature_special": "string",
    "surface_type": "string",

    # lot identifiers
    "lot_1": "string",
    "lot_2": "string",
    "lot_3": "string",
    "lot_4": "string",
    "lot_5": "string",

    # numeric (use nullable Float64 for consistency)
    "property_value": "Float64",
    "building_real_surface": "Float64",
    "land_surface": "Float64",
    "lot_1_surface": "Float64",
    "lot_2_surface": "Float64",
    "lot_3_surface": "Float64",
    "lot_4_surface": "Float64",
    "lot_5_surface": "Float64",

    # integer (nullable)
    "lots_count": "Int64",
    "main_rooms_count": "Int64",
}

def row_hash(row: pd.Series) -> str:
    values = row.fillna("<NA>").astype(str).tolist()
    row_str = "||".join(values)
    return hashlib.md5(row_str.encode("utf-8")).hexdigest()

total_rows = 0
duplicate_rows_count = 0
seen_hashes = set()

null_counts = None
columns = None
duplicate_samples = []

for chunk in pd.read_csv(
    FILE,
    chunksize=CHUNK_SIZE,
    dtype=dtype_map,
    low_memory=False
):
    if columns is None:
        columns = chunk.columns.tolist()
        null_counts = {col: 0 for col in columns}

    total_rows += len(chunk)

    # Null counts
    for col in columns:
        null_counts[col] += chunk[col].isna().sum()

    # Duplicate detection across all chunks
    chunk_hashes = chunk.apply(row_hash, axis=1)

    is_duplicate = chunk_hashes.isin(seen_hashes)
    duplicate_rows_count += is_duplicate.sum()

    # Save a few duplicate row samples for display
    if is_duplicate.any() and len(duplicate_samples) < 20:
        sample_dups = chunk.loc[is_duplicate].head(20 - len(duplicate_samples))
        duplicate_samples.append(sample_dups)

    # Add only new hashes
    new_hashes = chunk_hashes.loc[~is_duplicate]
    seen_hashes.update(new_hashes.tolist())

# Build null percentage summary
null_pct = {
    col: round(null_counts[col] / total_rows * 100, 2)
    for col in columns
}

nulls_df = pd.DataFrame({
    "column": columns,
    "null_count": [null_counts[col] for col in columns],
    "null_pct": [null_pct[col] for col in columns]
}).sort_values("null_pct", ascending=False)


# Print results
print(100 * "-")
print(f"Number of duplicate rows: {duplicate_rows_count}")
print("Nulls percentage in each column:")
display(nulls_df)
print(f"Duplicate rows percentage: {duplicate_rows_count / total_rows * 100:.2f}%")
print(100 * "-")

# Display duplicate samples if any
if duplicate_rows_count > 0:
    print("\nDuplicate row samples:")
    display(pd.concat(duplicate_samples, ignore_index=True))
else:
    print("\nNo duplicate rows found.")

----------------------------------------------------------------------------------------------------
Number of duplicate rows: 608
Nulls percentage in each column:

                   column  null_count  null_pct
0          transaction_id           0       0.0
1        transaction_date           0       0.0
2        transaction_type           0       0.0
3          property_value           0       0.0
4           street_number           0       0.0
5                btq_code           0       0.0
6             street_type           0       0.0
7               street_id           0       0.0
8             street_name           0       0.0
9             postal_code           0       0.0
10               com_name           0       0.0
11               dep_code           0       0.0
12               com_code           0       0.0
13         section_prefix           0       0.0
14                section           0       0.0
15            plot_number           0       0.0
16          volume_number           0       0.0
17                  lot_1           0       0.0
18          lot_1_surface           0       0.0
19                  lot_2           0       0.0
20          lot_2_surface           0       0.0
21                  lot_3           0       0.0
22          lot_3_surface           0       0.0
23                  lot_4           0       0.0
24          lot_4_surface           0       0.0
25                  lot_5           0       0.0
26          lot_5_surface           0       0.0
27             lots_count           0       0.0
28     property_type_code           0       0.0
29          property_type           0       0.0
30  building_real_surface           0       0.0
31       main_rooms_count           0       0.0
32            land_nature           0       0.0
33    land_nature_special           0       0.0
34           land_surface           0       0.0
35           surface_type           0       0.0

Duplicate rows percentage: 0.00%
----------------------------------------------------------------------------------------------------

Duplicate row samples:

,transaction_id,transaction_date,transaction_type,property_value,street_number,btq_code,street_type,street_id,street_name,postal_code,com_name,dep_code,com_code,section_prefix,section,plot_number,volume_number,lot_1,lot_1_surface,lot_2,lot_2_surface,lot_3,lot_3_surface,lot_4,lot_4_surface,lot_5,lot_5_surface,lots_count,property_type_code,property_type,building_real_surface,main_rooms_count,land_nature,land_nature_special,land_surface,surface_type
0,000001,2020-10-20,Sale,5308941.0,36,Unknown,RLE,0070,DES ATTES,97436,SAINT-LEU,974,13,Unknown,AV,1712,Unknown,Unknown,0.0,Unknown,0.0,Unknown,0.0,Unknown,0.0,Unknown,0.0,0,2,Apartment,73.0,4,S,Unknown,35.0,combined
1,000001,2020-10-20,Sale,5308941.0,36,Unknown,RLE,0070,DES ATTES,97436,SAINT-LEU,974,13,Unknown,AV,1712,Unknown,Unknown,0.0,Unknown,0.0,Unknown,0.0,Unknown,0.0,Unknown,0.0,0,2,Apartment,34.0,2,S,Unknown,35.0,combined
2,000001,2020-10-20,Sale,5308941.0,36,Unknown,RLE,0070,DES ATTES,97436,SAINT-LEU,974,13,Unknown,AV,1712,Unknown,Unknown,0.0,Unknown,0.0,Unknown,0.0,Unknown,0.0,Unknown,0.0,0,2,Apartment,73.0,4,S,Unknown,35.0,combined
3,000001,2020-10-20,Sale,5308941.0,36,Unknown,RLE,0070,DES ATTES,97436,SAINT-LEU,974,13,Unknown,AV,1712,Unknown,Unknown,0.0,Unknown,0.0,Unknown,0.0,Unknown,0.0,Unknown,0.0,0,2,Apartment,73.0,4,S,Unknown,35.0,combined
4,000001,2020-10-20,Sale,5308941.0,36,Unknown,RLE,0070,DES ATTES,97436,SAINT-LEU,974,13,Unknown,AV,1712,Unknown,Unknown,0.0,Unknown,0.0,Unknown,0.0,Unknown,0.0,Unknown,0.0,0,2,Apartment,34.0,2,S,Unknown,35.0,combined
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61,000001,2024-10-29,Sale in future state of completion,173500.0,Unknown,Unknown,Unknown,B235,LA LAGREMEUSE HAUTE,13290,AIX EN PROVENCE,13,1,Unknown,KV,214,Unknown,141,0.0,Unknown,0.0,Unknown,0.0,Unknown,0.0,Unknown,0.0,1,Unknown,Unknown,0.0,0,Unknown,Unknown,0.0,Unknown
62,000001,2024-11-14,Sale,164000.0,Unknown,Unknown,RUE,0400,JOSEPH LE MAT,29680,ROSCOFF,29,239,Unknown,AI,845,Unknown,Unknown,0.0,Unknown,0.0,Unknown,0.0,Unknown,0.0,Unknown,0.0,0,Unknown,Unknown,0.0,0,S,Unknown,35.0,land
63,000001,2024-03-25,Sale in future state of completion,207000.0,22,Unknown,AV,0380,LOUIS PASTEUR,84130,LE PONTET,84,92,Unknown,AL,14,Unknown,31,0.0,Unknown,0.0,Unknown,0.0,Unknown,0.0,Unknown,0.0,1,2,Apartment,79.0,4,Unknown,Unknown,0.0,building
64,000001,2024-03-25,Sale in future state of completion,207000.0,22,Unknown,AV,0380,LOUIS PASTEUR,84130,LE PONTET,84,92,Unknown,AL,14,Unknown,68,0.0,Unknown,0.0,Unknown,0.0,Unknown,0.0,Unknown,0.0,1,3,Outbuilding,0.0,0,Unknown,Unknown,0.0,Unknown
65,000001,2024-03-25,Sale in future state of completion,207000.0,22,Unknown,AV,0380,LOUIS PASTEUR,84130,LE PONTET,84,92,Unknown,AL,14,Unknown,63,0.0,Unknown,0.0,Unknown,0.0,Unknown,0.0,Unknown,0.0,1,3,Outbuilding,0.0,0,Unknown,Unknown,0.0,Unknown

### **DEAL with DUPLICATES**

In [25]:
from pathlib import Path
import pandas as pd

INPUT_FILE = Path("../data/processed/NULLS_ValeursFoncieres.csv")
OUTPUT_FILE = Path("../data/processed/DUPLICATES_ValeursFoncieres.csv")

CHUNK_SIZE = 500_000

dtype_map = {
    "transaction_id": "string",
    "transaction_date": "string",
    "transaction_type": "string",
    "street_number": "string",
    "btq_code": "string",
    "street_type": "string",
    "street_id": "string",
    "street_name": "string",
    "postal_code": "string",
    "com_name": "string",
    "dep_code": "string",
    "com_code": "string",
    "section_prefix": "string",
    "section": "string",
    "plot_number": "string",
    "volume_number": "string",
    "property_type_code": "string",
    "property_type": "string",
    "land_nature": "string",
    "land_nature_special": "string",
    "surface_type": "string",

    "lot_1": "string",
    "lot_2": "string",
    "lot_3": "string",
    "lot_4": "string",
    "lot_5": "string",

    "property_value": "Float64",
    "building_real_surface": "Float64",
    "land_surface": "Float64",
    "lot_1_surface": "Float64",
    "lot_2_surface": "Float64",
    "lot_3_surface": "Float64",
    "lot_4_surface": "Float64",
    "lot_5_surface": "Float64",

    "lots_count": "Int64",
    "main_rooms_count": "Int64",
}


def remove_duplicates_fast(
    input_file: Path,
    output_file: Path,
    chunk_size: int = 500_000
) -> None:
    output_file.parent.mkdir(parents=True, exist_ok=True)

    seen_hashes = set()
    first_write = True

    total_read = 0
    total_written = 0
    total_removed = 0

    for chunk_idx, chunk in enumerate(
        pd.read_csv(
            input_file,
            chunksize=chunk_size,
            dtype=dtype_map,
            low_memory=False
        ),
        start=1
    ):
        rows_before = len(chunk)
        total_read += rows_before

        row_hashes = pd.util.hash_pandas_object(chunk, index=False)

        # Keep first occurrence inside current chunk
        not_duplicate_in_chunk = ~row_hashes.duplicated(keep="first")

        # Keep only rows not already seen in previous chunks
        not_seen_before = ~row_hashes.isin(seen_hashes)

        keep_mask = not_duplicate_in_chunk & not_seen_before
        chunk_kept = chunk.loc[keep_mask].copy()

        # Store all unique hashes from this chunk
        seen_hashes.update(row_hashes[not_duplicate_in_chunk].tolist())

        rows_after = len(chunk_kept)
        removed_here = rows_before - rows_after

        total_written += rows_after
        total_removed += removed_here

        chunk_kept.to_csv(
            output_file,
            mode="w" if first_write else "a",
            header=first_write,
            index=False,
            encoding="utf-8"
        )

        first_write = False

        print(
            f"Chunk {chunk_idx} -> "
            f"read: {rows_before:,} | kept: {rows_after:,} | "
            f"removed: {removed_here:,} | total kept: {total_written:,}"
        )

    print("\n✅ Done")
    print(f"Saved file: {output_file}")
    print(f"Total rows read: {total_read:,}")
    print(f"Total duplicates removed: {total_removed:,}")
    print(f"Total rows written: {total_written:,}")


remove_duplicates_fast(INPUT_FILE, OUTPUT_FILE, CHUNK_SIZE)

Chunk 1 -> read: 500,000 | kept: 477,529 | removed: 22,471 | total kept: 477,529
Chunk 2 -> read: 500,000 | kept: 484,432 | removed: 15,568 | total kept: 961,961
Chunk 3 -> read: 500,000 | kept: 480,034 | removed: 19,966 | total kept: 1,441,995
Chunk 4 -> read: 500,000 | kept: 473,176 | removed: 26,824 | total kept: 1,915,171
Chunk 5 -> read: 500,000 | kept: 469,155 | removed: 30,845 | total kept: 2,384,326
Chunk 6 -> read: 500,000 | kept: 468,669 | removed: 31,331 | total kept: 2,852,995
Chunk 7 -> read: 500,000 | kept: 470,598 | removed: 29,402 | total kept: 3,323,593
Chunk 8 -> read: 500,000 | kept: 459,099 | removed: 40,901 | total kept: 3,782,692
Chunk 9 -> read: 500,000 | kept: 458,530 | removed: 41,470 | total kept: 4,241,222
Chunk 10 -> read: 500,000 | kept: 462,012 | removed: 37,988 | total kept: 4,703,234
Chunk 11 -> read: 500,000 | kept: 469,216 | removed: 30,784 | total kept: 5,172,450
Chunk 12 -> read: 500,000 | kept: 457,631 | removed: 42,369 | total kept: 5,630,081
Chunk 13 -> read: 500,000 | kept: 469,296 | removed: 30,704 | total kept: 6,099,377
Chunk 14 -> read: 500,000 | kept: 460,990 | removed: 39,010 | total kept: 6,560,367
Chunk 15 -> read: 500,000 | kept: 466,693 | removed: 33,307 | total kept: 7,027,060
Chunk 16 -> read: 500,000 | kept: 462,639 | removed: 37,361 | total kept: 7,489,699
Chunk 17 -> read: 500,000 | kept: 472,843 | removed: 27,157 | total kept: 7,962,542
Chunk 18 -> read: 500,000 | kept: 465,313 | removed: 34,687 | total kept: 8,427,855
Chunk 19 -> read: 500,000 | kept: 441,991 | removed: 58,009 | total kept: 8,869,846
Chunk 20 -> read: 500,000 | kept: 462,904 | removed: 37,096 | total kept: 9,332,750
Chunk 21 -> read: 500,000 | kept: 468,540 | removed: 31,460 | total kept: 9,801,290
Chunk 22 -> read: 500,000 | kept: 463,588 | removed: 36,412 | total kept: 10,264,878
Chunk 23 -> read: 500,000 | kept: 459,814 | removed: 40,186 | total kept: 10,724,692
Chunk 24 -> read: 500,000 | kept: 469,622 | removed: 30,378 | total kept: 11,194,314
Chunk 25 -> read: 500,000 | kept: 467,533 | removed: 32,467 | total kept: 11,661,847
Chunk 26 -> read: 500,000 | kept: 468,572 | removed: 31,428 | total kept: 12,130,419
Chunk 27 -> read: 500,000 | kept: 466,286 | removed: 33,714 | total kept: 12,596,705
Chunk 28 -> read: 500,000 | kept: 461,751 | removed: 38,249 | total kept: 13,058,456
Chunk 29 -> read: 500,000 | kept: 465,178 | removed: 34,822 | total kept: 13,523,634
Chunk 30 -> read: 500,000 | kept: 451,499 | removed: 48,501 | total kept: 13,975,133
Chunk 31 -> read: 500,000 | kept: 462,513 | removed: 37,487 | total kept: 14,437,646
Chunk 32 -> read: 500,000 | kept: 467,820 | removed: 32,180 | total kept: 14,905,466
Chunk 33 -> read: 500,000 | kept: 472,400 | removed: 27,600 | total kept: 15,377,866
Chunk 34 -> read: 500,000 | kept: 466,408 | removed: 33,592 | total kept: 15,844,274
Chunk 35 -> read: 500,000 | kept: 462,611 | removed: 37,389 | total kept: 16,306,885
Chunk 36 -> read: 500,000 | kept: 460,499 | removed: 39,501 | total kept: 16,767,384
Chunk 37 -> read: 500,000 | kept: 443,989 | removed: 56,011 | total kept: 17,211,373
Chunk 38 -> read: 500,000 | kept: 462,738 | removed: 37,262 | total kept: 17,674,111
Chunk 39 -> read: 500,000 | kept: 467,637 | removed: 32,363 | total kept: 18,141,748
Chunk 40 -> read: 408,349 | kept: 378,062 | removed: 30,287 | total kept: 18,519,810

✅ Done
Saved file: ..\data\processed\DUPLICATES_ValeursFoncieres.csv
Total rows read: 19,908,349
Total duplicates removed: 1,388,539
Total rows written: 18,519,810

### **SHAPE & HEAD - AFTER Dealing with Duplicates**

In [30]:
import pandas as pd

FILE = "../data/processed/DUPLICATES_ValeursFoncieres.csv"
CHUNK_SIZE = 500_000

dtype_map = {
    # categorical / identifiers
    "transaction_id": "string",
    "transaction_date": "string",  # convert to datetime after loading
    "transaction_type": "string",
    "street_number": "string",
    "btq_code": "string",
    "street_type": "string",
    "street_id": "string",
    "street_name": "string",
    "postal_code": "string",
    "com_name": "string",
    "dep_code": "string",
    "com_code": "string",
    "section_prefix": "string",
    "section": "string",
    "plot_number": "string",
    "volume_number": "string",
    "property_type_code": "string",  # keep as string (categorical)
    "property_type": "string",
    "land_nature": "string",
    "land_nature_special": "string",
    "surface_type": "string",

    # lot identifiers
    "lot_1": "string",
    "lot_2": "string",
    "lot_3": "string",
    "lot_4": "string",
    "lot_5": "string",

    # numeric (use nullable Float64 for consistency)
    "property_value": "Float64",
    "building_real_surface": "Float64",
    "land_surface": "Float64",
    "lot_1_surface": "Float64",
    "lot_2_surface": "Float64",
    "lot_3_surface": "Float64",
    "lot_4_surface": "Float64",
    "lot_5_surface": "Float64",

    # integer (nullable)
    "lots_count": "Int64",
    "main_rooms_count": "Int64",
}

# ---------------------------
# Get full dataset shape
# ---------------------------
total_rows = 0
columns = None

for chunk in pd.read_csv(
    FILE,
    chunksize=CHUNK_SIZE,
    dtype=dtype_map,
    low_memory=False
):
    total_rows += len(chunk)
    if columns is None:
        columns = chunk.columns

print("Shape:", total_rows, "rows and", len(columns), "columns")

# ---------------------------
# Display head with correct dtypes
# ---------------------------
df_head = pd.read_csv(
    FILE,
    nrows=5,
    dtype=dtype_map,
    low_memory=False
)

display(df_head)

Shape: 18519810 rows and 36 columns

,transaction_id,transaction_date,transaction_type,property_value,street_number,btq_code,street_type,street_id,street_name,postal_code,com_name,dep_code,com_code,section_prefix,section,plot_number,volume_number,lot_1,lot_1_surface,lot_2,lot_2_surface,lot_3,lot_3_surface,lot_4,lot_4_surface,lot_5,lot_5_surface,lots_count,property_type_code,property_type,building_real_surface,main_rooms_count,land_nature,land_nature_special,land_surface,surface_type
0,000001,2020-07-01,Sale,31234.16,Unknown,Unknown,Unknown,B064,SAINT JULIEN,1560,SAINT-JULIEN-SUR-REYSSOUZE,01,367,Unknown,A,8,Unknown,Unknown,0.0,Unknown,0.0,Unknown,0.0,Unknown,0.0,Unknown,0.0,0,Unknown,Unknown,0.0,0,AB,Unknown,1192.0,land
1,000001,2020-07-01,Sale,278000.0,Unknown,Unknown,Unknown,B188,A LA PEROUSE,1250,CORVEISSIAT,01,125,Unknown,C,509,Unknown,Unknown,0.0,Unknown,0.0,Unknown,0.0,Unknown,0.0,Unknown,0.0,0,Unknown,Unknown,0.0,0,BS,Unknown,10092.0,land
2,000001,2020-07-01,Sale,278000.0,Unknown,Unknown,Unknown,B188,A LA PEROUSE,1250,CORVEISSIAT,01,125,Unknown,C,510,Unknown,Unknown,0.0,Unknown,0.0,Unknown,0.0,Unknown,0.0,Unknown,0.0,0,Unknown,Unknown,0.0,0,L,Unknown,4570.0,land
3,000001,2020-07-01,Sale,278000.0,Unknown,Unknown,Unknown,B079,AUX COMMUNS,1250,CORVEISSIAT,01,125,Unknown,ZL,96,Unknown,Unknown,0.0,Unknown,0.0,Unknown,0.0,Unknown,0.0,Unknown,0.0,0,Unknown,Unknown,0.0,0,BS,Unknown,5750.0,land
4,000001,2020-07-01,Sale,278000.0,Unknown,Unknown,Unknown,B033,EN COMBARNAUD,1250,SIMANDRE-SUR-SURAN,01,408,Unknown,A,14,Unknown,Unknown,0.0,Unknown,0.0,Unknown,0.0,Unknown,0.0,Unknown,0.0,0,Unknown,Unknown,0.0,0,BT,Unknown,648170.0,land

### **UNIQUE VALUES & NULLS**

In [38]:
from collections import defaultdict
import pandas as pd

FILE = "../data/processed/DUPLICATES_ValeursFoncieres.csv"

unique_values = defaultdict(set)
null_counts = defaultdict(int)
total_rows = 0

for chunk in pd.read_csv(
    FILE,
    chunksize=500_000,
    dtype=str,          # ✅ avoids mixed types warning
    low_memory=False
):
    total_rows += len(chunk)

    for col in chunk.columns:
        # ✅ Count nulls (DO NOT drop them)
        null_counts[col] += chunk[col].isna().sum()

        # ✅ Collect only non-null values (nulls are still preserved in dataset)
        unique_values[col].update(
            chunk.loc[chunk[col].notna(), col].unique()
        )

# --------------------------------------------------
# Display results
# --------------------------------------------------
print(f"\nTotal rows processed: {total_rows:,}")
print(100 * "-")

for col in unique_values:
    values = list(unique_values[col])
    null_pct = (null_counts[col] / total_rows) * 100

    print(f"➡️ {col}:")
    print(f"Unique values count: {len(values)}")
    print(f"Null count: {null_counts[col]} ({null_pct:.2f}%)")
    print(f"Sample values: {values[:120]}")
    print(100 * "-")

Total rows processed: 18,519,810
----------------------------------------------------------------------------------------------------
➡️ transaction_id:
Unique values count: 311
Null count: 0 (0.00%)
Sample values: ['000189', '000145', '000261', '000115', '000232', '000183', '000141', '000085', '000164', '000126', '000308', '000283', '000043', '000122', '000153', '000055', '000031', '000223', '000143', '000229', '000167', '000022', '000074', '000051', '000200', '000219', '000150', '000015', '000111', '000291', '000007', '000274', '000235', '000068', '000277', '000053', '000166', '000147', '000216', '000154', '000014', '000222', '000311', '000246', '000046', '000021', '000255', '000079', '000162', '000227', '000276', '000295', '000244', '000243', '000161', '000056', '000149', '000280', '000250', '000034', '000116', '000253', '000170', '000080', '000301', '000247', '000176', '000137', '000088', '000086', '000271', '000182', '000281', '000087', '000027', '000019', '000032', '000071', '000093', '000171', '000095', '000168', '000180', '000078', '000217', '000192', '000045', '000293', '000054', '000075', '000102', '000245', '000123', '000136', '000155', '000146', '000037', '000234', '000029', '000109', '000041', '000066', '000300', '000023', '000310', '000212', '000106', '000215', '000303', '000072', '000207', '000199', '000069', '000131', '000268', '000026', '000256', '000292', '000097', '000121']
----------------------------------------------------------------------------------------------------
➡️ transaction_date:
Unique values count: 1804
Null count: 0 (0.00%)
Sample values: ['2023-10-08', '2024-05-20', '2021-08-25', '2023-04-01', '2021-05-24', '2021-08-15', '2024-07-30', '2025-04-04', '2022-07-23', '2021-03-12', '2022-03-31', '2021-04-08', '2021-11-30', '2025-06-28', '2024-11-26', '2024-07-25', '2021-03-17', '2025-03-25', '2022-04-15', '2022-04-26', '2023-12-05', '2023-12-13', '2023-12-28', '2021-05-15', '2022-10-28', '2021-07-14', '2024-07-14', '2022-06-11', '2025-05-19', '2021-09-30', '2024-07-07', '2020-10-31', '2021-04-03', '2021-07-27', '2022-06-03', '2023-06-05', '2021-01-17', '2022-10-26', '2024-10-29', '2024-02-25', '2022-01-24', '2021-03-21', '2021-06-01', '2022-01-21', '2024-06-21', '2024-02-03', '2025-06-02', '2021-03-16', '2025-05-31', '2025-04-25', '2022-11-29', '2024-02-20', '2022-11-05', '2021-10-13', '2025-01-31', '2024-03-28', '2021-08-29', '2024-11-12', '2020-07-03', '2023-12-03', '2022-03-18', '2021-11-22', '2020-11-09', '2024-05-15', '2024-08-12', '2024-08-09', '2020-07-30', '2021-04-21', '2024-04-13', '2021-05-30', '2025-01-29', '2024-12-25', '2025-03-30', '2022-02-07', '2020-09-08', '2023-05-13', '2021-01-21', '2020-12-15', '2020-11-03', '2020-08-03', '2023-02-15', '2024-03-16', '2024-03-14', '2021-10-17', '2024-08-02', '2020-08-31', '2022-09-01', '2024-10-05', '2022-03-22', '2021-03-05', '2021-10-04', '2024-01-29', '2024-10-07', '2024-01-30', '2021-06-21', '2023-07-18', '2025-06-19', '2020-12-29', '2023-10-20', '2024-02-11', '2024-04-11', '2024-07-28', '2022-09-26', '2022-07-26', '2022-12-06', '2024-07-04', '2023-05-01', '2022-09-09', '2022-02-19', '2021-11-27', '2021-04-16', '2025-06-20', '2025-01-07', '2023-07-07', '2021-05-02', '2024-09-06', '2024-04-17', '2021-11-14', '2023-11-03', '2021-06-20']
----------------------------------------------------------------------------------------------------
➡️ transaction_type:
Unique values count: 6
Null count: 0 (0.00%)
Sample values: ['Sale in future state of completion', 'Sale of unbuilt land', 'Expropriation', 'Auction', 'Sale', 'Exchange']
----------------------------------------------------------------------------------------------------
➡️ property_value:
Unique values count: 466667
Null count: 0 (0.00%)
Sample values: ['75572.47', '424131.0', '363151.0', '629335.0', '92915.0', '673340.0', '236008.0', '1768.0', '79707.0', '646146.0', '5423.7', '223070.0', '201536.0', '4281.42', '2311.75', '3205.5', '376944.0', '666.0', '78641.0', '212539.0', '12668.8', '122941.0', '175530.0', '94209.0', '131605.69', '16568.96', '213505.0', '290850.0', '88087.02', '23138.4', '831000.0', '1809825.0', '278280.0', '11835.68', '7575.2', '11864.4', '168997.0', '628100.0', '781.5', '972550.0', '244831.0', '117800.0', '111130.0', '135430.0', '43976.0', '2984.45', '144047.42', '137775.0', '93.33', '845775.0', '57542.27', '64301.0', '771159.0', '535432.0', '746300.0', '1878500.0', '135037.25', '181180.0', '13072.5', '68150.0', '214918.42', '26565.0', '543475.0', '9751.0', '60957.0', '47622.6', '392162.0', '34169.85', '33765.0', '485320.0', '1156332.0', '326205.0', '58129.45', '697.35', '30340.0', '76225.0', '1373700.0', '61192.0', '25334.4', '514942.0', '94980.0', '50815.0', '351208.0', '104718.0', '135828.11', '432505.0', '265786.0', '36468.75', '1643250.0', '809900.0', '96101.35', '47037.0', '25471.0', '237798.0', '481030.0', '1106780.0', '98410.0', '106195.0', '30005.0', '37083.6', '245028.0', '98782.0', '33772.5', '125627.52', '377160.0', '3876019.0', '27681.0', '98216.8', '220561.0', '45141.72', '8383.95', '1148.39', '21404.0', '483230.0', '552640.0', '734235.0', '6599723.5', '327124.0', '599240.0', '2675900.0']
----------------------------------------------------------------------------------------------------
➡️ street_number:
Unique values count: 9121
Null count: 0 (0.00%)
Sample values: ['1593', '6491', '9325', '1525', '1633', '2142', '9257', '6309', '3822', '5999', '7504', '303', '3131', '3899', '9650', '1059', '4229', '3003', '8000', '7039', '5617', '4846', '7442', '5370', '4634', '6271', '5666', '2046', '6546', '567', '6078', '2555', '9834', '1450', '6830', '1579', '8207', '931', '2388', '276', '6549', '9057', '7234', '5629', '5793', '6131', '1812', '3818', '1788', '5212', '8890', '7473', '3636', '5058', '7416', '2233', '3254', '9229', '6388', '5308', '1270', '7581', '2641', '568', '9219', '2217', '2969', '8335', '4411', '4571', '3521', '9140', '5490', '888', '9960', '2666', '1071', '8163', '2315', '840', '9657', '2615', '6061', '2499', '7908', '6740', '3405', '2417', '7831', '5008', '4309', '2098', '5640', '2150', '9600', '9236', '3560', '2403', '2782', '5107', '6895', '9788', '7580', '3082', '4378', '1675', '1318', '5924', '9507', '126', '9975', '9389', '4218', '6689', '628', '305', '3631', '4681', '2770', '3430']
----------------------------------------------------------------------------------------------------
➡️ btq_code:
Unique values count: 37
Null count: 0 (0.00%)
Sample values: ['Y', 'E', 'K', '1', '3', 'F', 'V', 'N', 'T', 'Unknown', 'G', 'B', 'Z', '2', 'H', '8', 'W', 'P', 'D', 'S', 'M', '9', 'Q', '7', 'U', '5', '4', 'R', 'O', 'J', '0', 'C', 'I', 'L', 'A', 'X', '6']
----------------------------------------------------------------------------------------------------
➡️ street_type:
Unique values count: 153
Null count: 0 (0.00%)
Sample values: ['ESPA', 'HLE', 'PAS', 'QUA', 'GR', 'PAE', 'HLM', 'MAIL', 'COTE', 'VALL', 'Unknown', 'COL', 'ALL', 'VTE', 'QUAI', 'PRT', 'CR', 'PLA', 'BORD', 'VIA', 'CHL', 'JTE', 'PLAG', 'PRV', 'PKG', 'CORO', 'TRA', 'CIVE', 'RULT', 'FOS', 'PCH', 'BRTL', 'AUT', 'DEVI', 'CAE', 'ZONE', 'ZUP', 'MAIS', 'CALL', 'VAL', 'DIG', 'TRAB', 'PLE', 'REM', 'PIST', 'CAN', 'ECL', 'ANGL', 'LOT', 'ZAC', 'D', 'VLA', 'CHEM', 'VOIE', 'BD', 'TSSE', 'ZAD', 'RIVE', 'ACH', 'VOUT', 'PTTE', 'VEN', 'RAC', 'PARC', 'CITE', 'LEVE', 'CRX', 'BSN', 'PLAN', 'CLOS', 'VCHE', 'PL', 'GAL', 'CC', 'HLG', 'FG', 'CHS', 'DRA', 'CHV', 'BRG', 'GPL', 'CRS', 'RLE', 'GARE', 'NTE', 'PTA', 'PASS', 'VIL', 'ZI', 'COIN', 'ART', 'DOM', 'N', 'MAR', 'SEN', 'CD', 'RTE', 'VC', 'COR', 'CLR', 'AGL', 'PTE', 'IMP', 'LICE', 'HAM', 'ILOT', 'SQ', 'CAMI', 'PONT', 'MRN', 'RTD', 'ESP', 'DSC', 'CAR', 'HAB', 'VOY', 'BRE', 'PORT', 'CPG', 'AV']
----------------------------------------------------------------------------------------------------
➡️ street_id:
Unique values count: 20003
Null count: 0 (0.00%)
Sample values: ['B680', '6491', 'H482', '9325', 'P363', 'G573', '8814', '1059', 'B146', 'G657', 'B130', 'C991', '5617', 'F928', 'F319', 'I462', '4634', 'F110', 'D515', '6546', 'F666', 'C982', '8621', '1579', 'Q578', '8207', 'C447', '8884', 'I753', 'I261', '9057', '5629', '1812', '8890', '5212', 'C707', 'B781', 'H801', '0322', '9229', 'I733', 'J379', 'A393', 'C387', 'H957', 'F062', '0289', 'C058', '2969', 'A152', '9140', '0998', 'C600', 'E032', 'D979', 'B083', 'E075', '4309', '2098', 'E652', 'B678', 'V163', '5107', '7580', '3082', 'D030', '9507', '9389', 'D558', '3631', 'E981', 'K422', 'H865', '5892', 'B506', 'I649', 'D918', '4158', 'X005', '7202', 'A621', '6907', '4479', '2333', '8296', 'X030', '6139', 'B474', 'D427', 'H123', '2162', '8743', 'E682', 'C195', 'E584', 'F311', 'G351', 'D105', 'D769', '3272', '6389', 'E650', '9437', 'E670', 'K468', '6698', 'B633', '2605', '2477', 'A747', '9544', '2342', 'H613', '9848', 'J124', '3946', 'D106', '0412', '6185', '4968']
----------------------------------------------------------------------------------------------------
➡️ street_name:
Unique values count: 1125220
Null count: 0 (0.00%)
Sample values: ['MAGISTRAT SUD', 'DES AUTRES PLANETES', 'SOUS SAUNIAL', 'FERMI', 'DU CITIS', 'CHEZ KAKI', 'CHAMPS MARTIN MEUNIER', 'ETANG DE LA PRAZ', 'BOUIGUO DE MEDAN', 'DE TAURENS', 'LA CELLIERE', 'FEYPOT', 'KERTOUDIC', 'LE DEVINET', 'DU FAYET', 'LE COUSINIE', 'BOSSELEINE', 'LA HAIE A TROCHARD', 'GEORGES CHARRIER', 'BAS DE POMME D ARC', 'LES COSSES DU MAGNOU', 'MARCEL LAUTARD', 'DE PIED BLANC', 'LES CHAMPS ANSELME EST', 'DES ROSSANDES', 'LA SERSIOGRAND', 'GROS ROCHER', 'CLOS DU BOIS ROSSIGNOL', 'LA CHEVESSERIE', 'DE COURRIN', 'JAUREZE', 'LE PRE DU BREUX', 'LA BERTONNIE', 'LEVITE', 'CHODORELLE', 'GRANDS ARRAYIES', 'ABBE ARTARIT', 'LA LANDE DE LA GRANGE', 'DE FEBVRY', 'LE COTEAU DE LIQUET', 'LE GRAND ROQUEMARD', 'KERVAN GOAREM AR STANC', 'DES BOSCHETTES', 'CHEZ DAMOUR', 'DERRIERE LA TUVIERE', 'DE LA NAUZETTE', 'LE CHEMIN DE L ABBAYE AUX', 'DANIEL SAGE', 'AU VEZIS', 'L ECLATE', 'KERBLEUNIOU', 'LA DOUBRIE', 'HOUDENT', 'DE GATEBOURG', 'DES NOISETIERS (MARIGNE)', 'CAPIGRIGIO', 'LA BARATRIE', 'LA TAPINIERE', 'ROUTE DE LA SERRE', 'DES 3 FRERES', 'PAUL MARAIS', 'SOMBEZAU', 'FEMAJOLA', 'CASTIGUES-SUD', 'RULANOU', 'FRANGOUILLE', 'LES SOUPEES', 'A ENMANSOT', 'SOUS LA CORVEE', 'VALESCHIERAS EST', 'PUYLAGORGE', 'LEON HUTIN', 'JEAN MARIE JEGO', 'DOMINIQUE LAGRU', 'LES HARDINES DE BELZAISE', 'CHAMP SABATAY', 'DU PUITS DE LA FIGUIERE', 'LE PUISEUX', 'VERKEERDE BECQUE ET KLAP H', 'JOUR DE FETE', 'LE THUEST', 'LA CROTTE', 'EDMOND LABATUT', 'CONSOLANT-SUD', 'ESTRADE', 'PASTEUR DE VALANJOU', 'CAMP A REDON', 'FRANCIS LOPEZ', 'GDE PIECE CARREFOUR AMOURE', 'BOIS DES CERISIOUX', 'CAP DE NAOU', 'LE FOND DE PAIX', 'PIECE DU PRE BOTEREAU', 'LA HAYE CATIN', 'CARTIVET', 'CHEZ LES BARROCHINS', 'AU PUY DE LA FON', 'AU BOIRAT', 'PRAIRIE DE BEAULIEU', 'L HERARDIERE', 'PRE DU VAUX', 'AR VELANEC RUBRAS', 'VOTEN VILLAREC', 'EN VECHERE', 'DE L ECOTTAIS', 'LANDAOUDEC', 'LE PUY DE BEAU', 'QUELME', 'LA DUPRAIRIE', 'JULIOCOURT', 'BEAUVAIS D EN BAS', 'LAZEUYS', 'LA GILLOUARDIERE', 'LE MASLEMONGE', 'ROIDE FONTAINE', 'LA PIOT', 'LE PRE DE SEVREAU', 'VERGER DU PRE', 'LE HALLIOU', 'DES JOYEUSES VACANCES']
----------------------------------------------------------------------------------------------------
➡️ postal_code:
Unique values count: 5872
Null count: 0 (0.00%)
Sample values: ['91440', '37110', '74410', '59400', '69560', '19130', '45370', '60160', '63710', '51360', '8000', '30480', '64800', '11270', '70440', '22450', '12720', '13850', '1450', '6830', '97225', '11140', '62158', '55270', '79460', '13750', '14860', '64520', '26570', '40990', '66670', '12630', '35200', '58440', '92000', '66680', '31700', '59180', '1270', '54450', '19300', '15100', '33350', '9140', '13830', '89430', '87140', '14850', '94430', '19290', '42430', '78250', '18500', '17640', '88100', '40260', '83420', '62132', '19330', '69170', '25870', '6740', '58230', '12210', '40560', '20244', '76910', '2150', '9600', '30760', '77660', '94290', '85250', '73000', '44600', '7580', '51140', '43260', '73800', '95570', '69910', '43340', '82340', '74330', '59157', '3430', '83600', '42360', '97470', '34920', '84130', '82390', '3290', '55230', '75005', '83143', '62100', '4370', '43290', '7200', '13610', '38530', '44310', '56400', '30840', '95520', '62460', '13111', '31370', '25530', '33430', '42740', '61800', '51460', '58500', '58240', '37400', '59154', '2450', '62131']
----------------------------------------------------------------------------------------------------
➡️ com_name:
Unique values count: 31569
Null count: 0 (0.00%)
Sample values: ['OUFFIERES', 'TAILLET', 'ICHY', 'EPECAMPS', 'LEIGNE-LES-BOIS', 'ANDON', 'LOMPNAS', 'BRAILLANS', 'AIGUEBELETTE-LE-LAC', 'LE VIEUX BOURG', 'PLANTY', 'MONLONG', 'PONTEILS-ET-BRESIS', 'SAINT-JAL', 'VALENCAY', 'CHAPONNAY', 'VARENNES-SOUS-DUN', 'CARSAN', 'SAINT-MARTIN-DU-LAC', 'CLERY-GRAND', 'VALLEROY-LE-SEC', 'ARIGNAC', 'NEVY-SUR-SEILLE', 'BEZANCOURT', 'AUMENANCOURT', 'GONDRECOURT-AIX', 'SAINT FLOUR', 'VINDRAC-ALAYRAC', 'HERMELINGHEN', 'BEAURAINS LES NOYON', 'CEAUX', 'BEAUTOT', 'NEUVELLE-LES-VOISEY', 'PEISEY-NANCROIX', 'BASSE-SUR-LE-RUPT', 'RIBECOURT DRESLINCOURT', 'SAINTE-ENGRACE', 'COURCELLES LES GISORS', 'ECLOSE-BADINIERES', 'SAINT-GERMAIN-DE-LIVET', 'METHAMIS', 'CABANNES', 'MARSANNAY-LE-BOIS', 'ESPEDAILLAC', 'BESSE SUR BRAYE', 'CARCANIERES', 'GALEY', 'BOUFFRY', 'ECHEVANNES', 'CESSIERES SUZY', 'SAINT-MARTIN-DU-TARTRE', 'VENOY', 'LICHERES-PRES-AIGREMONT', 'TROGUERY', 'VERGHEAS', 'PERRAY-EN-YVELINES (LE)', 'ST ANDRE DE L EURE', 'MOUCHY LE CHATEL', 'BEAUREVOIR', 'CUSSAC-SUR-LOIRE', 'CHATEAUNEUF-VAL-DE-BARGIS', 'FRONTENAC', 'RIGNOVELLE', 'VILLEFRANCHE-DU-PERIGORD', 'MAYAC', 'MESNIL-SAINT-DENIS (LE)', 'SEMILLY', 'VENTENAC', 'LETELON', 'BONNET', 'AVON LES ROCHES', 'MENIL ANNELLES', 'TUGERAS-SAINT-MAURICE', 'VARENNE-SAINT-GERMAIN', 'LA CHAPELLE HUON', 'BEAUCE LA ROMAINE', 'DIZIMIEU', 'VERT-TOULON', 'SAINT-MARTIN-LA-GARENNE', "GEUS D'OLORON", 'PERS-EN-GATINAIS', 'AVOCOURT', 'NARCY', 'CHEVREVILLE', 'ARPAVON', 'SERRE-NERPOL', 'RUPT', 'DERBAMONT', 'COLLEGIEN', 'OSTREVILLE', 'BIOULE', 'NOGNA', 'LE POISLAY', 'LES PAROCHES', 'ERVILLE-SUR-MER', 'SAINT-LEGER', 'VERS-SOUS-SELLIERES', 'PLESSIS-SAINT-BENOIST', 'MONTEAUX', 'SEPTVAUX', 'NANCY-SUR-CLUSES', 'LE CHATENET EN DOGNON', 'BONA', 'GRAND RIVIERE', 'TORCY-LE-GRAND', 'JONCHERE (LA)', 'CHAMPNETERY', 'FRANSECHES', 'HEUDREVILLE SUR EURE', 'VALGORGE', 'VIONS', 'LUZARCHES', 'SIX-FOURS-LES-PLAGES', 'MARVILLE MOUTIERS BRULE', 'ROUECOURT', 'BRIGNEMONT', 'CORPS', 'VILLANOVA', 'SENEUJOLS', 'VALLEROY']
----------------------------------------------------------------------------------------------------
➡️ dep_code:
Unique values count: 97
Null count: 0 (0.00%)
Sample values: ['34', '70', '02', '58', '14', '33', '41', '10', '31', '64', '84', '07', '55', '61', '2A', '79', '27', '51', '93', '29', '65', '69', '75', '52', '94', '01', '36', '48', '24', '26', '16', '08', '22', '11', '90', '13', '87', '60', '73', '83', '32', '49', '19', '56', '81', '45', '40', '66', '28', '72', '74', '95', '44', '37', '17', '972', '46', '43', '89', '59', '85', '03', '2B', '78', '86', '09', '21', '23', '76', '973', '62', '77', '971', '91', '92', '06', '63', '88', '53', '15', '25', '80', '54', '35', '82', '47', '71', '39', '12', '974', '05', '30', '50', '42', '18', '38', '04']
----------------------------------------------------------------------------------------------------
➡️ com_code:
Unique values count: 908
Null count: 0 (0.00%)
Sample values: ['600', '577', '622', '112', '483', '373', '1', '301', '70', '645', '787', '635', '303', '736', '871', '164', '377', '408', '856', '344', '58', '14', '691', '148', '175', '474', '683', '494', '797', '726', '216', '244', '382', '593', '466', '55', '274', '547', '567', '410', '701', '821', '150', '199', '51', '499', '613', '779', '29', '6', '376', '276', '69', '403', '740', '798', '285', '677', '332', '298', '737', '760', '497', '94', '258', '26', '734', '846', '590', '449', '22', '731', '644', '295', '198', '318', '666', '520', '425', '414', '543', '479', '487', '490', '245', '90', '11', '568', '388', '898', '209', '409', '806', '309', '225', '909', '60', '269', '73', '275', '184', '19', '689', '862', '820', '588', '502', '888', '747', '262', '508', '385', '702', '346', '621', '323', '283', '480', '655', '554']
----------------------------------------------------------------------------------------------------
➡️ section_prefix:
Unique values count: 760
Null count: 0 (0.00%)
Sample values: ['577', '600', '622', '112', '483', '373', '1', '301', '70', '645', '635', '303', '871', '164', '377', '408', '856', '344', '58', '14', '691', '148', '175', '494', '216', '244', '382', '593', '466', '55', '274', '547', '567', '410', '701', '821', '150', '199', '51', '499', '29', '376', '6', '276', '69', '403', '285', '332', '298', '497', '94', '258', '26', '846', '449', '22', '414', '295', '198', '318', '644', '479', '520', '543', '245', '568', '90', '11', '388', '898', '409', '209', '806', '309', '225', '909', '60', '269', '73', '275', '184', '19', '820', '588', '502', '888', '508', '262', '385', '702', '621', '346', '323', '283', '480', '655', '192', '208', '840', '311', '104', '380', '484', '43', '618', '132', '331', '322', '59', '653', '248', '688', '564', '340', '473', '730', '78', '98', '906', '530']
----------------------------------------------------------------------------------------------------
➡️ section:
Unique values count: 589
Null count: 0 (0.00%)
Sample values: ['OC', 'MH', 'VN', 'MJ', 'AD', 'RA', 'BR', 'ZR', 'SK', 'YK', 'LB', 'GF', 'WY', 'MN', 'SR', 'AK', 'RD', 'ES', 'YM', 'VX', 'IU', 'LV', 'NS', 'TR', 'TW', 'XM', 'HI', 'RM', 'WK', 'XB', 'XW', 'YC', 'FU', 'X', 'CS', 'TV', 'GN', 'SS', 'LP', 'YU', 'E', 'BS', 'NY', 'IG', 'GP', 'OH', 'ZZ', 'AH', 'BO', 'ZF', 'VW', 'RH', 'TH', 'AE', 'NB', 'YS', 'PZ', 'OP', 'YI', 'FL', 'HA', 'VB', 'DK', 'YJ', 'RT', 'BN', 'XA', 'PB', 'NR', 'YB', 'MT', 'MD', 'XO', 'AX', 'HV', 'ID', 'ST', 'FX', 'KK', 'WA', 'XK', 'HE', 'AC', 'YD', 'GB', 'OR', 'WV', 'BJ', 'T', 'DO', 'CD', 'DS', 'MM', 'BY', 'LI', 'TD', 'IC', 'BQ', 'LM', 'FM', 'JF', 'EM', 'OB', 'EB', 'RR', 'TT', 'MP', 'DM', 'FR', 'WB', 'YF', 'AZ', 'EV', 'CN', 'PH', 'TL', 'DW', 'TO', 'VR', 'NT']
----------------------------------------------------------------------------------------------------
➡️ plot_number:
Unique values count: 8235
Null count: 0 (0.00%)
Sample values: ['1593', '6491', '9325', '1525', '1633', '2142', '6309', '3822', '5999', '7504', '303', '3131', '3899', '1059', '4229', '3003', '8000', '7039', '5617', '4846', '7442', '5370', '4634', '6271', '5666', '2046', '6546', '567', '6078', '2555', '9834', '1450', '6830', '1579', '3837', '931', '2388', '276', '6549', '7234', '5629', '6131', '5793', '1812', '3818', '1788', '5212', '7473', '3636', '5058', '2233', '3254', '9229', '6388', '5308', '1270', '7581', '2641', '568', '9219', '2217', '2969', '4411', '4571', '3521', '8395', '5490', '888', '2666', '1071', '8163', '2315', '4861', '840', '2615', '6061', '2499', '7908', '6740', '3405', '2417', '4309', '5008', '2098', '2150', '5640', '7950', '3560', '2403', '2782', '5107', '6895', '9788', '7580', '3082', '4378', '1318', '1675', '5924', '126', '4218', '6689', '628', '4672', '305', '3631', '4681', '2770', '3430', '5892', '369', '4868', '3290', '1674', '7644', '2232', '4158', '6268', '4841', '652']
----------------------------------------------------------------------------------------------------
➡️ volume_number:
Unique values count: 1837
Null count: 0 (0.00%)

### Resetting the Index

When removing duplicates, the DataFrame index may have gaps due to removed rows. To reset the index after removing duplicates, we can use the `reset_index()` method with the `drop=True` parameter.

In [ ]:
df_without_duplicates.reset_index(drop=True, inplace=True)
df_without_duplicates.tail()

## Setting the index

To set an index in pandas, you can use the `set_index()` method of the DataFrame. This method allows you to specify which column you want to use as the index for the DataFrame.

In [ ]:
df.set_index('PassengerId',inplace=True)
df.head()

<hr>

## 6️⃣ OUTLIERS


<style>
h1 {
    text-align: center;
    color: black;
    font-weight: bold;
}
</style>

<style>
h2 {
    text-align: left;
    color: black;
    font-weight: bold;
}
</style>

<style>
h3 {
    text-align: left;
    color: black;
    font-weight: bold;
}
</style>

<style>
h4 {
    text-align: left;
    color: black;
    font-weight: bold;
}
</style>
<hr>

 An outlier is an observation that lies an abnormal distance from other values in a random sample from a population

**Outlier Analysis**

Purpose →  Identify extreme values that may negatively impact model performance and decide how to properly handle them to improve data quality and model reliability.

**Outliers can:**
- Skew statistical measures (mean, standard deviation)
- Distort model training (especially for linear models)
- Reduce predictive performance
- Sometimes represent important real-world insights

**We should:**
- keep outliers for Analysis. In this dataset ValeurFoncieres, outliers are insight and not noise.
- deal with outliers for Machine Learning. 

**We expect strong outliers in:**
- `property_value` → luxury sales
- `land_surface` → farms / huge land
- `building_real_surface` → industrial buildings

**We use `IQR` to detect outliers & treat extreme values.**
- top (Q3 + 1.5 x IQR)
- bottom (Q1 - 1.5 x IQR)

**We use BOX PLOTS, SCATTER PLOTS to visualise and detect outliers**


**Because the data:**
- is highly skewed
- has many zeros
- has wide value range

    👉 ALWAYS use: `np.log1p()` otherwise plots are useless.

In [ ]:
import pandas as pd
import numpy as np
import gc

INPUT_FILE = "../data/processed/DUPLICATES_ValeursFoncieres.csv"
OUTPUT_FILE = "../data/processed/OUTLIERS_ValeursFoncieres.csv"

CHUNKSIZE = 500_000
DATE_COL = "transaction_date"
DATE_FORMAT = "%d/%m/%Y"

dtype_map = {
    "transaction_id": "string",
    "transaction_date": "string",
    "transaction_type": "string",
    "street_number": "string",
    "btq_code": "string",
    "street_type": "string",
    "street_id": "string",
    "street_name": "string",
    "postal_code": "string",
    "com_name": "string",
    "dep_code": "string",
    "com_code": "string",
    "section_prefix": "string",
    "section": "string",
    "plot_number": "string",
    "volume_number": "string",
    "property_type_code": "string",
    "property_type": "string",
    "land_nature": "string",
    "land_nature_special": "string",
    "surface_type": "string",
    "lot_1": "string",
    "lot_2": "string",
    "lot_3": "string",
    "lot_4": "string",
    "lot_5": "string",
    "property_value": "Float64",
    "building_real_surface": "Float64",
    "land_surface": "Float64",
    "lot_1_surface": "Float64",
    "lot_2_surface": "Float64",
    "lot_3_surface": "Float64",
    "lot_4_surface": "Float64",
    "lot_5_surface": "Float64",
    "lots_count": "Int64",
    "main_rooms_count": "Int64",
}

GROUP_COLS = ["property_type", "dep_code", "year"]

ZERO_AS_MISSING = [
    "building_real_surface",
    "land_surface",
    "main_rooms_count",
    "lots_count",
    "lot_1_surface",
    "lot_2_surface",
    "lot_3_surface",
    "lot_4_surface",
    "lot_5_surface",
]

NUMERIC_WORK_COLS = [
    "property_value",
    "building_real_surface",
    "land_surface",
    "main_rooms_count",
    "lots_count",
    "lot_1_surface",
    "lot_2_surface",
    "lot_3_surface",
    "lot_4_surface",
    "lot_5_surface",
]

THRESHOLD_COLS = [
    "property_value",
    "price_per_m2_building",
    "land_price_per_m2",
    "building_real_surface_clean",
    "land_surface_clean",
    "main_rooms_count_clean",
    "lots_count_clean",
]


def read_chunks():
    return pd.read_csv(
        INPUT_FILE,
        chunksize=CHUNKSIZE,
        dtype=dtype_map,
        low_memory=False,
        keep_default_na=False,
        na_values=[],
    )


def prepare_chunk(chunk: pd.DataFrame) -> pd.DataFrame:
    chunk["year"] = pd.to_datetime(
        chunk[DATE_COL],
        format=DATE_FORMAT,
        errors="coerce"
    ).dt.year.astype("float64")

    for col in NUMERIC_WORK_COLS:
        if col in chunk.columns:
            chunk[col] = pd.to_numeric(chunk[col], errors="coerce").astype("float64")

    for col in ZERO_AS_MISSING:
        if col in chunk.columns:
            chunk[f"{col}_clean"] = chunk[col].mask(chunk[col] == 0, np.nan)
            chunk[f"flag_zero_{col}"] = chunk[col].eq(0).fillna(False)

    chunk["price_per_m2_building"] = (
        chunk["property_value"] / chunk["building_real_surface_clean"]
    )

    chunk["land_price_per_m2"] = (
        chunk["property_value"] / chunk["land_surface_clean"]
    )

    chunk["building_to_land_ratio"] = (
        chunk["building_real_surface_clean"] / chunk["land_surface_clean"]
    )

    chunk["surface_per_room"] = (
        chunk["building_real_surface_clean"] / chunk["main_rooms_count_clean"]
    )

    chunk["log_property_value"] = np.log1p(chunk["property_value"])

    chunk["flag_multi_lot"] = chunk["lots_count"].ge(2).fillna(False)
    chunk["flag_high_lot_count"] = chunk["lots_count"].ge(5).fillna(False)

    return chunk


print("Pass 1/2: computing thresholds from the full dataset...")

threshold_parts = []

for i, chunk in enumerate(read_chunks(), start=1):
    chunk = prepare_chunk(chunk)

    threshold_parts.append(
        chunk[GROUP_COLS + THRESHOLD_COLS].copy()
    )

    print(f"  processed chunk {i}")

    del chunk
    gc.collect()

threshold_base = pd.concat(threshold_parts, ignore_index=True)

thresholds = (
    threshold_base
    .groupby(GROUP_COLS, dropna=False)
    .agg(
        group_n=("property_value", "size"),

        value_p01=("property_value", lambda x: x.quantile(0.01)),
        value_p99=("property_value", lambda x: x.quantile(0.99)),

        ppm2_p01=("price_per_m2_building", lambda x: x.quantile(0.01)),
        ppm2_p99=("price_per_m2_building", lambda x: x.quantile(0.99)),

        land_ppm2_p01=("land_price_per_m2", lambda x: x.quantile(0.01)),
        land_ppm2_p99=("land_price_per_m2", lambda x: x.quantile(0.99)),

        building_p01=("building_real_surface_clean", lambda x: x.quantile(0.01)),
        building_p99=("building_real_surface_clean", lambda x: x.quantile(0.99)),

        land_p01=("land_surface_clean", lambda x: x.quantile(0.01)),
        land_p99=("land_surface_clean", lambda x: x.quantile(0.99)),

        rooms_p01=("main_rooms_count_clean", lambda x: x.quantile(0.01)),
        rooms_p99=("main_rooms_count_clean", lambda x: x.quantile(0.99)),

        lots_p01=("lots_count_clean", lambda x: x.quantile(0.01)),
        lots_p99=("lots_count_clean", lambda x: x.quantile(0.99)),
    )
    .reset_index()
)

del threshold_base
del threshold_parts
gc.collect()

print("Thresholds computed.")
print("Pass 2/2: removing outliers and writing cleaned dataset...")

first_write = True
total_rows = 0
kept_rows = 0
removed_rows = 0

for i, chunk in enumerate(read_chunks(), start=1):
    chunk = prepare_chunk(chunk)

    chunk = chunk.merge(
        thresholds,
        on=GROUP_COLS,
        how="left"
    )

    chunk["flag_property_value_outlier"] = (
        (chunk["property_value"] < chunk["value_p01"]) |
        (chunk["property_value"] > chunk["value_p99"])
    ).fillna(False)

    chunk["flag_price_m2_outlier"] = (
        (chunk["price_per_m2_building"] < chunk["ppm2_p01"]) |
        (chunk["price_per_m2_building"] > chunk["ppm2_p99"])
    ).fillna(False)

    chunk["flag_land_price_m2_outlier"] = (
        (chunk["land_price_per_m2"] < chunk["land_ppm2_p01"]) |
        (chunk["land_price_per_m2"] > chunk["land_ppm2_p99"])
    ).fillna(False)

    chunk["flag_building_surface_outlier"] = (
        (chunk["building_real_surface_clean"] < chunk["building_p01"]) |
        (chunk["building_real_surface_clean"] > chunk["building_p99"])
    ).fillna(False)

    chunk["flag_land_surface_outlier"] = (
        (chunk["land_surface_clean"] < chunk["land_p01"]) |
        (chunk["land_surface_clean"] > chunk["land_p99"])
    ).fillna(False)

    chunk["flag_rooms_outlier"] = (
        (chunk["main_rooms_count_clean"] < chunk["rooms_p01"]) |
        (chunk["main_rooms_count_clean"] > chunk["rooms_p99"])
    ).fillna(False)

    chunk["flag_lots_count_outlier"] = (
        (chunk["lots_count_clean"] < chunk["lots_p01"]) |
        (chunk["lots_count_clean"] > chunk["lots_p99"])
    ).fillna(False)

    chunk["flag_extreme_value"] = chunk["property_value"].gt(50_000_000).fillna(False)
    chunk["flag_extreme_building_surface"] = chunk["building_real_surface_clean"].gt(5_000).fillna(False)
    chunk["flag_extreme_land_surface"] = chunk["land_surface_clean"].gt(100_000).fillna(False)
    chunk["flag_extreme_rooms"] = chunk["main_rooms_count_clean"].gt(50).fillna(False)
    chunk["flag_extreme_lots"] = chunk["lots_count_clean"].gt(20).fillna(False)

    chunk["flag_tiny_room_surface"] = chunk["surface_per_room"].lt(5).fillna(False)
    chunk["flag_huge_room_surface"] = chunk["surface_per_room"].gt(150).fillna(False)

    outlier_flags = [
        "flag_property_value_outlier",
        "flag_price_m2_outlier",
        "flag_land_price_m2_outlier",
        "flag_building_surface_outlier",
        "flag_land_surface_outlier",
        "flag_rooms_outlier",
        "flag_lots_count_outlier",
        "flag_extreme_value",
        "flag_extreme_building_surface",
        "flag_extreme_land_surface",
        "flag_extreme_rooms",
        "flag_extreme_lots",
        "flag_tiny_room_surface",
        "flag_huge_room_surface",
    ]

    chunk["is_outlier"] = chunk[outlier_flags].fillna(False).any(axis=1)

    chunk_clean = chunk.loc[~chunk["is_outlier"]].copy()

    total_rows += len(chunk)
    kept_rows += len(chunk_clean)
    removed_rows += len(chunk) - len(chunk_clean)

    chunk_clean.to_csv(
        OUTPUT_FILE,
        mode="w" if first_write else "a",
        index=False,
        header=first_write
    )

    print(f"  chunk {i}: kept {len(chunk_clean):,} / {len(chunk):,} rows")

    first_write = False

    del chunk
    del chunk_clean
    gc.collect()

print("Done.")
print(f"Input rows processed: {total_rows:,}")
print(f"Rows kept: {kept_rows:,}")
print(f"Rows removed as outliers: {removed_rows:,}")
print(f"Saved cleaned dataset to: {OUTPUT_FILE}")

Pass 1/2: computing thresholds from the full dataset...
  processed chunk 1
  processed chunk 2
  processed chunk 3
  processed chunk 4
  processed chunk 5
  processed chunk 6
  processed chunk 7
  processed chunk 8
  processed chunk 9
  processed chunk 10
  processed chunk 11
  processed chunk 12
  processed chunk 13
  processed chunk 14
  processed chunk 15
  processed chunk 16
  processed chunk 17
  processed chunk 18
  processed chunk 19
  processed chunk 20
  processed chunk 21
  processed chunk 22
  processed chunk 23
  processed chunk 24
  processed chunk 25
  processed chunk 26
  processed chunk 27
  processed chunk 28
  processed chunk 29
  processed chunk 30
  processed chunk 31
  processed chunk 32
  processed chunk 33
  processed chunk 34
  processed chunk 35
  processed chunk 36
  processed chunk 37
  processed chunk 38
Thresholds computed.
Pass 2/2: removing outliers and writing cleaned dataset...
  chunk 1: kept 476,756 / 500,000 rows
  chunk 2: kept 478,019 / 500,000 rows
  chunk 3: kept 476,482 / 500,000 rows
  chunk 4: kept 477,030 / 500,000 rows
  chunk 5: kept 478,481 / 500,000 rows
  chunk 6: kept 477,430 / 500,000 rows
  chunk 7: kept 478,544 / 500,000 rows
  chunk 8: kept 473,732 / 500,000 rows
  chunk 9: kept 475,430 / 500,000 rows
  chunk 10: kept 477,494 / 500,000 rows
  chunk 11: kept 478,436 / 500,000 rows
  chunk 12: kept 478,301 / 500,000 rows
  chunk 13: kept 480,047 / 500,000 rows
  chunk 14: kept 478,395 / 500,000 rows
  chunk 15: kept 476,478 / 500,000 rows
  chunk 16: kept 479,055 / 500,000 rows
  chunk 17: kept 476,681 / 500,000 rows
  chunk 18: kept 471,857 / 500,000 rows
  chunk 19: kept 479,772 / 500,000 rows
  chunk 20: kept 478,069 / 500,000 rows
  chunk 21: kept 479,845 / 500,000 rows
  chunk 22: kept 479,127 / 500,000 rows
  chunk 23: kept 475,282 / 500,000 rows
  chunk 24: kept 478,574 / 500,000 rows
  chunk 25: kept 476,373 / 500,000 rows
  chunk 26: kept 476,314 / 500,000 rows
  chunk 27: kept 477,648 / 500,000 rows
  chunk 28: kept 478,904 / 500,000 rows
  chunk 29: kept 475,862 / 500,000 rows
  chunk 30: kept 475,436 / 500,000 rows
  chunk 31: kept 476,378 / 500,000 rows
  chunk 32: kept 475,885 / 500,000 rows
  chunk 33: kept 476,722 / 500,000 rows
  chunk 34: kept 476,338 / 500,000 rows
  chunk 35: kept 478,764 / 500,000 rows
  chunk 36: kept 477,665 / 500,000 rows
  chunk 37: kept 477,158 / 500,000 rows
  chunk 38: kept 19,104 / 19,810 rows
Done.
Input rows processed: 18,519,810
Rows kept: 17,677,868
Rows removed as outliers: 841,942
Saved cleaned dataset to: ../data/processed/OUTLIERS_ValeursFoncieres.csv

---
### **DETECT OUTLIERS (METHODS)**

---
#### **Method 1: IQR (Interquartile Range)**
- Calculate Q1 (25th percentile)
- Calculate Q3 (75th percentile)
- Compute IQR = Q3 − Q1
- Define bounds:
    - Lower bound = Q1 − 1.5 × IQR
    - Upper bound = Q3 + 1.5 × IQR
    - Values outside these bounds are considered **outliers**

Tukey's test for outliers involves using the interquartile range (IQR) to determine if values are outliers. While there isn't a direct "Tukey's test" function in Python's standard libraries, you can easily compute it using the IQR.

Here's how you can perform Tukey's test for outliers:

1. Calculate the first quartile (Q1) and third quartile (Q3) for the data.
2. Compute the interquartile range: \( \text{IQR} = Q3 - Q1 \).
3. Identify outliers:
   - Values less than \( Q1 - 1.5 \times \text{IQR} \)
   - Values greater than \( Q3 + 1.5 \times \text{IQR} \)

Here's a Python function that implements Tukey's test for outliers:

In [ ]:
def tukeys_test_outliers(data):
    Q1 = data.quantile(0.25)
    Q3 = data.quantile(0.75)
    IQR = Q3 - Q1
    
    # Define bounds for the outliers
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    
    # Identify the outliers
    outliers = data[(data < lower_bound) | (data > upper_bound)]
    
    return outliers

This function returns the values in the data that are considered outliers according to Tukey's method.

In [ ]:
# Example usage:
data_series = df['ColumnName']  # replace 'ColumnName' with your specific column
outliers = tukeys_test_outliers(data_series)
print(outliers)

If you want to **modify the outlier values**, you can replace them with a specific value, such as the median, or the bounds defined by Tukey's method.

If you wish to **delete the outliers**, you can simply filter them out.

Implement these three approaches modifying the function above.

---
#### **Method 2: Z-score**
- Calculate mean and standard deviation
- Compute Z-score for each value
- Values with |Z| > 3 are typically considered **outliers**

---
#### **Before removing anything, check:**
- Are they data entry errors?
- Are they rare but valid observations?
- Do they represent a specific subgroup?
- How many outliers are there (percentage of the data)?

---
#### **Then Decide whether to:**

**a. Keep outliers:**
- If they are valid and meaningful
- If they represent real-world variability

**b. Transform outliers:**
- Apply log transformation
- Apply scaling (RobustScaler)
- Apply winsorization (cap extreme values)

**c. Remove outliers:**
- If they are clear errors
- If they severely distort the model
- If they represent noise rather than signal

---
### **PLOTS**

#### **BOX PLOTS: Side by Side**

Box plots are a great way to visualize the distribution of a continuous variable across different categories. They show the median, quartiles, and potential outliers, providing a quick snapshot of the data's spread and central tendency.

Let's visualize the distribution of `property_value` for each column category using side-by-side box plots. This will help us understand the spread, median, and potential outliers for each category.

In [ ]:
sns.boxplot(data=df, x='MSZoning', y='SalePrice', palette="coolwarm")

- There are noticeable outliers in the `A` and `B` categories, with some houses selling at values much higher than the typical range for those categories.

### **SCATTER PLOTS**

**Potential Outliers**: There are a few houses with large surface areas but lower sale values. These points could be potential outliers or could represent houses in areas where value per square meter is lower.

<hr>

## 7️⃣ CLEAN


<style>
h1 {
    text-align: center;
    color: black;
    font-weight: bold;
}
</style>

<style>
h2 {
    text-align: left;
    color: black;
    font-weight: bold;
}
</style>

<style>
h3 {
    text-align: left;
    color: black;
    font-weight: bold;
}
</style>

<style>
h4 {
    text-align: left;
    color: black;
    font-weight: bold;
}
</style>
<hr>

ONE SCRIPT FOR CLEANING DATA & SAVING IT as CLEAN_ValeursFoncieres.csv